### ISSUE TITLE
A taxon image is not displayed after upload

### ISSUE THREAD

**Issue by isindexer** [solidusio/solidus#1003]
While testing 1.2.2 version, It appears that even if an image is uploaded on a taxon, it's not displayed.
The image filename should at least be displayed, even better the image itself should be displayed.

**Comment by jhawthorn** [comment]
Hi @isindexer. Thanks for the report.

The image has been added to master and will be in the next release (see #898)

**Comment by isindexer** [comment]
Thanks @jhawthorn
