### ISSUE TITLE
rake deface starts my rspec tests instead of running the deface task

### ISSUE THREAD

**Issue by stabenfeldt** [solidusio/solidus#1006]
I'm trying to follow the deface debugging technique [described here][1].
But my entire RSpec test suite is started when I run
 `rake deface:get_result['spree/shared/_link_to_account']`.

I'm using Solidus 1.3.0.alpha.

  [1]: http://stackoverflow.com/questions/30372496/deface-products-data-hook

Any idea why this happens? 

**Rakefile**

    require File.expand_path('../config/application', __FILE__)
    Rails.application.load_tasks

**Comment by mamhoff** [comment]
Since Solidus 1.2 we removed deface from core. Does your project have the gem installed locally?

**Comment by stabenfeldt** [comment]
I couldn't find the deface gem in my Gemfile, but it was installed globally on my machine.
After adding it to Gemfile and running bundle, then `rake deface` tasks started to behave as expected.

Thanks for letting me know about the gem. :-)
