### ISSUE TITLE
Deleting a line item deletes *all* matching line items from all shipments.

### ISSUE THREAD

**Issue by dholdren** [solidusio/solidus#1039]
## Steps to reproduce:
1) Start with an order with multiple quantities of a line item
2) Split the single shipment into multiple shipments
3) click the trash icon on one shipment's line item

### Expected:
The unrelated shipments should be left alone.

### Actual (Error):
Both shipments become empty.

![ogfij9uibn](https://cloud.githubusercontent.com/assets/28270/14295898/7d8e2a7e-fb45-11e5-8b63-59a74863a79e.gif)

**Comment by dholdren** [comment]
It looks like this is the commit that introduced the bug: https://github.com/solidusio/solidus/commit/c6fa6226d3028a2259461e66376c888588c02a5e

**Comment by jhawthorn** [comment]
Thanks @dholdren I have noticed that bug before. I'll see if we can revert that change to fix it.
