### ISSUE TITLE
Admin view customization not working

### ISSUE THREAD

**Issue by Leventhan** [solidusio/solidus#1044]
What is the idiomatic way to customize Solidus admin templates/partials?

**Comment by tvdeyen** [comment]
Thanks for your interest in Solidus. This issue tracker is for issues/errors you encounter while using Solidus. Please either provide more in depth information of your error or join the the Solidus Slack and ask your questions there.

I'm closing this right know. Please feel free to re-open if you have more informations for us. 

Thanks.
