### ISSUE TITLE
Clone Spree's documentation

### ISSUE THREAD

**Issue by stabenfeldt** [solidusio/solidus#1047]
Spree has a pretty extensive set of documentation available at guides.spreecommerce.com.
Can we clone that and make guides.solidus.io?

I understand that it might be outdated, but it would be much better than nothing. And we could update the documentation as we go.

**Comment by ajkamel** [comment]
@stabenfeldt you can find reference to the guides herehttps://github.com/solidusio/solidus_guides issues are marked as help wanted and we are accepting pull requests to complete the guides as of now we have the user guides up and they will be hosted on the Solidus domain soon. In the interim I've hosted them on my page for reference http://ashkamel.com/solidus-guides

**Comment by jhawthorn** [comment]
Closing as we do have the [solidusio/solidus_guides](https://github.com/solidusio/solidus_guides) repo and this is a work in progress
