### ISSUE TITLE
Multiple menus open in stock locations section

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#1074]
![](http://i.hawth.ca/s/TuhIJfG3.png)

**Comment by graygilmore** [comment]
@jhawthorn would you prefer to see the `Stock Locations` tab removed from `Settings > Shipping`? That makes the most sense to me

**Comment by graygilmore** [comment]
To clarify: and move it under `Stock` in the main navigation.

**Comment by Mandily** [comment]
I agree that it should only be accessible from one place. But putting it in the stock menu item leads me down a rabbit hole of asking, when does something get put in settings, and when does it get put into a parent category of it's own? Playing devil's advocate here - some of those things look like they could go under 'orders'. 

Does anyone have any thoughts on what's a setting and what's a sub section of a related parent?

**Comment by graygilmore** [comment]
I think this would be a good opportunity for us to put or "site architect" hats on and figure out the structure for the entirety of the admin area.

**Comment by forkata** [comment]
Managing stock locations seems like a configuration change to me that wouldn't be done on a day-to-day basis and should probably be limited to "super" admins. The stock screens are something that is probably used on a daily basis by someone like an inventory manager. In my mind there are two ways to think about the organisation of things, one would be per area, i.e. stock, products etc., the other would be based on the frequency of use or permissions required to manage things, i.e. configuration vs. day-to-day operations.
