### ISSUE TITLE
Add navigable breadcrumbs in the header

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#1076]
The title of many of the admin's pages is unintuitive and a duplicate of the parent pages. This issue exists to clean up page titles and introduce a navigable breadcrumb that better informs the user of where they are in the admin.

Breadcrumb labels should be a link when a specific parent page exists that can be linked to. For example the product listing page can be a link in the breadcrumbs, when the user is on a specific product. This means that we'll also be able to get rid of all "go back" buttons that currently exist.

A consistent page title will also be enforced. As "Listing Products" and "Products" are the same page, they will need to be made consistent with "Products" in all references.
<img width="355" alt="screen shot 2016-04-18 at 10 43 37 am" src="https://cloud.githubusercontent.com/assets/15271353/14613701/7d52546a-0552-11e6-8761-e14cbda2bd08.png">
<img width="301" alt="screen shot 2016-04-18 at 10 43 45 am" src="https://cloud.githubusercontent.com/assets/15271353/14613702/7d55b754-0552-11e6-8bf3-bd2b9308b74f.png">

Currently some pages use 'edit' in the title and others do not. To make it consistent and more concise across the app, we'll get rid of 'editing' in the breadcrumbs. When the user is on a page with fields instead of static text, there is enough affordance to tell them it is editable.

**Current**
<img width="972" alt="screen shot 2016-04-18 at 10 49 30 am" src="https://cloud.githubusercontent.com/assets/15271353/14613893/6641c4c6-0553-11e6-9a05-a5d8b4f418f1.png">
**Future**
<img width="964" alt="screen shot 2016-04-18 at 10 49 08 am" src="https://cloud.githubusercontent.com/assets/15271353/14613892/6641888a-0553-11e6-8f32-efc83075688c.png">

Please feel free to give feedback in the comments below.

**Comment by tvdeyen** [comment]
100% acknowledged :+1:

**Comment by Murph33** [comment]
Just like to add I'd started doing some work on this before getting side tracked with things.  I do intend to get back to finishing it when I have some available time.
