### ISSUE TITLE
html validation isn't aligned with Select2 dropdown

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#1077]
If a user leaves the mandatory "Shipping categories" field undefined, then an html validation note pops up on the screen. The note for this field is pushed to the top of the form. I suspect this is due to Select2 pushing the native form field out of sight to replace it with their own jquery one. 

![screen_shot_2016-04-18_at_1 33 40_pm](https://cloud.githubusercontent.com/assets/15271353/14615613/5a41e96e-055b-11e6-88ef-a6e53e879f84.png)

**Comment by jhawthorn** [comment]
This is a bug in select2 (select2/select2#128). It looks better, but still broken select2/select2#3824, in the 4.0 version (we're still on 3.5).

AFAICT the only workaround is removing the `required` attribute on the field and performing the validation ourselves.

**Comment by tvdeyen** [comment]
👍 for removing the `required` attribute.
