### ISSUE TITLE
Create 3 layout options for content area of admin UI

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#1078]
The content area of the Solidus admin is currently restricted to 940px. I'd like to create two new layouts - one to maximize the full width of the content area and another for forms and such that don't need to use as much space. These layouts will be created with Bootstrap and we'll be getting rid of the current 16 column grid for the core pages.

Design requirements:
- responsive
  - adjustable widths on layouts and form elements to make them best fit the screen size they’re on
  - stack multiple columns into one column when screen size reaches mobile size
- two layouts
  - full 100% width for table pages
  - max-width for form pages
#1012 Bootstrap was recently added to the admin to help prepare for this issue.

**Comment by Mandily** [comment]
We were planning both on creating templates and moving existing screens over to those new templates for 1.3. Due to time constraints, we're going to wait until a later release to merge the new layouts in.

**Comment by Mandily** [comment]
After running through an exercise with more of the admin forms, I've realized that 3 layouts instead of 2 is actually more useful. So we'll have the full width layout and two forms layouts as noted in #1290.

**Comment by gmacdougall** [comment]
Close due to staleness
