### ISSUE TITLE
Starting generator only works with bleeding edge

### ISSUE THREAD

**Issue by ckk-scratch** [solidusio/solidus#108]
I couldn't find why in the difference from stable -> bleeding edge but running ( $ bundle exec rails g spree:install ) with just gem 'solidus' gives following error. 

solidus_auth_devise.rb:1:in `require': cannot load such file -- spree_core (LoadError)
line 1 -> require "spree_core" 

Figured out that initial generator works when using gem 'solidus', github: 'solidusio/solidus'

**Comment by jhawthorn** [comment]
You're a little early to the party :tada:. We haven't cut a gem release yet, expect a prerelease gem shortly and a proper version in a few weeks.

Thanks for checking it out!

**Comment by ckk-scratch** [comment]
No thank you! Excited to start building with it.

**Comment by cbrunsdon** [comment]
Maybe we should leave a note on the readme that this is still a Secret Project™ and gems will be cut shortlyish.
