### ISSUE TITLE
Investigation into redundant page removal

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#1084]
On Orders > Payments, a user can click on a link in the identifier column that takes them to a new page. That page shows two columns of the same table that the link was contained in. I see no reason to keep this link or page but wanted to check with the community before we went ahead and removed it. 

Does anyone have any reason to leave it in?

<img width="1176" alt="screen shot 2016-04-19 at 4 38 31 pm" src="https://cloud.githubusercontent.com/assets/15271353/14659054/73f7a41e-064d-11e6-95e0-412c3e79ccef.png">
<img width="1177" alt="screen shot 2016-04-19 at 4 38 16 pm" src="https://cloud.githubusercontent.com/assets/15271353/14659056/75b7d35a-064d-11e6-95e0-c92dc008d17d.png">

**Comment by jeremyw** [comment]
@Mandily Oddly they are showing different timestamps...

**Comment by Mandily** [comment]
Good catch! I didn't see that. Does anyone know why they're different?

**Comment by jhawthorn** [comment]
One of the times is the payment's creation, and the other would be when it was captured/completed

**Comment by Mandily** [comment]
How about we combine them into the same table then?
<img width="1172" alt="screen shot 2016-04-19 at 5 05 05 pm" src="https://cloud.githubusercontent.com/assets/15271353/14659431/eda3a332-0650-11e6-893c-a6607f7b4eb8.png">

**Comment by mamhoff** [comment]
One of them is the payment itself, the other table is the logs around it (when it was authorized, captured and so on). Combining them into one table would mean essentially showing the Logs first, and not the payments. Given that most payments are only one or two events, having two pages for that seems redundant - and the only reason you want that much details about a payment is when you actually want to see the logs. 👍 .

**Comment by Mandily** [comment]
We've been having a conversation at Stembolt about the likelihood of multiple capture events on a payment. It seems like worst case its an edge case, and best case it doesn't happen at all. 

@mamhoff came up with the idea of two rows so that we don't have to deal with growing tables. As long as we span the rows across multiple columns in the payment section, I think this works. 


Single capture (this is what would show most of the time)
<img width="675" alt="single capture event" src="https://cloud.githubusercontent.com/assets/15271353/14684667/edcc1bf6-06e5-11e6-8448-86f9f7e56c7a.png">

Multiple capture (edge case)
<img width="668" alt="2 capture events" src="https://cloud.githubusercontent.com/assets/15271353/14685548/bff3928c-06e9-11e6-9c8b-e6a13eb78ddf.png">

**Comment by mtomov** [comment]
Have a look at different payment methods and you'll see it's high usefulness. It is supposed to contain payment method specific data, which can be lots (all sorts of transaction numbers, error codes & explanations and what not)

![screenshot from 2016-04-22 19 21 08](https://cloud.githubusercontent.com/assets/1651750/14750956/6ea0ac80-08bf-11e6-8ffc-9f63c665c5d9.png)

![screenshot from 2016-04-22 19 20 32](https://cloud.githubusercontent.com/assets/1651750/14750957/6ea0fb86-08bf-11e6-89a8-c9c4bb912ef1.png)

It's different levels of detail. I believe it's correctly displayed, and those who don't need it simply don't visit the link.

**Comment by Mandily** [comment]
@mtomov What you're saying here makes sense. Store credit isn't a method that's in the Solidus sandbox and wasn't part of my mental model until I saw your example above.

Until we have more concrete evidence that users prefer to see everything holistically on page, I'd prefer to keep things as they are instead of changing data display.
