### ISSUE TITLE
Submitting stock transfer form without a source location generates Ruby error

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#1087]
To reproduce:
1. Navigate to Stock > Transfers page, click "New Stock Transfer" button
2. On the New Stock Transfer page, click the continue button
3. View error.

<img width="1241" alt="screen shot 2016-04-20 at 2 20 54 pm" src="https://cloud.githubusercontent.com/assets/15271353/14690966/9e11c002-0703-11e6-9029-0828e773199d.png">

**Comment by jhawthorn** [comment]
This should be fixed by #1105
