### ISSUE TITLE
helper reimbursement_type is not included in customer returns controller

### ISSUE THREAD

**Issue by acreilly** [solidusio/solidus#1127]
When creating a customer return, I am an error that reimbursement_type_name is an undefined method. In the CustomerReturnsController, helper 'spree/admin/reimbursement_type' needs to be added in order for that helper method to work.

**Comment by mamhoff** [comment]
This has been fixed in https://github.com/solidusio/solidus/commit/726630f3f84ca4a79a675a91d6081bbf6cdfe718
