### ISSUE TITLE
Incompatible LineItem option permitting between Api::OrdersController and Api::LineItemsController

### ISSUE THREAD

**Issue by adaddeo** [solidusio/solidus#1131]
Unable to create a new order with a line item with options. This is the issue/motivation behind #1112.

To reproduce:

Start by permitting a new option on to permitted on a line item:

```
PermittedAttributes.line_item_attributes << :some_option
```

Now each of the requests should create the line item with some_option set to 4:

To OrdersController#create

```
{ order: { line_items: [variant_id: 1, quantity:1, options: { some_option: 4 } ] } }
```

To LineItemsController#create

```
{ line_item: variant_id: 1, quantity:1, options: { some_option: 4 } }
```

However, the OrdersController fails to permit the option.

**Comment by gus4no** [comment]
Working on it 👷

**Comment by adaddeo** [comment]
This was fixed by @gus4no
