### ISSUE TITLE
Remove icons from buttons and tabs

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#1161]
This is a bullet from #520 Solidus Admin branding that I wanted to separate out so that any interested parties could take a crack at it. 

Icons are generally a universal language that don't require words to explain them. They're great for things like stop signs and bathrooms, and in our case edit functions and calendar pickers, etc. They're not great when they're not clear and need text beside them to explain them.

Currently, there are icons in the left side navigation, tabs and some of the buttons. The ones in the navigation are useful for the #666 collapsible nav feature. The ones that stand solo beside the tables are useful too. Many of the others in the admin do not add any value to the page, but instead clutter it. To reduce the clutter and save a little space, we can remove them.

This issue is left for anyone in the community who would like to try their hand at contributing back to core. Leave a message below if you'd like to claim it or have any questions.

**Comment by tvdeyen** [comment]
👍

**Comment by RitaD** [comment]
I’m currently working on this, expect a PR soon!
