### ISSUE TITLE
Inconsistent select2 input options

### ISSUE THREAD

**Issue by AlessioRocco** [solidusio/solidus#1165]
All around the admin we have `select2` inputs, these inputs sometimes are initialized with the options inside the [spree-select2.js](https://github.com/solidusio/solidus/blob/master/backend/app/assets/javascripts/spree/backend/spree-select2.js#L5-L7) file but in some case, for example when a user add a promotion action they are initialized without options https://github.com/solidusio/solidus/blob/master/backend/app/views/spree/admin/promotion_actions/create.js.erb#L6, so when the promotion action was added the first time looks like:

![schermata 2016-05-19 alle 17 44 10](https://cloud.githubusercontent.com/assets/308848/15399796/5ceafdbc-1de9-11e6-8f1b-3df27296c3a9.png)

then when the page is reloaded it looks like:

![schermata 2016-05-19 alle 17 45 14](https://cloud.githubusercontent.com/assets/308848/15399833/78ff2e1a-1de9-11e6-8dcf-4e0bed2140ba.png)

I've also added this code https://github.com/nebulab/solidus/blob/44b6166ad1e6c17d1d1653689e16aa0f76bbe1e6/backend/app/views/spree/admin/promotion_rules/create.js.erb#L7-L11 to fix the `select2` inputs when a user add a promotion rule. In this code I had to duplicate the options to keep the original `select2` behavior.

I think the easy way to fix this little problem is to wait the upgrade to `select2 4.0` (https://github.com/solidusio/solidus/issues/763) and then use the [default options](https://select2.github.io/options.html#setting-default-options) to let the `select2` inputs behave in the same way all around the admin.

**Comment by jhawthorn** [comment]
These are no longer select2's but bootstrap-styled normal HTML selects. :tada:  I think this can be closed
