### ISSUE TITLE
Allow editing all Stores through the admin

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#1189]
Currently the "General" settings page is mostly (entirely?) for editing the default Store. It should be replaced with an interface for editing _any_ of the stores in the DB.

This would probably fix some awkwardness we see like #1176

**Comment by jasonfb** [comment]
Are multiple store supported natively in core? I thought support for this was provided though the solidus_multi_domain gem. It would seem logical then that it is that extension's responsibility to provide this.

**Comment by jhawthorn** [comment]
solidus_multi_domain includes some specifics about what multi-store behaviour means, but to some degree Stores have been natively supported since spree 2.3 (models in core, `current_store` method, association to orders) https://github.com/solidusio/solidus/blob/master/core/app/models/spree/store.rb
