### ISSUE TITLE
Accept terms and conditions: How to do this well?

### ISSUE THREAD

**Issue by mamhoff** [solidusio/solidus#1196]
Copying a Slack discussion here that arose in response to #1195 

> sebashton [1:22 PM] 
> Hi all, we’ve recently had to add terms and condition acceptance to a solidus checkout flow to comply with EU legislation. We thought this would be a nice bit of functionality to commit back to core. We'd appreciate feedback. https://github.com/solidusio/solidus/pull/1195
>  GitHub
> Add terms and conditions to comply with EU legislation by SebAshton · Pull Request #1195 · solidusio/solidus · GitHub
> This PR will add functionality for incorporating a terms and conditions checkbox onto the order confirmation page in the checkout flow. This is required for all stores with their main operating ad... 
> 
> clarke [2:30 PM] 
> sebashton: cool! thanks for contributing that back
> 
> [2:31] 
> sebashton: did you attempt any other ways to do this before you landed on the attr_accessor / before_transition?
> 
> sebashton [2:35 PM] 
> At first we had it as an attribute in the db itself, but we felt it was superfluous.
> 
> kennyadsl [2:35 PM] 
> @sebashton: we had the same requirement for one client and we used a validation on the order with a not persisted attribute
> 
> sebashton [2:36 PM] 
> did you use `acceptance_of`?
> 
> [2:36] 
> @kennyadsl ^
> 
> mamhoff [2:38 PM] 
> clarke, sebashton: We implemented it the exact same way before for a client. I'd be very happy for something like this to land in core, and I also don't think it has to be persisted.
> 
> kennyadsl [2:38 PM] 
> something like:

```
validates :field_name, acceptance: { accept: 'yes' }, if: ->(r) { # some condition }
```

(edited)

> [2:38] 
> I'd also like the step where the validation happen to be configurable
> 
> clarke [2:39 PM] 
> my biggest issue is "yet another before_transition" in the codebase (though I get it does almost nothing and is an optional configuration
> 
> kennyadsl [2:39 PM] 
> because for example we don't have the confirm step
> 
> [2:40] 
> and the client wants it on the address step
> 
> new messages
> sebashton [2:41 PM] 
> this is on the transition to complete, so it could be payment step
> 
> kennyadsl [2:41 PM] 
> you know, clients :troll:
> 
> sebashton [2:41 PM] 
> yea :slightly_smiling_face:
> 
> [2:42] 
> I guess its more of a UX question to where it appears
> 
> mamhoff [2:43 PM] 
> Hmnjem, the state machine is coupled to the UX, so we need to think that through
> 
> [2:45] 
> Can it be done without the state transition, and with a customizable lambda or method to check whether we need to check for the attribute?

```
if: :check_acceptance? 

def check_acceptance?
   Spree::Order::AcceptanceValidator.new(self).necessary?
end
```

(edited)

> kennyadsl [2:46 PM] 
> sebashton: yes but like this if it's not persisted and I put the checkbox on the address step it will be lost in the next steps and will fail the order completion right?
> 
> [2:46] 
> mamhoff: was thinking something similar
> 
> clarke [2:47 PM] 
> I'm not sure the order model is the place for this
> 
> kennyadsl [2:47 PM] 
> with `Spree::Order::AcceptanceValidator` to be a preference like `Spree::Config.terms_and_condition_validator_class`
> 
> clarke [2:47 PM] 
> other than "there isn't a better place for it right now"
> 
> [2:47] 
> also this wouldn't be a thing for admin-created orders, right?
> 
> kennyadsl [2:48 PM] 
> right
> 
> mamhoff [2:48 PM] 
> If the order object wouldn't also be the checkout object...
> 
> clarke [2:49 PM] 
> I'd be tempted to do it as part of a before_filter at the controller level
> 
> [2:49] 
> its more or less already done that way with the accept_terms_and_conditions call
> 
> kennyadsl [2:50 PM] 
> this is a great scenario for a Form Object IMHO
> 
> clarke [2:50 PM] 
> again, hard as its pretty UI-centric
> 
> [2:51](not that I have a better idea)
> 
> kennyadsl [2:51 PM] 
> clarke: yes, starting thinking that the controller is probably the best place at this point
> 
> sebashton [2:52 PM] 
> Should we create an issue on GitHub to track this discussion
> 
> [2:52] 
> assume this conversation could get lost at some point
> 
> [2:52] 
> otherwise
> 
> mamhoff [2:53 PM] 
> sebashton: Yes it will. I'll copy verbatim if you don't object @kennyadsl @clarke @sebashton
> 1
> 
> clarke [2:54 PM] 
> fine by me

**Comment by SebAshton** [comment]
Happy to will get cracking on this.

So we agree on the approach, an ideal solution will:

- use a `before_action` on `update` within `Spree::CheckoutController`
- use a service object to validate whether attribute is required to complete that transition

**Comment by jasonfb** [comment]
+1 for moving to controller concern at this time. It seems to me that if it isn't a datapoint on the actual database then it shouldn't be tied up with state_machine transition hooks which primarily are the concern of the models.

**Comment by jasonfb** [comment]
One other thought... (perhaps a feature request). It seems to me that every e-commerce company will want their T&C checkbox in a different place (our, for example, is on Registration/Log-In), so it would be cool if perhaps the implementation allowed for it to be on any step, and configurable through customization. Not sure if that is already accounted for in your design @SebAshton -- or if that is prohibitively more work --- it just seems to me that the core code would best serve all stores if it accounted for that.

**Comment by bbuchalter** [comment]
I'd also say that for those not use solidus_frontend, a controller filter seems like the wrong place to enforce such important business logic.

**Comment by jhawthorn** [comment]
I'd like to see this requirement met as simply as possible.

How about just binding some JS to the checkbox to enable/disable the complete order button.

**Comment by RoryMacDonald** [comment]
Couple of thoughts on this:

- If we're not persisting this value, then what happens when a user accepts T&Cs and wants to make a change to shipping / basket contents? Expect they will need to accept the T&Cs again. This behaviour will differ to the rest of the checkout forms, which isn't great from a UX perspective.

- I'd echo @bbuchalter views that this is important business logic and am also unsure if `solidus_frontend` (or a JS checkbox) is the right place for this.

**Comment by tvdeyen** [comment]
There is also a legal need in persisting the acknowledgment of the TnC.

**Comment by mamhoff** [comment]
From: http://www.out-law.com/page-424
> Step 3: Incorporating the terms and conditions
At the bottom of the terms and conditions page the purchaser should, ideally, be required to check a box to indicate that he or she has read, understood and accepted the terms and conditions, before clicking the "Accept" button. The "Accept" button should not work until the box has been checked. Equally the page should be designed in such a way that the consumer cannot check the box and click "Accept" until the page has fully loaded onto the screen. By doing this, you improve your position in the event that a purchaser claims there was no opportunity to read your terms.
While there is no responsibility on the retailer to ensure that the consumer has in fact read them, following this procedure will demonstrate that reasonable efforts have been made to bring them to purchasers' attention.

This looks like @jhawthorn s approach of disabling the submit button wherever the checkbox appears might just do the trick, and we don't need to persist anything. 

Maybe we could just look at a partial that incorporates the JS for disabling the submit button.

**Comment by peterberkenbosch** [comment]
any updates here? //cc @mamhoff @jhawthorn @SebAshton

**Comment by kennyadsl** [comment]
@peterberkenbosch we are working on a [PR for this](https://github.com/solidusio/solidus/compare/master...DanielePalombo:accept-terms-and-conditions?expand=1). It's in an internal review state so expect a PR soon.

**Comment by peterberkenbosch** [comment]
cool! Thanks for updating @kennyadsl

**Comment by jhawthorn** [comment]
#1448 has been merged, which I believe accomplishes what is needed for this.

Big thanks to @DanielePalombo
