### ISSUE TITLE
Add pagination to Stock Transfer page when there are more than 10 table rows

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#1204]
As noted by @mamhoff  on #1201, the stock transfer page would benefit from pagination.

Currently the Stock Transfer page will continue to add more and more transfers making the page longer and longer. Ideally, pagination would appear when there's more than 10 rows. Each page would consist of 10 rows. This would keep consistency between the Products page (and others that have pagination) and Stock Transfers.

Current view:
![15add574-2423-11e6-992c-afda4a341494](https://cloud.githubusercontent.com/assets/15271353/15657698/1501e39e-2668-11e6-8cee-f223149a09c6.png)

After pagination:
![stock transfers with pagination](https://cloud.githubusercontent.com/assets/15271353/15657930/c45f550e-266a-11e6-82c0-a0832bdcc101.jpg)

This issue is not spoken for, if you'd like to take a crack at it, leave a note below so that there's not duplicate efforts.

**Comment by tlindsay** [comment]
This is already how it works for me on the latest release (1.3.0.rc1). It also seems to be consistent with the [code for that view](https://github.com/solidusio/solidus/blob/master/backend/app/views/spree/admin/stock_transfers/index.html.erb#L69).
<img width="1365" alt="screen shot 2016-06-06 at 9 18 02 pm" src="https://cloud.githubusercontent.com/assets/2797532/15844028/719a4ef6-2c2c-11e6-8d4a-e1290ca94cec.png">

**Comment by Mandily** [comment]
I fall short when it comes to code things like this. I added more rows in my sandbox until I hit 15 and still no pagination. If someone else could confirm that this works as @tlindsay describes, I'd be happy to close this issue.

**Comment by mamhoff** [comment]
I  can confirm the code for pagination has been there since https://github.com/solidusio/solidus/commit/ab5faedd4dc93fbb900c81136e4ba942433bb453.

**Comment by Mandily** [comment]
Sorry to be picky, but does it work for you too @mamhoff?

**Comment by mamhoff** [comment]
I looked into this, and it appears that this particular page uses the config options `orders_per_page`, which by default is set to 15, which is why the pagination did not show up for you. This is a little unacceptably hidden, and the standard resource controller does not paginate either. I'll PR something up, but the issue is more complex than initally thought.

**Comment by Mandily** [comment]
@mamhoff Where did we land with this? Are you taking care of this in another issue or should I leave this one open?
