### ISSUE TITLE
on 1.3 OrderUpdater#update does call save with hooks -- is this a problem?

### ISSUE THREAD

**Issue by jrochkind** [solidusio/solidus#1228]
I’m running into trouble with some of my legacy (originally spree 2.0, updated little by little) code in solidus 1.3.0.rc1.  I have an Order before_save hook that ends up calling Order#update!.  In solidus 1.3, I get some infinite recursion, as update! calls save which calls my before save hook again -- this did not happen in previous versions. 

So at first I figured, okay, that's different now, got to figure out a workaround in my legacy logic. 

BUT then I noticed a relevant solidus code comment that contradicts solidus code a bit, [above OrderUpdater#update](https://github.com/solidusio/solidus/blob/37b97b4d906013a2ab2a569548bb66c1448332dc/core/app/models/spree/order_updater.rb#L14-L27):

>      # This method should never do anything to the Order that results in a save call on the
>      # object with callbacks (otherwise you will end up in an infinite recursion as the
>      # associations try to save and then in turn try to call +update!+ again.)"

BUT OrderUpdater#update calls persist_totals, which in solidus 1.3 [DOES do a save call on the object with callbacks](https://github.com/solidusio/solidus/blob/37b97b4d906013a2ab2a569548bb66c1448332dc/core/app/models/spree/order_updater.rb#L98-L100). 

It’s got `save!(validate: false)`, so ​_validation_​ callbacks don’t happen, but other ones do.

Which is what’s causing a problem with my code. SO.  If this is the new way it is, then at least that code comment saying #update should never do a save call with callbacks should be deleted -- since it does that now.  OR. Maybe this is a mistake and it shouldn’t do that? 

Any feedback or context very welcome.

**Comment by jhawthorn** [comment]
This was an intentional change #425. We should remove that comment.

**Comment by jrochkind** [comment]
I don't think it is, the before save is intentionally changing some things on the order that probably require it being updated. (It's our own super hacky legacy implementation of store credits from before it was included in solidus, possibly based on an old spree extension by someone else, that does store credits as adjustements).  I mean, it might be possible, but it would require more understanding of this legacy code and of solidus than I currently have. 

I've resorted to setting a 'my_callback_in_progress' to true and then back to false around the order updater, and have the before_save callback return if my_callback_in_progress.  Hacky, but it does the job.

**Comment by jrochkind** [comment]
although maybe i should leave the issue open until someone removes the misleading comment? I dunno.
