### ISSUE TITLE
1.3 Spree::Order#tax_address does not always return an Address

### ISSUE THREAD

**Issue by dholdren** [solidusio/solidus#1229]
[This commit](https://github.com/solidusio/solidus/commit/5dc8dd4fef3d0e874f7190c99d743dce51b74c1c) introduced a fallback for `Spree::Order#tax_address` to `store.default_cart_tax_location`

But `Spree::Store#default_cart_tax_location` returns a `Spree::Tax::TaxLocation` instance, which does not adhere to the `Spree::Address` API, for instance there's no `state` method.

So if I try to call `order.tax_address.state` it fails with `NoMethodError: undefined method `state' for #<Spree::Tax::TaxLocation:0x007f711afef488>` in come cases.

**Comment by cbrunsdon** [comment]
I've been poking into this and there are a few things here.

The biggest API change is ```order.tax_address``` used to return nil if the order had no shipment/billing addresses. That change was made for the very positive reason of cleaning up an orders taxes/zones with regards to what store it is in, but was an undocumented behaviour change for 1.3.

It would have been less obvious (and probably completely unnoticed) if we did more to ducktype the ```Spree::Tax::TaxLocation``` to be more address like.

So I think we should either:

1.  Do more to make TaxLocations behave like addresses
or
2.  Always return TaxLocations (and just build them from the ship/billing address)

**Comment by mamhoff** [comment]
2. implies 1. Would implementing `TaxLocation#state` suffice for your needs, @dholdren? In that case I'd go for that solution in the short run. 

In the medium/long term, I agree that always returning a `TaxLocation` is probably the best solution.

**Comment by kwstannard** [comment]
What about just setting the default location to a read only address instead of having a completely new class?
``` ruby
def default_cart_tax_location
  a = Spree::Address.new(country: Spree::Country.find_by(iso: cart_tax_country_iso))
  a.readonly!
  a
end
```

**Comment by jrochkind** [comment]
`readonly!` will make that particular in-memory copy refuse to save changes, but some other part of code could still change the same row in the db.

**Comment by kwstannard** [comment]
@jrochkind that is fine since this address is not a record in the DB.

**Comment by jhawthorn** [comment]
I don't think this is an issue. Relying on duck typing and `Address` and `Tax::TaxLocation` quacking the same way is the best way to deal with this IMO.
