### ISSUE TITLE
ShippingMethod display: backend does not work properly

### ISSUE THREAD

**Issue by Murph33** [solidusio/solidus#1237]
Setting a shipping method to display backend makes it not be displayed anywhere.  

https://github.com/solidusio/solidus/blob/master/core/app/models/spree/stock/estimator.rb#L14

https://github.com/solidusio/solidus/blob/master/core/app/models/spree/shipment.rb#L175-L198

https://github.com/solidusio/solidus/blob/master/backend/app/views/spree/admin/orders/_shipment.html.erb#L50-L52

The main (only?) way of generating shipping rates does not take a param to pass to the Estimator which defines new shipping rates so we always have `frontend_only = true`.  The shipping methods usable in the backend are found off of a shipments shipping rates.  In the front end shipping methods are commonly shown to customers through the shipments shipping rates so any order looked at in the backend would give the customer access to those shipping rates.

**Comment by florianguenther** [comment]
What is the preferred solution for this?
Is someone working on the issue?

**Comment by ericsaupe** [comment]
Is this resolved with #1984?

**Comment by jhawthorn** [comment]
I believe so
