### ISSUE TITLE
Move reports to their own gem

### ISSUE THREAD

**Issue by isaacfreeman** [solidusio/solidus#1262]
Working on PR #1250 prompted a discussion with @dhonig, wherein we agreed that having reports in Solidus is a two-edged sword. It's pretty easy to write a report that chews up all available resources and degrades performance on the same server that's serving the front end to customers. On the other hand,  the convenience of having reports right there in Solidus Admin is valuable for many merchants.

It would be good to encourage developers to make a conscious decision about how reports should be provided for each client. Moving them out of the main Solidus distribution into a separate gem would provide that decision point.

**Comment by jhawthorn** [comment]
This makes sense to me. The builtin reports section has been [stagnant for a long time](https://github.com/solidusio/solidus/commits/master/backend/app/controllers/spree/admin/reports_controller.rb) (at least before #1250, which looks great). Moving them to a gem I hope would allow for making faster and more opinionated changes. I'm sure there are more "common" reports we could share in an extension which are desirable across many stores.

**Comment by jacobherrington** [comment]
#2814 will close this issue.
