### ISSUE TITLE
Add hint tooltips to fields in the admin

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#1266]
In #1261 we introduced hint tooltips to help describe fields in the admin.

![](http://i.hawth.ca/s/UnN2Qttw.png)

Currently there's only one defined (Product promotionable), you can see aaef78d835444dd669c83ba0a49e88508892e150 as an example of how to add one. We don't want hints on every field, but it would be nice to have them on all fields whose purpose is non-obvious.

**Comment by agustifernandez** [comment]
So a PR to add tooltips would make sense if someone was to give this a try? I would like to give back to core but need easy/simple entry-level stuff to be able to commit to it and success.

**Comment by mamhoff** [comment]
@agustifernandez Yes, it'd be great if you could take a go at this. Good examples for not-so-easy-to understand form fields are: 

* `Variant#tax_category` (is an override, if not set, takes over the product)
* `Product#shipping_category`
* `Product#tax_category`
* `Price#country` (if empty, the price is valid for all countries)

**Comment by jhawthorn** [comment]
We have added a few, I don't think this issue is helpful to leave open without specific recommendations
