### ISSUE TITLE
Impressions of a new user/developer

### ISSUE THREAD

**Issue by Kingdutch** [solidusio/solidus#1270]
On Slack @jrochkind and @mamhoff asked me to write down my experience with solidus, questions that may arise when first using Solidus so we can see where documentation could be improved.

My biggest questions when I first came to Solidus was pretty much, "what's the 30000 ft view?". There's the 5 modules (api, backend, frontend, core and sample). They have a short one line description in the main README but if you click on their links and find their own README's, they're lacking in explaining what the module provides. 

For example, I don't like the default front end layout and just want a landing page with the two products I have so I probably don't need the front-end module. However I could be wrong and this functionality could be provided but I have little way of knowing this at the moment without going through the code.

I'm approaching Solidus very much from a developer point of view. I want to build a subscription service website (think Loot Crate). For me the most important part is figuring out which functionality comes packed (and where) and where I need to go to start extending stuff. For me personally that extension is in the payment section aimed at the European market. 

This also brings us to the contributed modules, I realise it's not something you can directly control but it's something you can influence. I'm currently not sure which modules are in a usable state for which version of Solidus as Solidus is rapidly changing. Some of the README's of the smaller modules sadly follow the barren examples of the solidus module. 

My finaly question, again regarding payment, would be: what would the best way to implement a new payment method at the moment.
1) Follow the changes that have been made with respect to the introduction of a Spree::Wallet and implement as a PaymentMethod
2) Implement as a method for ActiveMerchant, which has an available thin wrapper in solidus_gateway (which to be honest, should probably just have been named, solidus_active_merchant for clarity). This has the advantage that it could be used by me or others in other projects, but I'm not sure how well that would integrate.

A final question that just popped to mind is an explanation of what exactly solidus_auth_devise does. I understand it is an integration of Devise into Solidus but at the moment it very much seems like Devise is the only option (I've heard in Slack it's not).

Coming back to the purpose of extending, security and authorization is a big part of that. Some explanation of how user permissions are implemented. By browsing the issues I saw that cancan was used. 

Personally I'm a great fan of the way Drupal handles roles and permissions. It's very extendable and highly configurable from a user's perspective. It would avoid an issue I saw coming by where e-mail's for Super Users were uneditable but no other roles could be included because it couldn't be known what they were. 

EDIT: I do realise some of these things can be mitigated because this project follows common Rails structure. That's what has helped me out so far, but IMHO code should not be the first place to look.

**Comment by jasonfb** [comment]
@Kingdutch -- the (lack of good) documentation on Solidus is an issue. I have brought it up with various folks and also proposed we form a 'documentation squad' to seriously address the lack of documentation.

On a very macro level, speaking about Solidus + new developers, I would give you this word of perspective: Solidus is not for beginners. After having worked with Spree for years and mentored many devs on Spree, I would say it's not even for intermediate level developers. 

You need to be a strong dev and also have great debugging skills, as well as know some internals of how Ruby behaves. This fact is somewhat an artifact of how it was built, and somewhat just _it is what it is_. 

For this reason, I believe there was a little bit of a lack of interest in the old days (the Spree days) to even write thorough documentation for newbies. 

If you are a small outfit, you don't have a team of Rails developers on staff and you aren't prepared to hire a team of experienced Rails developers, **you're better off with Shoppify or WIx or Squarespace.**. (And by "you" I mean someone who wants to start an E-commerce website, not "you" a developer.)

So basically even though you may have seen Spree commerce's old glossy marketing website that makes it look "easy," Spree/Soldius is not easy. And I'm just talking about the basics--- let alone the stuff I myriad of stuff have to deal with on our high-volume website (which is true for most Rails apps, but somehow Spree/Solidus seems to make live production bugs very unpleasant to debug)

I definitely think the README needs to get replaced-- not just augmented and tweaked --- _replaced_  ---  but a whole new set of documentation & guides. 

>> However I could be wrong and this functionality could be provided but I have little way of knowing this at the moment without going through the code.

You may or may not be right actually, as someone recently reported that in Solidus 1.3.0 RC core there was code that depended on solidus frontend. (That code shouldn't have been there as yes, you are correct to assume they are intended to be a la carte)


>> I'm currently not sure which modules are in a usable state for which version of Solidus as Solidus is rapidly changing.

The idea here is that http://extensions.solidus.io will help you out for that. Yes, attrition is a problem.

>> I understand it is an integration of Devise into Solidus but at the moment it very much seems like Devise is the only option

Correct you can define your own User class, and provide your own auth, but devise is widely adopted across the Rails industry. It's more like, you "can" do this, but if you do you are on your own.

>>Coming back to the purpose of extending, security and authorization is a big part of that. Some explanation of how user permissions are implemented. By browsing the issues I saw that cancan was used.


I am inferring from your meaning that by "authorization" you mean "access control" . TBH, there actually isn't much in the way of Roles & permissions (although I think a basic User/Admin roles are created automatically), and yes it uses cancan. 

Most of the stores I know have to implement the granularity of access control themselves, which involved customizing both your ability.rb file and also wrapping certain sections of code or views in ```if can? ``` statements.

As far as security, we are all concerned with security. (You should see my production logs of robots hitting the site looking for .Net vulnerabilities!). Being on an OS platform means that everyone is scrutinizing the code we all share, and when a vulnerability is uncovered it gets patched quickly. Compared to a lot of the other web industry, Rails + Solidus is on secure side of things.

**Comment by Kingdutch** [comment]
I can understand that for an eCommerce system such as Solidus there are many moving parts and so it's not easy to just jump in and get going. I'm still of the believe that there should be, even for expert developers, better starting points than the code itself.

I'm not sure where to place myself on the developer level scale. I've been building websites for a bit over 12 years. Rails has only been a part of that for 6 months now (I've probably missed out) but I have seen a few other ways of implementing eCommerce, mostly in other languages so I feel like I should be able to utilise Solidus.

> you're better off with Shoppify or WIx or Squarespace..

I have looked at each example named (and a few more) and although I love development, my goal at this moment is to get something off the ground, sadly each of the existing solutions with the features I want doesn't provide the iDeal and SEPA payment options (which account for 80% of the Dutch market). Which leaves me with little choice but to roll my own. 

What I've seen of Solidus so far makes me believe that it can be a great solution, I just have to figure out how.

**Comment by jrochkind** [comment]
I agree with warning people that Solidus is basically a framework, a tool for programmers, and probably not for beginners. 

I'm an experienced Rails developer, I've figured out Spree-then-Solidus, partly with the help of colleagues who already were familiar with it (not sure how they've figured it out) -- but I still think some better docs are a good idea. Heck, any docs are a good idea. :)  

I made use of the Spree docs (before I had switched to Solidus), and found them very helpful even though they are incomplete and occasionally wrong. But someone coming to Solidus doesn't neccesarily know to look at the Spree docs, and they'll become less useful as Solidus continues to diverge.  

Different people learn different ways, I'm a lover of documentation. Docs are never going to eliminate the need to code-read sometimes/eventually (heck, we all need to dive into Rails code itself sometimes), but they're still very useful to give you a foundation.  You need to have an audience in mind when doing any writing, and I agree the audience for Solidus docs is devs with some substantial ruby/Rails experience, not complete beginners.  Solidus is complicated stuff, and even an experienced developer (depending on learning style/preferences) needs docs to provide a foundation for understanding the parts and how they fit together, the intended golden paths and installation procedures, etc. 

I understand that the main reason there aren't really any Solidus docs yet is just limited resources and that nobody's gotten around to it, not anti-doc sentiment.

**Comment by bbuchalter** [comment]
> My biggest questions when I first came to Solidus was pretty much, "what's the 30000 ft view?". There's the 5 modules (api, backend, frontend, core and sample). They have a short one line description in the main README but if you click on their links and find their own README's, they're lacking in explaining what the module provides.

I thought this was a very reasonable request. Here's a stab at getting started for core: https://github.com/solidusio/solidus/pull/1273

**Comment by jhawthorn** [comment]
Thanks for the feedback. We're continuing to improve our docs and new user experience. Some good work has already come from this (like Brian's addition of READMEs to the subprojects)

Closing this due to lack of actionable steps.
