### ISSUE TITLE
Split solidus modules into separate repo's

### ISSUE THREAD

**Issue by Kingdutch** [solidusio/solidus#1285]
Currently solidus is set-up to be a modular framework where you could use just solidus_core or solidus_core and solidus_backend without any other modules. However, there's currently no way for me to pull in the github version of just one of these gems.

I would like to propose to split off the solidus_x modules into separate repositories and have the solidus repository be the repository that will install all the modules like it happens now when you put `gem solidus` in your Gemfile.

As far as I can currently see this won't necessarily break anything as anything relying on a module can still do so and anything relying on the main solidus repo can also still do that.

It does however have the advantage of more clearly showing that the modules are able to function without one another. 

This request comes from me trying to install solidus_core and solidus_backend and running into something that felt like a dependency on solidus_frontend. I'll try to reproduce that in a separate issue but I believe my request above still holds merit even if that feeling was caused by something I did wrong.

**Comment by jhawthorn** [comment]
You can easily use the github version of just one gem in your `Gemfile`
``` ruby
gem 'solidus_core', github: 'solidusio/solidus'
```

It's not uncommon to group multiple gems in the same repository. Rails does this, for example. There's many advantages to this approach: PRs can include changes anywhere, we're always testing all the projects on any change (important for changes to core/api), and it's easier organizationally. It's also important that we keep the entire git history of this project.

I don't foresee us doing this.

**Comment by Kingdutch** [comment]
Thanks for the reply explanation and for showing me a new bundler trick :blush:
