### ISSUE TITLE
Can't view stock transfer if variant has been soft-deleted

### ISSUE THREAD

**Issue by isaacfreeman** [solidusio/solidus#1293]
Visiting `/spree/admin/stock_transfers/transfer_number` results in a crash if one of the TransferItems refers to a variant that has since been deleted.

Obviously we don't want create new stock transfers for deleted variants, but I think we should be able to look at old stock transfers even if they refer to variants that are no longer available.

If there are no side-effects I'm unaware of, we should be able to fix this in https://github.com/solidusio/solidus/blob/master/core/app/models/spree/transfer_item.rb by changing

```
belongs_to :variant
```

to

```
belongs_to :variant, -> { with_deleted }
```

**Comment by jhawthorn** [comment]
This was fixed by #1294
