### ISSUE TITLE
Deprecation warning: #table_exists? Use #data_source_exists? instead

### ISSUE THREAD

**Issue by Kingdutch** [solidusio/solidus#1310]
(For Rails5)

The way table_exists? functions before Rails 5 has been deprecated. As of version 5.1 it will only check for the existence of tables instead of both tables and database views as is the current behaviour.

This is used in a few migrations. I think Solidus doesn't actually create any views by itself so `#table_exists?` is probably fine. However, it's not unimaginable that someone replaces a certain table with a view made up of multiple tables and Solidus would probably want to know.

Should we rename the calls of `table_exists?` to `data_source_exists?` or should they not be renamed and is the new behaviour desired?

**Comment by jhawthorn** [comment]
Done in a6163f20c3c44b022b775ae0ea76a7b9a042e2f0.

Either behaviour is fine for how we're using it in migrations, so we might as well use the one which doesn't generate warnings.
