### ISSUE TITLE
Add tooltip usage to the Solidus style guide

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#1321]
I'd like to add some more context around when to use tooltips and which one to use. I'd like to add a two column layout to the style guide with the explanation on one side and the example and code on the other. Forgive the bad markdown table to demo.

Tooltips should only be used to add supplementary information to the object they’re being attached to. They should never hide content that a user needs to complete a task. This includes simple form field helper information like required input formats (ie DD-MM-YYYY)

| Type | Example |
| --- | --- |
| **Info tooltips** These are used to add supplementary information to form labels. The info icon is the coverable area for this tooltip and should be placed at the right side of the form label. | [Code and example for this tooltip goes here] |
| **Action icon tooltips** These are used to add textual context to the action icons used with tabular data like edit, delete, and clone. They are styled with a similar colour to the icon that they’re attached to. | [Code and example for this tooltip goes here] |

**Comment by tvdeyen** [comment]
I like that. Excuse me for correcting the markdown table 😊

**Comment by Mandily** [comment]
I missed the leading paragraph. I've just updated it. Thanks @tvdeyen for the headings. Much better.

**Comment by gus4no** [comment]
On it

**Comment by jhawthorn** [comment]
Fixed by #1955
