### ISSUE TITLE
Cannot add adjustments using Spree::Importer::Order

### ISSUE THREAD

**Issue by Elffers** [solidusio/solidus#1322]
I am trying to add an adjustment using the `Spree::Importer::Order` object. It appears that it should be able to based on [this](https://github.com/solidusio/solidus/blob/60ee1dffc7c3932cd7652cc2b4566f08a12f74b8/core/spec/lib/spree/core/importer/order_spec.rb#L345) spec, but it appears that `adjustments_attributes` are not listed as a permitted parameter based on looking [here](https://github.com/solidusio/solidus/blob/60ee1dffc7c3932cd7652cc2b4566f08a12f74b8/core/lib/spree/core/controller_helpers/strong_parameters.rb) and [here](https://github.com/solidusio/solidus/blob/60ee1dffc7c3932cd7652cc2b4566f08a12f74b8/core/lib/spree/permitted_attributes.rb). Is this a known issue?

Thank you!

**Comment by mamhoff** [comment]
Are you using the importer via the API or directly? Because within the importer class, there is no mention of `StrongParameters` or permitted attributes. It appears to just take in a params hash, and that should work (as the spec suggests). 

That said, adjustments are tricky, and there's a bunch of things that can go awry when dealing with them. Can you provide more details as to what specifically you're trying to do, and where and how it errors out?

**Comment by Elffers** [comment]
I am trying to incorporate a shipping price into the total amount charged for an order, but shipping is simply calculated as a flat rate based on which country we are shipping to. It seemed easier to use adjustments rather than going through the actual Shipment phase, since that has a lot of needless complexity.

I am using the Importer in an action override of the frontend Spree::OrdersController.

**Comment by mamhoff** [comment]
Adjustments are, unfortunately, not as easy as they look. I recommend going through the shipment phase as adjustments (at the moment) can only be tax or promo adjustments, and there is not such thing as shipping adjustments (apart from actually adding shipments). Going through creating shipments is also more close to standard Solidus behaviour, which will make things easier if you add more bells and whistles to your shipment behaviour. Also: the shipment system is complex, but also really quite powerful.

**Comment by swcraig** [comment]
There doesn't appear to be any further action required. May we close this?

**Comment by mamhoff** [comment]
Yeah, closing.
