### ISSUE TITLE
taxon permalink query contains extra slash

### ISSUE THREAD

**Issue by cheneveld** [solidusio/solidus#1335]
[In this product scope helper method](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/product/scopes.rb#L245) queries on taxon permalinks ending in a slash.  But it seems like permalinks are not stored in the db with trailing slashes.

I don't see this helper method and the [corresponding search scope](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/product/scopes.rb#L73) (in_taxons) being used in the project, but I ran into this after building some custom product filters.

**Comment by jhawthorn** [comment]
This issue was filed first, but #1549 covers the same issue and now has more infromation.

**Comment by jumph4x** [comment]
https://rubygems.org/gems/canonical-rails/versions/0.2.7
