### ISSUE TITLE
Multiple Payment Methods not working in Admin

### ISSUE THREAD

**Issue by ericsaupe** [solidusio/solidus#1336]
With the changes in 1.3 the javascript on `admin_order_payments_path` is no longer firing. It looks like it is because `#new_payment` is gone.

https://github.com/solidusio/solidus/blob/master/backend/app/views/spree/admin/payments/new.html.erb#L13 renders 

```
<form class="edit_payment" id="edit_payment_3126575" action="/admin/orders/:order_id/payments" accept-charset="UTF-8" method="post">
  <input type="hidden" name="_method" value="patch">
...
</form>
```

and the javascript for that page is looking for `#new_payment` https://github.com/solidusio/solidus/blob/master/backend/app/assets/javascripts/spree/backend/payments/new.js#L3

This causes issues if there are more than one payment method set up where the form will submit all fields even for non-selected payment methods.

It's also rendering the `patch` hidden method and as far as I can tell there is no `PATCH` path for admin payments which causes `No route matches [PATCH] "/admin/orders/:order_id/payments"`

**Comment by gmacdougall** [comment]
Hi Eric,

I'm taking a look at this issue and am having trouble reproducing the issue in a sandbox environment. Currently, when I attempt to add a payment to an existing order in the admin it correctly shows the `#new_payment` form.

Looking at the result that you are seeing, you have `id="edit_payment_3126575"` in your result, which shows that the payment has an ID.

Looking at your solution, you've removed a `payments.build` call. In a basic Solidus store, `payments.build` should not persist the record.

Example:

`Spree::Order.first.payments.build.id` #=> nil

Could you please provide more information on how to reproduce this issue in a Solidus sandbox store.

Thanks!

**Comment by ericsaupe** [comment]
Honestly, it may be some obscure customization we have going on. I also was not able to reproduce it in a vanilla Solidus build so I'd be OK closing this.
