### ISSUE TITLE
Payment#process! can over-authorize in some cases

### ISSUE THREAD

**Issue by jordan-brough** [solidusio/solidus#135]
See the comment from @gmacdougall here: https://github.com/solidusio/solidus/pull/134#discussion-diff-33771788

If auto_capture=true and you call `Payment#process!` on a payment that has already been authorized then I believe we will end up doing a new auth+capture (at least in the Braintree gateway code I looked at), leaving the previous auth stranded and over-authorizing on the user's card.

**Comment by bbuchalter** [comment]
@jordan-brough do you believe this is still an issue that should remain open?

**Comment by cbrunsdon** [comment]
Closing due to our suspicion this is now fixed or no longer a problem. Please re-open if anyone is having same issues.
