### ISSUE TITLE
User search is broken on promotion edit page

### ISSUE THREAD

**Issue by jeremyw** [solidusio/solidus#1350]
Entering a search term for a user rule on a promotion does not filter the results.

I've attached a screenshot that shows the search field that doesn't work.

https://github.com/solidusio/solidus/pull/1349 fixes this.

<img width="534" alt="screen shot 2016-07-24 at 4 33 30 pm" src="https://cloud.githubusercontent.com/assets/12091/17086308/75dcb020-51bc-11e6-92a0-3f75582613b0.png">

**Comment by jhawthorn** [comment]
Fixed by #1349
