### ISSUE TITLE
Blue Steel Theme is Green Still on the right side

### ISSUE THREAD

**Issue by flyfy1** [solidusio/solidus#1351]
![image](https://cloud.githubusercontent.com/assets/1553760/17092512/cd5a4452-5275-11e6-822e-80247baa2dfe.png)

I feel there's a bit of in-consistency with the BlueSteel colours.. it's basically only colouring the menus, leaving the right hand side sticked to the origin theme..

So it's a bit wired.. on the left it's dark colour, and on the right it's bright colour

**Comment by Mandily** [comment]
The Blue Steel theme is a work in progress, which is also why it's optional. When @Sinetheta moved the navigation to the left, he cleaned up the css so it would be easy to [update with the blue steel colours](https://stembolt.com/blog/customizing-the-solidus-admin-styles/), and then provided that colour palette if users wished to turn it on. 

It's on our to do list, but we won't be updating the main content visual brand until we've finished up some of the higher level items like implementing bootstrap grids and cleaning up forms. #1078
