### ISSUE TITLE
Stock::Coordinator incorrectly splits packages

### ISSUE THREAD

**Issue by adaddeo** [solidusio/solidus#1366]
On a 1.3 sandbox store:
1. In the admin, create a new order
2. Add 1 unit of any item
3. Update the quantity of item to 2
4. Enter customer details (anything will work) and update
5. Two shipments are created, each with 1 item

**Comment by jhawthorn** [comment]
Confirmed. Looks like it's realated to an `OrderStockLocation` record being careted, which are used to configure packages specifically for one location.

**Comment by DanielePalombo** [comment]
@jhawthorn i'm working on this issue, I'm almost done

**Comment by DanielePalombo** [comment]
@adaddeo Have you try if my PR resolve your issue?

**Comment by jhawthorn** [comment]
This should be fixed by #1709, which bypasses the "location configured package" feature, which is what caused the separate shipments.
