### ISSUE TITLE
Long server load time with many Taxons

### ISSUE THREAD

**Issue by skukx** [solidusio/solidus#1380]
The file at https://github.com/solidusio/solidus/blob/master/api/app/views/spree/api/taxons/index.v1.rabl attempts to load every child taxon from the parent.  The problem is that we have thousands of child taxons.  This results in the server trying to load a redundant amount of taxons from the database when only 50 are being displayed.  Load times are easily greater than 1 minute because of this.

**Comment by bbuchalter** [comment]
Please see https://github.com/solidusio/solidus/pull/1331
