### ISSUE TITLE
Setup heroku 'review apps' for pull requests

### ISSUE THREAD

**Issue by athal7** [solidusio/solidus#139]
It will be easier to review pull requests with the auto-creation of a [review app](https://devcenter.heroku.com/articles/github-integration#automatic-deploys)

**Comment by cbrunsdon** [comment]
I agree with this, @jhawthorn what are your feelings? It doesn't look like it'll be a huge job to set up (but its heroku, so who knows).

**Comment by jhawthorn** [comment]
I'm unable to connect heroku to github.

**Comment by jhawthorn** [comment]
I think this is way more work than it's worth. As far as I can tell we would need to write a custom buildpack in order to bundle install, generate the sandbox application, and use that directory as our app.

@athal7 I'm closing this. If you're interested in pursuing it please reopen.

**Comment by athal7** [comment]
@jhawthorn sounds good, thanks for looking into it

**Comment by BenMorganIO** [comment]
@TeatroIO is also an alternative which, honestly, is faster for implementation, but I don't think anyone ever used it on Spree. Its broken half the time.

Are we sure a review app would really help with the workflow?

**Comment by jordan-brough** [comment]
Fwiw this seems like something that is usually not used but is occasionally super handy (for showing off/discussing UI changes).  I know spree/spree used teatro at least for a while, though having it leave comments on the PRs was super annoying.  Anyway, if someone did find time for this I think it would be cool.

**Comment by BenMorganIO** [comment]
We should probably ask Teatro to add something when we want to skip @TeatroIO. Something like `[skip-teatro]` at the bottom of a PR might be nice.

But it is super handy and I'm enjoying it with Whole New Home.
