### ISSUE TITLE
Remove solidus_frontend from the solidus gem dependencies

### ISSUE THREAD

**Issue by athal7** [solidusio/solidus#141]
Since it is used by a subset of solidus users, if we remove it, then core features can be built more quickly, and those using solidus_frontend can keep that up to date as the need arises.

Will also want to prevent other extensions from requiring solidus_frontend directly so that people can exclude it if they desire.

**Comment by cbrunsdon** [comment]
There are a few plans on the table which have been discussed, like splitting up into (multiple?) gems that provide just controllers and additional gems to provide frontend views (bootstrap?  foundation? API-only?), but nothing concrete has been decided and this isn't going to be the place we discuss it.
