### ISSUE TITLE
Invert implicit order progressing behavior

### ISSUE THREAD

**Issue by athal7** [solidusio/solidus#143]
Rather than using state machine and ActiveRecord callbacks for order calculation and state progression, it would be nice to have an explicit interface for making changes to an order, both for performance reasons of not doing the same calculations multiple times, and for ease of development / testing.

**Comment by cbrunsdon** [comment]
There isn't any reasonable information here for a person to tackle to improve the codebase. Something we definitely want to do, but closing as we want more actionable issues.
