### ISSUE TITLE
How to get multiple orders from several vendors paid in batch? 

### ISSUE THREAD

**Issue by kevin-jj** [solidusio/solidus#1431]
It looks like solidus only supports to check out some items from ONE vendor.

**Comment by tvdeyen** [comment]
Thanks to your interest in solidus. 

Could you please ask such question in the Slack support channel? The github issues are for reporting bugs. You can join he Slack at http://slack.solidus.io

If you think this is a bug, we need some more information. First and foremost we need a reproducable test case.
