### ISSUE TITLE
No flash[:error] when updating user in backend

### ISSUE THREAD

**Issue by ericsaupe** [solidusio/solidus#1436]
In the admin/users_controller#update method there is no call to display what errors happened if the user doesn't save. This has caused complaints from our users who are confused why some actions aren't taking effect even though the page reloads.

https://github.com/solidusio/solidus/blob/master/backend/app/controllers/spree/admin/users_controller.rb#L36-L48

**Comment by mamhoff** [comment]
I think this issue is fixed via #1487 .
