### ISSUE TITLE
Investigate missing "inverse_of" relationships

### ISSUE THREAD

**Issue by jordan-brough** [solidusio/solidus#1452]
See https://github.com/solidusio/solidus/pull/1420.  It appears that Rails isn't automatically adding `inverse_of` to at least some of our relationships.  We should investigate and add more `inverse_of`s or fix the underlying problem.

**Comment by peterberkenbosch** [comment]
Some background information: http://guides.rubyonrails.org/association_basics.html#bi-directional-associations

**Comment by bbuchalter** [comment]
For the sake of good record keeping, https://github.com/solidusio/solidus/pull/1406 also addresses this issue.

**Comment by kennyadsl** [comment]
We added `inverse_of` everywhere it's needed.
