### ISSUE TITLE
checkout_flow - Error after checkout

### ISSUE THREAD

**Issue by bonekost** [solidusio/solidus#1456]
Hey,
after adding decorator for checkout_flow

```
#app/model/spree/order_decorator.rb
Spree::Order.class_eval do
  checkout_flow do
    go_to_state :delivery
    go_to_state :address
    go_to_state :payment
    go_to_state :confirm
    go_to_state :complete
  end
end
```
and adding Spree::Auth::Config[:registration_step] = true in initializer,
I try to go to cart and then go to checkout. Registration form appears. 
That's OK, BUT when I try go back to cart I have added shipping method in cart even I didn't choose and I cant continue with checkout because I got error:
`StateMachines::InvalidTransition in Spree::OrdersController#update`
`Cannot transition state via :next from :cart (Reason(s): Customer E-Mail can't be blank)`

Rails: 4.2.6

Thanks for any advice

**Comment by cbrunsdon** [comment]
After logging in (or registering) do you have a user or email address associated with the order? It looks like you are logged in but the user isn't associated to the user.
