### ISSUE TITLE
How to upload images for products using Spree Commerce REST API 

### ISSUE THREAD

**Issue by bbrangeo** [solidusio/solidus#1482]
Can you give me an example?

ex: 
curl -i -X POST -H 'X-Spree-Token: 7b9f789b3b90f66f26a62de477159fbd4950459c30b42ba1' -d 'product[name]=toto&product[price]=100&product[shipping_category_id]=1&product[description]="Description"&**_product[image]=...... ?????_**

Thanks

**Comment by stewart** [comment]
Hi @bbrangeo,

There is a specific [`Api::ImagesController`][code] used to upload images that you might find useful, as well as [tests][] for further reference.

[code]: https://github.com/solidusio/solidus/blob/master/api/app/controllers/spree/api/images_controller.rb
[tests]: https://github.com/solidusio/solidus/blob/master/api/spec/controllers/spree/api/images_controller_spec.rb

In the future, please ask support questions in the **#support** channel of the [Solidus Slack](http://slack.solidus.io).
The GitHub issues are for reporting bugs.
