### ISSUE TITLE
Unpermited Params in Stock Item Controller

### ISSUE THREAD

**Issue by ajkamel** [solidusio/solidus#1501]
When using the latest version of Solidus I've had issues trying to adjust the inventory getting unpermitted params.  

I've put together a hack that allows me to remove the params so that we can update the inventory accurately.  

`%w[force id stock_location_id created_at updated_at deleted_at].each{|v| params.require(:stock_item).delete(v)}`

If this is confirmed I can put together a PR to address this.

This is in relation to #811

**Comment by bbuchalter** [comment]
I believe this issue can be closed now that https://github.com/solidusio/solidus/pull/811 is merged?

**Comment by tvdeyen** [comment]
Thanks for pointing us here.
