### ISSUE TITLE
SolidusI18n  error

### ISSUE THREAD

**Issue by useiichi** [solidusio/solidus#1511]
I see forrowing error at  Admin-Settings.
when I remove a line "gem 'solidus_i18n'" from Gemfile, I don't see this error.

NameError in Spree::Admin::GeneralSettings#edit

Showing /var/www/solidus/backend/app/views/spree/admin/general_settings/edit.html.erb where line #71 raised:

uninitialized constant SolidusI18n::LocaleHelper::Locale

Extracted source (around line #18):
16    # this project. solidusio/solidus now has those keys.
17    def all_locales_options
18      Locale.all.map { |locale| locale_presentation(locale) }.push(['English (EN)', :en])
19    end
20
21    private

**Comment by mtylty** [comment]
@useiichi I think this is related to the [solidus_i18n](https://github.com/solidusio-contrib/solidus_i18n) extension, you'd better open an issue there.

That said, I tried adding the solidus_i18n extension to the sandbox app but I was unable to reproduce this bug.

**Comment by useiichi** [comment]
thanks for.
I'm going to open an issue in solidus_i18n.
