### ISSUE TITLE
Order behavior when currency is changed.

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#1515]
What happens when the order currency is changed? Is this behavior somehow supported?

I think we should recalculate prices for all line items and adjustments with the new currency or delete the whole order and create a new one. Both options could cause issues, especially if the user is into an advanced checkout step. Do you have any thought about this?

**Comment by gmacdougall** [comment]
I don't think that orders should be allowed to change currency. There's too much complication around it. If someone needs that functionality in their application, they can implement it on their own, but it's complicated enough that we should be very careful about supporting the functionality.

Some items may not have prices or availability in other currencies, migrating promotions, taxes, etc. would be complicated under a currency switch. The easier solution is for us to give them a new order with a new currency when they switch, which is what should happen if `current_currency` changes.
