### ISSUE TITLE
Loading wrapper upon XHR request

### ISSUE THREAD

**Issue by flyfy1** [solidusio/solidus#1518]
Currently, in `solidus_backend/app/assets/javascripts/spree/backend/progress.coffee`, it listens to ajax request globally. Whenever there's a AJAX request, the progress bar would show, something like this:

![image](https://cloud.githubusercontent.com/assets/1553760/19334954/3f1fe952-9132-11e6-9fce-8f8513d1e02e.png)

and this progress bar as a overlay would stop any activities on the backend interface.

When I was trying to provide a Direct File Upload from the Admin Backend, I build something like this:

![image](https://cloud.githubusercontent.com/assets/1553760/19335003/925231ca-9132-11e6-8e81-205abd89a590.png)

The idea as to let user upload images async.

However, the issue is that.. when a image is uploaded, the `Loading` would popup, and disable user from doing anything, until the upload is done (i.e., the AJAX request completes).

Any idea on how to solve this issue?

**Comment by mtomov** [comment]
I would love to see the direct image upload land in core of solidus! It's such a pain to upload images!

@tvdeyen  I know you'd share my suffering, so just pinging you for solidarity : )

**Comment by tvdeyen** [comment]
@mtomov you have my full solidarity. I would like to port Alchemys image upload over to Solidus. It's heavily based on https://github.com/blueimp/jQuery-File-Upload. Will see if so can free some time these days. The current image upload is just ridiculous, but as many stores don't even use the build in image solution and use services like Cloudinary, there was not much demand for a better solution yet. But anyway, this needs to be fixed. 

@flyfy1 I don't see an easy solution. As others will also be bothered by this we should think about replacing this with a custom trigger or event that all our own XHR requests call when we do expensive stuff. Any thoughts @jhawthorn?

**Comment by aitbw** [comment]
I think this can be closed as per #1553, can you confirm this @kennyadsl ?

**Comment by tvdeyen** [comment]
Yes. Thanks for that find.
