### ISSUE TITLE
How to translate solidus in Nepali?

### ISSUE THREAD

**Issue by bishisht** [solidusio/solidus#1527]
I would like to use spree in a village ecommerce system and for that I have to translate spree completely in Nepali. Please suggest some guides/links. Any ideas are welcome.

**Comment by tvdeyen** [comment]
Hey. Thanks for your interest in Solidus. 

The Solidus I18n project holds all translations. You can find it here https://github.com/solidusio-contrib/solidus_i18n

It will be helpful to also read the Rails I18n guides (http://guides.rubyonrails.org/i18n.html)

To get started it will help you to copy the English locale file to a Nepalis locale file and start translating in your local app. Then contribute by creating a pull request. 

If you have further questions please join the Slack at http://slack.solidus.io
