### ISSUE TITLE
Creating a new Spree::Price in admin requires a Country

### ISSUE THREAD

**Issue by chrisradford** [solidusio/solidus#1530]
# Issue

When creating a new price through the admin interface (Products > Prices > New Price), and setting both the product variant, and currency, Solidus gives a validation error on Country.

### Expected behaviour

It is expected that creating a price without a currency is possible in order to add prices for new currencies to existing variants.

### Possible Cause

In Spree::Price there is a validation for presence on country, the exception seems to only apply to existing records, although the edit screen does not allow the country to be changed.

--

I've had a look for an existing Issue relating to this but can't find one. I've also checked and believe this to be related to code in Solidus Core.

I'm happy to open a PR if this is an issue. Thanks :)

**Comment by mamhoff** [comment]
Hey @chrisradford , are you on Solidus master? It should be fixed there, via this PR https://github.com/solidusio/solidus/pull/1468 .

**Comment by chrisradford** [comment]
We're tracking slightly behind master, but we can pull that into our branch. Thanks!
