### ISSUE TITLE
Order total not taking promotion adjustments into account after applying a promo code.

### ISSUE THREAD

**Issue by dgra** [solidusio/solidus#1531]
@jordan-brough I posted in the support channel in slack and was told to mention you on an issue with the included information.

> I am hoping you guys can help me. We are in the process of upgrading from v1.3 to v1.4 but we are 
> seeing a problem when we apply a coupon to an order. What happens is that everything executes
> correctly except that when the page reloads, the order total hasn't taken the promotion adjustment
> into account. This is happening on our site using any line item adjustment. The first place we looked
> was at how our adjustments were being created and we have changed our
> `source.adjustments.create!`'s to `adjustable.adjustments.create!`'s. 
> 
> More info: 
>  If I use a local branch of Solidus
>     https://github.com/solidusio/solidus/blob/v1.4/core/app/models/spree/order_updater.rb#L79
>   returns updated information. Most notable is my `line_item#promo_total` takes into account the promotion adjustment but 
>    https://github.com/solidusio/solidus/blob/v1.4/core/app/models/spree/order_updater.rb#L81
> doesn't pull in the updated line items to calculate `order#promo_total`
> 
> Any advice or directions to look into would be greatly appreciated.
> Sorry if this is information overload.

**Comment by flyfy1** [comment]
Hi I've just noticed your issue. I think my latest pull request solves the issue: #1591

**Comment by flyfy1** [comment]
@dgra I've further looked into this issue.. for your case, did u use `create_quantity_adjustments` action?

**Comment by dgra** [comment]
@flyfy1 Hi, thank you for looking into this. I was not using the `create_quantity_adjustments` action. I believe I was using the `create_item_adjustments` action when I ran into this problem.

**Comment by flyfy1** [comment]
@dgra I'm looking into this issue cuz I was facing sth similar.. Are u able to replicate the issue on the master branch of solidus? If u can.. could u post a screenshot indicating the issue~? Thanks!

**Comment by dgra** [comment]
@flyfy1 I had time to dig back into the problem I was facing. It turns out our frontend code was using the `apply_coupon_code` api call https://github.com/solidusio/solidus/blob/v1.4/api/app/controllers/spree/api/orders_controller.rb#L81-L91 to apply the coupons which doesn't cause a `reload_totals` as far as I can tell. This was causing our in-memory order to be out of sync. So my problem doesn't appear to be a solidus issue anymore. I appreciate you taking a look and helping to narrow my focus on this.
