### ISSUE TITLE
Price bug when VAT set on the product

### ISSUE THREAD

**Issue by flyfy1** [solidusio/solidus#1533]
From the vanilla solidus, with only these lines of change in `initializers/spree.rb`:

```ruby
  config.default_country_iso = 'SG'
  config.admin_vat_country_iso = 'SG'
  config.currency = 'SGD'
```

Tax setup: 
![image](https://cloud.githubusercontent.com/assets/1553760/19504084/4a628d4e-95ea-11e6-8b83-5b798678c49d.png)

Product Setup:
![image](https://cloud.githubusercontent.com/assets/1553760/19504094/57f12254-95ea-11e6-8c5e-1135eabfb109.png)

Product Page:
![image](https://cloud.githubusercontent.com/assets/1553760/19504114/76d11134-95ea-11e6-9527-10b6e4872995.png)

At the Cart Page:
![image](https://cloud.githubusercontent.com/assets/1553760/19504125/8430c798-95ea-11e6-9ef1-e55a486d4255.png)

Checkout Page:
![image](https://cloud.githubusercontent.com/assets/1553760/19504168/ad696b60-95ea-11e6-8c47-675d426a11ab.png)

So the issue is that.. the price has already with tax subtracted, but also stating that `tax included`

**Comment by flyfy1** [comment]
When I was digging into the issue, I think the potential cause is a bit complicated.. let me try to describe them below:

- When building the variants with `rebuild VAT price` set, and my product is with tax included in price, a price with default country as `nil` would be created. This price is the set-price, minus the computed tax
- When adding product into cart, a line item is created. This line item would try to figure out the price from `variant.price_for(pricing_options)` (check source code [here](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/line_item.rb#L169)). However, the `price_for` is trying to figure out a correct price from the `country` field, but the `pricing_options` is telling the variant to get country information from `delivery address` or `billing address` (depends on setting).
- At the time of `add-to-cart`, this address information hasn't been set yet

Therefore, the LineItem would use the address from the default export price (the price without country), which is the price without Tax. Bug.

**Comment by flyfy1** [comment]
It seems to solve the issue after setting the `cart_tax_country_iso` upon store via:

```ruby
Spree::Store.first.update(cart_tax_country_iso: "SG")
```

And it solved the issue.

However, there's another issue:

let's say now we're selling to 2 countries: China & Singapore, with tax rate 17% for China, and 7% for Singapore:

![image](https://cloud.githubusercontent.com/assets/1553760/19514601/ba32c602-9626-11e6-80a3-cd72b0f7a29c.png)

With the default tax country set to Singapore, the price follows that for Singapore. However, when the consumer put in address for China, the item price is not updated.

I think an extra step of refreshing price (and tax) in LineItem is needed, after the address is put in

**Comment by mamhoff** [comment]
That scenario is why the `cart_tax_country_iso` setting is not a global setting, but one works by store. Can you have a separate store (URL) for China? Or can you somehow find out in the frontend where the customer is from?

**Comment by flyfy1** [comment]
@mamhoff ahh it's not a issue for me.. (we're only selling to 1 country currently). I was just trying to  give a bad input..

**Comment by mamhoff** [comment]
OK, closing this as resolved then. :)
