### ISSUE TITLE
Use ActiveModel::Naming for calculator descriptions

### ISSUE THREAD

**Issue by mamhoff** [solidusio/solidus#1544]
All of Spree's calculators and our internationalization would benefit from better use of `ActiveModel::Naming`, a module included in all Rails models. This is up for grabs, if you want a commit in Solidus, do this for other calculators in core! 

The base work for this is done in #1538 - all you'd have to do for each calculator is remove the `description` class method and add the correct translation key to the `spree.models` I18n namespace. 

Find the docs for `ActiveModel::Naming` [here](http://api.rubyonrails.org/classes/ActiveModel/Naming.html). 

These are the calculators still to be translated: 

- [ ] app/models/spree/calculator/flat_percent_item_total.rb
- [ ] app/models/spree/calculator/flat_rate.rb
- [ ] app/models/spree/calculator/flexi_rate.rb
- [ ] app/models/spree/calculator/free_shipping.rb
- [ ] app/models/spree/calculator/percent_on_line_item.rb
- [ ] app/models/spree/calculator/percent_per_item.rb
- [ ] app/models/spree/calculator/price_sack.rb
- [ ] app/models/spree/calculator/returns
- [ ] app/models/spree/calculator/returns/default_refund_amount.rb
- [ ] app/models/spree/calculator/shipping
- [ ] app/models/spree/calculator/shipping/flat_percent_item_total.rb
- [ ] app/models/spree/calculator/shipping/flat_rate.rb
- [ ] app/models/spree/calculator/shipping/flexi_rate.rb
- [ ] app/models/spree/calculator/shipping/per_item.rb
- [ ] app/models/spree/calculator/shipping/price_sack.rb
- [ ] app/models/spree/calculator/tiered_flat_rate.rb
- [ ] app/models/spree/calculator/tiered_percent.rb

**Comment by tvdeyen** [comment]
👍

**Comment by gevann** [comment]
I'll work  on this today
