### ISSUE TITLE
RMA amount not correct when the quantity of a line item is greater than 3

### ISSUE THREAD

**Issue by mdamian322** [solidusio/solidus#1564]
Steps to recreate:
1. Purchase 3 of a product
2. Create New RMA
3. The “Amount Before Sales Tax” field is autofilled with with an amount that is 19.99000000000000003398. I’m expecting it to be $19.99

<img width="1351" alt="amounts-before-sales-tax" src="https://cloud.githubusercontent.com/assets/13877138/19789535/9cd4a5b0-9c6d-11e6-83da-c493e9fc6b22.png">

**Comment by swcraig** [comment]
This was fixed by #1590. I can't recreate on master.

**Comment by aitbw** [comment]
As per #1590, this one's fixed @kennyadsl :tada:

**Comment by kennyadsl** [comment]
Thanks @DanielePalombo for fixing this!
