### ISSUE TITLE
Easier mechanism to override Order state machine?

### ISSUE THREAD

**Issue by anulman** [solidusio/solidus#1576]
Hi all! Thanks so much for forking and releasing Solidus, it's proving very helpful on a project we're building for a small chain of shops in meatspace.

One item we've found a bit difficult is overriding the standard Order FSM. What ships by default obviously works well for many flows, and already seems to allow for mods (e.g. via `:add_transition` & `:remove_checkout_step`).

We managed to easily remove e.g. `payment` and `delivery` steps for a subclass of `Spree::Order`. However, we looked for a similar mechanism to rm transition callbacks like `:validate_line_item_availability` and `:ensure_line_items_present` that made less sense in our flow as configured.

Have you explored adding a `yield if block_given?` to the state machine definition? For example, most of [this block](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order/checkout.rb#L58-L119) is optional already, but the transitions outside of conditionals cannot be modded / rm'ed. By conditionally yielding, you'd give consumers more granular control over their defined state machine w/o sacrificing the most basic defaults. For example:

```
class SubOrder < Spree::Order
  def self.define_state_machine!
    super do
      event :request_approval do
        transition from: :cart, to: :admin_required
      end

      before_transition to: :complete, do: :request_approval, if: :approval_required?
    end
  end
end
```

(Alternately—is this feature request more of a Spree thing?)

**Comment by seand7565** [comment]
Seems like the event bus might qualify as a solution for this issue. If that's true, can we explore closing this issue?

**Comment by anulman** [comment]
I'm not fussed! Been a while since I worked on this project, though I'm back in e-commerce 🤓.

@samkpower @CSStefan what do you think?

**Comment by jarednorman** [comment]
Have you taken a look at #3542?

**Comment by aldesantis** [comment]
💯, I also think #3542 solves exactly this problem.

**Comment by anulman** [comment]
Took a quick read; LGTM!

**Comment by seand7565** [comment]
#3542 appears to be on hold at the moment, but issue #3684 also covers this issue, if it gets a PR merged first!

**Comment by aldesantis** [comment]
We discussed #3542 in the latest core team meeting, it should be finalized and merged soon. 🙂
