### ISSUE TITLE
Custom Adjustments

### ISSUE THREAD

**Issue by skukx** [solidusio/solidus#1585]
It would be nice if there were a way to create custom adjustments. Use cases for this would be having a extra charge for gift wrapping or engraving/imprinting text onto an item.  Right now adjustments are strictly `TaxRates` or `Promotions` 

See https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order_updater.rb#L222

This is a feature currently supported by Spree

**Comment by skukx** [comment]
It was brought up before that this would be better on the line item. For example add columns `giftwrap`, `imprint` etc.  However I don't think it would be very scalable to be adding a new column for every new personalization.  Also I believe this would require a lot of monkey patching.

**Comment by Shigawire** [comment]
@skukx I am sorry for necromanting this old issue Issue, but I do have the same problem here. Some of our products have a deposit fee that will be returned once the customer returns the used product to the store. Think of the product as for example the cartridge of a gas grill.

The deposit is not taxable, but a fixed amount per product. To my understanding, a custom Adjustment would be the way to go here, or am I mistaken?
