### ISSUE TITLE
Background of project name

### ISSUE THREAD

**Issue by jbranchaud** [solidusio/solidus#1621]
Is this project named after the [chemistry term](https://en.wikipedia.org/wiki/Solidus_(chemistry)), the [metal gear solid character](https://en.wikipedia.org/wiki/List_of_characters_in_the_Metal_Gear_series#Solidus_Snake), or the [roman coin](https://en.wikipedia.org/wiki/Solidus_(coin))?

**Comment by jhawthorn** [comment]
[Solidus is the name of an old Roman coin and is also the name for a forward slash](https://github.com/solidusio/solidus/wiki/FAQ#why-is-it-called-solidus) :)
