### ISSUE TITLE
Customer and order emails are swapped in Admin

### ISSUE THREAD

**Issue by rainhead** [solidusio/solidus#1630]
I'm using Solidus 1.3.1, but the problem appears to persist in master.

If you look in the Customer pane of an order in the admin, the field labeled "Customer E-mail" is actually the order email. Meanwhile, in the "Order Information" sidebar, the email address labeled "User:" is actually the order's email address.

Ideally, non-guest orders would always have null email addresses in the database, and `order.email` would return the user's email address.

Short of that, these values should be swapped on the page.

**Comment by jhawthorn** [comment]
The "Customer E-mail" does indeed refer to the order's email. The wording could probably be more clear, but I don't think this is wrong, it is the customer's email as saved on the order.

As far as I can tell the sidebar does correctly show the user's email https://github.com/solidusio/solidus/blob/master/backend/app/views/spree/admin/shared/_order_summary.html.erb#L8

> Ideally, non-guest orders would always have null email addresses in the database, and order.email would return the user's email address.

We've preferred always setting an email on the order. I still think there's a lot of advantages to this approach (simple for querying, accessing, validating).

**Comment by rainhead** [comment]
All right. If there's any way to make this clearer, it'd be appreciated. It confused us.
