### ISSUE TITLE
VAT prices are generated twice for each country for variants

### ISSUE THREAD

**Issue by fschwahn** [solidusio/solidus#1634]
I have a tax rate which has `included_in_price` set to true. When I create a new product, prices get generated twice for all countries. I think the reason is that product calls `validate_master`, which runs validations, which triggers the `before_validation :build_vat_prices` callback. The validations are run again through rails associations, which trigger `before_validation :build_vat_prices` again. I just checked our production database, and this also happens for non-master variants, so there's probably something else going on).

That means `Spree::Variant::VatPriceGenerator` is run twice, and because nothing has been persisted to the database yet, `variant.prices.find_or_initialize_by` always builds a new record.

I'm not sure what's the right thing to do here:
- Make sure that the callback is only run once?
- Run the callback at a different time (eg. before_save)?
- Make search for existing prices in `Spree::Variant::VatPriceGenerator` work even if nothing has been saved yet (ie. put `variant.prices` in an array and use Array#select for finding existing prices)?
- ...?

**Comment by fschwahn** [comment]
Some more information:

This only happens when building a new product model, the validations are then run twice because of association autosave. There is already a spec in place (https://github.com/solidusio/solidus/blob/b7ca586099d7dec60c37fb69801dc55c5b7e34bf/core/spec/models/spree/variant_spec.rb#L73) which checks that the correct number of prices are added which doesn't trigger this behaviour because it operates on already saved products / variants. I can submit a PR which modifies this spec to showcase this problem.

**Comment by flyfy1** [comment]
Looking forward to the fix. This issue bugged me for quite a while also.
