### ISSUE TITLE
add taxon

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#1646]
I have just installed solidus and trying to add taxon , i get a error and no opcions display.

all-471af44….js:10255 GET http://localhost:3000/api/taxonomies/1?set=nested 422 (Unprocessable Entity)

**Comment by mamhoff** [comment]
sechix: It seems like you're running with precompiled assets, which shouldn't be happening in development mode. Have you seen our tutorial under https://github.com/solidusio/solidus/blob/master/guides/getting_started.md ? Please try re-installing using that tutorial. If you have trouble again, please post an exact description of what you did along with your `Gemfile` and `Gemfile.lock`.

Solidus is a Rails application, it might make sense for you to read through the Rails guides under http://guides.rubyonrails.org/.
