### ISSUE TITLE
Spree::Money should be comparable

### ISSUE THREAD

**Issue by eoinkelly** [solidusio/solidus#1650]
Is there a reason why `Spree::Money` does not implement `<=>` and include `Comparable`? The [current implementation](https://github.com/solidusio/solidus/blob/master/core/lib/spree/money.rb)  manually implements `#==` but not `<=>`. I think it would be convenient to be able to sort `Spree::Money` instances directly rather than having to reach into their wrapped `Money` instances.

I'm happy to have a go at a PR for this. Is there any constraint/reason I'm not seeing that would make it a bad idea?

**Comment by mamhoff** [comment]
We'd like `Spree::Money` to implement all the things that the base `Money` object supports, one by one. If this particular itches you, by all means submit a PR!

**Comment by kennyadsl** [comment]
@eoinkelly How do you want to implement this? I think we only should allow comparing Money objects that has the same currency with `<=>`.

**Comment by jhawthorn** [comment]
@kennyadsl I agree. That seems to be how `::Money` works already, so delegating to that will have the desired behaviour.

```
> ::Money.new(10) < ::Money.new(20)
=> true
> ::Money.new(10) > ::Money.new(20)
=> false
> ::Money.new(10, "USD") < ::Money.new(20, "CAD")
ArgumentError: comparison of Money with Money failed
```

@eoinkelly A PR would be most welcome

**Comment by eoinkelly** [comment]
Not comparing across currencies seems sensible. I'll have a go at a PR and then we'll have something concrete to discuss.
