### ISSUE TITLE
Error in 2.1.0.beta1 

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#1652]
I get this error with solidus 2.1.0.beta1 executing store frontend:

ExecJS::ProgramError in Spree::Home#index
Showing /Users/mariajosegonzalesantelo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/solidus_frontend-2.1.0.beta1/app/views/spree/shared/_head.html.erb where line #7 raised:

ReferenceError: CoffeeScript is not defined
Trace of template inclusion: /Users/mariajosegonzalesantelo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/solidus_frontend-2.1.0.beta1/app/views/spree/layouts/spree_application.html.erb

Can you help me?

**Comment by jhawthorn** [comment]
Hi @sechix 

This was an issue earlier today with the `coffee-script-source` gem having a broken release. It should be fixed now.

See:
https://github.com/rails/ruby-coffee-script/issues/11#issuecomment-267422413
https://github.com/rails/ruby-coffee-script/issues/13
https://github.com/jashkenas/coffeescript/issues/4403
