### ISSUE TITLE
Change of Variant Price does not re-compute VAT price

### ISSUE THREAD

**Issue by flyfy1** [solidusio/solidus#1653]
## Setup

In the tax category, having a tax rate included in the price

## How to reproduce:

1. Create a product with several Variants
2. Update variance price, make sure `rebuild VAT price` is checked

## Expectation

- What's seen: only variant default price is updated
- What's expected: the price for "all countries" should be also updated

## ScreenShot

![image](https://cloud.githubusercontent.com/assets/1553760/21250594/948554f0-c381-11e6-8883-33171a7c472a.png)

**Comment by gus4no** [comment]
Working on it

**Comment by gus4no** [comment]
Hello @flyfy1 what version of solidus are you using? I could not reproduce this on v2.2

**Comment by flyfy1** [comment]
@gus4no it has been a while since last time I develop in solidus.. I was probably on Solidus Master at that time.. Let me try on v2.2 and see how

**Comment by flyfy1** [comment]
The issue is gone with solidus 2.2.1

Thanks for reviewing issue again.
