### ISSUE TITLE
What is Calculator::PriceSack?

### ISSUE THREAD

**Issue by bbuchalter** [solidusio/solidus#1674]
While poking around I came across this [interesting comment](https://github.com/solidusio/solidus/blob/c676d0d23d239392e72ba7a4eceebed483490cea/core/app/models/spree/order.rb#L167) and started to wonder what use the [PriceSack calculator](https://github.com/solidusio/solidus/blob/c676d0d23d239392e72ba7a4eceebed483490cea/core/app/models/spree/calculator/price_sack.rb) has?

Aside from [this update to use ActiveModel::Naming](https://github.com/solidusio/solidus/commit/fa6f603c8be0645da660a104021a2a23e18c3928) which touched a whole lot of classes, and a [few other updates for things like Ruby 1.8 compatibility](https://github.com/solidusio/solidus/commits/c676d0d23d239392e72ba7a4eceebed483490cea/core/app/models/spree/calculator/price_sack.rb), this class hasn't seen any real attentions since 2012 when @radar [fixed a bug in it](https://github.com/solidusio/solidus/commit/b7917ba2d05ca53055f8987afa69a4725626a38c).

Any thoughts about deleting it as well as `Spree::Order#amount`?

**Comment by gmacdougall** [comment]
The basic structure of PriceSack is to give a different value to the promotion if the order or line_item  is above a certain amount. For example, $5 shipping on orders over $100.

We don't really have a good idea on how many people use this, so I'm a bit hesitant to remove it or even deprecate it. I think the best thing to do first would be to document it.

**Comment by jhawthorn** [comment]
I'm reluctant to ever remove a calculator, since it is a huge pain to be missing a class referred to in the DB through rails' STI.

It would be nice if we displayed it to users in a better way. "Price Sack" is a terrible name. 

Further complicating this is that the `Shipping::`, versions is broken and behaves differently to the promotion version :anguished:

**Comment by jhawthorn** [comment]
As for better names: I've heard the term "hurdle" used for this type of promotion. In slack Sean Denny suggested "price break" (which I like)

**Comment by mtomov** [comment]
Even if you call it "Price Break", one would still have to explain how it works, and as you said any name change would not be so non-invasive. So, I'd rather stick with this one, but add one of those little fellows:

![screenshot from 2017-03-31 09-30-42](https://cloud.githubusercontent.com/assets/1651750/24542807/f89f9a8e-15f4-11e7-91c7-b8b8784ae0bd.png)


I'm thinking that we should actually make the _info button_ sign a little larger.

**Comment by bbuchalter** [comment]
I think we've reached the end of useful conversation here.
