### ISSUE TITLE
NoMethodError in checkout (terms and condition)

### ISSUE THREAD

**Issue by Magnusvb** [solidusio/solidus#1676]
I'm a beginner on Solidus, and tried to place an order through the frontend. But, at the step after the payment (_confirm.html.erb), I get this error:

```
NoMethodError in Spree::Checkout#edit
Showing /Users/magnus/Documents/rails_projects/solidus-21-theme/app/views/spree/checkout/_confirm.html.erb where line #10 raised:

require_terms_and_conditions_acceptance preference not defined
```
I can not find any way to define if acceptance of terms and condition is required.

**Comment by graygilmore** [comment]
The preference is set here: https://github.com/solidusio/solidus/blob/master/frontend/app/models/spree/frontend_configuration.rb#L6

Can you confirm that that file is being loaded?

**Comment by jhawthorn** [comment]
@Magnusvb going out on a limb, sorry if I'm wrong.

Is it possible you've copied the `_confirm.html.erb` from Solidus master (which is 2.2.0.alpha) into your app running on an older version of Solidus? That method is brand new and doesn't exist in any Solidus gem releases. If you're copying views into your app, you will have to use the the version of the view matching the version you are using.

**Comment by Magnusvb** [comment]
John, you are totally right!
I had cloned (by mistake) the Master and used these files in my installation - which is version 2.1. Replacing with the right file solved the problem.

@graygilmore: I could not find the file with the settings, which made me wonder about the versions...

Sorry for the false issue (and late respons)! Many thanks!

**Comment by tvdeyen** [comment]
This is totally our fault as we never had a good way to override views in your app, until https://github.com/solidusio/solidus/pull/1681

**Comment by jhawthorn** [comment]
No worries @Magnusvb, you are hardly the first to run into this :wink: 

Hopefully #1681 will make this less common to run into.
