### ISSUE TITLE
Specifying stock locations on cart page doesn't work for existing line items

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#1695]
### Steps to reproduce

Start with a store with two stock locations

On a new order's cart page, add an item, taking quantity 1 from each stock location

![](http://i.hawth.ca/s/qCyJE5ug.png)

Do the same again with the same item

![](http://i.hawth.ca/s/Gh1LIJ1v.png)

View the shipments

### Expected behavior

Two shipments, one from each location, each with quantity two, as the user specified.

### Actual behavior

Three shipments are created. The quantities from each location aren't what the user specified.

![](http://i.hawth.ca/s/UMQJHF8W.png)

https://github.com/solidusio/solidus/blob/33797b434986cf8fdecf6369467d29d6bd31979b/core/app/models/spree/order_contents.rb#L101-L103

### System configuration
**Solidus Version**: Any
**Extensions in use**: None

**Comment by aayush2610** [comment]
Hey @jhawthorn I would like to contribute to this issue. I was not able to create a store with two stock locations, can you help with that?

**Comment by kennyadsl** [comment]
This has been closed with #1709
