### ISSUE TITLE
simple_current_order creates an Order without a Store

### ISSUE THREAD

**Issue by ridem** [solidusio/solidus#1700]
### Steps to reproduce
Try to access `available_payment_methods` from an order created by `simple_current_order` for a new user.

### Expected behavior
This should provide the available_payment_methods.

### Actual behavior
Can't find `payments`.

This is called to create the order:
```ruby
@simple_current_order = Spree::Order.new
```
(https://github.com/solidusio/solidus/blob/master/core/lib/spree/core/controller_helpers/order.rb#L27)

If trying to access `available_payment_methods`, the call fails because of this:
https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order.rb#L448

What fixed it for me is to associate the order with the store:
```ruby
@simple_current_order = Spree::Order.new(store: current_store)
```

I can PR if confirmed

### System configuration
**Solidus Version**:
`master`, `v2.1`

**Comment by jacobherrington** [comment]
This was fixed by #1915.

**Comment by aitbw** [comment]
Another closed that's fixed @kennyadsl

**Comment by kennyadsl** [comment]
Thanks @ericsaupe! Closing this one.
