### ISSUE TITLE
Post 1.0 Roadmap

### ISSUE THREAD

**Issue by cbrunsdon** [solidusio/solidus#171]
As I've promised for the last two weekly meetings, here's a place to discuss where we're going post 1.0.

As this is our first serious roadmap discussion we're really experimenting with the format here, so please take any roughness with a grain of salt.

I see there being split into four main areas for work to take place after a 1.0

1. Refactoring / Improving existing code
  * #142 Cleaning out the "front end" states
  * #143 Cleaning up the Order updating
  * Cleaning up the admin views/javascript/css/etc
2. Updating Extensions / Extension points
  * #112 Pulling multi_domain code into solidus
  * Removing class_eval's from "supported" extensions
  * Adding clearer points of extension into core
3. Adding new features
  * #146 New non-rabl API
  * #145 Adding Categories
4. Big Infrastructure
  * Renamespace Spree:: to Solidus::
  * #141 phasing out solidus_frontend

What we need to do is figure out what things we definitely want to do, and what things we don't want to slot in right now. After that, we need to prioritize and order, and figure out what should be going into releases.

**Comment by athal7** [comment]
:+1: this is a great summary / start. thanks @cbrunsdon for organizing these and for all of the background / history on the linked issues

**Comment by magnusvk** [comment]
Do we want to add #176 (better token auth) somewhere here? I see this maybe in 3.

**Comment by athal7** [comment]
@cbrunsdon I think the latter parts of item 2 are vaguely captured here: https://github.com/solidusio/solidus/issues/147

**Comment by athal7** [comment]
closing in favor of https://github.com/solidusio/solidus/milestones/Future
