### ISSUE TITLE
Not able to use backend shipping methods in admin

### ISSUE THREAD

**Issue by mdamian322** [solidusio/solidus#1711]
**Steps to Recreate:**
1. Select “Backend” from the Display dropdown on a Shipping Method in admin and save
2. Create an order in admin and get to the Delivery Step
3. Select a shipping method for the order. Notice that the shipping method you updated is not showing as an option, although “Backend” was selected

Expected Behavior: The shipping method should have been showing in the dropdown as an option since “Backend” was selected and admin users should be able use those shipping methods.

Actual Behavior: That shipping method is not showing as an shipping option

Solidus 2.0

**Comment by mamhoff** [comment]
Reopening this as the fix in #1984 would allow frontend users to select a backend-only shipping method too easily. See #2077.

**Comment by jhawthorn** [comment]
This didn't get fixed in time for 2.4, but I believe we will fix it before 2.5
