### ISSUE TITLE
copying view to edit breaks admin orders page

### ISSUE THREAD

**Issue by winterblack** [solidusio/solidus#1713]
### Steps to reproduce

1. Create a test app following the Getting started directions in the ReadMe
2. Copy and paste "views/spree/admin/orders/index.html.erb" from solidus master into test app

### Expected behavior
No change

### Actual behavior
NoMethodError in Spree::Admin::Orders#index
Showing /home/judd/sample_store/app/views/spree/admin/orders/index.html.erb where line #39 raised:

undefined method `order_promotions_promotion_code_value_cont' for #<Ransack::Search:0x007f05c0417a40>
Extracted source (around line #39):

          <div class="field">
            <%= label_tag nil, Spree.t(:promotion) %>
            <%= f.text_field :order_promotions_promotion_code_value_cont, :size => 25 %>
          </div>

          <div class="field">

Rails.root: /home/judd/sample_store

Application Trace | Framework Trace | Full Trace
app/views/spree/admin/orders/index.html.erb:39:in `block (2 levels) in _8b850bbfd07577539a3731a83efeffc1'
app/views/spree/admin/orders/index.html.erb:16:in `block in _8b850bbfd07577539a3731a83efeffc1'
app/views/spree/admin/orders/index.html.erb:14:in `_8b850bbfd07577539a3731a83efeffc1'

### System configuration
**Solidus Version**: 2.1.0

**Extensions in use**: solidus_auth_devise

**Comment by tvdeyen** [comment]
Please try to copy the view from the `v2.1` branch instead. You can either switch the branch in GitHub or use `bundle open solidus_backend` to open the gen in your local code editor.

**Comment by winterblack** [comment]
Fixed, thank you.
