### ISSUE TITLE
Admin: Edit customer returns show_decision broken style

### ISSUE THREAD

**Issue by vfonic** [solidusio/solidus#1723]
### Steps to reproduce
Go to order customer returns and edit one. You should see Accept/Reject action buttons. If you don't, for the sake of this issue, edit `backend/app/views/spree/admin/customer_returns/edit.html.erb` and replace `show_decision: false` with `show_decision: true` throughout. (Or create a pending return item or manual intervention return item). Hover over "Accept" or "Reject".

### Expected behavior
The "Accept"/"Reject" text should be shown in a visible color.

### Actual behavior
The "Accept"/"Reject" text is shown in white color when hovered.

### System configuration
**Solidus Version**:
master: 4cfd1a2b64482329f2e36452b4b2470659b3c8a9

**Comment by gregdaynes** [comment]
Looking into this, I tested it out using by adjusting `show_decision: true`

The following screenshots are from Safari 11 on macOS

![screen shot 2017-10-04 at 13 06 12](https://user-images.githubusercontent.com/43543/31197202-360fce86-a905-11e7-9e71-01e4c7f1150a.jpg)
![screen shot 2017-10-04 at 13 06 16](https://user-images.githubusercontent.com/43543/31197201-360cc394-a905-11e7-906d-fd3177a33fc6.jpg)

The text is white, but inside a coloured tooltip - this is consistent with the rest of the backend UI

Were you seeing it without the tooltip bubble (coloured background)? 
What browser/device were you using?

**Comment by vfonic** [comment]
Ah, I think the issue was with the background color not getting light green/light red. And the tooltip was completely missing. I don't recall exactly, as it was in Feb when I created this issue. But it seems to be fixed now. So I'm closing this issue. Thanks for looking into this!
