### ISSUE TITLE
Implement Solidus version 2.1 to my existing rails app

### ISSUE THREAD

**Issue by huyngvu** [solidusio/solidus#1728]
### Steps to reproduce
I have a Rails have with existing user table and using devise gem
Now I need to implement Solidus to my app. Something like that http://localhost/shop
I want to implement Solidus but use the same existing user table and devise gem instead of spree_users table.
Could someone please let me know what should I do?

### System configuration
2.1

Thanks for your help!
Huy

**Comment by tvdeyen** [comment]
The GitHub issues are solely meant for bugs. Please use Slack for seeking help.
http://slack.solidus.io
