### ISSUE TITLE
Cannot refund a payment from a soft-deleted payment gateway

### ISSUE THREAD

**Issue by bbuchalter** [solidusio/solidus#1729]
### Steps to reproduce
1. Setup a payment method
2. Complete an order with a payment from that payment method
3. Delete that payment method
4. Attempt to refund the payment on the completed order

### Expected behavior
Not sure what expected behavior should be. Some options could be:
1. Payments with a deleted payment method no longer have actions in the UI
2. Payments should use the `with_deleted` scope when calling `payment.payment_method`

I'm inclined to think option number 2 is preferred, as I assume that's the reason the payment method is being soft deleted in the first place. If I get some confirmation from the core team that this is the preferred solution, that would be a helpful step towards opening a PR for this issue.

### Actual behavior
`NoMethodError: undefined method payment_profiles_supported? for nil:NilClass` from [Spree::Refund#process!](https://github.com/solidusio/solidus/blob/de3eafbdf003a696de653d48c5b2f7e961f6c6c8/core/app/models/spree/refund.rb#L54)

### System configuration
**Solidus Version**: master

**Extensions in use**: none

**Comment by gmacdougall** [comment]
I would tend to side with adding the `with_deleted` scope. Though both are reasonable.

**Comment by bbuchalter** [comment]
This is a duplicate of https://github.com/solidusio/solidus/issues/1186 which was fixed by https://github.com/solidusio/solidus/pull/1200.
