### ISSUE TITLE
Stock Transfer receive dropdown autocomplete fails when all of stock in transit

### ISSUE THREAD

**Issue by brchristian** [solidusio/solidus#1737]
I’m on the latest gem release of `2.0.x`. If I transfer all of the stock of a given product from one warehouse to another, I can’t "receive" the package correctly. The product is out of stock in all locations while it’s in transit, and when I go to log the received stock, the dropdown won’t show that product.

My workaround: go to Store Stock, manually change quantity at my receiving warehouse to 1, use the dropdown, change quantity manually back to 0, then receive the shipment.

**Comment by gus4no** [comment]
Working on this. 👷
