### ISSUE TITLE
Better token auth

### ISSUE THREAD

**Issue by magnusvk** [solidusio/solidus#176]
We currently have a separate token auth solution at Bonobos that is considerably better than the default in Spree now:
- not susceptible to timing attacks
- stores hashed tokens, rather than cleartext tokens in the database
- supports multiple tokens per user
- supports token expiration

I've started work on breaking this out into a devise module, but there's more work to do there. I think we should make this a part of solidus_auth_devise by default and remove the current `api_key` from `spree_users`.

**Comment by gmacdougall** [comment]
Closing due to being stale.

**Comment by magnusvk** [comment]
👋 blast from the past here. 🙃

**Comment by skycocker** [comment]
@magnusvk and others as well: in case you were still interested, I created a fork of solidus that supports devise_token_auth: https://github.com/skycocker/solidus_devise_token_auth
