### ISSUE TITLE
Replace E-mail Validator

### ISSUE THREAD

**Issue by gmacdougall** [solidusio/solidus#1794]
Our current e-mail validator is not good. It is a simplistic regular expression that incorrectly flags some e-mails as being valid though they are not.

The [validates_email_format_of](https://github.com/validates-email-format-of/validates_email_format_of) gem can be of assistance here.  It has a superior implementation of e-mail validation, and superior test cases.

We should consider using this solution rather than our current validator.

**Comment by jasonfb** [comment]
https://davidcel.is/posts/stop-validating-email-addresses-with-regex/

**Comment by jasonfb** [comment]
having said that, we really like this approach (which isn't really an email validator at all, more a suggester): https://github.com/mailcheck/mailcheck

You can check that out live by going to Kickstarter (log out if you are already logged in), then click 'Sign up'. Then enter your email but purposefully leave off the ```.com``` (or in your case ```.ca```), you'll see it suggest the right email to you

**Comment by mtomov** [comment]
I think that so log as it does not flag correct emails as being wrong, it's fine as it is. I don't consider it to be a core responsibility of Solidus to handle such use cases with perfection. They can be implemented at the individual store level.

**Comment by gmacdougall** [comment]
I tend to think that since we're [providing an e-mail validator](https://github.com/solidusio/solidus/blob/v2.1.0/core/lib/spree/core/validators/email.rb) we should make it decent.

We can also try to get out of that business altogether, but that's a bit more of an invasive change.

**Comment by tvdeyen** [comment]
> We can also try to get out of that business altogether, but that's a bit more of an invasive change.

Why not let the user class provider handle this (in our case `solidus_auth_devise` could let Devise validate this email)?

That's definitely not something we should do in core.

**Comment by dividedharmony** [comment]
This didn't have the Solidus Hackathon label, but I thought it was simple enough, so I put in PR #1965 if this issue is still relevant
