### ISSUE TITLE
Undefined method `to_d` when adding item to order through backend

### ISSUE THREAD

**Issue by Draiken** [solidusio/solidus#1808]
### Steps to reproduce
* Go to the admin and selected an order
* Used the search bar to find a product to add
* Set the quantity to 1
* Click "Add"

### Expected behavior
Item added to the order's cart

### Actual behavior
Got an error. Stack trace: https://gist.github.com/1322d81cb0525a068a7700002196f7a6
The page removed the widget to add quantity and now the search doesn't work properly: clicking on the searched item does not show the quantity selection

### System configuration
**Solidus Version**: 2.0.0

**Extensions in use**: Only solidus_auth_devise

**Comment by kennyadsl** [comment]
@Draiken it seems like there's no price retrieved for that specific variant. Can you please check?

Anyway that code is much more solid on newer versions. Is it possible to update solidus to 2.1.0 for you?

**Comment by Draiken** [comment]
Yeah, I'll see if I can do it :slightly_smiling_face:
This is probably bad data then, closing
