### ISSUE TITLE
TaxRate <--> TaxCategory relation type

### ISSUE THREAD

**Issue by vladstoick** [solidusio/solidus#1836]
# Background:
- A TaxRate belongs to a TaxCategory
- A Product/ Variant belongs to a Tax Category
# Problem:
When adding multiple categories you end up duplicating a lot of tax rates as VAT is applied differently across Europe based on the TaxCategory. For instance some countries have special tax reduction for certain tax categories, while other don't. A rate must exist for each category if you want to properly apply VAT:
```
def rates_for_item(item)
  applicable_rates(item.order).select { |rate| rate.tax_category_id == item.tax_category_id }
end
```
This means that even if a tax category doesn't get a special rate for that category you still end up creating a tax rate for that category and that zone. This can lead to the creation of a lot of TaxRate even when they are not necessary as the general VAT can apply to them. This can become problematic for instance when implementing EU VAT where each country (28 at the moment) has different rules (in our (LMN) case books have a VAT of 0% in some countries, while in others they might be fully taxed or other taxes might be implemented).

# Potential solution
Allow a TaxRate to have many categories if the rate is the same (the general VAT tax for instance) and make additional TaxRates required if the rate is going to be different.

**Comment by mamhoff** [comment]
Go for it. I see a challenge in administering this nicely in the backend, but from a data architecture standpoint this makes a whole lot of sense. :+1:
