### ISSUE TITLE
Order state not changing from 'confirm' to 'complete', via API call

### ISSUE THREAD

**Issue by gaurav945** [solidusio/solidus#1841]
### Steps to reproduce
When you make the following API call (when the order is in confirm state),
PUT api/checkouts/order-number
it gives an error, which is, cannot transition to the next step.

### Expected behavior
Ideally, the state should get updated to 'complete', when the API call is made.
Right now, the code is as follows, in checkouts_controller for API : 

```ruby
if OrderUpdateAttributes.new(@order, update_params, request_env: request.headers.env).apply
  if can?(:admin, @order) && user_id.present?
    @order.associate_user!(Spree.user_class.find(user_id))
  end

  return if after_update_attributes

  if @order.completed? || @order.next
    state_callback(:after)
    respond_with(@order, default_template: 'spree/api/orders/show')
  else
    logger.error("failed_to_transition_errors=#{@order.errors.full_messages}")
    respond_with(@order, default_template: 'spree/api/orders/could_not_transition', status: 422)
  end
else
  invalid_resource!(@order)
end

```

Instead, it should be :
```ruby
if OrderUpdateAttributes.new(@order, update_params, request_env: request.headers.env).apply
  if can?(:admin, @order) && user_id.present?
    @order.associate_user!(Spree.user_class.find(user_id))
  end

  return if after_update_attributes

  #-------------this section needed--------
  if @order.state == 'confirm'
    @order.complete
  end
  #------------------------------------------

  if @order.completed? || @order.next
    state_callback(:after)
    respond_with(@order, default_template: 'spree/api/orders/show')
  else
    logger.error("failed_to_transition_errors=#{@order.errors.full_messages}")
    respond_with(@order, default_template: 'spree/api/orders/could_not_transition', status: 422)
  end
else
  invalid_resource!(@order)
end
```

### System configuration
**Solidus Version**:
2.1.0

**Extensions in use**:
No extension

**Comment by kennyadsl** [comment]
@gaurav945 there's [another endpoint](https://github.com/solidusio/solidus/blob/master/api/app/controllers/spree/api/checkouts_controller.rb#L38-L49) to complete the order via API. Is there anything that deny you to use that one? I think that the logic to check if current state is `confirm` is supposed to be placed where the API is consumed.

**Comment by gaurav945** [comment]
@kennyadsl I had completely ignored that endpoint, I am so sorry for that, thank you so much for your help, closing the issue now. :)

**Comment by kennyadsl** [comment]
@gaurav945 don't you worry, I'm happy to be of help!
