### ISSUE TITLE
Prevent user from deleting the default master variant price

### ISSUE THREAD

**Issue by robinboening** [solidusio/solidus#1861]
### Steps to reproduce
1. Create a product
2. Go to `/admin/products/xyz/prices`
3. Delete the one and only price

### Expected behavior
The one and only price should not be deletable.

### Actual behavior
I can just delete the one and only price. When I go back to "product details" I can see its still using that (paranoidly deleted) price as its default price, but I am not able to edit the record in the prices#edit view anymore.

### System configuration
**Solidus Version**: 2.3.0.alpha

**Extensions in use**: None

**Comment by laurawadden** [comment]
working on it

**Comment by laurawadden** [comment]
@mamhoff mentioned that you actually *should* be able to delete the master price.

However, it is a bug that when you go back to "product details", the master price is still shown (even though it's already deleted). Expected behaviour should be that the field should be blank.

**Comment by jasonfb** [comment]
my colleague @reidcooper and I literarily just noticed this yesterday — spree_prices seems to have acts_as_paranoid on it (using a soft delete with a ```deleted_at``` field), although for some reason Spree's code somehow works around the gem's mechanism. If you make a change to a price after deleting it, it still updates the "deleted" (soft) record in the database.
