### ISSUE TITLE
Port Developer Guides to Solidus

### ISSUE THREAD

**Issue by mamhoff** [solidusio/solidus#1862]
We would like to have better documentation, both for devs and for users. One way to get there is to take existing documentation from before Solidus was forked from Spree and "port" it: Go through the guide in question and adapt screenshots and terminology to Solidus. A few are done already and live in the `/guides` directory in Solidus’ main repository.

- [x] [Shipping](https://https://github.com/spree/spree-guides/blob/master/content/developer/core/shipments.md)
- [x] [Products and Variants](https://github.com/spree/spree-guides/blob/master/content/developer/core/products.md)
- [x] [Addresses, States, Countries and Zones](https://github.com/spree/spree-guides/blob/master/content/developer/core/addresses.md)
- [x] [Payments](https://github.com/spree/spree-guides/blob/master/content/developer/core/payments.md)
- [x] [Adjustments](https://github.com/spree/spree-guides/blob/master/content/developer/core/adjustments.mdl)
- [x] [Calculators](https://github.com/spree/spree-guides/blob/master/content/developer/core/calculators.md)
- [x] [Orders](https://github.com/spree/spree-guides/blob/master/content/developer/core/orders.md)
- [x] [Promotions](https://github.com/spree/spree-guides/blob/master/content/developer/core/promotions.md)

**Comment by Reddshift** [comment]
Going to working on this for Hack days - starting with Products and Variants at @mamhoff 's recommendation.

**Comment by Reddshift** [comment]
@mamhoff here is my pull request for Products and Variants - let me know what you think.  All feedback is welcome, wanting to make this as clear and helpful as possible.

https://github.com/solidusio/solidus/pull/1939

**Comment by Reddshift** [comment]
Starting on the Shipping documentation.

**Comment by Reddshift** [comment]
@mamhoff created a pull request for the Shipping guide: https://github.com/solidusio/solidus/pull/1966

Since Clarke just announced Stembolt would be hiring a technical writer to do documentation, should I or others continue working on these?

**Comment by mamhoff** [comment]
I think it's good to port existing docs and have something. The technical writer will probably change things, but let's just iteratively move forward on this. Thank you!

**Comment by afdev82** [comment]
I found this link is broken: https://github.com/solidusio/solidus/blob/master/guides/orders#line-items
It's in the https://github.com/solidusio/solidus/blob/master/guides/products_and_variants.md guide

**Comment by benjaminwil** [comment]
Hey, just chiming in to mention that there are open pull requests for ported payments documentation (#2388), adjustments documentation (#2459), and zones documentation (#2375), as well as updates to many of the existing Solidus guides (see [all my pull requests](https://github.com/solidusio/solidus/pulls/benjaminwil) for a list).

I would appreciate feedback and criticism from any and all of you.

**Comment by kennyadsl** [comment]
This has been done! Thanks @benjaminwil for your work here.
