### ISSUE TITLE
Extract responders to an extension

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#1869]
Solidus has some custom responders based code to allow overrides. Some stores use this, but not all. It doesn't tightly integrate with anything in Solidus so we should be able to extract it into its own extension with minimal difficulty.

* [core/lib/spree/core/controller_helpers/respond_with.rb](https://github.com/solidusio/solidus/blob/master/core/lib/spree/core/controller_helpers/respond_with.rb)
* [core/lib/spree/responder.rb](https://github.com/solidusio/solidus/blob/master/core/lib/spree/responder.rb)

There's also an API responder, which might be more challenging to remove.

* [api/lib/spree/api/responders.rb](https://github.com/solidusio/solidus/blob/master/api/lib/spree/api/responders.rb)
* [api/lib/spree/api/responders/rabl_template.rb](https://github.com/solidusio/solidus/blob/master/api/lib/spree/api/responders/rabl_template.rb)

**Comment by omnistegan** [comment]
I haven't written an extension yet, so I'm going to tackle this. :)

**Comment by kennyadsl** [comment]
This has been done and already in Solidus since 2.4, closing now.
