### ISSUE TITLE
Solidus as API only

### ISSUE THREAD

**Issue by gcmartins93** [solidusio/solidus#1873]
What if I want to use solidus as an API Server and code the frontend by myself? I don't need to use the solidus gem itself, right? Instead I tried to use solidus_api gem, but have got errors while trying to install solidus_auth_devise.

I found that I can use devise_token_auth to create and authenticate user by myself and override solidus user by using spree generator `spree:custom_user ` and defining `has_spree_role ` method on user. As show [here](https://gist.github.com/huoxito/5977700).

My question is: Is this the right approach to use solidus only as an api?

**Comment by jhawthorn** [comment]
Hi @gcmartins93 we do have a pluggable model for users for situations like this. However the api currently only accepts the `spree_api_key` column value, not the tokens from `devise_token_auth`.

Could you report whatever errors you ran into to the [solidus_auth_devise issue tracker](https://github.com/solidusio/solidus_auth_devise/issues). We do intend that it can be usable without the frontend or backend gems. Thanks :smile:

**Comment by gcmartins93** [comment]
## Steps to reproduce

1. Create a rails 5 api only project;
2. Add solidus_api and solidus_auth_device
3. Run the spree generator `bundle exec rails g spree:install`
### output
```sh
/home/gabriel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- sass/rails (LoadError)
	from /home/gabriel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/gabriel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/gabriel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /home/gabriel/.rvm/gems/ruby-2.3.0/gems/solidus_auth_devise-1.6.2/lib/solidus_auth_devise.rb:4:in `<top (required)>'
	from /home/gabriel/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:91:in `require'
	from /home/gabriel/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
...
```

If I remove devise_auth_devise from Gemfile, than the [generator runs](http://imgur.com/KCK0cyx), but, it creates vendor assets - that I guess it should not.

Any clue?

**Comment by skycocker** [comment]
@gbrlcustodio in case you were still interested, I created a fork of solidus that supports devise_token_auth: https://github.com/skycocker/solidus_devise_token_auth
