### ISSUE TITLE
2.3.0.alpha field  product images upload error

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#1875]
Hi, I have problems trying to upload images to products. After researching I realized that in a specific variant image uploading works but not in variant all. 
It's due to field of spree_assets table 'viewable_id' is 0 in variant all and not in specific variant.
I saw that file 'solidus/backend/app/assets/javascripts/spree/backend/images/upload.js' has been modified, maybe there is somwthing wrong here.

Could you check?

**Comment by sechix** [comment]
Confirmed !!! Is in 2.3.0.alpha, in 2.2 works ok.

**Comment by jhawthorn** [comment]
Thanks @sechix, taking a look now

**Comment by jhawthorn** [comment]
I believe this will be fixed by #1876
