### ISSUE TITLE
Release 5.1 fails on bundle update/bundle install

### ISSUE THREAD

**Issue by cd-rum** [solidusio/solidus#1891]
### Steps to reproduce
Make a new Rails 5.1 app. Add the two solidus gems. `bundle install` and `bundle update` both fail.

### Expected behavior
The gems should install.

### Actual behavior
This is the output of `bundle install`:

```
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.1.0)

  In Gemfile:
    rails (~> 5.1.0)

    solidus was resolved to 1.0.0, which depends on
      solidus_frontend (= 1.0.0) was resolved to 1.0.0, which depends on
        canonical-rails (~> 0.0.4) was resolved to 0.0.4, which depends on
          rails (< 5.0, >= 3.1)

    solidus was resolved to 1.0.0, which depends on
      solidus_core (= 1.0.0) was resolved to 1.0.0, which depends on
        deface (~> 1.0.0) was resolved to 1.0.2, which depends on
          rails (>= 3.1)

    solidus was resolved to 1.0.0, which depends on
      solidus_core (= 1.0.0) was resolved to 1.0.0, which depends on
        rails (~> 4.2.0)
```
And this is the output of `bundle update`:

```
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.1.0)

    solidus was resolved to 1.0.0, which depends on
      solidus_core (= 1.0.0) was resolved to 1.0.0, which depends on
        rails (~> 4.2.0)
```

### System configuration
**Solidus Version**: Unspecified/latest.

**Extensions in use**: None.

**Comment by mtomov** [comment]
Right, 5.1 compatibility is still in preparation I think, see the [Rails 5.1 milestone](https://github.com/solidusio/solidus/milestone/12) on it:  

And your concrete problem with Canonical Rails is likely to have been addressed by this one: https://github.com/solidusio/solidus/pull/1885, so might give it a try using the github master branch in your Gemfile.

**Comment by jhawthorn** [comment]
Rails 5.1 support is still a work in progress. Closing for #1788
