### ISSUE TITLE
Use Rails i18n for promotion rules

### ISSUE THREAD

**Issue by mamhoff** [solidusio/solidus#1899]
Currently, we use a custom `i18n` namespace to provide user-friendly names for promotion rules and actions. This should be changed to use the classical `rule.model_name.human` syntax for short class names and descriptions. 

[This line](https://github.com/solidusio/solidus/blob/master/backend/app/helpers/spree/promotion_rules_helper.rb#L6) for example could be done using `model_name.human` perfectly.

Advantages: We want to move towards using Rails' I18n features as they are intended and namespace as well as we can. Right now, one could easily add another promotion rule in another namespace with the same name as one in core, and things would break because of colliding keys. 

[This partial](https://github.com/solidusio/solidus/blob/master/backend/app/views/spree/admin/promotions/_promotion_rule.html.erb#L3-L11) also needs better I18n.

**Comment by swively** [comment]
On it!

**Comment by mamhoff** [comment]
Closed via #1938
