### ISSUE TITLE
Cannot generate api key

### ISSUE THREAD

**Issue by quesurifn** [solidusio/solidus#1911]
When I log into admin, the option to generate an API key is there but they key is hidden.

How do I get my api key?

**Comment by andrewkmin** [comment]
Why was this closed? @quesurifn any insights?

**Comment by quesurifn** [comment]
@andrewkmin No. Spree got me further and we have launched the solution and are receiving orders. To be honest, I'd stay away from spree based solutions altogether and look at other ecommerce solutions. I'm a JS dev and there were some pretty nice Node solutions and Golang solutions.

**Comment by andrewkmin** [comment]
Hmm.. so in terms of the api key there's legitimately no way to get it?

**Comment by quesurifn** [comment]
I ditched it for other reasons before I found a solution. @andrewkmin

**Comment by andrewkmin** [comment]
Gotcha. Thanks man and best of luck. @quesurifn

**Comment by kennyadsl** [comment]
@andrewkmin I usually check the API key via rails console, something like:

```ruby
Spree::User.find_by_email('admin@example.com').try(:spree_api_key)
```

We probably have to restore ability to view the API key in admin or remove the `generate key` button.

**Comment by andrewkmin** [comment]
@kennyadsl thanks! I'm a NodeJS developer but I'm trying to get my feet wet in a Solidus/Rails project. What is the API key good for? From the Spree docs, it seems like all that's really necessary is the order token, correct?

**Comment by kennyadsl** [comment]
@andrewkmin it can be helpful to perform API calls that require authentication. Take a look at the base api controller [here](https://github.com/solidusio/solidus/blob/6d5d40d9827cc449dfc9a7682cfce827a1f33f5c/api/app/controllers/spree/api/base_controller.rb#L102-L109). Passing that headers along with each request you'll be able to create/update stuff or view admin restricted resources.

The order token is useful to allow managing the order to guest users that do not have any key yet, so it is often what you need to implement checkouts/cart interaction in js applications.

**Comment by andrewkmin** [comment]
@kennyadsl ah I see, thanks.
For me, I'm not looking to get into the cart interactions and the actual requests that are made when a user is interacting with the site. Instead, I'm looking to draw data from the store itself (products/inventory, order history, etc.) and with Solidus, I'm not sure that there's an easy way to do so out-of-the-box. Do we have to implement these endpoints ourselves?

**Comment by quesurifn** [comment]
@andrewkmin http://guides.spreecommerce.org/api/

Solidus is build on spree 2.3 hence the docs will work.

**Comment by andrewkmin** [comment]
@quesurifn
My routes.rb file looks like the following:
```
--
Rails.application.routes.draw do
  |  
  | # This line mounts Spree's routes at the root of your application.
  | # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  | # If you would like to change where this engine is mounted, simply change the :at option to something different.
  | #
  | # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  |  
  | get 'design' => 'spree/static_pages#design'
  | get 'food' => 'spree/static_pages#food'
  | get 'faq' => 'spree/static_pages#faq'
  | get 'refer' => 'spree/static_pages#refer'
  | get 'careers' => 'spree/static_pages#careers'
  | get 'terms' => 'spree/static_pages#terms'
  | get 'dashboard' =>'spree/dashboard#index'
  | post 'dashboard/reorder/:id' => 'spree/dashboard#reorder'
  | root to: 'spree/home#index', constraints: ShopConstraint.new(false)
  | root to: 'spree/dashboard#index', constraints: ShopConstraint.new(true)
  | get '/explore' => 'spree/home#index', as: 'shop_page', constraints: ShopConstraint.new(true)
  | mount Spree::Core::Engine, :at => '/'
  | # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html'
  | end
```

Do I need to add back the routes that were included in the original documentation, as per this link? Thanks in advance ```https://github.com/spree/spree/blob/master/api/config/routes.rb```

**Comment by quesurifn** [comment]
They way spree / solidus works is all the core files are in the GEM kind of like NPM packages. The only difference is we spree is a complete solution unlike express so the routes are predefined. If you want to modify a core file you can override it by following the same folder structure as spree and creating a file with the same name (unlike NPM packages). 

As far as your routes you can leave it how you found it because the gem has all that stuff. @andrewkmin

**Comment by quesurifn** [comment]
@andrewkmin 

I actually don't use auth for my api. I didn't see the need.

**Comment by andrewkmin** [comment]
@quesurifn Thanks so much for the help man. Situation resolved. Turns out that the issue I was having was sending requests incorrectly -- once I fixed that, everything started working. Silly mistake haha

**Comment by quesurifn** [comment]
@andrewkmin  NP. Good luck. Ruby / Rails is infinitely more temperamental than node.
