### ISSUE TITLE
Empty Cart does not remove coupon code from order

### ISSUE THREAD

**Issue by seand7565** [solidusio/solidus#1919]
### Steps to reproduce
Create promotion of any kind
Add product to cart
Add promotion to cart
Empty cart
Add product to cart

### Expected behavior
There should be no promotions active

### Actual behavior
The previously entered promotion is still active

### System configuration
**Solidus Version**:Any

**Extensions in use**:None

**Comment by seand7565** [comment]
This should be fixed by changing these lines in models/spree/order.rb from:

`    def empty!
      line_items.destroy_all
      adjustments.destroy_all
      shipments.destroy_all

      update!
    end`

to 
`    def empty!
      line_items.destroy_all
      adjustments.destroy_all
      shipments.destroy_all
      promotions.destroy_all

      update!
    end`

Will test and PR

**Comment by gmacdougall** [comment]
This has been resolved by #1932
