### ISSUE TITLE
Remove taxons jstree route from api

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#194]
Taxons interface in the admin uses jstree to display and edit the taxons. It does this using a "jstree" route  in the API which returns taxons in the jstree-specific format. We should instead be using the normal show route and transform it in JS.

I started refactoring the taxons page in #157 but didn't get around to this.

**Comment by jhawthorn** [comment]
Also at the same time it might be worth removing jstree, which is complex and doesn't provide a particularly good interface (right click to add/edit/rename/remove) compared to a simpler nested sortable.

**Comment by jarednorman** [comment]
Looks like this is done.

**Comment by jhawthorn** [comment]
Closing for #2254
