### ISSUE TITLE
Allow customization of the promotion seperator

### ISSUE THREAD

**Issue by ericgross** [solidusio/solidus#1946]
Rather than always separating the promotion base with an underscore, allow the character to be changed without opening up the class.

**Comment by bbuchalter** [comment]
I just got a comment from my marketing team about making changes to this. 👍 

Extra points if it's administerable.

**Comment by jhawthorn** [comment]
As the [BatchBuilder](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/promotion_code/batch_builder.rb) can now take options, maybe we can store a desired separator value on `PromotionCodeBatch` and pass it in when running the `BatchBuilder` from `PromotionCodeBatchJob`
