### ISSUE TITLE
Round by currency fractional digits rather than by 2 digits

### ISSUE THREAD

**Issue by jordan-brough** [solidusio/solidus#1957]
In places like [this](https://github.com/solidusio/solidus/blob/v2.2.1/core/app/models/spree/calculator/flat_percent_item_total.rb#L8) we have code like this:

```ruby
computed_amount = (object.amount * preferred_flat_percent / 100).round(2)
```

The `round(2)` should really round by the number of fractional units for the order's currency.  E.g. `JPY` has no fractional units and we should round to whole numbers.

**Comment by dgra** [comment]
I can take this.
