### ISSUE TITLE
Give users a way to remove the message bar from the style guide

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#1958]
### Steps to reproduce
- Scroll down to the [flashes section](http://localhost:3000/admin/style_guide#flashes) of the style guide
- Click on any of the buttons
- See the resulting banners persist on the page until it's refreshed

### Expected behaviour
- Give the user a button to "Close open flash messages"
- Each type of flash message should only appear once

<img width="1264" alt="screen shot 2017-05-23 at 3 10 46 pm" src="https://cloud.githubusercontent.com/assets/15271353/26358323/1802d324-3fca-11e7-979a-9dd5f8752b9b.png">

**Comment by mtylty** [comment]
Will PR shortly.
