### ISSUE TITLE
Improve text in "new promotions" form for better usability

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#1960]
Related to the improvements in #1702, there's some improvements to the language used on the promotions form that will make it more intuitive for users to use.

- [x] Remove the "General" title from the top of the page. It doesn't add any value to the page, and takes up extra room.
- [x] Add info text to the description "Limit of 255 characters" - Bonus points if we can add a character counter to the description. If we can do this, we can get rid of the text and just write [number of characters used}/[max number of characters] (ie 0/255)
- [x] Change the label "Add rule of type" to "Discount rules"
- [x] Change the label "Add action of type" to "Adjustment type"
- [x] Change the label "Base Calculator" to "Discount type"
- [x] Add the currency symbol into the grey box prepended to the currency input
- [ ] <img width="515" alt="screen shot 2017-05-23 at 2 43 45 pm" src="https://cloud.githubusercontent.com/assets/15271353/26357213/847b8a54-3fc6-11e7-9a3c-5e4e80609a40.png">

**Comment by MFRWDesign** [comment]
@mfrwdesign is working on this

**Comment by kennyadsl** [comment]
This can be closed after #2917. 

> * Bonus points if we can add a character counter to the description. If we can do this, we can get rid of the text and just write [number of characters used}/[max number of characters] (ie 0/255)

is still to be implemented but I think it won't be done for now.
