### ISSUE TITLE
DisplayMoney displays '0.00' in default currency when amount is nil

### ISSUE THREAD

**Issue by laurawadden** [solidusio/solidus#1989]
### Steps to reproduce
1. in admin view, delete master price for a product
2. go to 'products' list view
3. master price is listed as '0.00' in default currency (e.g., "$0.00 USD")

### Expected behavior
If master price is empty, should show a "-" instead

### Actual behavior
If master price is empty, shows 0.00

### System configuration
**Solidus Version**:
solidusio/solidus master 4354667e6

Gemfile.lock(https://gist.github.com/laurawadden/19efb31ecf42cdebdfa1447e663767df)

**Comment by laurawadden** [comment]
Found this bug while working on #1861

**Comment by aitbw** [comment]
Unable to reproduce on `master` with rev. 3e43b22
