### ISSUE TITLE
Often can't LOGOUT

### ISSUE THREAD

**Issue by useiichi** [solidusio/solidus#1995]
### Steps to reproduce
browser is iphone safari.
login by my account.
and, click LOGOUT.

### Expected behavior
we should logout.

### Actual behavior
but can't logout.
LOGOUT link does not become LOGIN.
This occur often.

### System configuration
**Solidus Version**:v2.2.1
This does not occur on chrome in windows.

**Comment by jhawthorn** [comment]
I tried on iOS safari and was able to log out.

**Comment by jhawthorn** [comment]
If you have instructions on how to reproduce please file a new issue. Thanks.
