### ISSUE TITLE
Free shipping promotion applied when rules are not satisfied

### ISSUE THREAD

**Issue by nhippenmeyer** [solidusio/solidus#1999]
### Steps to reproduce
1. Create a free shipping promotion and add a rule for item total to be greater than or equal to a certain amount.
2. Check out with an order that doesn't satisfy the minimum item total.

### Expected behavior
The free shipping promotion should not be applied to the order.

### Actual behavior
The free shipping promotion is applied to the order even when the rule isn't satisfied.

### System configuration
**Solidus Version**: 2.2.1

**Pull request with fix**: https://github.com/solidusio/solidus/pull/1998

**Comment by fylooi** [comment]
Just upgraded to 2.2.1, seeing this as well.

**Comment by loicginoux** [comment]
Do you still have the issue with 2.4 or master branch ?

**Comment by jacobherrington** [comment]
This seems to be fixed in 2.7.

**Comment by aitbw** [comment]
This seems fixed via #2187
