### ISSUE TITLE
Missing user email not evaluated until confirm

### ISSUE THREAD

**Issue by brchristian** [solidusio/solidus#2008]
When I create a brand new Solidus 2.2 application and try to place an order from the backend, I notice that if I fill out the customer details with no email address, there is no validation error. Then later, when I go to Confirm >> Refresh Totals, I get an error message saying `Customer email can’t be blank`.

<img width="864" alt="screen shot 2017-06-08 at 4 20 07 pm" src="https://user-images.githubusercontent.com/2460418/26949084-99619f7e-4c66-11e7-980a-33a08599cd96.png">

It seems to me that we should run this validation on the _customer_ page, along with the other customer details validations (e.g., that state and country are present, etc.).

**Comment by jacobherrington** [comment]
This was solved by #2771.

**Comment by brchristian** [comment]
Closing issue. Thanks, @jacobherrington!
