### ISSUE TITLE
Parent page should be highlighted in navigation to tell user where they are

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#2029]
Different visual states are used in the menu to indicate to a user where they are in the menu. Currently we do a good job of telling them when they're on the first tab of a page, but once the user shifts to another tab, the highlighting cue disappears. 
This should consistently be highlighted for all tabs.

This affects the following pages:
Settings > Locations
Settings > Taxes
Settings > Refunds and returns

FIRST TAB
<img width="875" alt="screen shot 2017-06-16 at 11 16 30 am" src="https://user-images.githubusercontent.com/15271353/27239404-9c9d2530-5285-11e7-902f-adf28578e660.png">

SECOND TAB
<img width="817" alt="screen shot 2017-06-16 at 11 16 41 am" src="https://user-images.githubusercontent.com/15271353/27239403-9c8df9d4-5285-11e7-837e-3e1a5c5ba0f5.png">

Additionally, the side navigation should always be expanded. On the third (RMA Reasons) and fourth tab (Adjustment Reasons) the navigation is collapsed. This should be fixed so that it is always open when the user is on this page. 
<img width="1244" alt="screen shot 2017-06-16 at 11 23 26 am" src="https://user-images.githubusercontent.com/15271353/27239552-4069a256-5286-11e7-8f4a-8b865b537a32.png">

This only affects the Settings > Refunds and Returns page.

**Comment by tvdeyen** [comment]
Should be addressed by #1867

**Comment by jarednorman** [comment]
This is fixed on master and can be closed.
