### ISSUE TITLE
Initializer rename breaks extensions 

### ISSUE THREAD

**Issue by alepore** [solidusio/solidus#2033]
I just want to point out that the rename of the `spree.rb` initializer to `solidus.rb` in #1864 breaks some extension generators.
For example i have this problem with [solidus_affirm](https://github.com/StemboltHQ/solidus_affirm/blob/affirm-payment-method/lib/generators/solidus_affirm/install/install_generator.rb#L17) and [solidus_scaffold](https://github.com/freego/solidus_scaffold/blob/master/lib/generators/solidus_scaffold/scaffold/scaffold_generator.rb#L46).

Can we maybe add some helper to `solidus_support` to help backward compatibility?

### Steps to reproduce
- Install latest solidus
- Run any extension generator that writes on `spree.rb`

### Expected behavior
The generator should run

### Actual behavior
`Errno::ENOENT: No such file or directory @ rb_sysopen - (...)/solidus_affirm/spec/dummy/config/initializers/spree.rb`

### System configuration
**Solidus Version**: 2.3.0.alpha
**Extensions in use**: solidus_affirm

**Comment by tvdeyen** [comment]
Oh, this is actually an oversight on my side. The file should not be renamed. Fill provide a fix.

**Comment by alepore** [comment]
@tvdeyen or we can maybe provide both files on new installations, with some deprecations comments inside spree.rb?

**Comment by tvdeyen** [comment]
@alepore I'm fine with both approaches. What do others think?

**Comment by tvdeyen** [comment]
We agreed in the core meeting to revert the filename change
