### ISSUE TITLE
latest master branch missing the general settings page on backend

### ISSUE THREAD

**Issue by catsky** [solidusio/solidus#2054]
### Steps to reproduce
1. pull the latest master branch of solidus, and use that in a blank rails project and test with solidus
2. upon solidus is running, login with admin user
3. go to settings, can  not find 'general settings' link any more,  i dont know where to set currency :(

### Expected behavior
the 'general settings' link should be available in backend for admin user, to set the site level currency. as indicated on solidus doc:
http://ashkamel.com/solidus-guides/users/configuration/configuring_general_settings/

### Actual behavior
no link shown

### System configuration
latest master branch on 2017-07-04 94827fdce8a9d00370b3dcfae756e9aa95d1165e

**Extensions in use**:

no

**Comment by jhawthorn** [comment]
This was replaced with the "Stores" page as part of #1282

The solidus-guides (a straight port of the old spree guides) aren't terrifically up to date, and a replacement is in the works.

**Comment by DadiHall** [comment]
Is it possible to somehow to access the General settings in solidus 2.3?
