### ISSUE TITLE
rails-ujs cannot be found and is not an explicit Solidus dependency

### ISSUE THREAD

**Issue by benjaminwil** [solidusio/solidus#2067]
### Steps to reproduce

Create a typical Solidus project using the [Getting Started section of the README](https://github.com/solidusio/solidus/blob/master/README.md).

One caveat: I had to manually roll back from Rails `5.1.2` to `5.0.4`. This probably affects my (attached) Gemfile.

### Expected behavior

The sample store and backend should load at http://localhost:3000 and http://localhost:3000/admin, respectively.

### Actual behavior

On the final step, running the server (`bundle exec rails server`) ends with exceptions on both the front and backend URLs:

```
couldn't find file 'rails-ujs' with type 'application/javascript'
```

### System configuration

- `Ruby 3.16.0 2016-11-04 19:09:39 0e5ffd9123d6d2d2b8f3701e8a73cc98a3a7ff5f`
- `rails (5.0.4)`
- `solidus (2.2.1)`
- `solidus_api (2.2.1)`
- `solidus_auth_devise (1.6.3)`
- `solidus_backend (2.2.1)`
- `solidus_core (2.2.1)`
- `solidus_frontend (2.2.1)`
- `solidus_sample (2.2.1)`
- `solidus_support (0.1.1)`

[Here's my complete Gemfile](https://gist.github.com/benjaminwil/69327d0146d455cb9bce0dddd99700ba).

Let me know if you need any more information.

**Comment by graygilmore** [comment]
:wave: @benjaminwil! Thanks for the detailed write up. I just went through the `Getting Started` guide and was able to set up everything okay.

I imagine this bug was caused by the manual rollback of Rails versions. Does this happen when you start a project from scratch without the rollback?

**Comment by benjaminwil** [comment]
It looks like everything is working with Rails 5.1.x now, so no roll back would be necessary now.

If this actually was an issue, it is now even more trivial. Closing!
