### ISSUE TITLE
Error in taxes and suplicated variants

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#2071]
I have 0.21 in my taxes with taxes included in price true:
![image](https://user-images.githubusercontent.com/24247266/27967160-413b140e-6342-11e7-847f-95e597427ed3.png)

But it not calculate 0.21 x 25 =  5,25 not €4,34
![image](https://user-images.githubusercontent.com/24247266/27967286-c5dd285a-6342-11e7-8661-c06f8aa8e934.png)

Also in shipping taxes, 5 x 0.21 =1,05 not €0,87.

My product variant:
![image](https://user-images.githubusercontent.com/24247266/27967457-6c555af4-6343-11e7-8297-47770bd4f3de.png)

ALSO I have another problem, I don't know why my variants are duplicated in my _cart_form:

![image](https://user-images.githubusercontent.com/24247266/27967511-9a7db980-6343-11e7-84ca-5cff31fbb716.png)

**Comment by kennyadsl** [comment]
@sechix hello! If tax amount is included in price you have to calculate taxes starting from the price without tax. In this case it is: 20.66 (+ 4.34 = 25.00), right?
I think the same applies to shipping.

For the duplicated variants maybe it's better to open another issue with some more information, like steps to reproduce it so we can try the same locally on a clean Solidus app.

**Comment by sechix** [comment]
Ah!!! Ok, you are right!!! Sorry for the misunderstanding.
I will reproduce and open another one for dullicate variants
