### ISSUE TITLE
Separating Promotions and Taxes

### ISSUE THREAD

**Issue by MattDunbar** [solidusio/solidus#210]
Suggesting that both of these be separated from the core to be optionally remerged later when they are both ready for real life usage (probably involving a rewrite). I have *never* had a case where both actually fit all needs of a store, and there are many stores that don't need promotions at all.

We'd be happy to send a pull request for this if it'd be merged and push to the new repos (might take us a week or two to get to).

**Comment by athal7** [comment]
IMHO this is a bit heavy handed. These pieces of the system are tightly integrated into the checkout flow, and trying to extend them from outside of core has the risk of being brittle. Plus they are beneficial to many stores.

With that said, we have chatted internally about making the tax code easier to use, with defined extension points whereby one could easily attach their tax vendor of choice, which I think would solve your concern about tax (let me know if not). Regarding promotions, I would be interested to hear more specifics around what your frustrations are, as we probably have similar ones, and we can try to improve it in this codebase.

**Comment by MattDunbar** [comment]
Solving tax problems is equally good of a solution.

On the promotions side, most of the issues actually come down to the lack of coupling with taxes.

**Comment by athal7** [comment]
very good, this should be covered by https://github.com/solidusio/solidus/issues/171 and https://github.com/solidusio/solidus/issues/147 then. closing
