### ISSUE TITLE
[RFC] Canceling payments. The more correct way.

### ISSUE THREAD

**Issue by tvdeyen** [solidusio/solidus#2104]
## What happens?

When canceling orders Solidus [calls `cancel!` on each completed payment](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order.rb#L851-L858).

[`Spree::Payment#cancel!` calls `payment_method.cancel`](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/payment/processing.rb#L81-L84) and handles the response as a void response.

## The problem

That assumption is unfortunate. Lots of payment providers only allow voiding payments if they are not settled yet. Braintree is such a provider. After a transaction has settled you cannot void anymore but have to refund instead.

The `solidus_braintree` and `solidus_paypal_braintree` integrations handle this by checking the status of the transaction first and refund if the transaction cannot be voided anymore. Although this seems correct gateway wise, it is not for Solidus.

For a refunded payment we need to have a `Spree::Refund` object. Handling every response as a void and not as refund - if it should - is wrong and leads to incorrect payment state.

## Solution

The payment method itself should not know how to create refunds for payments. That's why I propose to add a new method to `Spree::PaymentMethod` called `try_void`.

`Spree::Payment#cancel!` will be changed to tell the payment method to try a void. If that succeeds we handle the response as a void - like we do currently -, but if that fails we create a refund with the full amount and "Order canceled" reason. `Spree::Refund` already talks with the gateway and credits accordingly. So, nothing more to do here.

With this change payment methods that do not have voidable states can return a valid void response like before, but payment methods that have voidable states can decide to return `false`.

**Comment by kennyadsl** [comment]
This seems a good approach. A couple of thoughts:

1. how will we handle `Spree::Refund` reason, which has to be present when the refund is created?
2. maybe it's better to call the method `void_or_refund` or something like that? Since `try_void` will also create a refund in some case it could be better to be explicit.
3. we can maybe create a (configurable) class that handle this voiding logic so it is easily customizable into stores. `try_void` will just call this class.

**Comment by tvdeyen** [comment]
> how will we handle `Spree::Refund` reason, which has to be present when the refund is created?

I went with the naive approach `first_or_create` and a hard coded string. This is not ideal, but used by us already on "Return processing". 

Ideally these reasons would be handled by `I18n`, but this is a whole new story.

> maybe it's better to call the method `void_or_refund` or something like that? Since `try_void` will also create a refund in some case it could be better to be explicit.

I don't think the payment method should handle the refund.

`try_void` should only handle the void and if that fails let the **payment** handle the refund. So, the name reflects exactly what happens: Try a void and return false if that fails (for whatever reasons).

Think of `try_void` being a little more conservative then `cancel` (the latter always voids, while the former only voids if the transaction is voidable).

### Example

#### The Payment

```ruby
# app/models/spree/payment/processing.rb

def cancel!
  if response = payment_method.try_void(response_code)
    handle_void_response(response)
  else
    reason = Spree::RefundReason.where(name: 'Order was canceled').first_or_create
    refunds.create!(amount: amount, reason: reason)
  end
end

```

#### The payment method

```ruby
# app/models/solidus_paypal_braintree/gateway.rb

def try_void(response_code)
  transaction = braintree.transaction.find(response_code)
  if VOIDABLE_STATUSES.include?(transaction.status)
    void(response_code, nil, {})
  else
    false
  end
end

```

> we can maybe create a (configurable) class that handle this voiding logic so it is easily customizable into stores. `try_void` will just call this class.

I would then move **the whole payment cancellation flow** into a configurable class. Since the disputable part of my idea is the "refund if void fails" behavior. Maybe some stores don't want that or want to keep the old behavior. 

We could even move the old behavior into a `LegacyPaymentCancellation` class. 

What do you think @mamhoff @jhawthorn @jordan-brough @gmacdougall @cbrunsdon ?
