### ISSUE TITLE
I unsuccessfully attempted to deploy Solidus on Heroku thrice

### ISSUE THREAD

**Issue by Yekutiel** [solidusio/solidus#2108]
I unsuccessfully attempted to deploy Solidus on Heroku thrice. Each time I used different login credentials on the odd chance that the login credentials I had used the first and second time might have caused the problem.

Each of the three times the following error messages appeared on my screen:

"**App creation failed. Please ensure you have valid values in the above form fields.**"

"**Run scripts & scale dynos
postdeploy exit code was not 0**"

![heroku screenshot](https://user-images.githubusercontent.com/16394972/28500319-17b83a40-6f7b-11e7-8536-ebaab9570579.png)

**Comment by jhawthorn** [comment]
Thanks for the report.

I believe this was failing because of missing solidusio/solidus_auth_devise#102, which wasn't in a release yet. I just released a new version of solidus_auth_devise and this should be fixed.

**Comment by Yekutiel** [comment]
> Thanks for the report.

Thanks for the quick, informative, and helpful response.


> I believe this was failing because of missing solidusio/solidus_auth_devise#102, which wasn't in a release yet. 

Ah. Ok. I see.


> I've just released a new version of solidus_auth_devise and this should be fixed.

I successfully deployed Solidus on Heroku therefore I assume your supposition was correct.

**Comment by jhawthorn** [comment]
> I successfully deployed Solidus on Heroku therefore I assume your supposition was correct.

:smile: Great!
