### ISSUE TITLE
Create a store credit reasons page

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#2110]
Currently, a developer needs to update the store credit reasons because admins don't have a UI to add new options. It would be better if admins could manage these reasons themselves similar to the other refund and return reasons.

To be fair - I'm not sure what reasons already exist in this table so the content in this table is made-up. If Solidus doesn't have any reasons out of the box, a message should appear inviting admins to create a new reason. 

The attached wireframes are created with the newly added inline table editing in mind. No additional pages are needed to edit or add new values.

![store credit reasons empty](https://user-images.githubusercontent.com/15271353/28549444-f4279516-708e-11e7-9daa-c633efbe89dd.png)
![store credit reasons](https://user-images.githubusercontent.com/15271353/28549443-f426d7a2-708e-11e7-8069-d68a7e677d44.png)

**Comment by kennyadsl** [comment]
Closed with #2798, thanks a lot @jtapia !
