### ISSUE TITLE
Use better routes naming convention in the backend's JS

### ISSUE THREAD

**Issue by graygilmore** [solidusio/solidus#2113]
The backend JS routes are currently arbitrarily named:

- `admin_product_search` for `admin/search/products`
- `option_type_search` for `api/option_types`
- `stock_locations_api` for `api/stock_locations`
- `stock_items_api` for `api/stock_locations/' + stock_location_id + '/stock_items` (uses a plural path despite targeting a singular resource)

If those routes were matched up to their Rails naming counterparts they would look like:

- `admin_search_products`
- `api_option_types`
- `api_stock_locations`
- `api_stock_location_stock_items`

These are easier to understand what paths they line up to in our application and remove some of the guessing work (knowing that you need to pass a stock location ID in the last example, for instance).

This could have negative side effects to extensions or customizations that are being tied into these. What would make a reasonable path forward on updating this part of our system?

**Comment by jhawthorn** [comment]
I've actually just been ignoring the JS routes and instead [just using `Spree.pathFor`](https://github.com/solidusio/solidus/blob/5283b4c4c91af37c1cc1f83ed4517628d18c4f93/backend/app/assets/javascripts/spree/backend/models/taxonomy.js#L2).

It's a level of indirection that I'm not sure we get any benefit from. Unlike the rails routes, which are generated and we know will exist for all routes, I fear [the backend routes](https://github.com/solidusio/solidus/blob/5283b4c4c91af37c1cc1f83ed4517628d18c4f93/backend/app/assets/javascripts/spree/backend/routes.js) are just extra maintenance work.

**Comment by graygilmore** [comment]
That makes way more sense to me. Perhaps this issue should then be to remove the `Spree.routes` object and update the routes throughout the backend JS to use `pathFor` instead. Is this something that we'd first want to deprecate before removing completely?

(I know this is likely far down the priority list)

**Comment by jarednorman** [comment]
I'm going to open a separate issue for this that reflects the real issue.
