### ISSUE TITLE
Move inventory unit to new shipment refresh the price

### ISSUE THREAD

**Issue by DanielePalombo** [solidusio/solidus#2134]
### Steps to reproduce
- Complete an order and adds a line item
- Change the master price of the variant
- Move the line item to another shipment

### Expected behavior
The price should not change on the new shipment.

<img width="1000" alt="screen shot 2017-08-04 at 11 52 49" src="https://user-images.githubusercontent.com/387690/28964861-e7069f0c-790e-11e7-8701-aa9f4225ab4c.png">

<img width="985" alt="screen shot 2017-08-04 at 11 53 31" src="https://user-images.githubusercontent.com/387690/28964823-c4f27896-790e-11e7-8231-d78d3feeb30b.png">

<img width="996" alt="screen shot 2017-08-04 at 11 53 58" src="https://user-images.githubusercontent.com/387690/28964822-c4f1c5a4-790e-11e7-9350-adfa044f06a4.png">

### Actual behavior
The price of line items in the new shipment is changed and the `payment state` is changed in `balance due`.

### System configuration
Affects all solidus versions.

Few days ago a new object to manage this movement is created.

https://github.com/solidusio/solidus/blob/master/core/app/models/spree/fulfilment_changer.rb

Maybe we can pass the informations of line_item and create a new line item with the correct price.

**Comment by mamhoff** [comment]
Have you checked whether this actually affects the current master branch? That object is precisely designed to avoid that flaw.

**Comment by DanielePalombo** [comment]
It works with FulfilmnetChanger. My tests was with the latest stable version (v2.3). 

Thank you.
We can close this issue.
