### ISSUE TITLE
Updating promotion can clear out association between adjustment and action.

### ISSUE THREAD

**Issue by adammathys** [solidusio/solidus#2142]
### Steps to reproduce
1. Create promotion with a CreateItemAdjustment action.
2. Complete an order using that promotion.
3. Update promotion to have a different action. (Could be the same type of action.)

### Expected behavior
I believe the adjustments should retain their association to the promotion action. (It's a paranoid record, so it hasn't fully been deleted by updating the promotion.)

### Actual behavior
Promotion adjustments now have `nil` as their `source_id`.

### System configuration
**Solidus Version**: 2.2+ (May be an issue on earlier versions, but this is the oldest I've tested.)

**Extensions in use**:
```
source "https://rubygems.org"

gem "rails", "~> 5.0.0"

gem "sqlite3"

gem "sass-rails"
gem "uglifier"
gem "coffee-rails"
gem "jquery-rails"

gem "solidus", "~> 2.2.0"
gem "solidus_auth_devise"
```

**Comment by jhawthorn** [comment]
I think this is caused by [this line in AdjustmentSource#deals_with_adjustments_for_deleted_source](https://github.com/solidusio/solidus/blob/b2acb1e048bfdd64bf01d2ea3dd92b775b16ae8a/core/app/models/concerns/spree/adjustment_source.rb#L16)

**Comment by jhawthorn** [comment]
@adammathys does #1419 solve this issue for you?

**Comment by adammathys** [comment]
@jhawthorn :+1: I believe so.

**Comment by adammathys** [comment]
Fixed by https://github.com/solidusio/solidus/pull/2259
