### ISSUE TITLE
Remove Bundler notice from README?

### ISSUE THREAD

**Issue by radar** [solidusio/solidus#2151]
Saw your Bundler issue link in the README. They [claim to have fixed this issue](https://github.com/bundler/bundler/issues/5633#issuecomment-316416212).

I'd be interested to know if the problems you're seeing, @jhawthorn, have gone away or not. If they have, then you can probably do away with the scary README notice 😛

**Comment by jhawthorn** [comment]
Great to see you here @radar :heart: :bowing_man: 

Unfortunately the [latest release of bundler](https://rubygems.org/gems/bundler), as of writing 1.15.3 is still very broken. I'm guessing the fixes won't make it in until a 1.16 release.

```
$ bundle update
Fetching gem metadata from https://gems.stembolt.io/...........
Fetching version metadata from https://gems.stembolt.io/..
Fetching dependency metadata from https://gems.stembolt.io/.
Resolving dependencies............................................................
...........................
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    solidus_core (= 2.2.0) was resolved to 2.2.0, which depends on
      rails (~> 5.0.0) was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0)

    rspec-rails (~> 3.4) was resolved to 3.4.0, which depends on
      railties (< 4.3, >= 3.0) was resolved to 4.2.8, which depends on
        actionpack (= 4.2.8)

jhawthorn@nestea:~/src/bundler_wtf (master ) [ruby 2.4.1]
$ bundler --version
Bundler version 1.15.3
```

**Comment by radar** [comment]
I just tried this with the latest master from Bundler:

1. `alias dbundle='~/code/gems/bundler/bin/bundle'`
2. New directory with [this Gemfile](https://github.com/bundler/bundler/issues/5633#issuecomment-301890682)
3. `dbundle install`
4. Saw that it ran successfully.

So yes I think you're right that the next version of Bundler will fix this issue :tada:

**Comment by jhawthorn** [comment]
Scary warning is gone :tada:
