### ISSUE TITLE
Spree::PermissionSets::ProductManagement missing Price management

### ISSUE THREAD

**Issue by loicginoux** [solidusio/solidus#2161]
### Steps to reproduce
- create a role with the permission `ProductManagement`, 
- assign a user this role
- login to admin page with this user
- go to an admin product page

```
# Adding role Business with product management
Spree::Role.where(name: "business").first_or_create
Spree::RoleConfiguration.configure do |config|
  config.assign_permissions :business, [
    Spree::PermissionSets::DashboardDisplay,
    Spree::PermissionSets::ProductManagement,
  ]
end
```
### Expected behavior
I would expect to see the prices tab with all the other product tabs

### Actual behavior
I don't see that the prices tab

### System configuration
**Solidus Version**: 2.2.1

I am happy to submit a PR if this is a confirmed bug.
Thanks.

**Comment by cbrunsdon** [comment]
Hmm, definitely looks like a bug to me. Happy to take a PR or we can get @swcraig on it.

**Comment by cbrunsdon** [comment]
Certainly looks like `Spree::Price` belongs with the other product management permissions:
https://github.com/solidusio/solidus/blob/master/core/lib/spree/permission_sets/product_management.rb

**Comment by swcraig** [comment]
@loicginoux Nice catch. I am more than happy to write a PR myself, unless you specifically would like to! Let me know.

**Comment by cbrunsdon** [comment]
@swcraig you may as well just do it, it should be pretty quick

**Comment by cbrunsdon** [comment]
Thanks @loicginoux, hopefully you're cool we sniped your PR opportunity, thanks for offering though.
