### ISSUE TITLE
Several payment methods are added to order in checkout process

### ISSUE THREAD

**Issue by fschwahn** [solidusio/solidus#2172]
### Steps to reproduce
Is reproducible with the spree demo app. Run through the checkout process, choose eg. "Check". On the confirmation page, go back and edit the payment method, and choose something different, eg. "Credit card". The order has now 2 payment methods (in the example: Check & Visa):
![image](https://user-images.githubusercontent.com/57876/29514841-45d94b5c-866a-11e7-9f9a-9f3eec1db24d.png)

### Expected behavior
I'd expect the existing payment method to be overwritten

### Actual behavior
Additional payment is added to the order along the previous payment method.

It's really unclear what this even means: what payment method is now used to pay the order? Is the order payment split between those 2? How can I _remove_ one of the payment methods?

My guess is that this is intentional, but I think the more common scenario is that someone wants to replace their payment method, which does not seem possible at all.

### System configuration
**Solidus Version**: reproduced in vanilla `2.3.0`, but also happens in `2.0.1`.

**Extensions in use**: only `solidus_auth_devise`

**Comment by tvdeyen** [comment]
This will be fixes by https://github.com/solidusio/solidus/pull/2075 in 2.4.0

If you want to use this today use the latest `master` in your `Gemfile`

**Comment by fschwahn** [comment]
Cool! I searched the issue tracker for this, but apparently not well enough 😞
