### ISSUE TITLE
Demo instance custom credentials fail

### ISSUE THREAD

**Issue by jtme** [solidusio/solidus#2179]
### Steps to reproduce
deploy heroku demo app, fill in fields for admin account, try to login. 

### Expected behavior
login should work with whatever email/passw set. 

### Actual behavior
login fails

### System configuration
n/a

PS - default credentials work

**Comment by benjaminwil** [comment]
Hey @jtme, I just deployed a demo app with custom credentials and was able to log in.

Could you double-check that you're still unable to do this?
