### ISSUE TITLE
Existing payment partial error/Store credit error

### ISSUE THREAD

**Issue by trevorh2007** [solidusio/solidus#2203]
### Steps to reproduce
1. Create new user
2. Order a product
3. Try to order another product after completion of first order
4. On checkout when attempting to reach payment page returns error

### Expected behavior
Payment screen should behave like the first time buying a product, with existing payment being a viable option for another order

### Actual behavior
Raises the error

undefined method `method_type' for nil:NilClass

changing line 24 in app/views/spree/checkout/_payment from

partial: "spree/checkout/existing_payment/#{wallet_payment_source.payment_source.payment_method.method_type}"

to

partial: "spree/checkout/existing_payment/gateway"

seems to be a quick fix, however doesn't seem to be dynamic when multiple payment methods are used. Also noted that in master it does change the "method_type" to "partial_name" and tested this as well, however there is no "partial_name" in these directories. We tested giving store credit to a user as well and another issue came about. When reaching the payment page with store credit resulted in this error:

Missing partial spree/checkout/payment/_storecredit with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder, :rabl], :versions=>[:v1]}

Again, using the quick fix this time gets the payment page to load, but once it does and you select store credit radio button and submit to update/payment we get this error:

unknown attribute 'number' for Spree::StoreCredit.

### System configuration
**Solidus Version**:

2.2.1

**Extensions in use**:

solidus_subscriptions
solidus_auth_devise
solidus_gateway
solidus_email_to_friend

**Comment by benmzh** [comment]
Thanks @trevorh2007 for the detailed breakdown. I've had the same problem with my live site. I'll use the quick fix but would prefer a more long term solution eventually. I'll stay tuned.

**Comment by kennyadsl** [comment]
This can be closed, I just tried on a new Solidus version and it works as expected.
