### ISSUE TITLE
Splitting a shipment on line item with promo removes the promo

### ISSUE THREAD

**Issue by loicginoux** [solidusio/solidus#2214]
### Steps to reproduce
- create a promotion on an item, in my example, "when product A is in cart, apply a 10% discount on this product"
- create an order with 2 lines items: 1 product A + 1 product B
- add a customer 
- we are now in state delivery
- on shipment tab, split the line items of the product A (line item with promo) 
- we are now in state confirm

### Expected behavior
- The total amount should not change

### Actual behavior

- The total amount has been changed because the line item promotion is not applied to line item so 
```
new_total_amount = old_total_amount + promo_adjustment_amount (10% of product A)
```

### System configuration
**Solidus Version**: 2.2.1

I tried to follow what was happening in the code so here is what I came up with, when splitting a line item, the old line item is destroyed and a new one is created. When this one gets created, the promotion adjustment is not added back to the order. 

It seems like `PromotionHandler::Cart.new(order, line_item).activate` is used to activate line item promotions when for example we first add a line item via `POST "/api/orders/R193974774/line_items"`
I guess that when splitting a line and recreating the line item this `PromotionHandler::Cart.new(order, line_item).activate` is not called

Note:
- when splitting the order on product B, everything is fine. 
- when splitting on product A when order is on state confirm or complete, I have the same bug.
- when making an order with only one product A, and splitting in delivery state, the promotion adjustment is not removed.
- the API call sent when splitting a line item is this one 
```
POST "/api/shipments/transfer_to_location"`
Processing by Spree::Api::ShipmentsController#transfer_to_location as JSON
  Parameters: {"original_shipment_number"=>"H34274667482", "variant_id"=>"75", "quantity"=>"1", "stock_location_id"=>"8"}
```

**Comment by mamhoff** [comment]
Would you mind trying this on the `master` branch? We worked a lot on those features, and bugs like that should be resolved now.

**Comment by loicginoux** [comment]
Sorry for late feedback, I'll upgrade to 2.4.0 shortly and come back on this as soon as I can. Thank you.

**Comment by loicginoux** [comment]
Hello, I finally tried the same steps on `v2.4.0.beta1`. The promotion didn't get removed from the order so this is fixed. 
There is still something that does not seem correct about the new shipment, it is not in "ready" state. I'll open a new ticket and close this one.
