### ISSUE TITLE
when splitting a shipment on a complete order, cannot add shipping method

### ISSUE THREAD

**Issue by loicginoux** [solidusio/solidus#2215]
### Steps to reproduce
- create an order with a product
- add a customer
- add a payment (by check for example)
- complete/confirm the order, the order is in "complete" state 
- capture the payment
- split the line item: the api call is `POST "/api/shipments/transfer_to_location`

### Expected behavior
- We should have kept the same shipping method or at least be able to add one

### Actual behavior
- the shipping method is empty and when editing it, the list is empty. We cannot add a new shipping method.

### System configuration
**Solidus Version**: 2.2.1

Note:
- works fine when order status is in delivery
- there is no unit tests on `POST api/shipments/transfer_to_location` to understand what this call is supposed to do

This issue may be related to #2214 

Let me know if you need more information

**Comment by mamhoff** [comment]
Can you try this out in the current `master` version of Solidus? This bug might be fixed already.

**Comment by digitalWestie** [comment]
Using solidus 2.3.0, same problem here.

**Comment by mamhoff** [comment]
I'm saying the current `master`, which is still unreleased. I know it's an issue in all released versions.

**Comment by digitalWestie** [comment]
Just tried on `master` working fine :+1:

**Comment by mamhoff** [comment]
We keep released versions stable, and only add changes in behaviour like this for new releases. We consider the bug, therefore fixed. Closing this issue.
