### ISSUE TITLE
update product classification should invalidate product cache

### ISSUE THREAD

**Issue by loicginoux** [solidusio/solidus#2237]
### Steps to reproduce
- get product details via api and see the classification
- change/update the taxons in admin product view.
- get product details via api and see the classification

### Expected behavior
The classification value from the api response should be updated

### Actual behavior
The classification value from the api response is not updated.

### System configuration
**Solidus Version**: 2.2.1

The cache key in the file `/solidus_api-2.2.1/app/views/spree/api/products/show.v1.rabl`
is :
```
cache [I18n.locale, @current_user_roles.include?('admin'), current_pricing_options, root_object]
```

I would suggest to add a `touch: true` in the product association of the model `Spree::Classification` :

```
    belongs_to :product, class_name: "Spree::Product", inverse_of: :classifications, touch: true
```

If this is ok with you, I can submit a PR for this.

**Comment by mamhoff** [comment]
I think products might have `touch: true` on classifications as well (I'm sure they have on taxons). Can you check whether touching on both sides does not create race conditions? If it does not, this makes perfect sense, and I would be very happy to see a PR for this.

**Comment by loicginoux** [comment]
Taxon touches the taxonomy tree in `#touch_ancestors_and_taxonomy`.
Product touches Taxon and Taxonomies but not classification.
Not sure what you mean by " touching on both sides does not create race conditions"  but touching a product or a taxon does not create a problem (infinite touch loop, if it's what you meant...)

**Comment by mamhoff** [comment]
Yeah, infinite touch loop is in fact what I meant :) Thanks for clarifying!

**Comment by loicginoux** [comment]
I guess this can be closed, if PR has been merged.
