### ISSUE TITLE
use products index like root route for frontend?

### ISSUE THREAD

**Issue by ccarruitero** [solidusio/solidus#2240]
Currently `home#index` is the root route for frontend, but looking the controller and view seems very similar to `products#index`.

I suppose there were different before, but now that are too similar why not change the root route to `products#index`?

**Comment by tvdeyen** [comment]
A lot of people make changes to the template, add static content or even dynamic content from CMS's, that should not appear on the products index template. Therefore I wouldn't make changes to this.

**Comment by ccarruitero** [comment]
I understand that people will desire customize their homepage in different way than products page.

I just was thinking that building an entire home page from scratch will be the option most used for customize the home page.

But like you mention could be people that made their customization on top of current template, and removing this could cause unnecessary problems in their implementation.

Anyway I'm closing this.
