### ISSUE TITLE
OrdersController#populate -- send options to order.contents

### ISSUE THREAD

**Issue by brendandeere** [solidusio/solidus#2249]
In a few scenarios now I have needed to override the whole of OrdersController#populate in order to change [this](https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/orders_controller.rb#L55) line to pass custom attributes to the OrderContents. 
ex.  `@order.contents.add(variant, quantity, order_populator_options)`.

In my use cases this has been useful to set custom attributes on lines items [here](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order_contents.rb#L99).

Would this be a useful contribution to frontend?
Would there be a benefit of adding a pluggable class like OrderPopulator to wrap some of this behaviour?

Or conversely

If this is not behaviour we wish to expose, should it exist at all in OrderContents

**Comment by jhawthorn** [comment]
This was attempted in #1918, #721, but isn't viable due to security concerns. Please feel free to file a PR if it addresses these concerns.
