### ISSUE TITLE
Make cart total/subtotal background color configurable

### ISSUE THREAD

**Issue by mamhoff** [solidusio/solidus#2251]
As identified by @akihitoalextsuboi in #1708, we have a hardcoded color variable for the background of the cart subtotal and total. We should change this to be a configurable, well-named variable. 

A good variable name would be `$cart-total-background-color`.

**Comment by kennyadsl** [comment]
It should also probably take into account `$product_price_text_color` now.

**Comment by gregdaynes** [comment]
I'll look into this later today.
