### ISSUE TITLE
Move all UI related stuff into solidus_ui

### ISSUE THREAD

**Issue by dt1973** [solidusio/solidus#2273]
Been seeing a lot of UI related stuff arriving in my email lately and I can't help but thinking; all these CSS hacks and Bootstrap adjustments has very little to do with the Solidus core, so wouldn't it be better to break it apart and modularize it into say `solidus_ui`, `solidus_ui_admin` etc.?

I'm using Solidus with my own [simplified](http://motherfuckingwebsite.com)/[redesigned](https://wolffolins.com/) views/CSS/JS so forgive me if I'm a little bit biased.

**Comment by mamhoff** [comment]
We offer a frontend and a backend, and you can just not require these or override their CSS/JS. You'll need both for a functional store. Closing this for not being specific enough.
