### ISSUE TITLE
Dynamic Price based on Options of a Product

### ISSUE THREAD

**Issue by aosorio1** [solidusio/solidus#2275]
I don't know where to ask this question, is there any community forum for Solidus? I wanted to know if this plugin is supported in Solidus https://github.com/QuintinAdam/spree_flexi_variants it's a way to avoid creating for every possible option type/option value a variant but instead creating it dynamically. Do I have to use a plugin like that? Or is there native support for this in Solidus?

**Comment by mamhoff** [comment]
@aosorio1 There is a Solidus version of that plugin by Boomer Digital: https://github.com/boomerdigital/solidus_flexi_variants.

We don't have a forum, but you're welcome to use our Slack channels under https://sodiusio.slack.com.

If you want to build this functionality yourself, we have good support for customizing pricing using the `Variant::PriceSelector` class.

**Comment by aosorio1** [comment]
I'll check that plugin. Thanks for your response.
