### ISSUE TITLE
question: an extension to have all order state changes from the backend UI

### ISSUE THREAD

**Issue by loicginoux** [solidusio/solidus#2297]
We added a tab in the order backend interface to follow the order workflow from the interface. 
<img width="1318" alt="screenshot 2017-10-17 15 44 37" src="https://user-images.githubusercontent.com/824936/31670293-8eb73f54-b357-11e7-9931-b74219f28e03.png">

That's a basic representation of the state_changes table. We needed it for non technician and support team to know exactly what happen in the workflow, at what time, etc... It's easier and quicker to follow.

Do you guys think that would be something that other people want as an extension ? We would be ok to open as an extension if you think it's worth it. Let me know !

**Comment by jhawthorn** [comment]
This is worth asking in Slack.

There's certainly no harm in more extension :smile:
