### ISSUE TITLE
rails g installation not working

### ISSUE THREAD

**Issue by krtschmr** [solidusio/solidus#2346]
```
NameError: undefined local variable or method `spree' for #<Spree::UserMailer:0x0000000b71c720>
/home/tim/.rvm/gems/ruby-2.4.1/gems/solidus_auth_devise-2.0.0/app/mailers/spree/user_mailer.rb:11:in `confirmation_instructions'
/home/tim/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:186:in `process_action'
/home/tim/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/tim/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:97:in `run_callbacks'
/home/tim/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/tim/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:124:in `process'
/home/tim/.rvm/gems/ruby-2.4.1/gems/actionmailer-5.1.4/lib/action_mailer/rescuable.rb:23:in `block in process'

```

**Comment by kennyadsl** [comment]
@krtschmr can you please post more information about what have you done and your Gemfile content in order to reproduce the issue?

**Comment by krtschmr** [comment]
i've added to Gemfile and `bundle update`

```
gem 'solidus'
gem 'solidus_auth_devise'
```

just ran `rake` to still have green tests, so i'm all good to run.



i run `bundle exec rails g spree:install`

which gives following output

> 
>       create  config/initializers/spree.rb
>       append  public/robots.txt
>       create  vendor/assets/javascripts/spree/frontend
>       create  vendor/assets/javascripts/spree/backend
>       create  vendor/assets/stylesheets/spree/frontend
>       create  vendor/assets/stylesheets/spree/backend
>        exist  vendor/assets/images/spree/frontend
>        exist  vendor/assets/images/spree/backend
>       create  vendor/assets/javascripts/spree/frontend/all.js
>       create  vendor/assets/stylesheets/spree/frontend/all.css
>       create  vendor/assets/javascripts/spree/backend/all.js
>       create  vendor/assets/stylesheets/spree/backend/all.css
>        exist  app/overrides
>       append  db/seeds.rb
>      copying  migrations
>     creating  database
>         rake  db:create
> Database 'project_rails5_development' already exists
> Database 'projectr_rails5_test' already exists
>      running  migrations
>         rake  db:migrate VERBOSE=false
> 
> 
> 
> generating cartons
> (1ms)
> linking inventory units to cartons
> (1ms)
>      loading  seed data
>         rake  db:seed 
> "create 8 user"
> rake aborted!
> NameError: undefined local variable or method `spree' for #<Spree::UserMailer:0x0000000cd80e80>
>

**Comment by krtschmr** [comment]
nevermind. it seems that it's loading *my seed.rb* and then the error occurs. urgh.

**Comment by kennyadsl** [comment]
ok, can we close this?
