### ISSUE TITLE
Error NameError: uninitialized constant ActiveMerchant::Billing::BeanstreamGateway

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#2357]
I have '2.5.0.alpha' I am getting this error   ActiveMerchant::Billing::BeanstreamGateway, I think is due to  ActiveMerchant version due to solidus_gateway. Any idea how to solve it? i am not using Beanstream Gateway

**Comment by sechix** [comment]
I added gem activemerchant last version, and now I get NameError: uninitialized constant Spree::Admin::ImagesHelper.

**Comment by ccarruitero** [comment]
Well is difficult to know where is firing the error, without an error trace or more details about the gems that you are using in your project.

Can you reproduce the error in a new solidus app?

**Comment by sechix** [comment]
Finally i solved by myself, adding and install Last gem of archive_merchant
