### ISSUE TITLE
Upgrade path from Spree 3.0

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#238]
Solidus currently provides a working upgrade path from Spree 2.2, 2.3, and 2.4 (and likely earlier) but not from 3.0. This may be tricky since our fork point was 2.4.

**Comment by BenMorganIO** [comment]
Working on this right now. Will make a PR with documentation changes as per my experience.

**Comment by jhawthorn** [comment]
We've merged #265, which means that migrations will now complete when coming from a 3.0 store. More work is needed to sync up the schemas and some functionality.

**Comment by BenMorganIO** [comment]
@jhawthorn Its awesome that we've merged #265. Just concerned about the UI functionality right now expecting an environment.

**Comment by jhawthorn** [comment]
@BenMorganIO how do you feel about this? Are there any additional changes we should make in order to close this?

**Comment by BenMorganIO** [comment]
Sent some images over Slack.

**Comment by jhawthorn** [comment]
Closing as it seems to be possible. Any issues upgrading should be filed as new issues.
