### ISSUE TITLE
order_with_totals factory does not set totals

### ISSUE THREAD

**Issue by cbrunsdon** [solidusio/solidus#2389]
The order_with_totals factory doesn't recompute the totals on an order, so the order doesn't in fact have any totals on it. 

We either need to change the name,  compute the totals, or just remove it entirely (I don't think we use it in core solidus?

https://github.com/solidusio/solidus/blob/master/core/lib/spree/testing_support/factories/order_factory.rb#L22-L30

**Comment by jhawthorn** [comment]
Fixed by #2470
