### ISSUE TITLE
Updating Shipping Address When Order is Complete Doesn't Update Shipping Methods on Shipments

### ISSUE THREAD

**Issue by ericsaupe** [solidusio/solidus#2410]
### Steps to reproduce
1. Complete an order on the frontend with an EU address
2. In backend, change the address for both billing and shipping to be US address
3. Go to the Deliveries tab and notice that the only shipping options is for the EU address

### Expected behavior
Shipping methods should be updated to the current shipping address if the shipment has not been shipped yet.

### Actual behavior
Shipping methods stay with what they were previously when created.

### System configuration
**Solidus Version**: Tested with 2.2, 2.3, and 2.4

**Extensions in use**: Solidus Auth Devise

**Comment by jacobherrington** [comment]
I can't reproduce this on Solidus 2.7.
