### ISSUE TITLE
[RFC] Events in Solidus

### ISSUE THREAD

**Issue by swcraig** [solidusio/solidus#2430]
@derrickp and I have been working on making user notifications more customizable.

Historically, Solidus has handled “transactional” communication to users with email, sent using [ActionMailer](https://github.com/rails/rails/tree/master/actionmailer). “Transactional” emails notify users that:
- Order has been confirmed
- Order has been cancelled
- Shipment has shipped

Additionally, in some cases we use email to notify admins that their operations have finished processing, as is the case in reimbursements and order inventory issues. Popular extensions have also used our ActionMailer settings, with [solidus_auth_devise](https://github.com/solidusio/solidus_auth_devise) using ActionMailer to send notifications for password reset or recovery.

How stores handle notifications to users is an integral part of the experience to shopping online. As Solidus stores evolved, external notification platforms (SMS, email-templating-as-a-service, A/B testing of email), individual stores have had to implement these alternate notification channels using very intrusive overrides to solidus core. While ActionMailer is the only notification system offered in core, it is not widely used and is often turned off and discarded.

We believe that Solidus core needs to support a clear, extendable, configurable system to give stores tighter control over how and when notifications are sent to users. Our goal would be to allow stores to implement whatever notification systems they desire without the need to override core. 

As almost all large Solidus stores have had to completely re-write or overwrite core to build complex user notifications, it is a long-standing problem in the Spree/Solidus ecosystem.

There have already been attempts to make behaviour customizable by adding “hooks” around specific actions. For example:
- [in reimbursements](https://github.com/solidusio/solidus/blob/354eb21a5469cc5487440e978ac780a06f5676cc/core/app/models/spree/reimbursement.rb#L108)
- [in orders](https://github.com/solidusio/solidus/blob/354eb21a5469cc5487440e978ac780a06f5676cc/core/app/models/spree/order.rb#L431)

These have been largely unsuccessful as they are obscure, undocumented, and insufficient for most stores needs.

In addition to at least [one large-scale attempt](https://github.com/solidusio/solidus/pull/1218) to tackle the problem, we’ve made two large and distinct attempts to achieve the goal of a customizable system:
  - [Command based approach](https://github.com/swcraig/solidus/pull/11)
  - [Observer based approached](https://github.com/swcraig/solidus/pull/9)

We don’t believe any of our previous approaches, or any attempt made or pitched to Solidus Core, have gone far enough to solve the problems mentioned above. We need to take a more “radical” approach to solve the problem.

We find it impossible to have the discussion on the behavior of when the system should notify users and what should happen without bringing up the concept of “events”. “When a user’s order is shipped, the user should receive an email.” “When an order is cancelled, the user should receive a text message.” The actions we discuss are in response to “events” of the system.

We believe the core concept missing in previous attempts at customizing a notification system is that Solidus lacks a common feature in similar-sized systems, that of an “event bus”. We’ve attempted many things to avoid needing an “event bus”, where these notifications can be watched and responded to, but argue it's now time to add an event system to Solidus.

We [have a work in progress](https://github.com/solidusio/solidus/pull/2431) that implements an event bus. In addition to what we’re already working on, we want to:
 - Represent our events as classes (instead of hash arguments)
 - Write the methods used in subscriptions as procs.
 - Consider using an existing RubyGem instead of writing our own.
 - Use a hierarchy for our event naming so that all ‘order’ events could be subscribed to. This also needs to prevent a custom event being accidentally ‘captured’ by the existing system.

We think that this path is the most reasonable way forward and that Solidus needs a system like this to grow. We’re happy to hear from the community about this proposal.

**Comment by tvdeyen** [comment]
Thanks for catching up on this topic. This is a long standing issue we have in Solidus. I like the idea of an event bus and think this is the right way to do it. 👍 

Have you looked into [`ActiveSupprt::Notifications`](http://api.rubyonrails.org/classes/ActiveSupport/Notifications.html)?

They seem to support everything we need from an event bus and ship with Rails. No need for an extra dependency and easy to adopt to.

I never worked with them, so I can't say if there are any caveats or downsides I'm not aware of, but I think we should give it a try.

**Comment by mtomov** [comment]
I also agree on the events system, and the proposed Event Bus implementation looks good! Thanks for that.

Such events should allow for easier integration with Webhook services such as [Zapier](https://zapier.com/) or [cangaroo](https://github.com/nebulab/cangaroo)

**Comment by kochis** [comment]
I realize this is over a year old, but wanted to check if there's any update on this.

Also wanted to say that I really like the idea of an event / pub-sub based solution for handling all the different state transitions that can occur. This was actually something that was a major pain-point for us (callback-hell), and we even made a couple attempts at implementing it ourselves.

Ultimately, I think the biggest challenge was knowing all the different types of events that could occur. It would be great if there was a way to compile a list of all the different transactions could occur / would make sense to hook into. I guess really it's any model change, so maybe `ActiveSupprt::Notifications` makes the most sense, but coming with a list of events before implementing might be a good way to track progress on the issue.

Anyways, love this idea, and think it would be solving a major pain point for a lot of developers 🙌

**Comment by jacobherrington** [comment]
@kochis #2431 is still being discussed, for sure, if you have ideas you should weigh in there!

**Comment by kennyadsl** [comment]
Closing now that #3081 has been merged!
