### ISSUE TITLE
Remove backend Admin::Search controller

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#244]
Split from #240

This controller has two "lightweight" versions of existing api index actions. We should switch to using the API, but it's currently significantly slower.

We'll have to either optimize the endpoint, or allow specifying which fields we want (ex. `?fields=name,id` or `?include=`)

**Comment by bbuchalter** [comment]
Now that #240 is merged, is there any reason we can't remove `Admin::Search`?

**Comment by bbuchalter** [comment]
Firing up a dummy app and running `rake routes` shows `admin_search_users` and `admin_search_products` are still out there, but not in use anywhere. I suppose we'd need to deprecate those end points? If there is a good example of how to do that, I'd be happy to open a PR. Or perhaps we just remove them?

**Comment by cbrunsdon** [comment]
Marked it down on my personal hit list, but closing this issue due to staleness.
