### ISSUE TITLE
Edit Product Details i18n Translation

### ISSUE THREAD

**Issue by grichardomi** [solidusio/solidus#2475]
Edit Product Details Taxons and Option Types are not translating.

Is this the expected behavior?

Any possible cause or solution?

**Comment by grichardomi** [comment]
Admin - Edit Product Details,  option types and taxons not translating might be a JS issue

I will accept cost proposal from anyone who can help fix this problem. Please respond to: cedarcity21@gmail.com

**Comment by jacobherrington** [comment]
Hey @grichardomi are you still dealing with this issue? Have you tried any solutions out?

**Comment by grichardomi** [comment]
Had a JS consultant  helped with this issue.
