### ISSUE TITLE
Non Eligible Order Adjustments Showing in Admin Order Cart Page

### ISSUE THREAD

**Issue by skukx** [solidusio/solidus#2484]
### Steps to reproduce
 - Go To Admin
 - Create a promotion with name `50% Off` and exactly mimics the below settings
<img width="1225" alt="screen shot 2018-01-03 at 1 28 02 pm" src="https://user-images.githubusercontent.com/1091314/34540596-03ecd3e6-f08a-11e7-9c0c-c184c7e2df7d.png">

- Go to Orders
- Create a new Order
- Add an item that the promotion won't apply to

### Expected behavior
Under Order Adjustments, The `50% Off` promotion should not appear since it isn't eligible for the order.

### Actual behavior
The `50% Off` promotion appears under Order Adjustments even though eligible is false.
<img width="739" alt="screen shot 2018-01-03 at 1 33 16 pm" src="https://user-images.githubusercontent.com/1091314/34540800-bd493abe-f08a-11e7-83c0-2462187c73e1.png">

### System configuration
Solidus 2.3

**Comment by jacobherrington** [comment]
I am able to replicate this issue. 
Not sure why it happens. Looking into it now.

**Comment by skukx** [comment]
@jacobherrington I looked into it a while ago. I believe it is an easy fix, just a scoping issue
