### ISSUE TITLE
Slack: this email address isn't currently associated with that workspace. 

### ISSUE THREAD

**Issue by denegny** [solidusio/solidus#2485]
try to join in your slack-workspace ((

>  Hi there,

> You requested a magic link for logging in to solidusio.slack.com. Unfortunately, this email address isn't currently associated with that workspace.
> 
> We also searched for Slack workspaces you've already joined or are allowed to join, using [my-email]. It looks like you have several!

**Comment by jhawthorn** [comment]
You'll need to [sign up](http://slack.solidus.io/) first. Unfortunately slack isn't particularly well suited for open source projects, so this is needed.
