### ISSUE TITLE
With oj gem - ActionView::Template::Error Infinity not allowed in JSON

### ISSUE THREAD

**Issue by hhff** [solidusio/solidus#2486]
### Steps to reproduce

Load an order from the Solidus Checkouts API with a Line Item Variant with `track_inventory: false`, using the following responder:

`respond_with(@order, default_template: 'spree/api/orders/show', status: 200)`

### Actual behavior

The API will throw: `ActionView::Template::Error Infinity not allowed in JSON.`

Source of the issue:
https://github.com/solidusio/solidus/blob/96b30d6f4e644383cfa13fb2dd208bcd3589cb81/api/app/views/spree/api/variants/_small.json.jbuilder#L8

As it corresponds to:
https://github.com/solidusio/solidus/blob/fb70a41064aa34d9e350e096998ce638fd83bec7/core/app/models/spree/stock/quantifier.rb#L26

### Expected behavior

I would expect that in the case `track_inventory` is false, the `_small.json.jbuilder` template would not include the `total_on_hand` attribute.

### System configuration
**Solidus Version**: 2.4.2

**Comment by jhawthorn** [comment]
I wasn't able to reproduce this, maybe I missed something.

I added a spec to the orders_controller (which renders the same partials and is easier to test), and it rendered without error.

https://github.com/jhawthorn/solidus/commit/5ae69a79cb4b4bad4756f9a6e0a06914d74eb99f

**Comment by hhff** [comment]
Hmm - will take a closer look a bit later, but perhaps it's because we're
using OJ

gem 'oj', '~> 3.3.5'

**Comment by jhawthorn** [comment]
Yep! oj seems to be the culprit

**Comment by SebAshton** [comment]
Anyone else stumbling into this error, the solution is to set the following in an initializer:

```
# https://github.com/ohler55/oj/blob/master/pages/Options.md#nan-symbol
# Fixes issue with Infinity in JSON

require 'oj'

Oj.default_options = {
  mode: :compat,
  nan: :huge
}
```
