### ISSUE TITLE
Flaky backend spec in new_order_spec.rb

### ISSUE THREAD

**Issue by jordan-brough** [solidusio/solidus#250]
I got this failure:

```
  1) New Order start by customer address completes order fine
     Failure/Error: expect(page).to have_css('.stock-item')
       expected to find css ".stock-item" but there were no matches
     # ./spec/features/admin/orders/new_order_spec.rb:141:in `block (3 levels) in <top (required)>'
```

in this CircleCI run:
https://circleci.com/gh/solidusio/solidus/433
for this pull request:
https://github.com/solidusio/solidus/pull/248
The same spec passed when I re-triggered the specs with an empty commit:
https://circleci.com/gh/solidusio/solidus/436

**Comment by BenMorganIO** [comment]
This could be from JS. Maybe `sleep 0.5` might solve it....

**Comment by braidn** [comment]
We could also wrap this expect in a `page.document.synchronize` block which seems like the new wait_until and the better sleep in capybara2. 

What's the best way to get this into the code base to pull against #248 ? Just pull branch off from master, implement the above and create a PR?

[syncronize docs][1]

[1]: http://www.rubydoc.info/github/jnicklas/capybara/Capybara/Node/Base:synchronize

**Comment by jhawthorn** [comment]
> We could also wrap this expect in a page.document.synchronize block which seems like the new wait_until and the better sleep in capybara2.

`expect(page).to have_css(...)` actually already does this internally.

I haven't been able to reproduce this failure after many, many runs with the same seed. I've added #295 which should help diagnosing future failures, but if this doesn't pop up again I will have to close it.

**Comment by braidn** [comment]
:+1:

**Comment by cbrunsdon** [comment]
@jhawthorn are we good to kill this now?

**Comment by jhawthorn** [comment]
I haven't seen this recently, not much I can do unless it's repeatable. Closing for now
