### ISSUE TITLE
'Available to users'/'Available to admins' tags on payment methods don't seem to restrict payment methods a user can use - just what is displayed

### ISSUE THREAD

**Issue by ollieh-m** [solidusio/solidus#2503]
### Steps to reproduce
As an admin, create a payment method (e.g a new Spree::PaymentMethod::Check payment method) and make it unavailable to users by unchecking the 'available to users' box. Not the ID of the new payment method in your database. As a user, go to checkout an order and at the payment step manually change the value of the payment method checkbox (using dev tools) to the ID of the new payment method.

### Expected behavior
The payment should not be processed, because the payment method is not available to users. This could, for example, be a payment method only intended to be available to users with an admin role - one that doesn't actually involve transferring money. I may be missing something, but this seems like a potential security issue.

### Actual behavior
The order is placed successfully. 

### System configuration
**Solidus Version**: 2.3.0

**Extensions in use**: solidus_auth_devise

**Comment by jhawthorn** [comment]
It is! We had a security release last month to address this (Solidus 2.3.1).

Please see https://groups.google.com/forum/#!topic/solidus-security/oU2K7WJ5H5E

For future security issues (or if you discover a flaw in this patch) please contact us privately :speak_no_evil:. Thank you
