### ISSUE TITLE
Country States Not Populating - Sandbox

### ISSUE THREAD

**Issue by grichardomi** [solidusio/solidus#2519]
### Steps to reproduce
New sandbox installation

### Expected behavior
States to change based on "Country" selection

### Actual behavior
States are not changing for selected countries

### System configuration
**Solidus Version**: Latest

**Extensions in use**:
None

**Comment by kennyadsl** [comment]
Do you mean in frontend checkout, address step?

**Comment by grichardomi** [comment]
Alberto,

Thanks for responding. I did not check the front-end. It is the back-end,
that I'm most concerned about.

Guy



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jhawthorn** [comment]
I can't reproduce this, it is working here. Can you provide more details?

![](http://i.hawth.ca/s/pD7HepUB.png)

**Comment by grichardomi** [comment]
Thanks John for the feedback.

Admin -> user -> address was not working in my solidus app. So I cloned and
ran sandbox version over two weeks ago. States are not working for me.

There could something abnormal, not necessarily the sandbox but in my
server environment. I'm using ubuntu instance. Is this possible?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jacobherrington** [comment]
I believe I have reproduced what @grichardomi is describing.

![screenshot from 2018-04-13 22-35-23](https://user-images.githubusercontent.com/11466782/38763900-01728b4e-3f6b-11e8-8322-4251f6eae801.png)

I am on Fedora 26 and followed the readme to build a sandbox application with Solidus. The screenshot was taken at `http://localhost:3000/admin/users/1/addresses`.

@jhawthorn I am new to Solidus, but happy to try and figure this one out.

**Comment by jacobherrington** [comment]
I am able to consistently reproduce this issue. I will be working on this for the moment.

**Comment by kennyadsl** [comment]
Thanks for your contribution!
