### ISSUE TITLE
Payment action icons cut off when table has long data

### ISSUE THREAD

**Issue by danmitchell-** [solidusio/solidus#2535]
### Steps to reproduce
`1280x800` screen resolution or small. Any long data in the table, see screenshot. You can see the delete action is hidden on the second payment -
![screen shot 2018-01-26 at 17 12 16](https://user-images.githubusercontent.com/3071606/35451850-81e4fb86-02bc-11e8-8d12-0ea8f6ee9fec.png)

### Expected behavior
Data in the table should wrap and not force out the width

### Actual behavior
The right hand side of the table is hidden behind the aside element `#sidebar`

### System configuration
**Solidus Version**:
Master
**Extensions in use**:
None

**Comment by DanielAmah** [comment]
I will love to fix this bug if no one is working on it. Thanks

**Comment by kennyadsl** [comment]
@DanielAmah please do it!

**Comment by jtapia** [comment]
hey guys, this is my proposal to fix that https://github.com/solidusio/solidus/pull/2589

**Comment by jhawthorn** [comment]
Should be fixed by #2589 :tada:
