### ISSUE TITLE
Can't upgrade higher than 2.2.1

### ISSUE THREAD

**Issue by codias** [solidusio/solidus#2541]
Hi, everyone @solidus
I have upgraded my rails from 4.2.8 to rails 5.1 every seem to be working fine with the new upgrade but solidus won't upgrade to any version high than 2.2.1. I have deleting all version off solidus i had but when i bundle the app permits only 2.2.1 and if I explicitly set 2.4.2 in the Gemfile i get these errors: 
Bundler could not find compatible versions for gem "solidus_core":
  In snapshot (Gemfile.lock):
    solidus_core (= 2.2.2)

  In Gemfile:
    solidus (= 2.4.2) was resolved to 2.4.2, which depends on
      solidus_core (= 2.4.2)

    solidus_auth_devise was resolved to 2.1.0, which depends on
      solidus_core (< 3, >= 1.2.0)

    solidus_gateway was resolved to 1.2.0, which depends on
      solidus_core (< 3, >= 1.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

After doing bundle update i get more errors:
Bundler could not find compatible versions for gem "actionview":
  In Gemfile:
    rails (< 5.1, >= 5.0.0.rc2) was resolved to 5.1.0.rc2, which depends on
      actionview (= 5.1.0.rc2)

    web-console (>= 3.5.1, ~> 3.5) was resolved to 3.5.1, which depends on
      actionview (>= 5.0)

Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    rails (< 5.1, >= 5.0.0.rc2) was resolved to 5.1.0.rc2, which depends on
      activemodel (= 5.1.0.rc2)

    web-console (>= 3.5.1, ~> 3.5) was resolved to 3.5.1, which depends on
      activemodel (>= 5.0)

Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    solidus_gateway was resolved to 1.2.0, which depends on
activemerchant (!= 1.58.0, != 1.59.0, ~> 1.48) was resolved to 1.76.0,
which depends on
        activesupport (< 6.x, >= 3.2.14)

    jbuilder (~> 2.5) was resolved to 2.7.0, which depends on
      activesupport (>= 4.2.0)

    rails (< 5.1, >= 5.0.0.rc2) was resolved to 5.1.0.rc2, which depends on
      activesupport (= 5.1.0.rc2)

    rails_best_practices was resolved to 1.19.0, which depends on
      activesupport

Bundler could not find compatible versions for gem "json":
  In Gemfile:
    rails_best_practices was resolved to 1.19.0, which depends on
      json

    scrivito (~> 1.7) was resolved to 1.12.0, which depends on
      scrivito_sdk (= 1.12.0) was resolved to 1.12.0, which depends on
        json (>= 1.8.3)

    sdoc (~> 0.4.0) was resolved to 0.4.2, which depends on
      json (>= 1.7.7, ~> 1.7)

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (< 5.1, >= 5.0.0.rc2)

    deface was resolved to 1.3.0, which depends on
      rails (>= 4.1)

    scrivito_advanced_editors was resolved to 1.4.1, which depends on
      rails

    scrivito (~> 1.7) was resolved to 1.12.0, which depends on
      scrivito_sdk (= 1.12.0) was resolved to 1.12.0, which depends on
        rails (< 5.2, >= 4.2)

    solidus (= 2.4.2) was resolved to 2.4.2, which depends on
      solidus_core (= 2.4.2) was resolved to 2.4.2, which depends on
        rails (~> 5.1.0)

Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    solidus_auth_devise was resolved to 2.1.0, which depends on
      devise (~> 4.1) was resolved to 4.4.1, which depends on
        railties (< 5.2, >= 4.1.0)

    jquery-rails was resolved to 4.3.1, which depends on
      railties (>= 4.2.0)

    rails (< 5.1, >= 5.0.0.rc2) was resolved to 5.1.0.rc2, which depends on
      railties (= 5.1.0.rc2)

    sass-rails (~> 5.0) was resolved to 5.0.7, which depends on
      railties (< 6, >= 4.0.0)

    scrivito (~> 1.7) was resolved to 1.12.0, which depends on
      scrivito_editors (= 1.12.0) was resolved to 1.12.0, which depends on
        railties

    web-console (>= 3.5.1, ~> 3.5) was resolved to 3.5.1, which depends on
      railties (>= 5.0

I installed(or upgraded) all the mentioned gems but to no avail. 
A snapshot of the Gemfile:

> source 'https://rubygems.org'
> 
> ruby '2.3.1'
> ##
> ## Basic
> ##
> gem 'rails', '>= 5.0.0.rc2','< 5.1'
> gem 'sass-rails', '~> 5.0'
> #gem 'uglifier', '>= 1.3.0'
> #gem 'coffee-rails', '~> 4.2'
> gem 'pg', '~> 0.20.0'
> gem 'puma', '~>3.7'
> gem 'rails_12factor'
> gem 'scrivito', '~> 1.7'
> # gem 'devise'
> # gem 'carrierwave'
> # gem 'mini_magick'
> # gem 'attribute_normalizer'
> gem 'bootstrap-sass', '~> 3.3.7'
> gem 'autoprefixer-rails'
> gem 'figaro'
> gem 'deface'
> gem 'jquery-rails'
> # gem 'turbolinks','~> 5'
> gem 'jbuilder', '~> 2.5'
> gem 'sdoc', '~> 0.4.0', group: :doc
> # gem 'therubyracer', platforms: :ruby
> # gem 'paper_trail'
> # gem 'jquery-turbolinks'
> # gem 'workbook'
> # gem 'delayed_job_mongoid' #(or when lazy: delayed_job_active_record'
> #gem 'dotenv-rails', '~> 2.0'
> #gem 'activerecord-colored_log_subscriber'
> ##
> ## SEARCH
> ##
> 
> # gem 'elasticsearch-model'
> # gem 'elasticsearch-rails'
> 
> ##
> ## DEVELOPMENT
> ##
> 
> group :development do
> 	gem 'web-console', '~> 3.5', '>= 3.5.1'
> 	# gem 'spring'
>   gem 'guard'
>   gem 'guard-rails', require: false
> 	# gem 'rspec-rails
> 	# gem 'capistrano-rbenv'
> 	# gem 'capistrano-bundler'
> 	# gem 'capistrano-rails'
> 	# gem 'capistrano-passenger'
> 	gem 'rails_best_practices'
> 	gem 'pry-rails'
> end
> 
> group :development, :test do
> 	gem 'byebug'
> 	gem 'thin'
> end
> 
> gem 'scrivito_section_widgets'
> gem 'scrivito_elastic_slider_widget'
> gem 'scrivito_table_widget'
> gem 'scrivito_advanced_editors'
> gem 'scrivito_tabbed_content_widget'
> gem 'scrivito_space_widget'
> gem 'scrivito_column_widget'
> gem 'scrivito_two_column_widget'
> gem 'scrivito_three_column_widget'
> gem 'scrivito_text_image_widget'
> gem 'scrivito_picture_widget'
> 
> # gem 'foundation-rails' # Post-install run: rails g foundation:install
> # gem "compass-rails"
> ##
> ## OTHER FREQUENTLY USED
> ##
> # gem 'bcrypt', '~> 3.1.7'
> # gem 'unicorn'
> 
> ## SHOP
> 
> 
> gem 'solidus','2.4.2'
> gem 'solidus_auth_devise'
> gem 'solidus_gateway'
> 

I don't really know what i'm missing out. 
Need help!!
Thx

**Comment by jhawthorn** [comment]
It looks like you are specifying `rails` `< 5.1`. Solidus 2.3.0 and later use Rails 5.1

**Comment by codias** [comment]
Thank you very much for the quick response and you were right.
Changed it to rails '>= 5.1' now all is working fine.
thx
