### ISSUE TITLE
Order not recalculating

### ISSUE THREAD

**Issue by skukx** [solidusio/solidus#2606]
### Steps to reproduce
In Solidus Admin:
 - Create New Order
 - Add Items to cart
 - Complete Order
 - Mark order as shipped
 - Create RMA
 - Create Return
 - Create Reimbursement but don't complete the reimbursement

### Expected behavior
The order now has a balance due and the order payment state should be `credit_owed`

### Actual behavior
The order now has a balance due and the order payment state is `paid`. The payment state doesn't get updated until `order.recalculate` is called.

The fix is to call `order.recalculate` when the reimbursement has been created

### System configuration
**Solidus Version**: v2.4

**Comment by aitbw** [comment]
Closing via #2711
