### ISSUE TITLE
Wrongly determining ready state for shipment with partial cartons

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#2622]
This issue comes from #2621

There's an issue determining the state (in particular `ready`) of shipments when a partial Carton is made on it. 

This is happening because we check that all shipment inventory units are `on_hand` or `canceled` (?) but some of them could be `shipped`.

### Details

Right now shipment is considered `ready` if:

- order can be shipped: `complete? || resumed? || awaiting_return? || returned?`
- order is paid
- **all** inventory units are `on_hand` or `canceled`(still not sure why canceled made items shippable)

We have `Carton`s which represents the shipped part of a shipment, so it's legit to expect that you can ship the same shipment in 2 or more parts. So maybe not **all** inventory units need to be `on_hand` and we could also have some of them already `shipped`?

In fact, *even if not supported by our admin UI* you can programmatically do:

```ruby
Spree::OrderShipping.new(order).ship(
  inventory_units: inventory_units,
  stock_location: stocklocation,
  address: order.shipping_address,
  shipping_method: order.shipments.first.shipping_method,
  shipped_at: Time.now,
  external_number: "test_number",
  tracking_number: "12345",
  suppress_mailer: true
)
```

passing only a subset of inventory units you want to ship. Right now this moves the shipment state to `pending`, which seems to be wrong.

At this point if you want to complete the shipment via admin UI, you can't since the button is hidden (shown only for `ready` shipments) even if pressing it, it would correctly do the job. 

**Note**: Pior to #1004 shipment state would have been determined as "ready". I think that we should keep this change since it allows to overwrite logic that determines when IU is shippable but we should handle the check in a different way.

### A possibile solution

Change what ready shipment means: from "all should be shippable" to "at least one should be shippable".

This means that shipments having:

  - 1 already shipped item (via a partial Carton creation, see code above)
  - 2 items to be shipped, on_hand

will be considered ready to be shipped.

Pressing "Ship" at this point will create a new `Carton` with [only shipplable IUs](https://github.com/solidusio/solidus/blob/daea52ff1ce4f860bd061b81f62804df2c229234/core/app/models/spree/order_shipping.rb#L20).

The only issue I see with this approach is that user do not expect the ship button to ship the order partially and what's happening could not be clear.

Users that do not programmatically create Cartons will not see any change, while user that do that will be able to see shipment in the right state.

**Comment by isindexer** [comment]
Thanks kennyadsl. 
The synthesis you wrote here is perfect 👌

**Comment by sebfie** [comment]
Thx for this analysis :)

**Comment by jhawthorn** [comment]
I think the definition of a "ready" shipment should be: "we are able to ship the _remaining_ inventory units"

This would require changing [this line in Shipment#can_transition_from_pending_to_ready?](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/shipment.rb#L85)

From

``` ruby
inventory_units.all? { |iu| iu.allow_ship? || iu.canceled? } 
```
to
``` ruby
inventory_units.all? { |iu| iu.shipped? || iu.allow_ship? || iu.canceled? } 
```

Would this solve the issue?

**Comment by loicginoux** [comment]
@sebfie is not here this week but I think this change would fix the issue we are having with partial shipped shipments.

**Comment by kennyadsl** [comment]
John already did that in #2634, we can close the first PR!

**Comment by sebfie** [comment]
Ok thx
