### ISSUE TITLE
When a reimbursement is created, a store credit is not created only a store reimbursement credit.

### ISSUE THREAD

**Issue by prwhitehead** [solidusio/solidus#2645]
### Steps to reproduce
Ship order 
Create returns authorisation
Create customer return with reimbursement type of `Spree::StoreCredit`
Create reimbursement

### Expected behavior
Spree::StoreCredit created

### Actual behavior
Reimbursement credit is created with a `creditable_type` of `Spree::StoreCredit` but a `creditable_id` of `nil`. 

### System configuration
**Solidus Version**: 2.4.2

After falling down the rabbit hole debugging this I think I have worked out what is going on. 

    module Spree::ReimbursementType::ReimbursementHelpers
      #...
      def create_creditable(reimbursement, unpaid_amount)
        Spree::Reimbursement::Credit.default_creditable_class.new(
          user: reimbursement.order.user,
          amount: unpaid_amount,
          category: Spree::StoreCreditCategory.reimbursement_category(reimbursement),
          created_by: Spree::StoreCredit.default_created_by,
          memo: "Refund for uncreditable payments on order #{reimbursement.order.number}",
          currency: reimbursement.order.currency
        )
      end
    end

The first issue is that the `create_creditable` method requires a `created_by` attribute to be set, and `Spree::StoreCredit.default_created_by`, which turns out to be... 

    class Spree::StoreCredit < Spree::PaymentSource
      #...
      DEFAULT_CREATED_BY_EMAIL = "spree@example.com"
      #....
      class << self
        def default_created_by
          Spree.user_class.find_by(email: DEFAULT_CREATED_BY_EMAIL)
        end
      end
    end

So unless you still have a user with `spree@example.com` as an email address in your database the store credits will never save.

**Comment by kennyadsl** [comment]
I confirm the bug on master sandbox. I'm trying to create a spec to reproduce the issue but still can't do that, it seems like our specs on that are correctly creating the creditable object.

**Comment by prwhitehead** [comment]
Its very likely that the specs pass because they use the default user email address.

**Comment by kennyadsl** [comment]
This can be closed with #2802
