### ISSUE TITLE
Provide a way to add before-process-payments validations

### ISSUE THREAD

**Issue by jordan-brough** [solidusio/solidus#266]
There is no a reasonable way that I can see to add a `before_transition to: :complete` validation for Orders within your app or within an extension.

For example if you want to add something of your own along the lines of [these validations](https://github.com/solidusio/solidus/blob/ae7f9d4b1fa0930c17487251a1a073f10f40c5db/core/app/models/spree/order/checkout.rb#L113-L117 that are in Solidus):

``` ruby
before_transition to: :complete, do: :validate_line_item_availability, unless: :unreturned_exchange?
before_transition to: :complete, do: :ensure_available_shipping_rates
before_transition to: :complete, do: :ensure_promotions_eligible
before_transition to: :complete, do: :ensure_line_item_variants_are_not_deleted
before_transition to: :complete, do: :ensure_inventory_units, unless: :unreturned_exchange?
```

there is no good way to do that.  You can't call `Spree::Order.before_transition` from StateMachine directly because you will want it to fire before [this existing `before_transition`](https://github.com/solidusio/solidus/blob/ae7f9d4b1fa0930c17487251a1a073f10f40c5db/core/app/models/spree/order/checkout.rb#L119):

``` ruby
before_transition to: :complete, do: :process_payments_before_complete
```

but you won't be able to insert your own `before_transition` before that one.

A couple solutions I can think of:
## 1) Move payment processing outside of state machine

And call it explicitly instead.  e.g. to complete an order and process payments you'd call:

``` ruby
order.complete!
order.process_payments!
```

instead of just `order.complete!`.
I like how this is more explicit and is probably more adaptable to different ways that various stores handle payments, but I don't know how pragmatic it would be.
## 2) Provide a way to add validations

E.g.:

``` ruby
before_transition to: :complete, do: :run_before_complete_validations
before_transition to: :complete, do: :process_payments_before_complete

def self.add_before_complete_validation(proc)
  @@before_complete_validations << proc
end

def run_before_complete_validations
  @@before_complete_validations.each { ... }
end
```

Thoughts? Other ideas?

**Comment by cbrunsdon** [comment]
These actions could now technically be handled in PaymentCreate, or another way, but closing this due to staleness as I don't think its a priority for anyone anymore.
