### ISSUE TITLE
Absent Spree::OrderStockLocation class/file in v2.5.0

### ISSUE THREAD

**Issue by jcsanti** [solidusio/solidus#2661]
Hi,

We are using Solidus in production in the company I work at (epicery.com).

Following the release of `v2.5.0` we created a branch to run our tests and see how things go. The removal — whether intentional or not — of `order_stock_location.rb` broke a lot of them.

### Steps to reproduce
In our code base, simply doing this in a `rails console`:
```ruby
Spree::Order.includes(:order_stock_location)
```

### Expected behavior
This should not trigger any issue.

### Actual behavior
```ruby
NameError:
    uninitialized constant Spree::Order::Spree::OrderStockLocation
```

### System configuration
**Solidus Version**: `v2.5.0`

**Extensions in use**:
`solidus_core`
`solidus_backend`
`solidus_frontend`
`solidus_auth_devise`
`solidus_comments`
`solidus_product_assembly`

### Solidus diff
```
# git diff v2.4.2 v2.5.0 -- core/app/models/spree/order_stock_location.rb

diff --git a/core/app/models/spree/order_stock_location.rb b/core/app/models/spree/order_stock_location.rb
deleted file mode 100644
index ff734a50b..000000000
--- a/core/app/models/spree/order_stock_location.rb
+++ /dev/null
@@ -1,15 +0,0 @@
-module Spree
-  class OrderStockLocation < Spree::Base
-    belongs_to :variant, class_name: "Spree::Variant"
-    belongs_to :stock_location, class_name: "Spree::StockLocation"
-    belongs_to :order, class_name: "Spree::Order"
-
-    def self.fulfill_for_order_with_stock_location(order, stock_location)
-      where(order_id: order.id, stock_location_id: stock_location.id).each(&:fulfill_shipment!)
-    end
-
-    def fulfill_shipment!
-      update_attributes!(shipment_fulfilled: true)
-    end
-  end
-end
```
```
# git show v2.5.0:core/app/models/spree/order.rb
# ...

has_many :order_stock_locations, class_name: "Spree::OrderStockLocation"
has_many :stock_locations, through: :order_stock_locations
```

**Comment by stem** [comment]
Hi,

In order to not loose what Kevin said on slack a few days ago, I paste it here : 
 - this was probably intentionally remove here [96a553d](https://github.com/solidusio/solidus/commit/96a553dd63c2a9d32fa2e805094e9730b6ffe727#diff-64491147e2e92477c6f48b524aac7e20)
 - and extracted to [solidusio-contrib/solidus_stock_transfers](https://github.com/solidusio-contrib/solidus_stock_transfers)
 - but the associations snuck back in here [747293a](https://github.com/solidusio/solidus/commit/747293a570abfdf8fbd8798353aa2a670b170248#diff-434de9976fbb9c7d9358f1cb3d401019)

**Comment by jhawthorn** [comment]
This was actually extracted to https://github.com/solidusio-contrib/solidus_legacy_stock_system (solidus_stock_transfers was a separate effort)

The `OrderStockLocation` model became non-functional in Solidus 2.4 when the old `Stock::Coordinator` was extracted to solidus_legacy_stock_system. It would have been nice to have removed `OrderStockLocation` at that time, but I didn't get around to it until #2270

Including the solidus_legacy_stock_system should fix any issues. Though if you don't need location configured packages it is probably better to just remove references to them
