### ISSUE TITLE
Error on initializer a new promotion rule

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#2667]
I am trying to create a new promotion rule, following the steps in solidus:
# app/models/spree/promotion/rules/my_promotion_rule.rb
module Spree
  class Promotion
    module Rules
      class MyPromotionRule < Spree::PromotionRule
        def applicable?(promotable)
          promotable.is_a?(Spree::Order)
        end

        def eligible?(order, options = {})
        
        end

        def actionable?(line_item)
        
        end
end
end
end
end

but give me error in the initializer,
/Users/sechix/pislow-production/config/initializers/spree.rb:99:in `<top (required)>': uninitialized constant MyPromotionRule (NameError)

Rails.application.config.spree.promotions.rules << MyPromotionRule

**Comment by loicginoux** [comment]
That's not related to Solidus, that's a ruby issue in your code
```Rails.application.config.spree.promotions.rules << Spree::Promotion::Rules::MyPromotionRule```

**Comment by sechix** [comment]
ok, thanks!!!
