### ISSUE TITLE
duplicated payments with solidus_gateway gem and Stripe

### ISSUE THREAD

**Issue by spaghetticode** [solidusio/solidus#2680]
### Issue

I'm using the gem __solidus_gateway__ to integrate Stripe payments, I noticed that, when paying with an existing credit card (a card previously used and already stored in the DB) then **two payments are created**. The last one seems the right one, while the first has amount 0.0 and is marked as invalid. 

I am on Solidus 2.5.0.rc1, I understand the integration with external gems is generally off topics here, especially when such gems use has been explicitly deprecated in the readme, but still I'd like to properly understand what should be the correct payment flow within Solidus in order to fix my issue and hopefully submit a PR on the right codebase. 

### Debugging

During debugging I found out that the Order::Checkout state machine transition
`before_transition to: :payment, do: :add_default_payment_from_wallet` creates the zero amount payment by calling `add_default_payment_from_wallet`, which eventually initializes a new instance of `Spree::Wallet::DefaultPaymentBuilder` that persists the blank payment on the DB. 

After that, while advancing the checkout process OrdersController#update_order instantiates a `OrderUpdateAttributes` object which instantiates a `PaymentCreate` object. At this moment the second payment with correct amount data is created, and this payment is later used for Stripe payment integration. 

The two payments have a few similarities, for example these attributes `"source_type" => "Spree::CreditCard", "source_id" => 2, "payment_method_id" => 1`
where the payment_method is the `#<Spree::Gateway::StripeGateway id: 1` object.

### Questions

Is there any rationale behind having 2 different payments? Can the first dummy payment be eliminated from the checkout flow or should the `PaymentCreate` class update it with new data instead of creating a new one? 

Thanks for your attention,

Andrea

**Comment by kennyadsl** [comment]
Hello @spaghetticode, if I recall correctly the reason behind this implementation is related with how the checkout works:

- on the payment step it makes an authorization payment without capturing any amount, this create the fake payment and store all the information about the payment source (which will allow user to capture the payment later without readding the credit card information)
- on the confirm step it actually makes the payment using the source from the payment previously authorized, this is why that payment is needed.

Despite the process in not intuitive and it can probably be improved, storing the first null payment in terms of logging could also be useful to understand where payment issues are.

Let us know if this makes sense!

**Comment by spaghetticode** [comment]
@kennyadsl thank you for the answer. 

So, you're basically saying that the procedure is right when it creates 2 payments, the first with zero amount that is invalidated when the second, the real one is created. 

I can understand debugging may benefit from this process, and for sure Solidus devs are more knowledgeable than me on managing ecommerce checkouts, so I trust your opinion on this matter. 

Again thank you for sharing the information.
