### ISSUE TITLE
Pending package from 'default'

### ISSUE THREAD

**Issue by davideghz** [solidusio/solidus#2699]
### Steps to reproduce
- Push a fresh solidus app to Heroku
- Run the installer

### Actual behavior
In orders tab, I see H25053077262 - Pending package from 'default'

### System configuration
**Solidus Version**: ~> 2.5

![image](https://user-images.githubusercontent.com/6973157/38817762-5783399a-4199-11e8-9631-62290d4942c7.png)

What does it mean? In my local environment, I do not see that message
Thx

**Comment by loicginoux** [comment]
"Default" is the name of the default stock location.

**Comment by kennyadsl** [comment]
`Pending` means that the shipment can't be shipped since the payment has not been captured yet. When you'll capture the payment the shipment will move in `ready` state and you'll see a `Ship` button on it.

**Comment by davideghz** [comment]
ok, I completely misunderstood the meaning of 'package' here :) thx
I think this "issue" can be safely closed
