### ISSUE TITLE
Cleaning up the admin views/javascript/css/etc

### ISSUE THREAD

**Issue by athal7** [solidusio/solidus#270]
Originally written by @cbrunsdon on https://github.com/solidusio/solidus/issues/171

**Comment by radar** [comment]
![133235985845](https://cloud.githubusercontent.com/assets/2687/9211467/ceb3fa0e-40c5-11e5-9730-949d77c8213e.jpg)

**Comment by mamhoff** [comment]
This issue is not actionable, closing.
