### ISSUE TITLE
Add a controller for the static pages.

### ISSUE THREAD

**Issue by webmaster219** [solidusio/solidus#2701]
Hi @gmacdougall , @jhawthorn , how can I add static pages on my app using solidus.
Just added static_pages controller and created routes, but in the static pages can't use spree helpers and routes.
So I need your help.

**Comment by braidn** [comment]
@webmaster219 what if your statics controller were to inherit from the `store_controller`?

https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/store_controller.rb

Would you have access to the routes/helpers?

**Comment by memotoro** [comment]
@webmaster219 I'm not sure if this gem is going to help you, but I use it to add static pages in stores for T&Cs, help, etc. I actually forked the project and did some bespoke changes for my stores. It works fine. Have a look. https://github.com/solidusio-contrib/solidus_static_content

**Comment by kennyadsl** [comment]
Closing since this is no more active and some solution has been proposed.
