### ISSUE TITLE
Professional Copywriter Willing To Contribute... 

### ISSUE THREAD

**Issue by order4adwriter** [solidusio/solidus#2702]
Hello @gmacdougall and the rest of the guys out there,

I am a professional copywriter and I 'd like to contribute to the Solidus repository by writing compelling and informative content /webpage copy, especially for the [Solidus website's](https://solidus.io/) About Us page, Privacy Policy, Help/FAQ, Terms Of Use, Case Studies, Blog posts ... and other necessary marketing content needed on the  website.

My question is .... would you merge them into your repository when it's all done?

Please let me know so I can get started as soon as possible.

Thanks.

**Comment by order4adwriter** [comment]
Still haven't gotten any response from you.

I assure you that my intentions are sincere and I will provide quality content for your open source project repo....
Besides, you'll definitely have the final say anyway..whether to accept my contribution or not...

Looking forward to your positive reply.

**Comment by jacobherrington** [comment]
@order4adwriter if you see an area to improve -- please submit a PR. Thanks for getting involved!
