### ISSUE TITLE
i18n gem seems not working on devise controller

### ISSUE THREAD

**Issue by liwuqi95** [solidusio/solidus#2712]
### Steps to reproduce
How can we make this happen
install solidus_auth (devise)
install i18n
set language to be not en (e.g zh-CN)

### Expected behavior
Tell us what should happen
at session/new page, should return "zh-CN"
### Actual behavior
Tell us what happens instead
at session/new page, I18n.locale returns "en"
### System configuration
**Solidus Version**:
2.5.0
**Extensions in use**:

**Comment by jacobherrington** [comment]
Hey @liwuqi95 are you using https://github.com/solidusio/solidus_i18n?

**Comment by aitbw** [comment]
I think this is the same as #2856 and it was fixed via #3044
