### ISSUE TITLE
Error due to spree/api/payments/source_views

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#2722]
### Steps to reproduce
Iam getting error in orders that not load shipment and line items, I realized debugging that gets error because doesn't exist _stripe.json.jbuilder in spree/api/payments/source_views

![image](https://user-images.githubusercontent.com/24247266/39488904-1365164c-4d84-11e8-84db-eb353335f22f.png)

This file 'sources_views' has been created 1 month ago.

### System configuration
**Solidus master last version**:

**Comment by sechix** [comment]
I solved creating this file, I am using solidus_stripe extension, but I guess that happen with each of payments gateway

**Comment by kennyadsl** [comment]
I think it's solidus_stripe responsibility to create this file. Can you open this same issue there as well please?

**Comment by sechix** [comment]
Ok, thanks!!!!
