### ISSUE TITLE
Solidus Default install on MySQL 

### ISSUE THREAD

**Issue by jasonfb** [solidusio/solidus#2724]
### Steps to reproduce
Solidus default installation on MySQL 5.6

### Expected behavior
```rake db:seed``` should run through cleanly

### Actual behavior
crashes with Encoding issue

### System configuration
**Solidus Version**:
tested latest

**Extensions in use**:

not applicable

this can be fixed easily in the solidus_one_for migration 

    create_table "spree_states", force: :cascade do |t|
      t.string "name"
      t.string "abbr"
...
    end

by adding ```, :options => 'ENGINE=InnoDB DEFAULT CHARSET=utf8'``` to both `name` and `abbr`

note this is easily fixed after the schema migrations themselves are created in your app, in the copied files.

**Comment by jasonfb** [comment]
TODO (Jason): provide reproduction app

**Comment by jacobherrington** [comment]
Hey @jasonfb! I'm not able to reproduce this -- are you still seeing issues using MySQL?
