### ISSUE TITLE
Error in available_locales

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#2730]
I am getting this error, from admin/settings in solidus master:
I updated solidus i18n etc but nothing....

![image](https://user-images.githubusercontent.com/24247266/39716109-b5355bb2-522f-11e8-9d3c-1189365e3d2d.png)

Any idea?

**Comment by wycleffsean** [comment]
Be sure to run migrations, you need this https://github.com/solidusio/solidus/blob/master/core/db/migrate/20180313220213_add_available_locales_to_stores.rb

**Comment by sechix** [comment]
ok, solved!!! Missing migrations
