### ISSUE TITLE
Deprecate Spree.t

### ISSUE THREAD

**Issue by BenMorganIO** [solidusio/solidus#2773]
So I'm currently working on a Solidus project and I saw that @jhawthorn has changed `Spree.t` => `t('spree.')`. I'm thinking we should deprecate `Spree.t` as I've been going into the project I've been on and changing `t('spree.')` to `Spree.t`; I'm regretting that now. I think a warning should begin to be emitted to programmers using `Spree.t` and remove it in Solidus 3 or 4.

Issue #2309

What are some thoughts on this?

**Comment by BenMorganIO** [comment]
On another note, we could use this as a chance to help migrate translations over to the Solidus namespace instead of the Spree namespace. Or rather, since many projects use `Spree.t`, we could add a `Solidus.t` and have `Spree.t` point to it. This solves a namespace problemo. Then finally in another version notify that we're deprecating `Spree.t` and Solidus.t` in preference for `t('solidus.')`.

I hope this little blurb on Solidus-ifying the project helps :)

**Comment by jacobherrington** [comment]
Not sure if swapping the namespace is on the current roadmap. Seems like it would be better to just start off with implementing a warning and go from there. $.02

**Comment by tvdeyen** [comment]
Swapping the namespace is not planned and has more disadvantages than advantages. Adding a depreciation warning to `Spree.t` would be great, though. Anybody?

**Comment by BenMorganIO** [comment]
OK, that works. If I see some more interest from Members I'll do a PR up to deprecate `Spree.t`. Get back to contributing to Solidus in a long while.

**Comment by kennyadsl** [comment]
I agree we can deprecate `Spree.t`, thanks @BenMorganIO !
