### ISSUE TITLE
Solidus 2.1 does not support Bourbon 5

### ISSUE THREAD

**Issue by antonzaytsev** [solidusio/solidus#2786]
### Steps to reproduce
Every page with loaded css from solidus fail to load
I prepare simple app with reproduced issue https://github.com/antonzaytsev/solidus21_bourbon
![action controller exception caught 2018-06-28 12-16-51](https://user-images.githubusercontent.com/409432/42014738-0ca67ea0-7ace-11e8-86ea-6e1ba1982817.png)

### Expected behavior
Page should be loaded properly.

### Actual behavior
On css compile it expect to have mixin `display`, which was removed in Bourbon 5.
https://www.bourbon.io/docs/migrating-from-v4-to-v5/

### System configuration
**Solidus Version**: 2.1

Issue already fixed in v2.1 branch https://github.com/solidusio/solidus/commit/e05d43b6ef4ad693b14ae0280ae41a2690b7e41c

Latest branch version is not tagged. Is it possible to release 2.1.2 ?
Diff between 2.1.1 and v2.1 branch https://github.com/solidusio/solidus/compare/v2.1.1...v2.1

**Comment by jacobherrington** [comment]
@tvdeyen do we plan to solve this, or should the issue be closed for EOL?

**Comment by tvdeyen** [comment]
Close. This is easy to solve by updating to Solidus 2.2
