### ISSUE TITLE
API endpoints produces InvalidAuthenticityToken with POST

### ISSUE THREAD

**Issue by dschuermann** [solidusio/solidus#2799]
### Steps to reproduce
``curl -X POST -k -H 'X-Spree-Token: 1111111111111111111111111111111' -i 'https://example.com/api/orders'``

I get ``"ActionController::InvalidAuthenticityToken in Spree::Api::OrdersController#create"
in actionpack (5.2.0) lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'``

### Expected behavior
The API endpoints should not require an authenticity_token.

In Spree, the CSRF protection is disabled for JSON/XML requests:
``protect_from_forgery unless: -> { request.format.json? || request.format.xml? }`` (https://github.com/spree/spree/blob/master/api/app/controllers/spree/api/base_controller.rb)

this is missing in https://github.com/solidusio/solidus/blob/master/api/app/controllers/spree/api/base_controller.rb

Maybe I am missing something, but I did not found a way to get the API to work correctly.

### System configuration
**Solidus Version**: 2.6.0

**Extensions in use**: none

**Comment by kennyadsl** [comment]
Thanks! I think it’s due to this Rails (5.2) commit: https://github.com/rails/rails/commit/ec4a836919c021c0a5cf9ebeebb4db5e02104a55

I’ll take a look soon!

**Comment by dschuermann** [comment]
Great, Thanks. I will try downgrading to rails 5.1 for now.

**Comment by kennyadsl** [comment]
Yes, it should work but I think that Solidus should second Rails defaults. I think it's just matter of adding that:

```
protect_from_forgery unless: -> { request.format.json? || request.format.xml? }
```

when needed (API only).

**Comment by dschuermann** [comment]
Yup, for now I don't want to fork Solidus to fix it. But, let's see which other requirements will appear :grin: 

I just started working on a project that uses Solidus as the backend and calls its API on Android.
