### ISSUE TITLE
Items on Back Order when Track Inventory is false

### ISSUE THREAD

**Issue by brettallred** [solidusio/solidus#2817]
### Steps to reproduce
* Set config.track_inventory_levels = false
* Create one or two shipment locations
* Submit and order for two products or a quantity of two for a single product
* In the order section, press the Split button
* Choose a different shipment location or even the same shipment location

### Expected behavior
* Item should be shippable

### Actual behavior
* Item says it is back ordered and you can't get out of that state

### System configuration
**Solidus Version**:
2.6.0

**Extensions in use**:
```
gem 'solidus' 
gem 'solidus_auth_devise'
gem 'deface'
gem 'solidus_wishlist', github: 'boomerdigital/solidus_wishlist', branch: 'master'
gem 'solidus_reviews', github: 'solidusio-contrib/solidus_reviews'
gem "searchkick", github: "ankane/searchkick"
gem 'solidus_cmd'
```

https://gist.github.com/brettallred/fe054c6dd4df820b0a510cbb4872f610

**Comment by jacobherrington** [comment]
This exists in Solidus 2.7.0

**Comment by aitbw** [comment]
Haven't figured this one yet but here's a spec to reproduce the bug without needing to build the sandbox; copy the following snippet between [these two lines](https://github.com/solidusio/solidus/blob/master/backend/spec/features/admin/orders/order_details_spec.rb#L196-L198), and it should fail as expected.

```ruby
context 'when inventory levels are not being tracked' do
  before do
    Spree::Config[:track_inventory_levels] = false
  end

  after do
    Spree::Config[:track_inventory_levels] = true
  end

  # Regression for https://github.com/solidusio/solidus/issues/2817
  it "should allow me to ship an order's items" do
    visit spree.edit_admin_order_path(order)

    within('tr', text: line_item.sku) { click_icon 'arrows-h' }
    complete_split_to(stock_location2)

    expect(page).to have_css('.shipment', count: 2)
    expect(order.shipments.count).to eq(2)
    expect(page).not_to have_content('Backordered')
    expect(page).to have_content('On hand', count: 2)
  end
end
```

**Comment by nspinazz89** [comment]
I'm able to reproduce this on master and am going to work on knocking this out.
