### ISSUE TITLE
solidus_backend_manifest might link wrong directory? 

### ISSUE THREAD

**Issue by christophebeling** [solidusio/solidus#2820]
Hey guys, 

i set up rails 5.2 with solidus 2.7 and ran into an error `couldn't find file 'spree/backend/all.js'`. In `solidus/backend/app/assets/javascripts/spree/backend` there is no `all.js`. 

If i change the manifest to `spree/backend.js` it's working. Did i missconfigure something in my setup or is https://github.com/solidusio/solidus/blob/master/backend/app/assets/config/solidus_backend_manifest.js not correct?

**Comment by christophebeling** [comment]
I have the same issue for the frontend btw.

**Comment by nori3tsu** [comment]
I have the same issue both v2.6.1 and v2.7.0.

**Comment by rsmithlal** [comment]
> I had the same issue both v2.6.1 and v2.7.0, but I finally have resolved.
> 
> ```
> $ rails generate spree:install
> ```
> 
> then
> 
> ```
> $ bundle exec rake assets:precompile
> ```

Thank you, running the generator helped me fix my issue!
