### ISSUE TITLE
Pull 2513 broke order api json when there is a Stripe payment

### ISSUE THREAD

**Issue by joshua-honig** [solidusio/solidus#2833]
The changes made in [Pull 2513](https://github.com/solidusio/solidus/pull/2513) ("Fix view for orders api (Fixes Issue #2512)") actual broke the `solidus_api/app/views/spree/api/orders/_big.json.jbuilder` when the source type for a payment is Stripe. 

Specifically, at line 38, the updated `_big.json.jbuilder` as distributed in `solidus_api 2.6.0` introduces the expectation that there is a jbuilder view with the same name as the `partial_name` property of the payment method:

https://github.com/solidusio/solidus/blob/853bc56249861803388eacfe2151b79ca8e125fa/api/app/views/spree/api/orders/_big.json.jbuilder#L36-L41

The same pull request included jbuilder views for `check`, `gateway`, and `storecredit`, but did not account for the fact that when using `solidus_gateway` the `partial_name` of the payment method is not `gateway` but the name of the specific gateway--`stripe` in my case. 

`solidus_gateway` includes the erb partial view `_stripe` (see https://github.com/solidusio/solidus_gateway/blob/master/lib/views/backend/spree/admin/payments/source_views/_stripe.html.erb), but no jbuilder.

As a result, calls to route `api/orders/[order_number]` fail with the error:

```
ActionView::MissingTemplate: Missing partial spree/api/payments/source_views/_stripe with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:jbuilder]}.
```

Relevant stats:
- Ruby 2.5.1
- `rails 5.1.1`
- `solidus 2.6.0`
- `solidus_gateway 1.3.0`

**Comment by joshua-honig** [comment]
For others encountering this, the immediate workaround was to add the following file to my own project:

`app/views/spree/api/payments/source_views/_stripe.json.jbuilder`:

```ruby
# frozen_string_literal: true

json.partial!('spree/api/payments/source_views/gateway', payment_source: payment_source)
```

**Comment by skukx** [comment]
@joshua-honig This is a great find. However this issue and pull request should probably be better suited for https://github.com/solidusio-contrib/solidus_stripe.  `Stripe` is not part of core and therefore the extension should be responsible for adding that view

**Comment by joshua-honig** [comment]
@skukx That makes sense. This really represents an incremental requirement for payment method plugins, to be implemented by each plugin. In our case we're actually using https://github.com/solidusio/solidus_gateway, not `solidus_stripe`, but same idea. Given the deprecation alert now in the readme for `solidus_gateway` I'll put it on my medium term list to transition to `solidus_stripe`.

That said, this change will likely break most other currently supported payment plugins, because none of them will have the newly required jbuilder corresponding to their own `partial_name`s. 

For example, the currently supported https://github.com/solidusio/solidus_paypal_braintree gem defines `partial_name` to be 'paypal_braintree':

https://github.com/solidusio/solidus_paypal_braintree/blob/da9343edf6558061535ca3b7b5afeb356225a149/app/models/solidus_paypal_braintree/gateway.rb#L41-L43

..but does **not** have a `_paypal_braintree.json.jbuilder` in [`lib/views/backend/spree/admin/payments/source_views/`](https://github.com/solidusio/solidus_paypal_braintree/tree/da9343edf6558061535ca3b7b5afeb356225a149/lib/views/backend/spree/admin/payments/source_views)

Rather than just breaking them and waiting for each of them to encounter, figure out, and fix this same issue, perhaps there could be an automatic fallback to the `gateway` jbuilder, with a corresponding warning?

**Comment by skukx** [comment]
Every payment method which inherits from `Spree::Gateway` already by default defines
```
def partial_name
  "gateway"
end
```

If a payment method defines a different partial name, it should be expected that they actually provide the correct partials.  That is just my opinion though and others may think differently.  I did notice looking through that that the `Spree::Gateway` is going to be deprecated so I'll look through and see how things will be changing in the future

**Comment by jontarg** [comment]
Just upgraded to 2.7 from 2.5 and found this same issue. We're using `solidus_gateway`.

**Comment by kennyadsl** [comment]
This is fixed in [`solidus_stripe`](https://github.com/solidusio-contrib/solidus_stripe/pull/1), which should be used instead of `solidus_gateway`.
