### ISSUE TITLE
Spree::Api::VariantsController#index returns variants duplicate for as many stock location it is available at

### ISSUE THREAD

**Issue by octave** [solidusio/solidus#2834]
### Steps to reproduce
`Spree::Api::VariantsController#index` returns variants duplicate for as many stock location it is available at. Example when creating a manual order in the backend, when using the autocomplete to select a variant, it will duplicate the variant row, with no difference at all if the variant is available at more than one stock location.

### Expected behavior
`Spree::Api::VariantsController#index` should not duplicate variant even if available at multiple stock locations.

### Actual behavior
`Spree::Api::VariantsController#index` duplicates variant when available at multiple stock locations.

### System configuration
**Solidus Version**: 2.6.0

**Extensions in use**: `solidus_paypal_braintree`, `solidus_related_products`, `solidus_taxjar`, `solidus_shipstation`, `solidus_mailchimp_sync`, `solidus_sitemap`

**Comment by octave** [comment]
Adding `distinct: true` fixes at the end of this line:

https://github.com/solidusio/solidus/blob/425240b84f670558aab61df2655be9a75e00dda0/api/app/controllers/spree/api/variants_controller.rb#L29

Like this: `.ransack(params[:q]).result(distinct: true)`

**Comment by jacobherrington** [comment]
@octave If you have a solution in mind for this, would you mind making a PR? 👍

**Comment by kennyadsl** [comment]
Closing, I'm not seeing this issue on a fresh sandbox anymore. Thanks for reporting.
