### ISSUE TITLE
How to get rails actionmailer::preview to work with spree?

### ISSUE THREAD

**Issue by mobentec** [solidusio/solidus#2839]
### Steps to reproduce
We would like to make use of rails built in email template preview feature, but we can't seem to set it up properly with our solidus/spree app.  We followed the steps mentioned within https://edgeguides.rubyonrails.org/action_mailer_basics.html

Any help would be much appreciated.

**Comment by kennyadsl** [comment]
Are you looking for previews of the solidus emails? If yes I think you can just find them into `/rails/mailers/`

**Comment by ccarruitero** [comment]
@mobentec Can you share the code you did? Otherwise it's complicated to figurate what is the problem.

Personally, for mail previews I prefer to use [letter_opener_web](https://rubygems.org/gems/letter_opener_web) that not require too much extra configuration

**Comment by kennyadsl** [comment]
I think we can close this one. Please reopen it if you have more details.

**Comment by gildardoperez** [comment]
http://localhost:3000/rails/mailers/

**Comment by coorasse** [comment]
I managed to have it working only by monkey patching:

```
# config/initializers/mail_previews.rb

module ActionMailer
  class Preview
    def self.all
      load_previews
      descendants
    end
  end
end
```

**Comment by PeteTheSadPanda** [comment]
Hey all, 

The above statement results in a warning 6.0.3.4 using Zeitwerk. In the future this warning will end up being an error, I believe this issue warrants another look as using Solidus as an engine within an existing Rails application does indeed blow away the previews in the containing Rails app. The above monkey patch against ActionMailer::Preview does indeed solve the issue, however it will soon break as soon as the constant definitions during initialization becomes an error in future versions of Rails.

**Comment by PeteTheSadPanda** [comment]
Apologies, what I wrote above is true however the monkey patch is not the culprit. Rather the way in which the Previews are being loaded in core's engine.rb is. I'll file a bug with the project in addition to leaving the following

`DEPRECATION WARNING: Initialization autoloaded the constants ...Spree::EmailNudgeMailerPreview, ..`

If you remove the following line from lib/spree/core/engine.rb:101

`      if Rails.env.development?
        initializer "spree.mailer_previews" do
          ActionMailer::Preview.all              #<--
          Dir[root.join("lib/spree/mailer_previews/**/*_preview.rb")].each do |file|
            require file
          end
        end
      end
`

Then the error goes away, though obviously a different issue appears.
