### ISSUE TITLE
Languages aren't changing in the backend

### ISSUE THREAD

**Issue by jacobherrington** [solidusio/solidus#2856]
### Steps to reproduce
Change the language from the admin

### Expected behavior
The language should change

### Actual behavior
The page refreshes and the language is still English (US)
https://www.useloom.com/share/0da9e1340f8c43ab980ae82e567da0b6

### System configuration
**Solidus Version**:
2.7.0

**Extensions in use**:
N/A

Is this user error?

**Comment by tvdeyen** [comment]
> Is this user error?

Yes. You need to install `solidus-I18n` in order to get translations

**Comment by jacobherrington** [comment]
@tvdeyen in that case, should the language drop down be disabled if `solidus-I18n` is not present?

**Comment by ValerianV** [comment]
Actually, i have the same problem.

I installed solidus_il8n

gem 'solidus_i18n', '~> 2.0'
gem 'rails-i18n', '~> 5.1'
gem 'kaminari-i18n', '~> 0.5.0'

and, on the backend, whenever i select another langage, it switch back to english.

**Comment by DanielePalombo** [comment]
I'm on it

**Comment by christophebeling** [comment]
This is happening for me too.
