### ISSUE TITLE
Products at mulitple Stock Locations appear as unique variants

### ISSUE THREAD

**Issue by jacobherrington** [solidusio/solidus#2868]
### Steps to reproduce
**1.** Create a store with two (or three) Stock Locations.
<img width="1163" alt="screen shot 2018-09-25 at 7 23 06 pm 1" src="https://user-images.githubusercontent.com/11466782/46050364-60e7e500-c0f9-11e8-9894-a30fc4374dd1.png">
**2.** Choose a product with no variants (I used the RoR Mug). 
**3.** Add stock to the product in each location.
<img width="879" alt="screen shot 2018-09-25 at 7 30 16 pm" src="https://user-images.githubusercontent.com/11466782/46050387-74934b80-c0f9-11e8-99fc-71b68e859ba7.png">
**4.** Create a new order from `admin/orders` and try to add the item. You will see the two (or three) variants with the same SKU.
<img width="1139" alt="screen shot 2018-09-25 at 7 23 58 pm" src="https://user-images.githubusercontent.com/11466782/46050399-7d841d00-c0f9-11e8-8968-719dc615f206.png">

### Expected behavior
One variant should exist in the dropdown, regardless of the number of Stock Locations.

Please correct me if this is not ideal.

### Actual behavior
There are as many variants listed in the drop down as there are Stock Locations with stock.

### System configuration
**Solidus Version**: 2.7.0

**Extensions in use**: Sandbox

**Comment by mayanktap** [comment]
Hi @jacobherrington , I am able to reproduce this issue in my local machine and tried to fix. I guess I would be able to fix this. 
I would like to work on this. Can I ?

**Comment by jacobherrington** [comment]
Please do @mayanktap! Let me know if you need help and I'll try to give you some guidance. :)

**Comment by mayanktap** [comment]
@jacobherrington , According to my understanding and investigation, I made some changes and tested it thoroughly. I will raise the PR so that you can review and take decision accordingly. 
I would just need some guidance in the process of making PR.
 
I want to verify one point regarding the process of raising PR: 
1.) I am raising PR as base branch as **master**. That means the new branch that I will create to push the change will be from **master** branch. Is it correct?

**Comment by mayanktap** [comment]
Is there any naming convention regarding the name of the branch? I didn't find anything related to this in CONTRIBUTION documentation.

**Comment by jacobherrington** [comment]
Wow that's great 🎉 

Yes, we usually branch off of master and PR back to master and branch names aren't a big deal to Solidus.

Thanks a ton for your help! 👍

**Comment by mayanktap** [comment]
Ok then I will raise the PR after another round of testing.

**Comment by mayanktap** [comment]
Please refer to this new PR(https://github.com/solidusio/solidus/pull/3063) for the fix of this issue.
