### ISSUE TITLE
Deprecation warnings from RubyMoney/money

### ISSUE THREAD

**Issue by jacobherrington** [solidusio/solidus#2870]
### Steps to reproduce
`bundle exec rspec` in `solidus/backend`.

Spree::Money.to_html logs a bunch of deprecation warrnings.

https://github.com/solidusio/solidus/blob/8caf58aabc3d5390051d1f866a537df34f7f6181/core/lib/spree/money.rb#L84

### Expected behavior
Test should run with a minimal amount of noise.

### Actual behavior
An absurd number of deprecation warnings log during the tests:
<img width="600" alt="screen shot 2018-09-25 at 11 03 23 pm" src="https://user-images.githubusercontent.com/11466782/46078299-578e6500-c159-11e8-9c44-61660dbbf7a5.png">

### System configuration
**Solidus Version**: 2.7.0

---

#2869 attempted to fix this, I will repost my comment from that PR here:

I was working on this last night actually. I agree that getting rid of the huge number of deprecation warnings would be great. 

<img width="400" alt="screen shot 2018-09-25 at 11 03 23 pm" src="https://user-images.githubusercontent.com/11466782/46078019-848e4800-c158-11e8-99d7-d772d423230e.png">

The problem is that back in June [RubyMoney/money deprecated `html` in favor of `html_wrap`](https://github.com/RubyMoney/money/commit/1a752273bb905c1093853de27a1de2376d005820#diff-ed0226fe7de46664f666cd7a6e7e7b46), which doesn't exactly do the same thing.

From [RubyMoney/money docs](https://www.rubydoc.info/gems/money/Money/Formatter):

> Money.ca_dollar(570).format(html: true, with_currency: true)
#=> "$5.70 <span class=\"currency\">CAD</span>"

VS

> Money.ca_dollar(570).format(html_wrap: true, with_currency: true)
#=> "<span class=\"money-currency-symbol\">$</span><span class=\"money-whole\">5</span><span class=\"money-decimal-mark\">.</span><span class=\"money-decimal\">70</span> <span class=\"money-currency\">CAD</span>"

Unfortunately because `html_wrap` and `html` actually do different things, this change breaks a handful of important tests. Also if you look at the frontend after making this change you will see this:

<img width="765" alt="screen shot 2018-09-26 at 6 49 55 am" src="https://user-images.githubusercontent.com/11466782/46077995-688aa680-c158-11e8-99bd-70182b469725.png">

So it's possible that getting rid of these deprecation warnings would take more than just using `html_wrap` where we were using `html`.

**Comment by antstorm** [comment]
Not sure why your front-end looks like this because `html` would also require result string to be `html_safe` or sanitisation to be off when rendering

**Comment by antstorm** [comment]
@jacobherrington yes, we're aiming for a new major version to be released soon, hence all the deprecation warnings. Hopefully there's enough info on how to remove these messages, making the future transition into Money v7 much easier for you

**Comment by antstorm** [comment]
@JDutil the deprecation warning might be a bit confusing since it's referring to `:format` option for `Money#format` the method, not the method itself. Have a loot at this — https://github.com/RubyMoney/money/blob/master/lib/money/money/formatter.rb#L214-L219. Does it make sense?

**Comment by JDutil** [comment]
Thanks @antstorm that makes sense 👍

**Comment by antstorm** [comment]
@JDutil please ping me if you need any help moving forward

**Comment by LucasKuhn** [comment]
I was getting the same error, got rid of it by adding a format rule rule ( format: '%u %n' ) and stripping the .to_html that was being called at the end :)
