### ISSUE TITLE
Unable to change the activation after a promotion has been created

### ISSUE THREAD

**Issue by jacobherrington** [solidusio/solidus#2873]
### Steps to reproduce
Create a promotion.

### Expected behavior
The admin should be able to change a promotion's activation after it has been created.

### Actual behavior
There is no UI to change the promotion's activation.

### System configuration
**Solidus Version**: 2.7

**Extensions in use**: solidus_auth_devise

**Comment by aitbw** [comment]
Hey @jacobherrington, can you elaborate further on this? With current `master`, I'm able to change the start date of a promotion **after** it was created.

**Comment by jacobherrington** [comment]
@aitbw It's been a while since I opened this -- I think I was referring to the actual coupon code.
