### ISSUE TITLE
Error in permittedattributes 

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#2906]
Hi, 
After upgrade I had an error in method 'add_to_line_item' of Spree::OrderContents. It was due to PermittedAttributes.

If you change from 'PermittedAttributes' to 'Spree::PermittedAttributes' found the attributes  and 	works

line_item.options = ActionController::Parameters.new(options).permit(Spree::PermittedAttributes.line_item_attributes).to_h

**Comment by sechix** [comment]
Sorry , I don't have the error now

**Comment by kennyadsl** [comment]
Ok, I'm going to close this one, feel free to reopen if this happens again and you can attach an error message that allows debugging. Thanks anyway for reporting back!
