### ISSUE TITLE
Deprecate 'X-SPREE-TOKEN' header

### ISSUE THREAD

**Issue by skukx** [solidusio/solidus#2934]
Rather than using a custom header we should move this to be under the `Authorization` header.
Example:
```
Authorization: Bearer my_secret_token
```

We then could update the `load_user` method to look like
```ruby
def load_user
  @current_api_user ||= authenticate_with_http_token do |token, options|
    Spree.user_class.find_by(spree_api_key: token)
  end
end
```
See: https://github.com/solidusio/solidus/blob/8fd6b1f9175b936b5db3d1724c87bd1fe426425a/api/app/controllers/spree/api/base_controller.rb#L45-L47

**Comment by kennyadsl** [comment]
Closed with #3029, thanks @Nittarab and @twist900!
