### ISSUE TITLE
When user has no orders, `ADD ONE` link creates guest order instead

### ISSUE THREAD

**Issue by gbxl** [solidusio/solidus#2935]
https://github.com/solidusio/solidus/blob/475d9db5d0291dd4aeddc58ec919988c336729bb/backend/app/views/spree/admin/users/orders.html.erb#L77

This should instead be like the top button `spree.new_admin_order_path(user_id: @user.id)`

**Comment by jacobherrington** [comment]
Thanks for reporting this, small usability upgrades are great!

**Comment by kennyadsl** [comment]
Closed with #2936, thanks @jacobherrington and @gbxl for reporting the issue! 🎉
