### ISSUE TITLE
Misleading notification when updating stock for a variant that is not tracking inventory

### ISSUE THREAD

**Issue by ychaker** [solidusio/solidus#2946]
### Steps to reproduce

1. Create a product and add at least one variant
2. Edit the variant and uncheck the "Track Inventory" checkbox
3. Go to the stock locations tab and try updating the count for the variant you created

You'll see the something like this:
![solidus](https://user-images.githubusercontent.com/29512/48420492-2b866d80-e720-11e8-84cd-b618467709e5.gif)

### Expected behavior

I expect one of 2 things to happen:

**Option A:** The stock count is updated successfully
**Option B:** The message tell me as a user that the count was not updated because the variant is set to not track inventory.

### Actual behavior

What actually happens is that I get a success message telling me the count was updated, when it wasn't, which is misleading to a regular user, especially if it wasn't the same person who unchecked the track inventory option.

### System configuration
**Solidus Version**: 2.7.0.alpha (we're using edge, tracking the master branch, but haven't updated a few weeks)

**Extensions in use**:

**Comment by jacobherrington** [comment]
Which of these two expected behaviors is ideal? I feel like if a product is set to "do not track" then we shouldn't allow changes to the count, but does anyone else feel different?

**Comment by VzqzAc** [comment]
I agree with that @jacobherrington, having a product that does not track inventory to actually count the inventory might be a very special use case

**Comment by seand7565** [comment]
Disabling or removing the edit button on non-tracked products makes sense to me.

**Comment by kennyadsl** [comment]
@seand7565 maybe disabling the count on hand input field is better? The edit button is still needed if you need to change the `track inventory` option to `false` for example.

**Comment by ychaker** [comment]
from working with people who manage the products but are very tech averse, I would say that if you disable or remove the ability to edit the count, please also add a tooltip or something explaining why. it's a tiny thing that would go a long way.

**Comment by jacobherrington** [comment]
@ychaker yes, I think there should be some indication for sure.

**Comment by aitbw** [comment]
I'll have a look at this one :smile_cat:
