### ISSUE TITLE
Admin Navigation Tab Double Highlighting

### ISSUE THREAD

**Issue by jacobherrington** [solidusio/solidus#2950]
### Steps to reproduce

In the admin area, navigate to a product and then click "Product Stock."

### Expected behavior

On the nav, the Stock tab should be highlighted.

### Actual behavior

Both the Product and Stock navigation tabs are highlighted.
![screenshot_2018-11-13 store stock - ruby on rails baseball jersey - products](https://user-images.githubusercontent.com/11466782/48492149-c0f03300-e7ee-11e8-9c44-d40a7bca3dd8.png)

### System configuration
**Solidus Version**:

2.8.0.alpha

**Extensions in use**:
N/A

**Comment by aitbw** [comment]
I'll have a look at this one :)
