### ISSUE TITLE
Missing image in autocomplete variant

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#2951]
Trying to add a product variant to an order from admin. If variant don't have images no image appears. It should display master image as in the other parts of solidus. 
![image](https://user-images.githubusercontent.com/24247266/48497005-9379a880-e833-11e8-9f95-966c0393341a.png)

In this case this can be solved modifying this file : 'assets->javascript->spree->backend->templates->variants->autocomplete.hbs' buy I have detected more handlebars using the same logic.

**Comment by jacobherrington** [comment]
In Slack @VzqzAc brought up:

> wouldn’t show the master image misinform the user of the variant being selected? Thinking a bit about UX in here :thinking_face: open to discussion though

I think he has a point, but I also don't expect the people using this page to really understand the difference between a normal variant and a master variant. As long as the SKU is correct, I don't think it would be a bad user experience.

**Comment by VzqzAc** [comment]
In the projects I've worked on we have different images for each variant, so I think that showing the master variant's image could lead the user to think they're choosing that variant.

But I think @jacobherrington has a point too, users that can use the admin panel, and add products to orders, might have better knowledge of the application flow and thus rely on SKUs to make sure it's the variant they want.

Still I think that relying on the master variant could have some UX issues

**Comment by sechix** [comment]
@VzqzAc Only when variant don't show image has to display master image. This is how hows in every part of solidus

**Comment by VzqzAc** [comment]
Right @sechix, we should keep consistency in this case in my opinion, if the way it is showed in this part changes, it should come along with many other places updated, so might be better to keep it as is in the rest of the project
