### ISSUE TITLE
The navigation menu should be a collapsible

### ISSUE THREAD

**Issue by jacobherrington** [solidusio/solidus#2961]
This is a continuation of #666 based on feedback from an MVP attempt at this functionality in #2957 and the earlier work done in #1718.

One of the more pressing issues with Solidus' admin UI is a lack of responsiveness. A key step in achieving a more responsive, modern feeling UI is recovering some lost screen real estate by reworking the navigation menu.

Ideally, the navigation menu could be collapsed much like the navigation menu in GitLab and Spree:

<img width="207" alt="screen shot 2018-11-20 at 4 27 39 pm" src="https://user-images.githubusercontent.com/11466782/48806843-49843d00-ece1-11e8-9ecc-6a04a33ad018.png">

## Some of the requirements laid down in previous issues and discussions:

- [ ] Default open on large screens.
- [ ] Default close on small screens.
- [ ] Remember user preferences on the computer/device they're using.
- [ ] Stays open/close until user changes the preference.
- [ ]  Label on collapsed nav items to appear on hover. Tooltip should look consistent with admin, but different from menu styles.

## An example mockup:

![image](https://user-images.githubusercontent.com/11466782/48807548-79344480-ece3-11e8-9e13-520f3780440a.png)

**Comment by jacobherrington** [comment]
I am currently working on this, but would love to take suggestions here!

**Comment by tvdeyen** [comment]
I have a branch with a working prototype as well. Just tell me if I should send it to you.

**Comment by tvdeyen** [comment]
@jacobherrington https://github.com/tvdeyen/solidus/tree/collapsible-nav

**Comment by seand7565** [comment]
@jacobherrington If you're not still working on this I'd love to take a crack at finishing it - this is a feature I'd love to see in the next release.

**Comment by jacobherrington** [comment]
@seand7565 Please do, I haven't had much free time in the last few months. 👍

**Comment by tvdeyen** [comment]
@seand7565 this would be great 👍

**Comment by seand7565** [comment]
Great! I've started working on it here -> https://github.com/seand7565/solidus/tree/nav-collapse

**Comment by jacobherrington** [comment]
@seand7565 Please let me know if I can help, I don't have much time, but happy to give feedback. Thanks Sean! 🥇

**Comment by jacobherrington** [comment]
https://github.com/solidusio/solidus/pull/3322 Work is being done in this PR!
