### ISSUE TITLE
Rake task for seeding sandbox app aborted

### ISSUE THREAD

**Issue by aitbw** [solidusio/solidus#2978]
### Steps to reproduce

* Run `DB=postgresql bundle exec rake sandbox` on your Solidus source folder

### Expected behavior

* Sandbox app should be created without errors

### Actual behavior

* The following error raises:

`NoMethodError: undefined method 'downcase' for nil:NilClass`

And the sandbox's front-end looks like this:

![image](https://user-images.githubusercontent.com/9470839/49100839-362a2200-f24b-11e8-8ecf-6ecc433f50a8.png)

### System configuration

* Latest master revision (318ff36)

**Extensions in use**:

* `solidus_auth_devise`

**Comment by jacobherrington** [comment]
I can confirm this, it has been present for at least a couple of months. This seems to happen about 10% of the time (that's a fabricated statistic).

**Comment by aitbw** [comment]
As a workaround, you can do `bundle exec rake sandbox` and it will seed the DB without errors. It looks like the problem occurs when you want to use MySQL or PostgreSQL.

**Comment by jacobherrington** [comment]
@aitbw I believe I have seen it with sqlite as well actually.

**Comment by aitbw** [comment]
@jacobherrington :thinking: that's weird, I've created ~4 sandboxes with SQLite without any issues.

**Comment by aitbw** [comment]
## Update (12/06/2018)

This issue also arises when using MySQL as DB, but it happens more frequently with PostgreSQL. I haven't been able to reproduce this problem with SQLite.

**Comment by jacobherrington** [comment]
I have been able to reproduce this error with SQLite, at least once. The error is being thrown from: https://github.com/solidusio/solidus/blob/9ae2ed16bad7e29ea422fab1403118a3a0e66266/sample/db/samples/assets.rb#L88

I'm still not able to get it to fail consistently.
