### ISSUE TITLE
Calling Spree::Order#promotions calls code which raises an error

### ISSUE THREAD

**Issue by StefanoDeVuono** [solidusio/solidus#2979]
### Steps to reproduce
Calling `promotions` on an order calls `code` on the object, because the `spree_promotions` table has a `code` column. This raises an error. 

### Expected behaviour
The `columns` method should exclude `code` from being called

### Actual behaviour
Raises error: `RuntimeError (Attempted to call code on a Spree::Promotion. Promotions are now tied to multiple code records)`

### System configuration
**Solidus Version**: 2.6.0

The `columns` method should be a class method. I can create a quick PR for this.

**Comment by kennyadsl** [comment]
@StefanoDeVuono Hey thank you for reporting, can you please expand a little bit on:

> Calling promotions on an order calls code on the object

In which context are you seeing this happening? Do promotion and order need to be created in some specific way to reproduce this issue?

Thanks!

**Comment by StefanoDeVuono** [comment]
@kennyadsl It's an issue I'm only able to reproduce on an app running rails 5.1. However, if I change the for `columns` method in the `Spree::Promotion` from an instance method to a class method, my issue goes away.

My guess is that that the instantiation of the model calls the class's column attributes. The `columns` method ostensibly asks to ignore the `code` column thereby preventing the error that calling `code` on an instance would raise.

Currently solidus implements `columns` as an  _instance_ method. I might need to do more digging, but my understanding is the canonical override of `columns` is to call `self.columns` -- ie: a class method:

https://blog.codeship.com/rails-migrations-zero-downtime/
https://blog.bigbinary.com/2016/05/24/rails-5-adds-active-record-ignored-columns.html
https://stackoverflow.com/questions/30798849/ignore-columns-in-activerecord

I think this implementation if flawed--even if it works sometimes.

**Comment by kennyadsl** [comment]
I think #3000 fixes this issue, anyway we should also open another PR to remove the column from the database.

**Comment by kennyadsl** [comment]
> I think #3000 fixes this issue, anyway we should also open another PR to remove the column from the database.

Done in #3028
