### ISSUE TITLE
Solidus breaking with Rails 5.2.2

### ISSUE THREAD

**Issue by aitbw** [solidusio/solidus#2989]
### Steps to reproduce

* Run `bundle exec rake sandbox` on your Solidus source folder

### Expected behavior

* Sandbox app should be created

### Actual behavior

* Rake task to create sandbox app crashes with the following error:

```
rake aborted!
NameError: undefined method `apply_free_shipping_promotions' for class `#<Class>'
```

A "workaround" is available by commenting [this line](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order.rb#L555) but doing so raises two (2) more errors:

```
rake aborted!
NameError: undefined method `Spree::Store.by_url is DEPRECATED' for class `#<Class>'
```

and

```
rake aborted!
ActiveRecord::RecordNotFound: Couldn't find Spree::Zone
```

### System configuration

* Latest master revision (7a33685)

**Extensions in use**:

* `solidus_auth_devise`

**Comment by jacobherrington** [comment]
Most likely related to #2978

**Comment by aitbw** [comment]
@jacobherrington Maybe but I doubt it; the issue presented in #2978 failed from time to time (I'm assuming that's because of some random value being taken into consideration when seeding the database) while this one always fails.

**Comment by kennyadsl** [comment]
Could it be something related to the last Rails release happened yesterday?

**Comment by kennyadsl** [comment]
I don’t think it’s related since Ransack released a version that should fix that issue a couple of hours ago.

**Comment by jacobherrington** [comment]
@aitbw I see this now, I thought this was intermittent. This failure is new.

**Comment by kennyadsl** [comment]
I think it's related to some [ActiveSupport deprecation change](https://github.com/solidusio/solidus/blob/dde082e96b56a96ea0b535637685f37f0a96e8bf/core/app/models/spree/order.rb#L555) in latest Rails. I'd lock Rails support to 5.2.1 for now until we know what's going on.

**Comment by tvdeyen** [comment]
It seems like `ActiveSupport::Deprecation` now checks if the deprecated method actually exist, what it does not in this case. 

Adding a simple `alias_method :apply_free_shipping_promotions, :apply_shipping_promotions` should do the trick.

**Comment by kennyadsl** [comment]
👍 where did you find that? I couldn't find any info about that in the ActiveSupport changelog

**Comment by kennyadsl** [comment]
Also, I don't think it's the only place where we are using `deprecate` like that.

**Comment by tvdeyen** [comment]
> where did you find that?  I couldn't find any info about that in the ActiveSupport changelog

Just my gut feeling 😊

**Comment by tvdeyen** [comment]
Even with that alias added I get lots of strange method missing errors. Seems like something big (autoloading?) is screwed up in Rails 5.2.2 👎

**Comment by kennyadsl** [comment]
I think it's related to this commit: https://github.com/rails/rails/commit/a982a42d766169c2170d7f100c2a5ceb5430efb1

**Comment by aitbw** [comment]
Closing via #2992
