### ISSUE TITLE
Error running `bundle exec rails generate spree:install`

### ISSUE THREAD

**Issue by ryangall7** [solidusio/solidus#2990]
### Steps to reproduce
When trying to install solidus for the first time following this guid https://guides.solidus.io/developers/getting-started/first-time-installation.html, I run into an error running `bundle exec rails generate spree:install`

> /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/deprecation/method_wrappers.rb:67:in `alias_method': undefined method `apply_free_shipping_promotions' for class `#<Class:0x00007fdfabb901a8>' (NameError)
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/deprecation/method_wrappers.rb:67:in `block in deprecate_methods'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/deprecation/method_wrappers.rb:57:in `each'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/deprecation/method_wrappers.rb:57:in `deprecate_methods'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/deprecation/instance_delegator.rb:22:in `deprecate_methods'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/core_ext/module/deprecation.rb:23:in `deprecate'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/solidus_core-2.7.0/app/models/spree/order.rb:555:in `<class:Order>'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/solidus_core-2.7.0/app/models/spree/order.rb:24:in `<module:Spree>'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/solidus_core-2.7.0/app/models/spree/order.rb:6:in `<main>'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:476:in `block in load_file'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:661:in `new_constants_in'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:475:in `load_file'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:373:in `block in require_or_load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:356:in `require_or_load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:510:in `load_missing_constant'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:195:in `const_missing'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/solidus_backend-2.7.0/app/controllers/spree/admin/orders_controller.rb:12:in `<class:OrdersController>'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/solidus_backend-2.7.0/app/controllers/spree/admin/orders_controller.rb:5:in `<module:Admin>'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/solidus_backend-2.7.0/app/controllers/spree/admin/orders_controller.rb:4:in `<module:Spree>'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/solidus_backend-2.7.0/app/controllers/spree/admin/orders_controller.rb:3:in `<main>'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:476:in `block in load_file'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:661:in `new_constants_in'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:475:in `load_file'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:373:in `block in require_or_load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:356:in `require_or_load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:510:in `load_missing_constant'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:195:in `const_missing'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/solidus_auth_devise-2.1.0/lib/controllers/backend/spree/admin/admin_orders_controller_decorator.rb:1:in `<main>'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/solidus_auth_devise-2.1.0/lib/spree/auth/engine.rb:34:in `block in prepare_backend'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/solidus_auth_devise-2.1.0/lib/spree/auth/engine.rb:33:in `glob'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/solidus_auth_devise-2.1.0/lib/spree/auth/engine.rb:33:in `prepare_backend'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/solidus_auth_devise-2.1.0/lib/spree/auth/engine.rb:21:in `block in <class:Engine>'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `instance_exec'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `catch'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:199:in `block in halting'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `each'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `invoke_before'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/reloader.rb:89:in `prepare!'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/gallagher/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	from /Users/gallagher/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/gallagher/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/gallagher/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/gallagher/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each'
	from /Users/gallagher/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `call'
	from /Users/gallagher/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/gallagher/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	from /Users/gallagher/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
	from /Users/gallagher/Sites/solidus/solidus-test/config/environment.rb:5:in `<main>'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/gallagher/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/gallagher/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/gallagher/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from -e:1:in `<main>

I was able to fix this and get it installed by commenting out line #555 of `/solidus_core-2.7.0/app/models/spree/order.rb`

**Comment by jacobherrington** [comment]
This is the same issue documented #2989. Thanks for reporting it @ryangall7!
