### ISSUE TITLE
Cannot order items with different shipping categories

### ISSUE THREAD

**Issue by afdev82** [solidusio/solidus#2998]
### Steps to reproduce
In the sandbox of Solidus 2.7.1, create two shipping categories and assign them to two products.
Add the two products to the cart and go until the address  step, compile and click "save and continue".

### Expected behavior
It should go to the Delivery step

### Actual behavior
It throws the error "We are unable to calculate shipping rates for the selected items."

### System configuration
**Solidus Version**: 2.7.1 (sandbox)
It worked with v2.4, actually I'm updating from 2.4 to 2.7.

I had a look and I found that the second `shipment` doesn't have any `shipping_rate` (`shipments.second.shipping_rates` is empty).
If I add the single items to the cart, they work.

**Comment by vassalloandrea** [comment]
Hey @afdev82, while I'm searching the problem on Solidus, I found that the issue can be resolved creating on the Solidus admin a new shipping method with the new shipping category or adding the new shipping category to an existing shipping method.

[Here](https://github.com/solidusio/solidus/blob/e2ef677cfff4b4cc264d8eaa20b6edcf545fa05d/core/app/models/spree/stock/estimator.rb#L56) the `Spree::Stock::Estimator` class retrieves all the shipping methods to build the shipping rates calling this class [method](https://github.com/solidusio/solidus/blob/e2ef677cfff4b4cc264d8eaa20b6edcf545fa05d/core/app/models/spree/shipping_method.rb#L50) without returning any shipping method.

#### Editing a shipping method

![image](https://user-images.githubusercontent.com/9986708/49888227-b1d8c100-fe3e-11e8-9b40-fba78c83e850.png)

**Comment by afdev82** [comment]
Hi @vassalloandrea , thank you for your help.
I was already using the `UPS Ground (EUR)` for one category and the `UPS Ground (EU)` for the other, but it didn't work, but I think I found out why.
The shipping methods have different currency, if I use the same currency in both, it works.
For sure it works if I add both shipping category to the same shipping method, but my setup is with two different shipping methods, because I want two different rates per category.
Online in my app I use the same currency for both shipping methods, so it should be something else. I'm debugging the two parts that you pointed out in my app, trying to figure out.

**Comment by afdev82** [comment]
I find the source of the error in my app. It's something very strange.
After this line I don't have any shipping_method anymore: https://github.com/solidusio/solidus/blob/e2ef677cfff4b4cc264d8eaa20b6edcf545fa05d/core/app/models/spree/stock/estimator.rb#L58

The reason is this line in the scope `available_to_store`:
https://github.com/solidusio/solidus/blob/e2ef677cfff4b4cc264d8eaa20b6edcf545fa05d/core/app/models/spree/shipping_method.rb#L44

If I execute `package.shipment.order.store.shipping_methods` I get my two shipping methods that I have for each shipping category:
```
#<ActiveRecord::Associations::CollectionProxy [#<Spree::ShippingMethod id: 2, name: "UPS", deleted_at: nil, created_at: "2017-11-15 15:50:06", updated_at: "2018-01-22 10:51:20", tracking_url: "https://wwwapps.ups.com/tracking/tracking.cgi?trac...", admin_name: "Courier for Germany (M120)", tax_category_id: 1, code: "de-m120", available_to_all: true, carrier: "UPS", service_level: "", available_to_users: true>, #<Spree::ShippingMethod id: 1, name: "UPS", deleted_at: nil, created_at: "2017-11-15 15:49:16", updated_at: "2018-01-22 10:51:39", tracking_url: "https://wwwapps.ups.com/tracking/tracking.cgi?trac...", admin_name: "Courier for Germany (M90)", tax_category_id: 1, code: "de-m90", available_to_all: true, carrier: "UPS", service_level: "", available_to_users: true>]>
```
but `package.shipment.order.store.shipping_method_ids` returns only the id of the first shipping method!
`package.shipment.order.store.shipping_methods.ids` returns `[2,1]`, so I don't know what's going on here.

**Comment by afdev82** [comment]
I found the problem.
I'm using the `solidus_multi_domain` gem, that didn't have the `inverse_of` option for the association.

```
  has_many :store_shipping_methods, inverse_of: :store
```

If I add it, it works! I will submit a PR for the gem in order to fix this.

**Comment by afdev82** [comment]
Anyway, it's strange that if I don't have this option, the two methods returns different results, I don't know the internals of ActiveRecord, maybe this is a bug there.
