### ISSUE TITLE
N+1 in Spree::API::TaxonsController#index

### ISSUE THREAD

**Issue by stem** [solidusio/solidus#3004]
### Steps to reproduce
Make a request with 3 taxon IDs like `GET /api/taxons?ids=1,2,3`

### Expected behavior
It should not make a new SQL query for each taxon

### Actual behaviour
Because of the `pretty_name` method, it generates a new SQL query for each taxon : 
```
=>   Spree::Taxon Load (0.2ms)  SELECT "spree_taxons".* FROM "spree_taxons" WHERE "spree_taxons"."lft" <= 9 AND "spree_taxons"."rgt" >= 10 AND ("spree_taxons"."id" != 7) ORDER BY "spree_taxons"."lft" ASC
=>   Spree::Taxon Load (7.5ms)  SELECT "spree_taxons".* FROM "spree_taxons" WHERE "spree_taxons"."lft" <= 16 AND "spree_taxons"."rgt" >= 17 AND ("spree_taxons"."id" != 9) ORDER BY "spree_taxons"."lft" ASC
```

### Root cause
In `app/views/spree/api/taxons/index.json.jbuilder`, the `taxon_attributes` returns
```
[:id, :name, :pretty_name, :permalink, :parent_id, :taxonomy_id]
```
and each associated method is call on each taxon.

The `pretty_name` and the `permalink` methods need to know the full ancestors chain, and both of them will generate a N+1
In our case, the `permalink` does not generate queries because of the one done by `pretty_name`. If `pretty_name` wasn't called, it will make a query to get the taxon parent, then another to get the parent's parent, and so on...

I didn't see anything from awesome_nested_set to mitigate this problem and have no any idea of how we can preload all ancestors of all selected taxons but preloading seems to be the only solution

### System configuration
**Solidus Version**: 2.7.0

**Extensions in use**:
```
gem 'solidus', '~> 2.7.0'
gem 'solidus_auth_devise'
```

**Comment by kennyadsl** [comment]
Thanks for opening the issue. Can we do something similar to https://github.com/solidusio/solidus/pull/3002 ?

**Comment by stem** [comment]
@kennyadsl yes, we should do an `includes`, but I don't know on what relation we can do it.

awesome_nested_set does not seem to define a `has_many ancestors` so I'm not sure if we can take that road. I've asked them for advice because I don't see any "clean" way to resolve this. If they can point us to a good direction, we should probably refactor `pretty_name` and `permalink` to work the same way (using `ancestors` or `parent` but not both)

The "wrong" / "ugly" way could be to refactor `pretty_name` to recursively preload all `parent_id` we found with something like : 

```
def index
  @taxons = ....
  preload_ancestors(@taxons)
end

def preload_ancestors(taxons)
  return if taxons.empty?

  ActiveRecord::Associations::Preloader.new.preload(taxons, [:parent])
  preload_ancestors(taxons.map(&:parent).compact)
end
```

This is really ugly, and will generate 1 query per level of the selected taxon's maximum depth. It may or may not be more efficient than 1 query per taxon, depending of the number of taxons listed and the maximal depth selected 😞

**Comment by kennyadsl** [comment]
I see this now, thanks for the accurate explanation.
I can't see any clean solution to this but maybe someone from awesome_nested_set could help us.
