### ISSUE TITLE
Receiving "Sass::SyntaxError in Spree::Home#index" after starting the server

### ISSUE THREAD

**Issue by vinu-pillai** [solidusio/solidus#3014]
### System configuration
**Solidus Version**:

**Extensions in use**:

**Comment by vinu-pillai** [comment]
After installing solidus successfully in Ubuntu machine, I have received the following on the browser after starting the server -

Sass::SyntaxError in Spree::Home#index
Showing /var/lib/gems/2.3.0/gems/solidus_frontend-1.4.2/app/views/spree/shared/_products.html.erb where line #31 raised:

Undefined mixin 'display'.

**Comment by kennyadsl** [comment]
It looks like you are using a very old Solidus version (1.4.2) can you try with the latest version (2.7.1)?

**Comment by jacobherrington** [comment]
You probably need to change your Gemfile to point at a more recent version. 

This will probably help: https://bundler.io/v1.17/guides/bundler_sharing.html

**Comment by kennyadsl** [comment]
Closing since it looks like an issue with Rails/Solidus versions.

**Comment by Naokimi** [comment]
I encountered the same issue when updating a Spree app to Solidus. The reason this happens is that Solidus 1.4.2 depends on [gem Bourbon](https://github.com/thoughtbot/bourbon) which when installing resolves to version 5.1.0. This version doesn't include this and other mixins that solidus uses, leading to the error. 
This dependency is removed from solidus 2.2 on with this commit: https://github.com/solidusio/solidus/commit/b23c89564a46e6377d1e8187f76103fe37b1a47b

If you need to (temporarily) stay on Solidus 1.4.2 you can fix this error by adding to your Gemfile `gem 'bourbon', '~> 4.3.4'`
