### ISSUE TITLE
Store credits applied after the payment is created

### ISSUE THREAD

**Issue by BravoSimone** [solidusio/solidus#3050]
**Describe the bug**

In the payment step, if the user has store credits, a first payment with the total amount is saved to the database. After that, store credits are subtracted from the payment and the amount is updated with the remaining total. This happens even if store credits completely cover the order total and the user still needs to input his credit card.

**Solidus Version**:

master

**To Reproduce**

1. Assign yourself some store credits in the admin area
2. Put a byebug [here](https://github.com/solidusio/solidus/blob/375305d7791c605d414f486792cffadee44778fd/core/app/models/spree/order.rb#L631)
3. Check how the payment evolves after each action
4. Complete the checkout

**Expected behavior**

The payment is directly saved with the correct amount on the database

**Additional context**

If this behavior is intended to be as it is now, I'm going to add some documentation to explain the reasons better.

**Comment by ccarruitero** [comment]
Hi all :wave: 

I plan to work on this bug, if anyone is already looking at this please let me know

**Comment by waiting-for-dev** [comment]
Sure, @ccarruitero, go ahead! 🙂

**Comment by ccarruitero** [comment]
Well, I was looking at this but not totally sure it's a bug

When we [update the order on checkout](https://github.com/solidusio/solidus_starter_frontend/blob/main/templates/app/controllers/checkouts_controller.rb#L37) we use the [`OrderUpdateAttributes`](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order_update_attributes.rb) module which call the [`assign_payments_attributes`](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order_update_attributes.rb#L35-L39) method. This method create new payments from payment parameters. So, when we hit `update_order` from payments step, we create a new payment with selected payment method and order total amount. Then when call [`add_store_credit_payments`](https://github.com/solidusio/solidus/blob/master/core/lib/spree/core/state_machines/order.rb#L88) https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order.rb#L582, we apply store credits (if any) and update other payments with remaining amount.

Do you think we should modify something?
