### ISSUE TITLE
Error in admin order due to select2_locale_es

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#3057]
**Describe the bug**
After upgrade to master solidus version my atocomplete variant in order to add new items  is not working

**Solidus Version**:
Master

**To Reproduce**
Go to admin -> order:

![image](https://user-images.githubusercontent.com/24247266/51831830-65184f00-22f3-11e9-801f-cd62938e1318.png)

Tha autocomplete variant doesn't work. Checking errores I found this:
![image](https://user-images.githubusercontent.com/24247266/51831772-3f8b4580-22f3-11e9-81e0-b215dc91f416.png)

**Comment by kennyadsl** [comment]
@sechix I think it could be related to #3027. Can you please paste your `vendor/assets/javascripts/spree/backend/all.js` file's content?

**Comment by sechix** [comment]
I have this in vendor/assets/javascripts/spree/backend/all.js:

vendor/assets/javascripts/spree/backend/all.js
![captura de pantalla 2019-01-28 a las 13 22 20](https://user-images.githubusercontent.com/24247266/51836146-cf36f100-22ff-11e9-903c-535dc001f7c0.png)

**Comment by kennyadsl** [comment]
@sechix I'm trying to replicate the issue but I can't see that autocomplete in `admin -> order`. Which page are you using exactly?

**Comment by sechix** [comment]
I realized that it is not related to variant autocomplete, none of the script work , I guess it is due to the jquery error that I have in every page of solidus admin

**Comment by sechix** [comment]
Hi, yes I had a syntax error , sorry. Solved!
