### ISSUE TITLE
Filter Product Taxons  - taxons.js

### ISSUE THREAD

**Issue by grichardomi** [solidusio/solidus#3071]
Hello,

Attention:: JS Experts!

Let's say I have 3 Taxons (Builders, States, Services). Is there a way for Edit Product to list, when clicked,  only  "Services" Taxon in the dropdown?

Thanks

**Comment by kennyadsl** [comment]
@grichardomi Hey there, can you please explain your issue better. Which page are you talking about?

**Comment by grichardomi** [comment]
Let's say I have "Builders, States and  Services" taxonomies. In Admin Edit Product, all Taxons for builders, states, and services are listed in the dropdown list.

I would like to be able to filter which taxonomies get listed. In this case, I would like the dropdown list box to list only "**Services**" taxons. 

**Would like to see this:**
Services -> Senior Care
Services -> Nurse 

**Do not want this:**
Builders -> Wall
Builders-> Mason
Services -> Senior Care
Services -> Nurse 
States -> Utah
States -> Texas

**Comment by grichardomi** [comment]
Managed to get this work by modifying taxon_autocomplete.js
