### ISSUE TITLE
factory_bot is breaking 2.5 - 2.6 specs in extensions 

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#3074]
`factory_bot` removed support for (already deprecated) static attributes. 

We already have done this in v2.7 with [this PR](https://github.com/solidusio/solidus/pull/2831) but this means [all extensions on v2.5 and v2.6 are broken now](https://extensions.solidus.io/), for example, https://travis-ci.org/solidusio/solidus_auth_devise/jobs/487615455. 
v2.4 is not broken since it has the `factory_bot` [version locked](https://github.com/solidusio/solidus_auth_devise/blob/ddded44fccf7d6319b1c597c62fe93f84107e7c2/Gemfile#L12-L17) to a previous one, due to the factory_girl rename issue). 
We have 2 way to fix this:

- cherry-pick that commit in v2.5 and v2.6 and release a new version on Rubygems
- update all extensions to lock factory_bot to an early version doing something similar [to this](https://github.com/solidusio/solidus_auth_devise/blob/ddded44fccf7d6319b1c597c62fe93f84107e7c2/Gemfile#L12-L17).

I think I prefer the first option so we don't have to update all extensions. WDYT?

**Comment by ericsaupe** [comment]
I prefer the first method as well. While I don't love the idea of doing a new release simply for a test suite change I think it is the best path in supporting all of the extensions. Using the most up to date/supported version of supporting gems is important imo.

**Comment by aitbw** [comment]
I'm all in for the first option —easiest and quickest way to address the issue. I gladly take care of that PR when a consensus is reached :relaxed:

**Comment by peterberkenbosch** [comment]
Awesome! I was just looking at this.

**Comment by spaghetticode** [comment]
count me in for option 1 👍

**Comment by tvdeyen** [comment]
First option is ok. It's not breaking anything (hopefully we don't not have changes in factories between those versions 🤞) and should not effect any production code, so 👍

**Comment by kennyadsl** [comment]
Released v2.5.1 and v.2.6.3 that contains #3078 and #3079. If this will fix the extension matrix we can close this issue.

**Comment by kennyadsl** [comment]
Problems on extensions seem fixed, we can close this one!
