### ISSUE TITLE
Backend: Add product via shipment tab buggy

### ISSUE THREAD

**Issue by loicginoux** [solidusio/solidus#3085]
**Solidus Version**:
2.7.1

**To Reproduce**
- via backend, "new order"
- skip "cart" tab
- add user to order
- go to shipment tab and add product via "add product" block
- change shipping method of the shipment newly created
- create a check payment
- go back to shipments tab

**Current behavior**
The shipment loose its custom shipping method and instead the default shipping method is applied. 

**Expected behavior**
the shipment should not change. When doing the same step bug adding product via "cart" tab, the shipment is not changed when creating a check payment.

**Additional context**
What's happening is that during this `create_proposed_shipments`
```
before_transition to: :delivery, do: :create_proposed_shipments
```

it destroys and rebuilds shipments for the order. In the case "add product", the state is still in "cart" and when adding payment, we rebuild shipments after having updated its shipping method and thus we loose changes. When doing via "cart" tab, we trigger a state change, we pass by delivery step before being able to do any changes to shipments, so shipments are recreated before any custom update to shipments.

I see 2 solutions:
- we update state of the order when adding product via "add product", it would make the state being "delivery" before applying any changes to shipments.
- I would advise to remove completely this block "add products", and we would be able to add products only via the cart tab. We loose the feature to being able to select the stock location but I don't see the point of it if you already have a stock location coordinator... It also means a UI more simple and less code to maintain :)

What do you think ? I don't mind fixing this in a PR. Let me know the solution you'd prefer to see.

**Comment by tvdeyen** [comment]
I am a huge fan of the second solution. There must be no way to add products to an existing shipment but through the cart. I even have an (outdated) branch laying on my hard drive that removes that select from the order shipments tab. Will open a PR.
