### ISSUE TITLE
Error 500 when creating an exchange for product with insufficient stock

### ISSUE THREAD

**Issue by fkoessler** [solidusio/solidus#3095]
**Solidus Version**:
2.7.1

**To Reproduce**

*  edit Ruby on Rails bag stock to 3 and set to NOT back orderable

* Create order for 2 Ruby on Rails Bag and ship

* create a new "RMA" for 2 Ruby on Rails bag exchange

* edit Ruby on Rails bag stock to 1 and set to NOT back orderable

* create customer return for the 2 Ruby on Rails bags

* click the "Create reimbursement" button

* click the "Reimburse" button

**Current behavior**
An error 500 is raised (see the attached stacktrace).

**Expected behavior**
We should be redirected to the edit reimbursement page with an error message in the flash.

**Screenshots**

![create-rma](https://user-images.githubusercontent.com/1450340/52701494-a0b14b00-2f7a-11e9-9574-58371a2bd63c.png)

![create-cr](https://user-images.githubusercontent.com/1450340/52701498-a3ac3b80-2f7a-11e9-8577-deaccf44f0de.png)

**Additional context**

[stacktrace.txt](https://github.com/solidusio/solidus/files/2859679/stacktrace.txt)

**Comment by aitbw** [comment]
Let me have a look at this.

**Comment by aitbw** [comment]
Hey @fkoessler, thanks a lot for reporting this issue! I tried to reproduce it on my machine but I wasn't able to do so. Could you provide a spec for this so I can take a further look?
