### ISSUE TITLE
[DEMO] non-heroku demo?

### ISSUE THREAD

**Issue by rubyFeedback** [solidusio/solidus#3103]
Is there some way to get a non-heroku demo?

Reason I ask is that heroku requires sign-in when I clicked the Demo link on the main readme here ("You'll need a Heroku account to deploy the app") and I really don't want to sign-in just to 
try out solidus.

Anyway, if this is too much work or unwanted, please feel free to close the issue request - ultimately I could just go ahead and sign up at heroku, but I'll rather skip that altogether (I am a lazy person, I know).

**Comment by kennyadsl** [comment]
If you can clone the repo locally, you could just run

```
bundle install
bundle exec rake sandbox
cd sandbox
bundle exec rails s
```

to have a working Solidus demo store. Alternatively, there's no way at the moment.

**Comment by JuanCrg90** [comment]
@kennyadsl, with the docker demo addition, is this issue still valid?

**Comment by kennyadsl** [comment]
@JuanCrg90 yes, you are right. Thanks!
