### ISSUE TITLE
No-variant products no longer show weight or dimension fields

### ISSUE THREAD

**Issue by seand7565** [solidusio/solidus#3111]
Looks like in #2875 an `else` statement was removed that allows for weight & dimension fields to show on the [admin product _form partial](https://github.com/solidusio/solidus/blob/master/backend/app/views/spree/admin/products/_form.html.erb). Now, those fields are not displayed, unless you are on a product WITH variants - in which case, you wouldn't want to edit the master variants weight & dimensions.

This could be fixed by adding the `else` statement back in - I can push a fix for this by tomorrow if nobody else has an opportunity to.

**Comment by aitbw** [comment]
Closed via #3112
