### ISSUE TITLE
Deleting a user with orders throws Missing Template exception

### ISSUE THREAD

**Issue by brchristian** [solidusio/solidus#3126]
When attempting to delete a user from the backend who has orders, the deletion will fail and a `Missing Template` error screen will be shown. (Screenshot below.)

**Solidus Version**:
2.8.1

**To Reproduce**
Create new 2.8.1 app.
Complete an order with a user.
Attempt to delete user from backend.

**Current behavior**
Missing Template exception will be seen.

**Expected behavior**
I would expect either to see an explanation to the effect of ``Cannot delete user with orders``, or a dialogue ``This user has orders. Continue?``, or a successful deletion.

**Screenshots**
<img width="1253" alt="screen shot 2019-02-27 at 12 56 19 pm" src="https://user-images.githubusercontent.com/2460418/53522611-9e2d1600-3a8f-11e9-873f-45166f08c0f8.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Safari
 - Version 12.0.3

**Comment by jacobherrington** [comment]
This still exists in master. I'll try to make a fix today.

**Comment by jacobherrington** [comment]
Just as an update, the change in #3139 does not close this issue. It is only a temporary fix.

**Comment by tvdeyen** [comment]
Fixed with https://github.com/solidusio/solidus/pull/4415
