### ISSUE TITLE
Demo store is not responsive to 320px

### ISSUE THREAD

**Issue by alansutherland** [solidusio/solidus#3178]
The demo store does not have CSS styling down to 320px screen width. This should be supported since it's iPhone SE width. Obviously, I can add this but I would assume that most devs would ship their project with this already added.

**Comment by kennyadsl** [comment]
@alansutherland the demo store provided is supposed to be replaced entirely with custom frontends and it’s there just as a frontend placeholder. Thank you for reporting the issue anyway!
