### ISSUE TITLE
User picker proposes the same users at promotion edit page

### ISSUE THREAD

**Issue by VitaliyAdamkov** [solidusio/solidus#3183]
When we have a user, who has few addresses then he will be proposed with user_picker.js multiple times.

**Solidus Version**:
2.4.2 (checked at https://solidus-master-demo.herokuapp.com/ also)
[Gemfiles](https://gist.github.com/VitaliyAdamkov/738512cfe887ead87d852be34c5ec99a)

**To Reproduce**
1. Make an order for default user with Address1.
2. Make an order for default user with Address2.
3. Create a promotion.
4. Go to the promotion edit page.
5. Add the user promotion rule.
6. Type any letter from default user's email.

**Current behavior**
API call runs and select shows default user at least two times.

**Expected behavior**
Select is expected to show unique users.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/25305511/56215775-e1a40980-6068-11e9-94d5-a07e936bfebc.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Mozilla Firefox
 - Version 66.0.2

**Comment by vzqzac** [comment]
I reproduced this and will open a PR in a moment
