### ISSUE TITLE
Error in taxons 

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#3184]
Hi, I updated to master solidus and I am getting an error 
`CollectiveIdea::Acts::NestedSet::Move::ImpossibleMove - Impossible move, target node cannot be inside moved tree` trying to add a taxon to a taxonomy .

**Solidus Version**:
Master branch

**To Reproduce**

1. Go to '/admin/taxonomies'
2. Click on 'create a taxonomy'
3. Click on 'create a taxon for this taxonomy'
-->
![image](https://user-images.githubusercontent.com/24247266/56217574-c08cea00-6063-11e9-9aec-e6cae121a3c5.png)

**Comment by aitbw** [comment]
Hey @sechix, thanks a lot for reporting this. Unfortunately, I'm unable to reproduce this issue with the latest `master` revision —could you provide us with more details on your configuration?

**Comment by sechix** [comment]
New taxonomy 
![image](https://user-images.githubusercontent.com/24247266/56222448-59276800-606c-11e9-8c0b-efd15b66a8ef.png)
Create 'test':
![image](https://user-images.githubusercontent.com/24247266/56222502-765c3680-606c-11e9-9e19-1e411d54ffa0.png)

![image](https://user-images.githubusercontent.com/24247266/56222630-a99ec580-606c-11e9-9854-91d7865bdd50.png)

**Comment by sechix** [comment]
Sorry I had an error in my db, I cleaned the taxons table and now it is working ok. Thanks for your support.
