### ISSUE TITLE
Database migrations from Spree stores don’t apply correctly

### ISSUE THREAD

**Issue by brchristian** [solidusio/solidus#3190]
Users (like myself) who are migrating to Solidus after having Spree stores will find that some of their Solidus migrations don’t do anything. For instance, https://github.com/solidusio/solidus/blob/master/core/db/migrate/20160101010000_solidus_one_four.rb bails out entirely if a `spree_addresses` table exists. The code contains the comment:

```
Do not run it if one of the core tables
already exists. Assume the best.
```

I recently encountered a problem installing `solidus_easypost` that can be traced back to this migration not running and `assuming the best`.

Spree 0.9.0 has a migration to create the `spree_calculators` table, and it specifies that [a calculator may not be created without a `calculable` object](https://github.com/spree/spree_base_1_2/blob/master/db/migrate/20121119131006_spree_zero_nine_zero.spree.rb#L34-L40).

In Solidus, a calculator [_may_ be created without a `calculable` object](https://github.com/solidusio/solidus/blob/master/core/db/migrate/20160101010000_solidus_one_four.rb#L124-L125).

As a result of this, I am unable to run the `solidus_easypost` extension properly.

What I’m wondering is if there is a way that rather than having the Solidus migration bailing out entirely, we can find differences in a user’s db from what Solidus expects, and either change these or at least flag them for the user. I have been using Solidus since the initial release and had no idea until yesterday that it was possible/allowable to save a Calculator with no `calculable` object.

This makes me wonder what other things  in my db are configured differently from how a fresh solidus install would have them.

Is there another way we can do our migrations to keep users on the same page?

**Solidus Version**:
2.8.3

**Comment by aitbw** [comment]
For other users facing this issue, please check solidusio-contrib/solidus_easypost#35 for further reference.

**Comment by kennyadsl** [comment]
@brchristian I'm not sure there's a way to be sure all the stores databases are consistent, we should compare the generated schema of each solidus version with each possible ways users upgraded from spree to another spree version and from spree to solidus. 

Anyway, thanks for posting the issue. If you want to submit a PR that removes those database constraints we will think about merging it into master. The only thing that worries me at the moment is if some store re-added those constraints (maybe to use easypost?) and what would happen in that case. What do you think?

**Comment by brchristian** [comment]
@kennyadsl I agree with your analysis. It is a complex issue, and maybe it’s right to take the conservative/cautious approach that the solidus migrations take. I can see the argument for having a rake task or something that compares a user’s db schema with the standard schema for a particular solidus version. Does that seem useful?

At the same time, maybe it’s just fine it if is left up to individual site owners to periodically stay on top of this. We’ve been running our store since Spree 0.10 or something, and this is the first such issue we’ve had in a long while. In that case, we can close this issue but it will hopefully serve as a paper trail if other folks encounter a similar issue. It took me a while to realize that there was an important schema difference, and I would be happy to save someone else all that digging!

**Comment by kennyadsl** [comment]
> I can see the argument for having a rake task or something that compares a user’s db schema with the standard schema for a particular solidus version. Does that seem useful?

I see this more as an external tool (maybe already exists) that could also be used with Solidus. I'm not sure we have the skills required to maintain that kind of tool in core. Or maybe just a blog post? If you want to write something we could post it on the solidus.io website as well.

**Comment by brchristian** [comment]
Sounds good. I will close the issue here and if I can get such a tool working on our side, would be happy to share with the Solidus community.
