### ISSUE TITLE
Order state does not change after a customer return is received

### ISSUE THREAD

**Issue by spaghetticode** [solidusio/solidus#3198]
When an order has more than one line item, creating a return for all the items at once and setting the reception status to `Received` fails to change the order state to `Returned`, like it does with orders with one single line item. See attached screenshot.
 
**Solidus Version**:

master

**Screenshots**

<img width="979" alt="Schermata 2019-05-03 alle 17 22 38" src="https://user-images.githubusercontent.com/141220/57147972-ff8f9f00-6dc8-11e9-988f-90d2249c4406.png">

**Comment by jacobherrington** [comment]
@spaghetticode Can this issue be closed after #3199?

**Comment by spaghetticode** [comment]
@jacobherrington sure!
