### ISSUE TITLE
undefined local variable or method `meta_data_tags'

### ISSUE THREAD

**Issue by vinaymehta** [solidusio/solidus#3201]
I am new to solidus. Trying to integrate solidus in my existing rails application along with solidus_multi_domain. Below is my Gemfile

```
ruby '2.4.1'
gem 'rails', '~> 5.2.3'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'devise'
gem 'solidus', :git => 'https://github.com/solidusio/solidus', :branch => 'master'
# gem 'solidus_auth_devise'
gem 'solidus_multi_domain', :git => 'https://github.com/solidusio/solidus_multi_domain', :branch => 'master'
```

I ran install cmds like below
```
rails g spree:install --migrate=false --sample=false --seed=false --copy_views=true --user_class=User
rails g solidus_multi_domain:install
```

Now when I started my application, it gave me error as
`undefined local variable or method "meta_data_tags" for #<#<Class:0x007f8ac9c08b80>:0x007f8ac9bf37f8>`

Please help me how to fix this. Thanks in advance

**Comment by kennyadsl** [comment]
Hey @vinaymehta from your other issue (#3208) it seems that this has been fixed. Closing this but feel free to reopen if needed.
