### ISSUE TITLE
Promotion eligibility? usage count

### ISSUE THREAD

**Issue by cedum** [solidusio/solidus#3205]
When performing the eligibility check for a promotion, the usage limit check should not count the promotable that has been already applied for the promotion.
I suspect the same must be done also when re-computing the amounts in promo actions, otherwise, it sets them to zero.

Here's a test case (I did my best to explain it without letting my brain go into a loop 💥):
- Given I have an active promotion with 1 usage limit
- Given I have a completed order with the promotion above applied
- When I edit and save the promotion' adjustment and the promo has _0 usages left_
  - The adjustment is saved as _ineligible_ and amount set to `0`
  - The promotion changes to 1 usage left
- When I edit and save again the promotion' adjustment
  - The adjustment is saved as eligible and amount to the promo discount
  - The promotion changes back to "0 usages left"

Rinse and repeat to switch the adjustment to ineligible and back

Reproduced against solidus versions: `2.9.0.alpha` and `2.7.1`

**Comment by loicginoux** [comment]
Just checking but was your order completed ? it should only count promotion usage for completed order normally.

**Comment by cedum** [comment]
@loicginoux yes, tested it on a completed order (I've updated the issue description to reflect this)

**Comment by kennyadsl** [comment]
I think you are right, this happens because the eligibility check is done when there are no eligible "usage" left. I think we should add that "usage" to the count somehow to make it work.
