### ISSUE TITLE
ActiveModel::UnknownAttributeError: unknown attribute 'deleted_at' for Spree::User.

### ISSUE THREAD

**Issue by vinaymehta** [solidusio/solidus#3207]
My Gemfile looks like

```
ruby '2.4.1'
gem 'rails', '~> 5.2.3'
gem 'sqlite3'
gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'solidus', github: 'solidusio/solidus'
gem 'solidus_auth_devise'
gem 'solidus_multi_domain', :git => 'https://github.com/solidusio/solidus_multi_domain', :branch => 'master'
gem "awesome_print"
```
I ran cmds like
bundle exec rails g spree:install
bundle exec rails g solidus:auth:install
bundle exec rake railties:install:migrations

Now I am trying to load sample data, and getting ActiveModel::UnknownAttributeError: unknown attribute 'deleted_at' for Spree::User.
Please help how to fix this

**Comment by EmCousin** [comment]
@vinaymehta I'm getting the same issue. Did you solve it on your own? If so, what was the problem?

**Comment by piousbox** [comment]
3 years later, the problem seems to still be there. Spree v3.7.14.1
