### ISSUE TITLE
Solidus integration in already existing application

### ISSUE THREAD

**Issue by vinaymehta** [solidusio/solidus#3208]
Team,
I have an rails application using devise and other many gems. Now I want to integrate solidus with multi domain feature. I added gems in my Gemfile like below

```
ruby '2.4.1'
gem 'rails', '~> 5.2.3'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'devise'
gem 'solidus', github: 'solidusio/solidus'
gem 'solidus_multi_domain', :git => 'https://github.com/solidusio/solidus_multi_domain', :branch => 'master'
gem "awesome_print"
```

I ran spree generator cmds like
```
bundle exec rails g spree:install --migrate=false --sample=false --seed=false --copy_views=true --user_class=User
rails g solidus_multi_domain:install
rails g spree:custom_user User
```

Now When I restart e application, It goes to devise sessions controller but calls Spree Layout. Though I have mounted in rotes like
`mount Spree::Core::Engine, at: '/solidus'`

Also I have added following lines in my application controller
  ```
  include Spree::AuthenticationHelpers
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Common
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Store
  helper 'spree/base' 
```
And I have added following line in user model
`include Spree::UserMethods`

Tried to check the solution but can't find anything which helps. Please help me to get out of this. Thanks in advance.

**Comment by kennyadsl** [comment]
👋 Hey there,

I'm not sure to get which error or problem are you having, can you please be more specific about it?

**Comment by vinaymehta** [comment]
@kennyadsl I integrated Solidus gems into my already existing application. I wanted to use my old pages with their own application layouts and solidus pages with its own layout. But for all pages, it just uses spree_application as layout.
But Now I did a trick and added conditions on spree_application layout file itself and rendering layout files from partial in the same file.
But Now I see UI of store page is not so good. Do I need to include any bootstrap theme to make The UI beautiful or is there any other option available?

**Comment by kennyadsl** [comment]
@vinaymehta it's not easy to debug this issue without the proper context, some screenshot would help. Anyway, you don't need to add any theme, the default style should work and there are probably some issues in how you integrated solidus into your existing application.

I also suggest you join our [#support Slack channel](http://slack.solidus.io/) where you could find some more people willing to help.
