### ISSUE TITLE
Improve specs reliability when changing `Spree::Config.track_inventory_level`

### ISSUE THREAD

**Issue by spaghetticode** [solidusio/solidus#3219]
I recently imported some specs from Solidus in my codebase in order to broaden test coverage locally, before applying some patches to the original code. 

I only later realized that some of these specs changed the value of a relevant global setting without putting it back to the original value, thus creating random failures in other subsequent specs that relied on the original value of that parameter.

While this does not seem to affect Solidus test suite, I think the issue is still relevant as I believe it's generally good practice, after changing a global parameter, to put it back to the original value.
One example is [this spec](https://github.com/solidusio/solidus/blob/master/core/spec/models/spree/variant_spec.rb#L791):

```ruby
    context "inventory levels globally not tracked" do
      before { Spree::Config.track_inventory_levels = false }

      it "includes all variants" do
        expect( subject ).to include(in_stock_variant, backordered_variant, out_of_stock_variant)
      end
    end
```

and, more generally, all the times `Spree::Config.track_inventory_levels` is changed in a `before` block but not returned to the original value.

**Comment by kennyadsl** [comment]
I'm curious if it's possible that this is not affecting the test suite. Could it be that some database cleanup strategies (or similar resets) are taking care of resetting the preference before each test execution?

**Comment by spaghetticode** [comment]
@kennyadsl the reason is `reset_spree_preferences` being called in the `config.before` block for each `spec_helper.rb` file in Solidus. 

I think that while `reset_spree_preferences` is very convenient, it encourages what I would personally consider the bad practice of not returning the state of changed settings to the original values within each spec. But I understand that's just my personal point of view. 

Currently, removing `reset_spree_preferences` from `core/spec_helper.rb` yields a whopping `4033 examples, 1594 failures`, I'm not sure (yet) that the failures are all due to non-returned config changes. 

If removing `reset_spree_preferences` is feasible and makes sense, I would propose to add this helper method: 

```ruby
def with_spree_preferences(config_hash)
  original_config = {}

  config_hash.each do |preference, value|
    original_config[preference] = Spree::Config.send(preference)
    Spree::Config.send("#{preference}=", value)
  end

  yield

ensure
  original_config.each do |preference, value|
    Spree::Config.send("#{preference}=", value)
  end
end
```

to be used like this:

```ruby
it "sends no email" do
  with_spree_preferences send_core_emails: false do
    message = Spree::OrderMailer.confirm_email(order)
    expect(message.body).to be_blank
  end
end
```

that method can also be combined in `around` blocks like this, when we want to run multiple examples with the same config:

```ruby
around do |example|
  with_spree_preferences track_inventory_levels: false do
    example.run
  end
end
```

If you and other people in the core team think this may be a good improvement I'd be happy to work on it.

**Comment by kennyadsl** [comment]
We can discuss it in the next core team meeting. Anyway, another option could be using RSpec metatags, so we can probably have a simpler API, something like:


```
it "sends no email", with_spree_preferences: { send_core_emails: false } do
  message = Spree::OrderMailer.confirm_email(order)
  expect(message.body).to be_blank
end
```

but I'm not sure it applies to all the specs that use preferences: maybe in some specs the preference value is set in the `it` block dynamically?

**Comment by spaghetticode** [comment]
@kennyadsl I like the idea of RSpec metatags, but you're right there are instances where the preference value is dynamic. Just to list the first examples I met in Solidus core:

* [base_helper_spec.rb](https://github.com/solidusio/solidus/blob/95e6962301e6bdec0f2809ea88aa1c28a0c90463/core/spec/helpers/base_helper_spec.rb#L36)

* [address_spec.rb](https://github.com/solidusio/solidus/blob/95e6962301e6bdec0f2809ea88aa1c28a0c90463/core/spec/models/spree/address_spec.rb#L148)
* [country_spec.rb](https://github.com/solidusio/solidus/blob/95e6962301e6bdec0f2809ea88aa1c28a0c90463/core/spec/models/spree/country_spec.rb#L74)

So, if we go for metatags we'll need another option that works with dynamic values as well.
