### ISSUE TITLE
allow_guest_checkout doesn't do anything

### ISSUE THREAD

**Issue by RyanQuey** [solidusio/solidus#3255]
As far as I can tell, the `allow_guest_checkout` setting is not working. I'm not having success when I put this in my config file, and furthermore when I search the repository the only time that `allow_guest_checkout` seems to come up is in the setting definition file and in markdown files...which seems to mean spree sets the default for this setting but never uses it (?)

**Solidus Version**:

2.6.0

**To Reproduce**

1. Add `config.allow_guest_checkout = false` `to config/initializers/spree.rb`
2. Go to solidus frontend view, and without logging in add items to cart then go through checkout process. 

**Current behavior**

Currently, allows guests to purchase items in cart

**Expected behavior**

Redirects user to login page at a certain point, or at least prevents them from finishing checkout

**Comment by jacobherrington** [comment]
Thanks for reporting this issue @RyanQuey. I'm investigating this, will post here if I can confirm or find a quick fix!

**Comment by jacobherrington** [comment]
This bug doesn't seem to exist in master, I'm checkout on 2.6.0 at the moment. Are you using `solidus_auth_devise`?
