### ISSUE TITLE
Rename open/close_adjustments routes?

### ISSUE THREAD

**Issue by jordan-brough** [solidusio/solidus#326]
See discussion here: https://github.com/solidusio/solidus/pull/321#issuecomment-134731242

As of https://github.com/solidusio/solidus/pull/279 we're deprecating "open" and "close" on Adjustment in general.  Shall we also change the /open_adjustments and /close_adjustments routes to /finalize_adjustments and /unfinalize_adjustments?

**Comment by cbrunsdon** [comment]
I'm usually a fan of nesting resources where things make sense.

Rather then close_adjustments and unfinalize_adjustments I'd personally prefer ```/orders/:id/adjustments/finalize``` and ```/orders/:id/adjustments/unfinalize```
