### ISSUE TITLE
Integrate new API documentation in guides

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#3261]
Follow-up to #3252. 

We need to integrate the new API documentation into the current Guides to make it easily available to all users.

We need to take into account that at the moment we only have `v2.9` API version's documentation but in the future, we will have documentation for multiple versions available.

**Comment by minhlongdo** [comment]
Hi,

I am new on this project and would like to contribute to it, is this something I could pick up?

**Comment by kennyadsl** [comment]
@minhlongdo sure! Feel free to share your ideas about how to solve this issue before starting!
