### ISSUE TITLE
Split API documentation in multiple files

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#3263]
Follow-up to #3252. 

Right now we have a single 6k-row file (`openapi/api.oas2.yml`) that describes our API, we should investigate if makes sense and there is a way to split this file into multiple smaller ones, in order to make changes easier.

**Comment by JuanCrg90** [comment]
I'll be working on this I hope to send a PR soon

CC @aldesantis @kennyadsl

**Comment by kennyadsl** [comment]
@JuanCrg90 please take a look at instructions on how to work/contribute to API as well: https://github.com/solidusio/solidus/tree/master/api#documentation. We changed that after Spotlight Studio has been released and I'm concerned that it's not compatible anymore with splitting this file into multiple ones, but I could be wrong. Let us know!

**Comment by kennyadsl** [comment]
@aldesantis and I tried to change API documentation recently and we think this is no more needed now that we have Stoplight Studio. Going to close, thanks anyway @JuanCrg90
