### ISSUE TITLE
White font on white background in active tab on products

### ISSUE THREAD

**Issue by jsfan** [solidusio/solidus#3279]
In a vanilla production deployment, the active tab in the product view in the backend has a white font on white background.

**Solidus Version**:
2.9.0

**To Reproduce**
1. Open a product in the shop admin backend.
2. The `Product Details` tab which is selected is completely white.
3. Select any other tab.
4. The `Product Details` tab is now grey with the words `Product Details` shown on it in a darker shade of grey while the tab you just selected is all white now.

**Current behavior**
Tab label is invisible because foreground and background colour are the same.

**Expected behavior**
Background colour should have sufficient contrast against the background colour for the label to be legible.

**Comment by jsfan** [comment]
This actually seems to be the same on other tabbed views in the backend.

**Comment by jacobherrington** [comment]
@jsfan I believe this has been fixed on master in https://github.com/solidusio/solidus/pull/3269

Can you confirm that this is the same issue?

**Comment by octave** [comment]
@jacobherrington I think those are two different menu types /cc @mfrecchiami

**Comment by mfrecchiami** [comment]
Hi guys!
Maybe @jacobherrington wanted to refer to this merged PR: https://github.com/solidusio/solidus/pull/3274

Thanks for notifying me @octave !

**Comment by octave** [comment]
@mfrecchiami oh there you go! Thank you!

**Comment by kennyadsl** [comment]
We are going to release a new patch version with this fix as soon as possible.

**Comment by kennyadsl** [comment]
Closing since Solidus 2.9.1 has been released!
