### ISSUE TITLE
Dead Link For MenuItem Docs

### ISSUE THREAD

**Issue by skukx** [solidusio/solidus#3284]
**Solidus Version**:

NA

**To Reproduce**

1. Go to https://guides.solidus.io/developers/customizations/customizing-admin.html
2. Click the link to `See Spree::BackendConfiguration::MenuItem`
3. You will be taken to: http://docs.solidus.io/Spree/BackendConfiguration/MenuItem.html

`404 Not Found`

**Current behavior**

`404 Not Found`

**Expected behavior**

Either the link should be removed or the url needs to be updated.

**Comment by kennyadsl** [comment]
Thanks for pointing this out @skukx. It is my fault since I started to fix that docs issue and but I forgot to finish before merging the PR. For some reason, classes defined into `backend` are not present in the documentation, I need to investigate further.

**Comment by kennyadsl** [comment]
I found out that the issue is related to the docs site not being deployed correctly for a DNS issue. That's why we can't see new stuff in there. We are close to a solution for this.

**Comment by kennyadsl** [comment]
We fixed this, thanks @gmacdougall!
