### ISSUE TITLE
Heroku Build app is getting fail 

### ISSUE THREAD

**Issue by cybertricks** [solidusio/solidus#3285]
Heroku Build app is getting fail 

Error:

!     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
			Detected buildpacks: Ruby,Node.js
			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.6.2
-----> Installing dependencies using bundler 2.0.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
       Fetching gem metadata from https://rubygems.org/............
       Fetching rake 12.3.2
       Installing rake 12.3.2
       Fetching concurrent-ruby 1.1.5
       Fetching thread_safe 0.3.6
       Fetching minitest 5.11.3
       Installing minitest 5.11.3
       Installing thread_safe 0.3.6
       Installing concurrent-ruby 1.1.5
       Fetching builder 3.2.3
       Installing builder 3.2.3
       Fetching erubi 1.8.0
       Installing erubi 1.8.0
       Fetching mini_portile2 2.4.0
       Installing mini_portile2 2.4.0
       Fetching crass 1.0.4
       Installing crass 1.0.4
       Fetching rack 2.0.7
       Installing rack 2.0.7
       Fetching nio4r 2.3.1
       Fetching websocket-extensions 0.1.3
       Installing websocket-extensions 0.1.3
       Installing nio4r 2.3.1 with native extensions
       Fetching mini_mime 1.0.1
       Installing mini_mime 1.0.1
       Fetching arel 9.0.0
       Installing arel 9.0.0
       Fetching mimemagic 0.3.3
       Fetching execjs 2.7.0
       Installing execjs 2.7.0
       Installing mimemagic 0.3.3
       Fetching aws_cf_signer 0.1.3
       Installing aws_cf_signer 0.1.3
       Fetching bcrypt 3.1.12
       Installing bcrypt 3.1.12 with native extensions
       Fetching msgpack 1.2.10
       Installing msgpack 1.2.10 with native extensions
       Using bundler 2.0.2
       Fetching cancancan 2.3.0
       Installing cancancan 2.3.0
       Fetching method_source 0.9.2
       Installing method_source 0.9.2
       Fetching thor 0.20.3
       Installing thor 0.20.3
       Fetching climate_control 0.2.0
       Installing climate_control 0.2.0
       Fetching unf_ext 0.0.7.6
       Installing unf_ext 0.0.7.6 with native extensions
       Fetching mime-types-data 3.2019.0331
       Installing mime-types-data 3.2019.0331
       Fetching netrc 0.11.0
       Installing netrc 0.11.0
       Fetching coffee-script-source 1.12.2
       Installing coffee-script-source 1.12.2
       Fetching orm_adapter 0.5.0
       Installing orm_adapter 0.5.0
       Fetching ffi 1.11.1
       Installing ffi 1.11.1 with native extensions
       Fetching tilt 2.0.9
       Installing tilt 2.0.9
       Fetching kaminari-core 1.1.1
       Installing kaminari-core 1.1.1
       Fetching pg 1.1.4
       Installing pg 1.1.4 with native extensions
       Fetching puma 3.12.1
       Installing puma 3.12.1 with native extensions
       Fetching rails_serve_static_assets 0.0.5
       Installing rails_serve_static_assets 0.0.5
       Fetching rails_stdout_logging 0.0.5
       Installing rails_stdout_logging 0.0.5
       Fetching rb-fsevent 0.10.3
       Installing rb-fsevent 0.10.3
       Fetching state_machines 0.5.0
       Installing state_machines 0.5.0
       Fetching truncate_html 0.9.3
       Installing truncate_html 0.9.3
       Fetching solidus_support 0.2.2
       Installing solidus_support 0.2.2
       Fetching turbolinks-source 5.2.0
       Installing turbolinks-source 5.2.0
       Fetching tzinfo 1.2.5
       Installing tzinfo 1.2.5
       Fetching nokogiri 1.10.3
       Installing nokogiri 1.10.3 with native extensions
       Fetching i18n 1.6.0
       Installing i18n 1.6.0
       Fetching websocket-driver 0.7.0
       Installing websocket-driver 0.7.0 with native extensions
       Fetching mail 2.7.1
       Installing mail 2.7.1
       Fetching rack-test 1.1.0
       Installing rack-test 1.1.0
       Fetching sprockets 3.7.2
       Installing sprockets 3.7.2
       Fetching warden 1.2.8
       Installing warden 1.2.8
       Fetching autoprefixer-rails 9.5.1.1
       Installing autoprefixer-rails 9.5.1.1
       Fetching uglifier 4.1.20
       Installing uglifier 4.1.20
       Fetching marcel 0.3.3
       Installing marcel 0.3.3
       Fetching terrapin 0.6.0
       Installing terrapin 0.6.0
       Fetching mime-types 3.2.2
       Installing mime-types 3.2.2
       Fetching coffee-script 2.4.1
       Installing coffee-script 2.4.1
       Fetching bootsnap 1.4.4
       Installing bootsnap 1.4.4 with native extensions
       Fetching unf 0.1.4
       Installing unf 0.1.4
       Fetching rb-inotify 0.10.0
       Installing rb-inotify 0.10.0
       Fetching sassc 2.0.1
       Installing sassc 2.0.1 with native extensions
       Fetching rails_12factor 0.0.3
       Installing rails_12factor 0.0.3
       Fetching turbolinks 5.2.0
       Installing turbolinks 5.2.0
       Fetching activesupport 5.2.3
       Installing activesupport 5.2.3
       Fetching money 6.13.3
       Installing money 6.13.3
       Fetching handlebars_assets 0.23.3
       Installing handlebars_assets 0.23.3
       Fetching loofah 2.2.3
       Installing loofah 2.2.3
       Fetching domain_name 0.5.20180417
       Installing domain_name 0.5.20180417
       Fetching sass-listen 4.0.0
       Installing sass-listen 4.0.0
       Fetching rails-dom-testing 2.0.3
       Installing rails-dom-testing 2.0.3
       Fetching globalid 0.4.2
       Fetching activemerchant 1.95.0
       Installing globalid 0.4.2
       Fetching activemodel 5.2.3
       Installing activemodel 5.2.3
       Installing activemerchant 1.95.0
       Fetching carmen 1.1.2
       Installing carmen 1.1.2
       Fetching jbuilder 2.9.1
       Installing jbuilder 2.9.1
       Fetching monetize 1.9.1
       Installing monetize 1.9.1
       Fetching rails-html-sanitizer 1.0.4
       Installing rails-html-sanitizer 1.0.4
       Fetching http-cookie 1.0.3
       Installing http-cookie 1.0.3
       Fetching sass 3.7.4
       Installing sass 3.7.4
       Fetching activejob 5.2.3
       Installing activejob 5.2.3
       Fetching activerecord 5.2.3
       Installing activerecord 5.2.3
       Fetching paperclip 5.3.0
       Installing paperclip 5.3.0
       Fetching state_machines-activemodel 0.6.0
       Installing state_machines-activemodel 0.6.0
       Fetching actionview 5.2.3
       Installing actionview 5.2.3
       Fetching rest-client 2.0.2
       Installing rest-client 2.0.2
       Fetching acts_as_list 0.9.19
       Installing acts_as_list 0.9.19
       Fetching awesome_nested_set 3.1.4
       Fetching discard 1.1.0
       Installing awesome_nested_set 3.1.4
       Installing discard 1.1.0
       Fetching friendly_id 5.2.5
       Fetching kaminari-activerecord 1.1.1
       Installing friendly_id 5.2.5
       Installing kaminari-activerecord 1.1.1
       Fetching paranoia 2.4.2
       Installing paranoia 2.4.2
       Fetching state_machines-activerecord 0.6.0
       Fetching cloudinary 1.11.1
       Installing state_machines-activerecord 0.6.0
       Installing cloudinary 1.11.1
       Fetching actionpack 5.2.3
       Installing actionpack 5.2.3
       Fetching kaminari-actionview 1.1.1
       Installing kaminari-actionview 1.1.1
       Fetching paperclip-cloudinary 1.3.2
       Installing paperclip-cloudinary 1.3.2
       Fetching kaminari 1.1.1
       Installing kaminari 1.1.1
       Fetching actioncable 5.2.3
       Fetching actionmailer 5.2.3
       Installing actioncable 5.2.3
       Installing actionmailer 5.2.3
       Fetching activestorage 5.2.3
       Installing activestorage 5.2.3
       Fetching railties 5.2.3
       Installing railties 5.2.3
       Fetching sprockets-rails 3.2.1
       Installing sprockets-rails 3.2.1
       Fetching ransack 2.1.1
       Installing ransack 2.1.1
       Fetching rails 5.2.3
       Fetching coffee-rails 4.2.2
       Installing coffee-rails 4.2.2
       Installing rails 5.2.3
       Fetching responders 2.4.1
       Fetching font-awesome-rails 4.7.0.5
       Installing responders 2.4.1
       Installing font-awesome-rails 4.7.0.5
       Fetching jquery-rails 4.3.3
       Installing jquery-rails 4.3.3
       Fetching sass-rails 5.0.7
       Installing sass-rails 5.0.7
       Fetching solidus_core 2.8.3
       Fetching canonical-rails 0.2.5
       Installing canonical-rails 0.2.5
       Fetching devise 4.6.2
       Installing solidus_core 2.8.3
       Installing devise 4.6.2
       Fetching devise-encryptable 0.2.0
       Installing devise-encryptable 0.2.0
       Fetching solidus_api 2.8.3
       Fetching solidus_sample 2.8.3
       Installing solidus_api 2.8.3
       Installing solidus_sample 2.8.3
       Fetching solidus_auth_devise 2.1.0
       Installing solidus_auth_devise 2.1.0
       Fetching sassc-rails 2.1.1
       Installing sassc-rails 2.1.1
       Fetching solidus_backend 2.8.3
       Fetching solidus_frontend 2.8.3
       Installing solidus_frontend 2.8.3
       Installing solidus_backend 2.8.3
       Fetching solidus 2.8.3
       Installing solidus 2.8.3
       Bundle complete! 23 Gemfile dependencies, 117 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into `./vendor/bundle`
       Post-install message from i18n:
       
       HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
       But that may break your application.
       
       Please check your Rails app for 'config.i18n.fallbacks = true'.
       If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
       'config.i18n.fallbacks = [I18n.default_locale]'.
       If not, fallbacks will be broken in your app by I18n 1.1.x.
       
       For more info see:
       https://github.com/svenfuchs/i18n/releases/tag/v1.1.0
       
       Post-install message from handlebars_assets:
       Remember to rake assets:clean or rake assets:purge on update! this is required because of handlebars updates
       Post-install message from paperclip:
       ##################################################
       #  NOTE FOR UPGRADING FROM 4.3.0 OR EARLIER      #
       ##################################################
       
       Paperclip is now compatible with aws-sdk >= 2.0.0.
       
       If you are using S3 storage, aws-sdk >= 2.0.0 requires you to make a few small
       changes:
       
       * You must set the `s3_region`
       * If you are explicitly setting permissions anywhere, such as in an initializer,
         note that the format of the permissions changed from using an underscore to
         using a hyphen. For example, `:public_read` needs to be changed to
         `public-read`.
       
       For a walkthrough of upgrading from 4 to 5 and aws-sdk >= 2.0 you can watch
       http://rubythursday.com/episodes/ruby-snack-27-upgrade-paperclip-and-aws-sdk-in-prep-for-rails-5
       Post-install message from sass:
       
       Ruby Sass has reached end-of-life and should no longer be used.
       
       * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
         primary implementation: https://sass-lang.com/install
       
       * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
         sassc gem: https://github.com/sass/sassc-ruby#readme
       
       * For more details, please refer to the Sass blog:
         https://sass-lang.com/blog/posts/7828841
       
       Bundle completed (173.35s)
       Cleaning up the bundler cache.
-----> Installing node-v10.15.3-linux-x64
-----> Detecting rake tasks
 !
 !     Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.
 !     Activating bundler (2.0.1) failed:
 !     Could not find 'bundler' (2.0.1) required by your /tmp/build_ce057a120693846c64d551e719242cfe/Gemfile.lock.
 !     To update to the latest version installed on your system, run `bundle update --bundler`.
 !     To install the missing version, run `gem install bundler:2.0.1`
 !     Checked in 'GEM_PATH=/tmp/build_ce057a120693846c64d551e719242cfe/vendor/bundle/ruby/2.6.0', execute `gem env` for more information
 !     
 !     To install the version of bundler this project requires, run `gem install bundler -v '2.0.1'`
 !
/app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/helpers/rake_runner.rb:106:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
ensure you can run `$ bundle exec rake -P` against your app
and using the production group of your Gemfile.
Activating bundler (2.0.1) failed:
Could not find 'bundler' (2.0.1) required by your /tmp/build_ce057a120693846c64d551e719242cfe/Gemfile.lock.
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.1`
Checked in 'GEM_PATH=/tmp/build_ce057a120693846c64d551e719242cfe/vendor/bundle/ruby/2.6.0', execute `gem env` for more information
To install the version of bundler this project requires, run `gem install bundler -v '2.0.1'`
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/ruby.rb:866:in `rake'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails4.rb:84:in `block (2 levels) in run_assets_precompile_rake_task'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:134:in `log'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails4.rb:78:in `block in run_assets_precompile_rake_task'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:48:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:44:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails4.rb:77:in `run_assets_precompile_rake_task'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/ruby.rb:107:in `block (2 levels) in compile'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/ruby.rb:887:in `allow_git'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/ruby.rb:101:in `block in compile'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:48:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:44:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/ruby.rb:90:in `compile'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails2.rb:62:in `block in compile'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:48:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:44:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails2.rb:60:in `compile'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails3.rb:42:in `block in compile'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:48:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:44:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails3.rb:41:in `compile'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails4.rb:41:in `block in compile'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:48:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:44:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/rails4.rb:40:in `compile'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/bin/support/ruby_compile:20:in `block (2 levels) in <main>'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/base.rb:134:in `log'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/bin/support/ruby_compile:19:in `block in <main>'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:35:in `block in trace'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:35:in `trace'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/bin/support/ruby_compile:15:in `<main>'
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

**Comment by kennyadsl** [comment]
@cybertricks Hey there, thanks for reporting this issue. Can you please share which kind of Heroku build are you running? Is it the deploy button on the README or something else? Thanks in advance.

**Comment by kennyadsl** [comment]
I fixed the Heroku deploy button with https://github.com/solidusio/solidus-example-app/commit/261dee00022dcfa85b5909440b14d4d1fda9976b, it should work now.
