### ISSUE TITLE
Rspec capybara test

### ISSUE THREAD

**Issue by KimTiel** [solidusio/solidus#3290]
Im doing test script using rspec, capybara. and i got this error 
![Screenshot from 2019-08-01 18-57-37](https://user-images.githubusercontent.com/51952189/62354883-6cd5dc00-b540-11e9-9315-fc3469c01e2c.png)

**Comment by peterberkenbosch** [comment]
This is not part of Solidus, sorry but this should not be here. I noticed you also cross posted this problem in multiple Slack channels, the Support channel is the correct one, however this issue is not Solidus related, it looks like there is a problem in your Rails testing setup.

**Comment by jacobherrington** [comment]
We can follow up in the Slack channel, thanks!
