### ISSUE TITLE
Rename one letter variables

### ISSUE THREAD

**Issue by spaghetticode** [solidusio/solidus#3294]
Throughout Solidus' codebase there are many one-letter variables. These are not ideal as they are not expressive and meaningful for human beings. 

I think these should be replaced with human intelligible words, as @jacobherrington already did with some in #3292. 

This is a beginner-friendly issue, especially suited for anybody interested in starting helping with open source.

**Comment by mkoltonski** [comment]
Hi
I can handle it if you don't mind

**Comment by jacobherrington** [comment]
Hey @mkoltonski I would love to have your help with this. Here is a good trick to find these variables:

```
# in the solidus repository
gem install reek
reek --smell UncommunicativeVariableName
```

That should give you a list of them 👍

**Comment by mkoltonski** [comment]
#3304

**Comment by kennyadsl** [comment]
Thanks to @mkoltonski, @JDutil and @juliannatetreault for the work on this issue!
