### ISSUE TITLE
Shared Examples for Spree::Event::Subscriber

### ISSUE THREAD

**Issue by skukx** [solidusio/solidus#3298]
**Is your feature request related to a problem? Please describe.**

When writing specs for a subscriber which includes the `Spree::Event::Subscriber`, it would be nice to have `shared_examples`.

For example:
```ruby
module MySubscriber
  include Spree::Event::Subscription
end

RSpec.describe MySubscriber do
  it_behaves_like "a spree event subscriber"

 # Rest of specs
end
```

**Comment by waiting-for-dev** [comment]
Closing as we're now using [Omnes](https://github.com/nebulab/omnes) for the event bus. Please, see its [testing section in the docs](https://github.com/nebulab/omnes#testing).
