### ISSUE TITLE
Unable to calculate shipping rates for the selected items

### ISSUE THREAD

**Issue by memotoro** [solidusio/solidus#3315]
Hello. I found and issue with calculating shipping methods in v2.8.4 and v2.9.0. It seems that the shipping methods ids associated to a particular products are not loaded correctly.

**Solidus Version**:
v2.8.4 
v2.9.0
v2.9.1

**To Reproduce**

Admin Section
1. Bootstrap a solidus store with sample data.
2. Make sure all the shipping methods belong to the default store (e.g Sample Store)
3. Create a new shipping category (e.g Big Products)
4. Change or Create one shipping method associated to that new Category. (e.g UPS Ground (USD) to use only Big Products category) for the default store (e.g Sample Store)
5. Change any product (e.g Ruby on Rails Mug) to use the new shipping category (e.g Big Products)

Customer
1. Put in your basket two products, one with Default shipping category (e.g Ruby on Rails Stein) and the one with the new shipping category (e.g Ruby on Rails Mug)
2. Go through the checkout and fill the form with a valid delivery address and click 'Save and Continue' to go to Delivery Options
3. You get an error saying: 'We are unable to calculate shipping rates for the selected items.'

**Expected**

The expected result should be that the customer has two different shipping options, one for each product as each product has a different shipping category.

**Information**

Digging the code and the queries, it seems that the `estimator` line 58 https://github.com/solidusio/solidus/blob/v2.8/core/app/models/spree/stock/estimator.rb#L58 call the scope `available_to_store` with options `package.shipment.order.store`. For some reasons, the scope is not returning all the shipping associated to the store, it returns only a partial of that. As a result, not all the shipping rates are calculated.

If the shipping methods are not associated to a Store, it works, as the scope for the query in model `shipping_method` line 44 https://github.com/solidusio/solidus/blob/v2.8/core/app/models/spree/shipping_method.rb#L44 include all the shipping if no association with store is provided. Has anyone else seen these?

I found a way to patch, it seems that if I called `@order.store.shipping_method_ids` somewhere before the delivery state is change (e.g `before_delivery` method in `checkout_controller`https://github.com/solidusio/solidus/blob/v2.8/frontend/app/controllers/spree/checkout_controller.rb#L202), the query picks up all the shipping method associated to the store, not an elegant solution. Is the query being cached? Why is not picking up all the shipping methods? If I'm missing something in the config, please let me know. Any suggestions are welcome. Check the queries in the log to see the values for the shipping and you will see some of them are missing.

If anyone in the solidus team needs more details or the steps are not clear, please drop me a message here and I'll try to provide details. At the moment I have the patch that I mention but I wonder if anyone else has found it as I think it is pretty standard to have different shipping categories for different types of products. It should work OK unless I'm doing something wrong.

Regards

**Comment by kennyadsl** [comment]
Hey @memotoro, thanks for the detailed report. 

Do you think this issue could be related to https://github.com/solidusio/solidus/issues/2998 (and its possible fix https://github.com/solidusio/solidus/pull/3130)?

**Comment by memotoro** [comment]
Hello @kennyadsl 

Yes, the error is the same reported in https://github.com/solidusio/solidus/issues/2998 , however, I'm not using https://github.com/solidusio-contrib/solidus_multi_domain , so the issue is in solidus core.

I'll check in my own fork project the fix for it https://github.com/solidusio/solidus/pull/3130 proposed by 
@aitbw will fix it. I'll keep you updated

**Comment by kennyadsl** [comment]
@memotoro Hey there, did you have the chance to see if that PR fixes the issue?

**Comment by memotoro** [comment]
Hello @kennyadsl. I can confirm that the changes made on #3130 by @aitbw have fixed the issue I found and reported in this ticket. Sorry for the late reply. Regards
