### ISSUE TITLE
Error Could not find the inverse association for return_items (:inventory_unit in ReturnItem)

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#3319]
I am getting this error after upgrade solidus, 
Could not find the inverse association for return_items (:inventory_unit in ReturnItem)

Maybe we have to specify the key in this relation of model 'InventoryUnit' ?
 has_many :return_items, inverse_of: :inventory_unit, dependent: :destroy

**Solidus Version**:
Master

**To Reproduce**
1. Go to admin/orders
2. Click on an order with a rma created
3. I am not able to display the order only the error

**Comment by kennyadsl** [comment]
@sechix Hey there 👋, thanks for your report! 
Can you please also tell which version you upgraded from?

**Comment by kennyadsl** [comment]
@sechix I'm trying to replicate this issue but everything seems to work fine in master. Can you please share also the list of extensions you are using?

**Comment by sechix** [comment]
Hi @kennyadsl when I deploy to staging it works, so has to be something in my localhost dB. Thanks
