### ISSUE TITLE
bundle exec rails generate spree:install Traceback error

### ISSUE THREAD

**Issue by aroojahmad** [solidusio/solidus#3329]
Error is as follows:

Traceback (most recent call last):
	29: from bin/rails:4:in `<main>'
	28: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	27: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	26: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	25: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	24: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	23: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	22: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	21: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	20: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
	19: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
	18: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
	17: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	16: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	15: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	14: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	13: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	12: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/command/actions.rb:22:in `require_application!'
	11: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	10: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	 9: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	 8: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	 7: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	 6: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 5: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	 4: from /Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 3: from /Users/arooj/Desktop/projects/volumeusa/volumeusacom/config/application.rb:9:in `<main>'
	 2: from /Users/arooj/Desktop/projects/volumeusa/volumeusacom/config/application.rb:10:in `<module:Volumeusacom>'
	 1: from /Users/arooj/Desktop/projects/volumeusa/volumeusacom/config/application.rb:12:in `<class:Application>'
/Users/arooj/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/application/configuration.rb:118:in `load_defaults': Unknown version "6.0" (RuntimeError)

**Comment by BenMorganIO** [comment]
Judging by the `Unknown version "6.0"` I would assume you've got a Rails 6 setup going, but Solidus currently supports Rails 5.2.

**Comment by ericsaupe** [comment]
`master` currently supports Rails 6.

@aroojahmad what version of Solidus are you trying?

**Comment by aroojahmad** [comment]
@ericsaupe I got frustrated and deleted the repo, gonna try again using 'getting started' docs

https://guides.solidus.io/developers/getting-started/first-time-installation.html

will post up on solidus slack with any updates

**Comment by Yesh123456** [comment]
Hey have you found the solution after reinstalling bcoz even i am stuck in same situation
