### ISSUE TITLE
"New Store Credit Reason" button has wrong translations. it says "New Adjustment Reason" instead.

### ISSUE THREAD

**Issue by dimidev** [solidusio/solidus#3344]
i think there is an error at http://localhost:3000/admin/store_credit_reasons . if you check upright the button says "New Adjustment Reason", but it must be "New Store Credit Reason" . if you click it, it works fine. you redirected to correct page.

**Solidus Version**:
2.9.1

**To Reproduce**
1. Go to 'Sidebar Menu' and click on 'Settings'
2. Go and click on tab "Store Credit Reasons"
3. When it loads look upright to the button. it must be "New Store Credit Reason" but it says "New Adjustment Reason".
4. If you click it, it works fine. it redirects to proper page

**Screenshots**
[https://pasteboard.co/IyjiOLa.png](https://pasteboard.co/IyjiOLa.png)

**Comment by amingilani** [comment]
Dibs — unless I can't fix it in under two hour, in which case, my dibs has expired and anyone else seeing this please take it.

**Comment by spaghetticode** [comment]
The issue has already been fixed with 45fcce61c543926bc766a9b6f395c5b4c759d0e5 . In order to get the fix, you may want to upgrade your Solidus version to `v2.10.0.beta1` or use `master`.

**Comment by sabunt** [comment]
Plz close issue
