### ISSUE TITLE
Locale spelled wrong for Logged In Successfully

### ISSUE THREAD

**Issue by nolantait** [solidusio/solidus#3345]
The locale for t('spree.logged_in_succesfully') is spelled wrong. Just had a time trying to figure out why it wasn't working. Successfully should have two s.

**Solidus Version**:
2.9.1

**To Reproduce**
1. Start an application and try to use the In8n translation for spree.logged_in_successfully in console.

**Comment by askl56** [comment]
@jacobherrington Can we close this topoic?
