### ISSUE TITLE
Ability to unset a taxon icon

### ISSUE THREAD

**Issue by octoxan** [solidusio/solidus#3349]
**Is your feature request related to a problem? Please describe.**
Copied the existing icon functionality to let clients upload a banner for taxons as well, and realized after an icon is uploaded, there's no way besides editing the database for a user to remove the icon. You could replace the icon, but sometimes this may not be wanted. For example the site I'm working on has a grid of the taxons with an icon.

**Describe the solution you'd like**
Perhaps a little red remove icon + text below the existing icon.

**Describe alternatives you've considered**
Building a one off route that does this and a link to it. My Rails skills aren't there yet though.

**Comment by johnny243** [comment]
Anyone working on this issue? @octoxan @jacobherrington I'd like to give it a shot

**Comment by octoxan** [comment]
Go for it! I'm too new to Rails to really know the best way to implement
this personally, but would love to see how someone does it.

**Comment by seand7565** [comment]
#3446 should have closed this issue
