### ISSUE TITLE
Add tooltips on calculators in the admin panel

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#3363]
Currently what calculators do is not clear in our admin panel. I think we could easily add a tooltip when calculators are displayed to tell users how to use them. It's quite easy to get some text for them since we have calculators well described in our Guides:

- https://guides.solidus.io/developers/calculators/promotion-calculators.html#promotion-calculators
- https://guides.solidus.io/developers/calculators/shipping-calculators.html#shipping-calculators
- https://guides.solidus.io/developers/calculators/tax-calculator.html#tax-calculator

**Comment by octoxan** [comment]
I'll jump on this tonight or tomorrow night.

**Comment by seand7565** [comment]
Looks like this one has been solved by #3382 - can we close this?
