### ISSUE TITLE
Module.prepend does not work nicely with included modules

### ISSUE THREAD

**Issue by spaghetticode** [solidusio/solidus#3371]
`Module.prepend` is currently the official way to quickly and easily patch Solidus in order to customize behavior, and its a much better solution that `class_eval` that was used previously. 

Unfortunately, `#prepend` does not work nicely with modules, especially with the ones that  `extend ActiveSupport::Concern`.

**Solidus Version**:

all

**To Reproduce**

Let's consider one use case from my IRL experience. I need to change the behavior of `Spree::Core::ControllerHelpers::Auth#store_location`, a module that is included in many Solidus controllers. 

Let's try with `prepend`:

```ruby
module M
  def store_location
    "M store location"
  end
end

Spree::Core::ControllerHelpers::Auth.prepend M

Spree::BaseController.new.store_location
# => NoMethodError: undefined method `host' for nil:NilClass
# this error means it's still using the original version of the method
```

Reincluding the module in `Spree::BaseController` won't help: 

```ruby
Spree::BaseController.include Spree::Core::ControllerHelpers::Auth

Spree::BaseController.new.store_location
# => NoMethodError: undefined method `host' for nil:NilClass
```
One way to make this work is include directly `M`:

```ruby
Spree::BaseController.include M
Spree::BaseController.new.store_location
# => "M store location"
```

but IMHO that defeats the purpose of extending the behavior of the original module. 

On the other hand, good old `class_eval` works as a charm:

```ruby
Spree::Core::ControllerHelpers::Auth.module_eval do
  def store_location
    "patched store location"
  end
end

Spree::BaseController.new.store_location
# => "patched store location"
```

I think that, as we moved away from `class_eval` with Solidus classes, we need to move away also from `module_eval` (`class_eval` and `module_eval` are just aliases) and find better ways  to extend Solidus modules.

**Comment by dportalesr** [comment]
I think that `Spree::Core::ControllerHelpers::Auth.extend M` is supposed to be `Spree::Core::ControllerHelpers::Auth.prepend M`

**Comment by gsmendoza** [comment]
We recently encountered this issue when we monkey-patched `Spree::BaseHelper` in Solidus Demo. Please see PR https://github.com/solidusio/solidus-demo/pull/103.

In our investigation of the issue, we learned that if you prepend a module B to another module A, the prepended module B won't be added to the ancestors of classes that have already included module A prior to the prepend. To illustrate:

```rb
irb(main):001:0> module A
 def a
   puts 'a'
 end
end
=> :a
irb(main):006:0> class B
 include A
end
=> B
irb(main):010:0> module C
 def a
   puts 'c'
 end
 A.prepend self
end
=> A
irb(main):017:0> class D
 include A
end
=> D
irb(main):021:0> B.new.a
a
=> nil
irb(main):022:0> D.new.a
c
=> nil
irb(main):023:0> B.ancestors
=> [B, A, Object, Kernel, BasicObject]
irb(main):024:0> D.ancestors
=> [D, C, A, Object, Kernel, BasicObject]
```

Both classes `B` & `D` include `A`, but only `D` takes the new behavior as it's the one defined after we call `prepend`.

In our discussions of https://github.com/solidusio/solidus-demo/pull/103, we suspect that Rails has already included `Spree::BaseHelper` in the views before it prepended our monkey-patch to the module. As a result, the views do not load our overridden helper.

Interestingly, we also learned that class inheritance does not exhibit this behavior:

```ruby
class A
  def a
    puts 'a'
  end
end

class B < A
end

module C
  def a
    puts 'c'
  end

  A.prepend self
end

class D < A
end

B.new.a
D.new.a
puts "B.ancestors: #{B.ancestors}"
puts "D.ancestors: #{D.ancestors}"
```

Here's the result:

```
c
c
B.ancestors: [B, C, A, Object, Kernel, BasicObject]
D.ancestors: [D, C, A, Object, Kernel, BasicObject]
```

This time, both classes `B` & `D` have taken the new behavior, even if `B` was defined before we called `prepend`.

**Comment by gsmendoza** [comment]
FYI, we've also posted about this in https://stackoverflow.com/questions/70709163/is-there-a-reason-why-rubys-prepend-behaves-differently-when-used-with-modules?noredirect=1#comment125018214_70709163.

**Comment by gsmendoza** [comment]
Per https://stackoverflow.com/a/70782216/65925, we have manually confirmed that the issue no longer exists in Ruby 3.0.

**Comment by waiting-for-dev** [comment]
> Per https://stackoverflow.com/a/70782216/65925, we have manually confirmed that the issue no longer exists in Ruby 3.0.

That's great news! Should we close this issue, now?

**Comment by gsmendoza** [comment]
Yes for me! @spaghetticode ?

**Comment by gsmendoza** [comment]
Wait. Take note though that we can't verify the fix yet on Solidus because AFAIk Solidus is not yet tested on Ruby 3.

**Comment by waiting-for-dev** [comment]
> Wait. Take note though that we can't verify the fix yet on Solidus because AFAIk Solidus is not yet tested on Ruby 3.

Well, that's not part of Solidus's own behavior, right? As long as we've updated the docs, I think we should be fine!

**Comment by gsmendoza** [comment]
> Well, that's not part of Solidus's own behavior, right? As long as we've updated the docs, I think we should be fine!

Hehe.. Cool with me!

**Comment by kennyadsl** [comment]
We mentioned this on the customization instructions in the edgeguides: https://edgeguides.solidus.io/customization/customizing-the-core#using-overrides. I think we can close this issue. cc @spaghetticode @gsmendoza

**Comment by spaghetticode** [comment]
@gsmendoza @waiting-for-dev I'm very happy to read that this is now fixed on ruby 3.x 💯 🎉
