### ISSUE TITLE
Sprockets 4 compatibility

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#3374]
Sprockets 4 requires a configuration manifest file to be created in the application. This is fine for new stores but it's not working with our DummyApp at the moment since it is an in-memory application, and not a real application on the filesystem, like most engines do in `spec/dummy` with `rake test_app`.

At the moment, [Sprockets 4 is not able to allow setting a custom location](https://github.com/rails/sprockets-rails/issues/369) for this configuration manifest file and it is looking for our manifest in `spec/dummy/app/assets/config/manifest.js`, which does not exist. Spec fails consequently.

I'm trying to propose a change to sprockets-rails that allows setting a custom location for the manifest with [this PR](https://github.com/rails/sprockets-rails/pull/446), even because there's a Rails config named `config.assets.manifest`, which I think is only used for this reason, but I'm not super sure since I can't find a lot of documentation around.

The only alternative solution I can think about is locking Sprockets to 3.x on all the currently supported Solidus versions.

**Comment by elia** [comment]
Fixed by #3379
