### ISSUE TITLE
RFC: Deprecate And Remove Spree.routes

### ISSUE THREAD

**Issue by jarednorman** [solidusio/solidus#3405]
As documented in #2113, the route helpers in `Spree.routes` are poorly and inconsistently named. [Hawth also stopped using them in new admin code](https://github.com/solidusio/solidus/issues/2113#issuecomment-317821762), instead preferring to use `pathFor` directly. As mentioned in #2113, this is a pretty low priority issue, but making a decision allows us to close the old issue and move on with a solution.

**Solution:**
Deprecate `Spree.routes` and replace all uses of it with `pathFor`. Remove it in a future major version. I prefer this solution because `Spree.routes` doesn't provide much value and is a small burden to keep up to date.

**Alternative:**
Warn users that we will be making `Spree.routes` consistent with the Rails route naming. Update all the names in the next major version. Given that _this is still a breaking change_, I'm less a fan of it, but if people truly find `Spree.routes` valuable, then I'm not opposed to keeping it.

**Comment by jarednorman** [comment]
Now that we have this issue, someone with permissions can close #2113.

**Comment by seand7565** [comment]
#3605 is merged and should close this issue! 🎉
