### ISSUE TITLE
Bundler could not find compatible versions for gem "ruby"

### ISSUE THREAD

**Issue by la-ruby** [solidusio/solidus#3411]
Any reason [this file](https://github.com/solidusio/solidus/blob/master/solidus.gemspec) doesn't say 2.5 as the minimum requirement for the master branch?

**To Reproduce**

```ruby
$ $ ruby -v
ruby 2.4.7p357 (2019-08-28 revision 67796) [x86_64-darwin19]
$ DB=postgresql bundle install
Fetching https://github.com/jejacks0n/teaspoon.git
The dependency jruby-openssl (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency activerecord-jdbcsqlite3-adapter (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/..............
Fetching gem metadata from https://rubygems.org/..............
Resolving dependencies...
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    pry was resolved to 0.12.2, which depends on
      ruby (>= 1.9.3)

    rails (~> 6.0.0) was resolved to 6.0.0, which depends on
      ruby (>= 2.5.0)
```

**Comment by kennyadsl** [comment]
Yes, Solidus supports both Rails 6 and 5.2. 

Rails 5.2 does not need Ruby 2.5.x so we can't bump the Ruby dependency to that Ruby version. Does it make sense?

**Comment by la-ruby** [comment]
That makes sense, thanks! followup:

So is a newcomer reading the [README.md](https://github.com/solidusio/solidus/blob/master/README.md) is **supposed** to get that error?
It can be argued that

    bundle exec rake sandbox

is creating the inappropriate rails version for my ruby. It created a rails 6 app, when perhaps it should have created a 5.x app for the ./sandbox/ folder.

**Comment by kennyadsl** [comment]
Yes, you are right. We should update the README with this thing. I didn't think that we could create two different sandbox applications based on the host Ruby version, that's a good idea. I'm creating a couple of issues to track these. Thanks!

**Comment by kennyadsl** [comment]
I've opened #3412 so I think we can safely close this one, thanks a lot for reporting the issue, @la-ruby!.
