### ISSUE TITLE
Turbolinks installation documentation is out of date

### ISSUE THREAD

**Issue by pedantic-git** [solidusio/solidus#3440]
Hi Solidus team. I'm an old-hand at Rails but new to Solidus. I just joined the Slack and was advised to report this on Github.

The Turbolinks installation documentation at [Getting started: Installation instructions](https://guides.solidus.io/developers/getting-started/installation-options.html) is out of date.

It says:

> Then, enable Turbolinks in the backend by appending these lines to the JavaScript manifest at `vendor/assets/spree/backend/all/js`:
>
> ```javascript
> //= require turbolinks
> //= require backend/app/assets/javascripts/spree/backend/turbolinks-integration.js
> ```

There are three things that need updating:

1. The file that needs changing is `vendor/assets/javascripts/spree/backend/all.js`
2. The integration file is now just `spree/backend/turbolinks-integration.js` because spree_backend is a gem in its own right.
3. The order here matters - the `//= require turbolinks` needs to come before `//= require spree/backend` and the integration file needs to come after. I was experiencing bugs before I changed this order because the `Spree.ready` function from spree_core was assuming Turbolinks wasn't installed.

**Solidus Version**: 2.10.0.beta1

**Comment by kennyadsl** [comment]
@pedantic-git I've opened #3444, let me know if it works now and looks comprehensible for you. Thanks again.

**Comment by pedantic-git** [comment]
Apart from one duplicated line it looks good!
