### ISSUE TITLE
Why is `Spree::Address.build_default` not used?

### ISSUE THREAD

**Issue by delphaber** [solidusio/solidus#3441]
Hey! This is not a feature request actually. But it's not a bug either ;)

I've noticed that [here](https://github.com/solidusio/solidus/blob/v2.9.3/frontend/app/controllers/spree/checkout_controller.rb#L197) in the checkout controller Solidus is building a new address with a default attribute (`country_id`).

I'm wondering why can't we use [`Spree::Address.build_default`](https://github.com/solidusio/solidus/blob/v2.9.3/core/app/models/spree/address.rb#L33) in the controller? 🤔 

Is there a reason? If not, would you consider a PR for this? :)

**Comment by kennyadsl** [comment]
I think you are right @delphaber, I couldn't find a good reason browsing the git history either. So I think it would be a good PR. 

Thanks for spotting it!

**Comment by softr8** [comment]
I think it has to be with the state select box, it needs to be initialized with the current country, will try to confirm it later
