### ISSUE TITLE
Explore using ApplicationRecord instead of ActiveRecord::Base as models parent class

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#3450]
Rails 5 introduced the `ApplicationRecord` concept and started suggesting using it instead of inheriting from `ActiveRecord::Base` directly. 

This is to allow developers to apply some configurations to all the application models without the need to monkey-patch `ActiveRecord::Base`, since `ApplicationRecord` should be present in the host application, and it is added by the Rails generator during the installation (after Rails 5, so stores that started from Rails 4 and upgraded may not have it yet). 

If we want to be aligned with what Rails does, we should start relying on it, being sure our host applications have the `ApplicationRecord` file in place, in order to avoid breaking them. 

*References*

- https://github.com/rails/rails/pull/22567
- https://github.com/solidusio/solidus/blob/6aa743680e17287e177893fb203a8dbc9bc40803/core/app/models/spree/base.rb#L3

**Comment by tvdeyen** [comment]
I like that 👍

**Comment by jarednorman** [comment]
While we didn't do _exactly_ what this ticket outlines, I think with #3476 we can close this.
