### ISSUE TITLE
Is it possible to remove Registration Page?

### ISSUE THREAD

**Issue by ylluminarious** [solidusio/solidus#3468]
In our online shop, our client wants to have it so that when a user checks out, they do not need to register. Currently they have to fill out the Registration Page form before checking out:

![image](https://user-images.githubusercontent.com/4912973/71700615-0d038b80-2d93-11ea-8463-8a5ad45b9403.png)

This form is a bottleneck that causes some users to abort the checkout process. We are aware that there is an option for the user to checkout as a guest, but this apparently requires entering an email address. Ideally, we would like to eliminate this page from the checkout process altogether. Is there a way for us to do this? If not, is there a way to automatically register the user as a guest with as little friction as possible?

**Comment by fastjames** [comment]
We don't have a registration page in our current store, and I think we accomplished this by setting the following config variable in `config/initializers/spree.rb`:

```
Spree::Auth::Config[:registration_step] = false
```

That's from a quick skim of our code, you should probably look that key up in this repo and see what effects it has.

**Comment by ylluminarious** [comment]
@fastjames Fantastic, thank you. This appears to have worked. Are there any gotchas or caveats I need to be aware of by enabling this option? Searching for `registration_step` in this repository yields no results, but upon searching in my local gem directory, I found that the string was defined and used in [`solidus_auth_devise`.](https://github.com/solidusio/solidus_auth_devise) I searched for it there and [found a few results,](https://github.com/solidusio/solidus_auth_devise/search?q=registration_step&unscoped_q=registration_step) but no real description or details of how it works or what it does exactly.

**Comment by fastjames** [comment]
I can't think of anything offhand, other than maybe how it interacts with some solidus extensions. For example, in `solidus_virtual_gift_card` I think it tries to require a login when purchasing a gift card so you'll have to work around that. I fully support your goal of removing everything that stands between the customer and the buy button.

**Comment by ylluminarious** [comment]
@fastjames Great, thanks for the info. We'll have to keep that in mind for any extensions we use. I'll go ahead and close this now since your feedback has solved the problem.
