### ISSUE TITLE
Error trying to clon a product

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#3469]
I get an error trying to clon a product from admin -> products

**Solidus Version**:
Last master version

1. Go to admin -> products
2. Click on  icon 'copy'

**Current behavior**
Get error : 
ActiveRecord::RecordInvalid in Spree::Admin::ProductsController#clone
Valudation failed: Images is not valid, Master images is not valid

**Expected behavior**
Clone product

**Desktop (please complete the following information):**
 - Heroku
 - Browser chrome

**Additional context**
I have the images connected to s3 with CDN

**Comment by jarednorman** [comment]
Can you provide any more info here? Did you solve or make any progress?

**Comment by sechix** [comment]
Its solved.  Close the issue, thanks!
