### ISSUE TITLE
Selected shipping methods are not preserved when proposed shipments are generated

### ISSUE THREAD

**Issue by richardnuno** [solidusio/solidus#347]
Calling [create_proposed_shipments](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order.rb#L518) on an order when shipments already exist, does not preserve the selected shipping methods.

Example scenario:
A store with two shipping methods, 2-day and overnight.
2-day is less expensive than overnight.
A user creates an order and chooses upgraded shipping to overnight.
Calling `create_proposed_shipments` on the order would assign 2-day shipping to the newly generated shipments.

Maintaining the selected shipping method becomes even more challenging if a store wanted to allow different shipping methods for different shipments within the same order.

**Comment by mamhoff** [comment]
The referenced PR has not been merged, and from what I see Solidus still does not preserve selected shipping methods when running `Spree::Order#create_proposed_shipments`. I would be a nifty feature to have, but likely add more complexity to the Stock coordinator. There has not been any activity on this feature for more than a year now; closing.
