### ISSUE TITLE
Put a live demo

### ISSUE THREAD

**Issue by Henrik41** [solidusio/solidus#3475]
I am a new user. I cannot find a demo! 
Suggestion: Either put a demo on your website or have some kind of showcase so new user can see how it looks like.
Going through Heroku just to have a demo install is not adequate as many of us don't use Heroku.

**Comment by EduardoGHdez** [comment]
There is another alternative 😄 
> You can use Docker to run a demo on your local machine. Run the following command to download the image and run it at `http://localhost:3000.`

`docker run --rm -it -p 3000:3000 solidusio/solidus-demo:latest`

**Comment by seandawes** [comment]
@Henrik41 Happy to share some stores that are on solidus as examples if you want.

**Comment by elia** [comment]
There's also the heroku button linked on the README that will deploy a fully functional solidus store:

https://github.com/solidusio/solidus#demo

**Comment by seand7565** [comment]
I'd like to work on this one - I think a demo site is a great idea. Not just so people get a feel for how the frontend and backend operate, but so we can gather metrics through analytics for the platform as a whole. Seeing what people visit on the demo site could give us some insight into what people are looking for in a platform.

**Comment by seand7565** [comment]
So I'm working on this now - at this repo -> https://github.com/seand7565/solidus-sample

The goals for this project are:
* Allow users to access the backend without having to log in, but limiting/removing the ability to change things (this is just a demo, after all)
* Add a "User Guide" that can serve as training material on how to use Solidus. Mostly relevant on the backend, but currently I've got it displayed on frontend as well.
* Create a "Guided Tour" of Solidus that will take you through some of the benefits of using that platform and show off what makes us special, and if possible, how extensible the platform is. 

You can see some of this in action here, though it's _far_ from being done. http://solidemo.herokuapp.com/

**Comment by aldesantis** [comment]
Closing this, @seand7565's demo is awesome!
