### ISSUE TITLE
Spree::Event Support regex/wildcard

### ISSUE THREAD

**Issue by skukx** [solidusio/solidus#3481]
**Is your feature request related to a problem? Please describe.**

Right now it is not possible to subscribe to all spree events:

```ruby

Spree::Event.subscribe('*') { Analytics.report(event) }

# Or

Spree::Event.subscribe(/.*/) { |event| Analytics.report(event) }
```

You can do a workaround and go directly through `ActiveSupport::Notifications` or whatever the interface but should probably be supported through spree events.

**Describe the solution you'd like**

The wildcard is going to specific to the adapter being used so whatever the final name becomes will need to be parsed at the adapter level.

For example: In order to match multiple events with `ActiveSupport::Notifications`, a regex object is required. However with `Redis`, a string is sufficient.

Redis: `'*.spree'`
Rails: `/.*\.spree$/`

**Additional context**

**Comment by skukx** [comment]
One of the obstacles I'm noticing with this is the [`Spree::Event.name_with_suffix`](https://github.com/solidusio/solidus/blob/master/core/lib/spree/event.rb#L109-L111) method.

The method checks to see if the suffix is already contained, if it isn't then appends the suffix.

However when looking at a regexp object, this gets messy to if the suffix is included in the regexp.

Is it ok to exclude the suffix and expect users to include it in their regexp?

**Comment by skukx** [comment]
## Option 1
```ruby
module Spree::Event
    # ...

    # Resolve Event Name with suffix
    #
    # @param [String, Regexp] name The event name
    # @return [String, Regexp]
    #
    # @example Get name with suffix
    #   self.name_with_suffix('foo')
    #   #=> 'foo.spree'
    #
    # @example Get name with included suffix
    #   self.name_with_suffix('foo.spree')
    #   #=> 'foo.spree'
    #
    # @example Get name with suffix using regexp
    #   self.name_with_suffix(/foo/)
    #   #=> /foo\.spree$/
    #
    # @example When using regexp, don't include the suffix
    #   self.name_with_suffix(/foo\.spree$/)
    #   #=> /foo\.spree$\.spree$/
    #
    def name_with_suffix(name)
      if name.is_a?(Regexp)
        return Regexp.new(name.source + suffix_as_regexp.source)
      end

      name.end_with?(suffix) ? name : [name, suffix].join
    end

    def suffix_as_regexp
      /#{Regexp.quote(suffix)}$/
    end

    # ...
end
```

**Comment by skukx** [comment]
## Option 2

Move logic to adapter

```ruby
module Spree::Event
  # ...

  def name_with_suffix(name)
    adapter.resolve_event_name(name, suffix)
  end
end

module Adapters::ActiveSupportNotifications
  WILDCARD = '*'

  # ...

  # Convert event name to the proper format for the adapter
  def resolve_event_name(name, suffix)
    name = name.end_with?(suffix) ? name : [name, suffix].join

    return name unless name.include?(WILDCARD)

    # convert to regexp

    regex_str = name.split('*').
        map { |value| Regexp.quote(value) }.
        inject { |compound, value| compound + '.*' + value }

   Regexp.new("#{regex_str}$")
  end
end
```

```
adapter.resolve_event_name('foo', '.spree') # => 'foo.spree'
adapter.resolve_event_name('foo.spree', '.spree') #=> 'foo.spree'
adapter.resolve_event_name('*.spree') #=> /.*\.spree$/
adapter.resolve_event_name('foo.*.spree' #=> /foo\..*\.spree$/
```

**Comment by skukx** [comment]
Obviously would need a bit of cleanup, but option 2 just assumes the event will always be a string, and in the ActiveSupportNotifications adapter it converts the wildcard string to regex

**Comment by spaghetticode** [comment]
@skukx I think that the best solution is to delegate to the adapter what can be subscribed (strings, regexp or any other supported types).

I opened this [PR](https://github.com/solidusio/solidus/pull/3512) with a possible implementation, it seems to work fine to me, let me know if it works on your side too and matches your needs.

**Comment by skukx** [comment]
Sorry for the confusion, what I mean is instead of conditionally appeneding the suffix, we always append the suffix.

```ruby
# Conditional
name_with_suffix('my_event.spree')
#=> 'my_event.spree'
```

Changes to:

```ruby
# Always
name_with_suffic('my_event.spree')
#=> 'my_event.spree.spree'
```

I'm ok with the current code as is though.

**Comment by waiting-for-dev** [comment]
That was implemented in https://github.com/solidusio/solidus/pull/3512 for the legacy adapter. However, we're now using [Omnes](https://github.com/nebulab/omnes) for pub/sub. Most of the time, [`#subscribe_to_all`](https://github.com/nebulab/omnes#global-subscriptions) will be what's needed. Otherwise, you can use a [custom matcher](https://github.com/nebulab/omnes#custom-matcher-subscriptions). However, notice that using regex subscribers is dangerous as you can end up subscribing unwillingly to some events.
