### ISSUE TITLE
Adding any custom promotion rule next to a taxon filter rule and use per line-item-adjustment breaks the whole promotion

### ISSUE THREAD

**Issue by b1nary** [solidusio/solidus#3500]
When i add any custom promotion rule next to a taxon filter promotion rule and use a line-item-adjustment action the promotion breaks and returns the following when applied:

```json
{ "success":null,
  "error":"This coupon code could not be applied to the cart at this time.",
  "successful":false,
  "status_code":"coupon_code_unknown_error" }
```

**Solidus Version**: 2.9.4

**To Reproduce**

1. Create `app/models/spree/promotion/rules/always_true_rule.rb`
```ruby
module Spree
  class Promotion
    module Rules
      class AlwaysTrueRule < Spree::PromotionRule
        def applicable?(promotable)
          true
        end

        def eligible?(order, options = {})
          true
        end

        def actionable?(line_item)
        end
      end
    end
  end
end
```
2. Create `app/views/spree/admin/promotions/rules/_always_true_rule.html.erb`
3. Add to `config/initializers/spree.rb`
```
Rails.application.config.spree.promotions.rules << Spree::Promotion::Rules::AlwaysTrueRule
```
4. Create a Promotion like the following:
- **Rule:** Always True Rule
- **Rule:** Taxon(s) [ Whatever taxon, one item ]
- **Action:** Create per-line-item adjustment [ anything ]
- _Probably also other options, havent tested them_
5. Create eligible cart and add created coupon to see the error

**Current behavior**
^ See above

**Expected behavior**
Being able to use other rules with my rules.

**Screenshots**
![](https://i.imgur.com/F1ySPWG.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome

**Comment by stem** [comment]
I believe your error is due to 
```
def actionable?(line_item)
end
```

It is defined in `Spree::PromotionRule` and returns `true` by default to let the action create an adjustment for all items.
Some rules overwrite this method (Taxon, Product and OptionValue) to narrow the actionable items, but if your rule prevent any adjustment creation, the action will fail to apply and the coupon as well.

Can you try removing this definition and let us know if it's working properly?

**Comment by b1nary** [comment]
This 100% solved my issue. I didn't think it would do anything like that because most examples feature an empty `actionable?` block. So glad this works now. Kudos.
