### ISSUE TITLE
Standardize Spree Event arguments

### ISSUE THREAD

**Issue by skukx** [solidusio/solidus#3518]
**Is your feature request related to a problem? Please describe.**

With wildcard subscriptions coming up (#3481), I believe it even more important to standardize the arguments passed in.

**Describe the solution you'd like**

Some discussion has been around this [here](https://github.com/solidusio/solidus/pull/3457).

The idea is every event has one context. **If there is an event with more than 1 context, I believe it reasonable that that event may need to be broken up into 2 or more events**.

For example:

`adjustment_added_to_order` could have 2 potential contexts. The adjustment added, and the order getting updated.

However something like this could be broken down to: `adjustment_created` and `order_updated`.

**Argument Against**

There are events which would need multiple contexts in some use cases.

For example:

What about an event called `order_merged`. This potentially has two contexts, the order being merged into and the order being merged.

Both would be good to know especially for logging purposes. However it wouldn't break this implementation.

```ruby
Spree::Event.fire('order_merged', context: deleted_order, new_order: new_order)
```

The main context to `order_merged` is the order that was merged, any other metadata like `What is the new order?` can still be passed along but still considered metadata since it is not the topic of the event.

You could also argue creating a new model for this event `Spree::OrderMerge.new(old_order, new_order)` which also could be the context.

**Why**

```ruby
Spree::Event.subscribe(/.*/) do |event|
  context = event.payload[:context]

  # Pass of the main object of the event to our analytics library to decide how to handle.
  Analytics.report(event.name, context)
end
```

As we add more and more events with different keys as to how to get the object that is associated to the event (:order, :payment, :user, etc), this because more tedious.

Instead generalize our argument into one argument for all (:context.  There is nothing to enforce the use of context but Rails is a major user of convention over configuration so I think that would be ok.

when firing events it could then look like

```ruby
Spree::Event.fire('order_finalized', context: order)

# Or

metadata = { other: 'params' }
Spree::Event.fire('order_finalized', order, metadata)
```

### Note

The pull request referenced needs some work as it is not backward compatible so please don't use it as a strict reference as to how this should be implemented.

**Comment by kennyadsl** [comment]
Thanks for writing this Taylor. 

I still think we should wait to have more events in core before trying to create abstractions here. 

Also, you can probably do the wildcard to analytics thing even now, passing the whole payload to the library with:

```ruby
Spree::Event.subscribe(/spree.*/) do |event|
  Analytics.report(event.name, event.payload)
end
```

Or am I missing something?

**Comment by waiting-for-dev** [comment]
Closing as we're now using [Omnes](https://github.com/nebulab/omnes) for the event system.
