### ISSUE TITLE
Error in move stock on exchange action

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#3527]
Size exchange action is not working ok, the stock after the exchange is reimbursed is not discount from the new size stick but of original size stock. After research I found the problem in 

**Solidus Version**:
Last Master solidus version

**To Reproduce**
Create a return authorization with exchange action 'change size' and the new size
After create the customer return and received.
Reimburse it
-->

**Current behavior**
The reimbursement is discounting stock from the original size not the new size variant that is going  to be sent
**Expected behavior**
Discount stock from the new variant size

**Screenshots**
![image](https://user-images.githubusercontent.com/24247266/75435833-e78a9c80-5953-11ea-8143-e7bd7d029cbb.png)

**Additional context**
The problem is in 'InventoryUnitsFinalizer'  model in method 'unstock_inventory_units'.  This can be solve changing the line 'shipment.stock_location.unstock line_item.variant, units.count, shipment' to 'shipment.stock_location.unstock units.first.variant, units.count, shipment' . and remove 'line_item = units.first.line_item'. 
Because now is taking the line_item original variant but not the new variant in exchange case.

**Comment by kennyadsl** [comment]
@AlessioRocco is this fixed with https://github.com/solidusio/solidus/pull/3514 ?

**Comment by AlessioRocco** [comment]
@kennyadsl Yes, it should fix it, basically is the same logic that @sechix proposes but written in a different way.

**Comment by sechix** [comment]
Perfect, thanks!!

**Comment by kennyadsl** [comment]
Closed with #3514, thanks @sechix for reporting and @AlessioRocco for the PR!
