### ISSUE TITLE
Promotions aren't advertised?

### ISSUE THREAD

**Issue by cdrage** [solidusio/solidus#3534]
**Solidus Version**:

Master branch

**To Reproduce**

To reproduce:
1. Add a promotion
2. Create a rule to select an item
3. Visit the homepage (there is no promotions being shown)

**Current behavior**

When adding a promotion, there's no way to 'advertise' it on the main page or even the product..

I see that there are `advertise` code all throughout solidus, but there is no button to activate it?

**Expected behavior**

Shows the advertisement on the product / homepage.

**Screenshots**

N/A. It's just not there.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by peterberkenbosch** [comment]
Hi Charlie, this has been removed from master some time ago. also see https://github.com/solidusio/solidus/pull/2737

**Comment by seandawes** [comment]
@cdrage We implemented some front end simple logic that may be of interest here and to community as its pretty common on any platform. If an item is marked on sale on product admin, on front end the product is tagged with a SALE banner in product listing / category pages in addition to the product page itself

Example category page

![image](https://user-images.githubusercontent.com/1217031/76096889-bf72ed00-5f94-11ea-8f4e-3bd90abf4ceb.png)

We much rather create front end discounts than insist users use coupon codes for the manufacturer based sales generally. Unless in fact you need to add an additional layer of tracking in certain marketing instances that warrant it. (ie. using unique discount codes)

**Comment by jarednorman** [comment]
This functionality is technically used in the default frontend. The product show page renders [this partial](https://github.com/solidusio/solidus/blob/master/frontend/app/views/spree/products/_promotions.html.erb) which relies on [`Spree::Product#possible_promotions`](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/product.rb#L270-L274).

The partial shows a list of links to products that are part of promotions this product is part of. I tend to think we should just remove the advertised as the promotions partial is confusing from a customer perspective (it's just a list of products with the title "Promotions" with no explanation) and the functionality to create "advertised" promotions was removed from the admin ages ago.

Stores generally have broader promotion advertising needs than we would likely want to build into the frontend, so I'm for deprecating and removing the remaining functionality that relies on this feature. Documenting strategies for adding visibility to your promotions is something I think a lot of stores would benefit from though.
