### ISSUE TITLE
[admin] Prefill user's address when creating a new order for specific user

### ISSUE THREAD

**Issue by spaghetticode** [solidusio/solidus#3537]
Go to `/admin/orders` and click `New Order`. Click on the `Customer` tab, now you can choose from the autocomplete the user's email. This will populate the form address fields accordingly.

Now go to `/admin/users` and pick a user. You can now click the link `Create order for this user`. You will be redirected to a similar form as the one for the feature above, but this time in the `Customer` tab the email address in the form is prefilled, but the address is not. 

I think in this case it would make sense to have the form already populated with the user's address, when available. 

<img width="1013" alt="Schermata 2020-03-02 alle 15 16 59" src="https://user-images.githubusercontent.com/141220/75684371-f301fe80-5c98-11ea-8e3a-d0e7d5efa7e8.png">

**Comment by jaimelr** [comment]
Hi! I'm going to work on this issue, I hope to have PR up with progress soon. 🙂

**Comment by jaimelr** [comment]
@spaghetticode Hi! I got a PR up for this, reviews are appreciated! #3558

**Comment by seand7565** [comment]
Looks like #3558 solves this one! 🎉 If so, can we close this issue?

**Comment by jarednorman** [comment]
Affirmative! This was resolved by #3558.
