### ISSUE TITLE
Investigate removal of associate_user in OrdersController#edit

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#3559]
Apparently, we can stop [calling this method](https://github.com/nebulab/solidus/blob/dd62a3b83298bd77c3673fd13e86d30eab1207f8/frontend/app/controllers/spree/orders_controller.rb#L44), see [here](https://github.com/solidusio/solidus/pull/3494#discussion_r386117331) for a more in-depth discussion.

**Comment by bitberryru** [comment]
My mail server continues to flag github mails as spam :( I have not seen the discussions, I would have answered earlier.

I’ll try to explain again, in the old versions building order and association user with it was in different places, now when you build/create an order (by calling current_order) it is immediately associated with the current user, now there is no need to separately associate the user with the order. This call (https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/orders_controller.rb#L44) has survived from the old days and has no sense now.

FYI: There is only one case when it is required to associate an anonymous order with a user - after user authentication. This task is solved by solidus_auth_devise in warden hook. And this is the responsibility of the authentication system.

**Comment by carlosep** [comment]
Thanks, I understand now.
Based on this I opened **https://github.com/solidusio/solidus/pull/3667** removing the `associate_user` line from the `OrdersController#edit`. It also seems to make sense to remove it from the `CheckoutController` but I'm worried about the mentioned order of execution and would like some comments from @elia on the PR about that and maybe about some way we could test it before I could remove that line as well if it is the case.

**Comment by elia** [comment]
@carlosep I agree with @bitberryru about being time to get rid of that. 

About testing it I would suggest going through a deprecation cycle (which I will make it into 2.11) using a configuration flag to get the old behavior. In this scenario any stori having an OrderController decorator that defines a method like this:

```rb
    def associate_user
      super

      # Update the order to reset the adjustments on the order once a user has
      # been associated with it.
      @order.recalculate
    end
```

should see a deprecation and be able to move its customization elsewhere before upgrading. If done properly that should also cover the CheckoutController before-action and we should be able to cleanup things in a short cycle.

**Comment by carlosep** [comment]
This seems like a good solution. Would that mean just a `warn` in the `associate_user` method or is there a standard way we should go through?

**Comment by elia** [comment]
Hey @carlosep, yeah, that would surely mean a deprecation in the method, but that should also be accompanied by a Solidus configuration that allows disabling the new behavior, you can find many examples of similar deprecations in the Solidus codebase, e.g. you can see [here](https://github.com/solidusio/solidus/blob/a77df8a9160f40f0185ea3b42859a9330f91e058/api/app/helpers/spree/api/api_helpers.rb#L130-L135) how `Spree::Config.use_combined_first_and_last_name_in_address` is used to control the behavior and enables supporting some legacy attributes if set to false.

This is done to let store-owners update their stores individually, one deprecation at a time. Feel free to reach to me in the Solidus slack channel if you need more examples or have questions. 👍

**Comment by carlosep** [comment]
Hi, @elia! I closed the previous PR and opened [a new one](https://github.com/solidusio/solidus/pull/3677) with the configuration flag for this deprecation.

**Comment by waiting-for-dev** [comment]
Closing because of https://github.com/solidusio/solidus/pull/4201#issuecomment-1150909814
