### ISSUE TITLE
No customer return endpoint for solidus api

### ISSUE THREAD

**Issue by roshita02** [solidusio/solidus#3566]
I am working with solidus api and there seems to be no endpoint for creating customer returns for store admins after creating the return authorization.

**Solidus Version**:
2.10.0.beta1 

**To Reproduce**
1. Create return authorization.

**Current behavior**
Currently, solidus api has endpoint for creating return authorization. After i create a return authorization by the given endpoint, corresponding return item is created but with nil customer_return_id.  

**Expected behavior**
I studied the solidus docs and as mentioned in it, After store admin gets the item when customer returns it, Admin has to create customer return with corresponding return item id. But there is no any endpoint to create customer returns with the created return item as attribute.

**Comment by kennyadsl** [comment]
Thanks for pointing this out. There are no endpoints for customer returns yet. Any contribution is welcome to add them!

**Comment by kennyadsl** [comment]
Thanks for opening the issue @roshita02! @seand7565 implemented this and we can close here. Also thanks to SuperGood for sponsoring this PR.
