### ISSUE TITLE
problem when Install new extension

### ISSUE THREAD

**Issue by Mohammedalasaad** [solidusio/solidus#3576]
Hi,
Do we need to remove the bootsnap from /sandbox/config/boot.rb?

```ruby
require 'bootsnap/setup' # Speed up boot time by caching expensive operations.
```

And remove it as welll from the gemfile /sandbox/Gemfile?

```ruby
Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false
```
I tried to install extensions and I does not work, I got error:

after I run this:

```
bundle exec bin/rails g solidus_comments:install

Traceback (most recent call last):
	3: from bin/rails:3:in `<main>'
	2: from bin/rails:3:in `require_relative'
	1: from /Development/App/solidus/sandbox/config/boot.rb:4:in `<top (required)>'
/Development/App/solidus/sandbox/config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)
```

btw, I am running:
- Rails 6.0.2.2
- ruby 2.6.3p62
- Solidus master

**Comment by kennyadsl** [comment]
Bootsnap is added by Rails when generating the sandbox application. I don't think it's related to that error. Maybe it's just swallowing the real error? Do you have any error if you comment the `bootsnap` code?

**Comment by malasaad82** [comment]
Hi Kennyadsl,
Thank you for your answer,  I think i was running it wrong, I should run the command inside the sandbox folder.

bundle exec rails g solidus_comments:install

Its running now and without any probem :)

I just dont understnad.. is Solidus copy of Spree ? 
Thanks again

**Comment by kennyadsl** [comment]
Great it's working.

Solidus is a fork of Spree. This means that these projects share some parts of the codebase but took different paths since a specific moment (2015). You can google a little bit to understand the story behind that. Hope this helps!
