### ISSUE TITLE
Let the heroku button create an app that can send emails

### ISSUE THREAD

**Issue by elia** [solidusio/solidus#3578]
_ref: https://solidusio.slack.com/archives/C0JBKDF35/p1586021529189900?thread_ts=1586020481.189500&cid=C0JBKDF35_

The heroku button should spin up apps that are basically ready for production, so it should also setup email with one of the available Heroku addons with a free plan, e.g. Sendgrid.

https://elements.heroku.com/addons/sendgrid
https://devcenter.heroku.com/articles/sendgrid#ruby

**Solidus Version**:
Latest

**To Reproduce**

Create a new solidus app using the heroku button.

**Current behavior**

It lacks configuration for the email.

**Expected behavior**
It correctly sends emails.

**Comment by waiting-for-dev** [comment]
Closing it, as we're going to remove the heroku button. See https://github.com/solidusio/solidus/issues/4502
