### ISSUE TITLE
Organize Products which belongs to the Shop

### ISSUE THREAD

**Issue by nguyentamphu** [solidusio/solidus#3597]
I wanna implement the function: Organize some products which belong to the specify **Shop**

Like Spree, I found an extension can handle this issue: [spree_multi_vendor](https://github.com/spree-contrib/spree_multi_vendor)
And [here](https://marketplace-demo.spreecommerce.org/shops) is demo for *spree_multi_vendor*

Please help me point another extension of **solidus** like *spree_multi_vendor* of Spree.

Thanks for your support!

**Comment by aldesantis** [comment]
@nguyentamphu Solidus already supports the concept of multiple stores: each store has its own payment methods, shipping methods, products etc. If you just need to create multiple stores, the existing functionality can be a good starting point, although it definitely requires some customization, especially on the storefront side (e.g. associating different domains with different stores, having different styling depending on the store etc.)

If you're building an actual marketplace, as far as I know there is no actively maintained marketplace extension for Solidus. Having an extension may be reassuring for the community, but marketplaces are so different from one another that it's pretty much impossible for an extension to provide the required level of flexibility, and in most cases you're better off rolling your own implementation.

With that said, GitHub issues are not the place for support requests, so I'm going to close this one — you're more than welcome to join our [Slack community](http://slack.solidus.io/) and we can continue the conversation there though!

**Comment by nguyentamphu** [comment]
@aldesantis 
Thank you very much for your advice.
