### ISSUE TITLE
Sorting Stock Locations

### ISSUE THREAD

**Issue by seandawes** [solidusio/solidus#3601]
**Is your feature request related to a problem? Please describe.**
Currently stock locations cannot be sorted.  When you add more than 1 stock location orders will default to the newest stock location. For stores who have more than 1 supplier they generally have a picking order either by brand or sku. 

Example
![image](https://user-images.githubusercontent.com/1217031/80722480-65426400-8acd-11ea-813c-3a54f79dbf35.png)

**Describe the solution you'd like**
Think the easiest logic to follow would be how images are sorted on the product admin as this behavior would make it consistent user experience and this could be applied to anywhere sorting may need to be done. 

![image](https://user-images.githubusercontent.com/1217031/80722572-81de9c00-8acd-11ea-83ad-9668bfd67504.png)

**Describe alternatives you've considered**
Could not think of any other alternative solutions which made more logical sense.

**Additional context**
For stores who hold internal warehouses most will want their own warehouses to be the first in picking so by having sorting this could accomplish this versus overrides which others like ourselves have done which include making our default always the picking order.

**Comment by kennyadsl** [comment]
I think sorting stock locations would be a good addition, but you can already do this using https://guides.solidus.io/developers/shipments/stock-locations-sorter.html#stock-locations-sorter.

**Comment by seandawes** [comment]
Was more so looking for UI to follow consistencies in the admin. Such as how images can be sorted

**Comment by bigbob33** [comment]
Hi, @seandawes!

Should the stock location order be global or just for the specific item?

I can easily see both cases and I am wondering which one you had in mind.
