### ISSUE TITLE
Ruby 2.7 warnings

### ISSUE THREAD

**Issue by softr8** [solidusio/solidus#3611]
The following warnings are thrown when running Solidus with Ruby 2.7:

* core/lib/spree/preferences/preferable.rb:162: warning: deprecated Object#=~ is called on TrueClass; it always returns nil
* core/app/models/concerns/spree/user_address_book.rb:8: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
* core/lib/spree/i18n.rb:34: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

**Comment by jacquesporveau** [comment]
I've opened up a PR for the first warning.

**Comment by softr8** [comment]
Fist and second were fixed here #3737
