### ISSUE TITLE
Incorrect Request Type: (GET) Select the shipping method for a shipment

### ISSUE THREAD

**Issue by jacklalley** [solidusio/solidus#3618]
The API documentation for the select shipping method is mislabeled and should be PUT. 
https://solidus.docs.stoplight.io/api-reference/shipments/select-shipment-shipping-method

1. Run rake routes and you can see expected request type is PUT.

**Comment by kennyadsl** [comment]
It was already fixed in master with https://github.com/solidusio/solidus/commit/9056edb9d634f20716420e00278ffaeda1061b12, I backported the fix to v2.10. CircleCI should now regenerate the right documentation and update it.

**Comment by kennyadsl** [comment]
Thanks for reporting!
