### ISSUE TITLE
Duplicated scope in StoreCreditReason

### ISSUE THREAD

**Issue by halilim** [solidusio/solidus#3628]
[StoreCreditReason](https://github.com/solidusio/solidus/blob/afd7f5b3bc1f3701012b7932725941aa772e04f8/core/app/models/spree/store_credit_reason.rb#L10) & [NamedType](https://github.com/solidusio/solidus/blob/afd7f5b3bc1f3701012b7932725941aa772e04f8/core/app/models/concerns/spree/named_type.rb#L8) both have the scope `active` with the same definition. This logs a warning:

```
Creating scope :active. Overwriting existing method Spree::StoreCreditReason.active.
```

**Comment by peterberkenbosch** [comment]
Good find! Thanks @halilim
