### ISSUE TITLE
Encrypted Preferences

### ISSUE THREAD

**Issue by elia** [solidusio/solidus#3652]
**Is your feature request related to a problem? Please describe.**
Credentials for payment methods are stored as preferences. That means that if anyone gains access to the database or to a database backup can potentially perform operations on the payment provider.
Although this is not a very common scenario it would still be better to have those credentials encrypted in the database.

**Describe the solution you'd like**
I'd like to see the encryption capabilities that Rails already uses for cookies and secrets applied to preferences (when requested). E.g.:

```rb
module SolidusMyPaymentProvider
  class Gateway < SolidusSupport.payment_method_parent_class
    preference :client_id, :encrypted_string
    preference :client_secret, :encrypted_string
    # ...
  end
end
```

**Describe alternatives you've considered**
I initially tried to write getter/setters for those preference, and leverage `Rails::Secrets.encrypt` and `Rails::Secrets.decrypt`, but those are meant to be used in their context, and eventually I thought this is a problem common to almost all payment methods.

**Comment by aldesantis** [comment]
Encrypted credentials would be a good addition, but to be honest I think we should just move away from using database-stored preferences for credentials in the first place, and encourage people to use environment variables instead. Having to change a gateway's credentials is a rare occurrence and you can ask a developer to do it, especially considering how quick it is to change an environment variable.

**Comment by elia** [comment]
@aldesantis I agree, whenever possible we should avoid storing credentials in the database. There are, however, some cases in which that's is not possible or would require an unjustified burden on the user. 

The use case I have in mind, and from which this issue emerged, is the case in which the payment method is created through an inline onboarding process. Of course I'm working on an extension that does just that 😄.

**Comment by kennyadsl** [comment]
I think it's a good idea to add this to Solidus but I'm a bit concerned about adding things that can be critical for security. Is there a way to use/delegate some Rails internal mechanism, so that we don't add extra security concerns in Solidus?

**Comment by cedum** [comment]
I think [`MessageEncryptor`](https://api.rubyonrails.org/v6.0.3.1/classes/ActiveSupport/MessageEncryptor.html) (used also by `Rails::Secrets` in this case) is fairly easy to use as a simple encryption mechanism.
The biggest issue here IMO in most the encryption key management: safe generation, storage, and rotation, even by reusing the Rails secrets key.

**Comment by elia** [comment]
> The biggest issue here IMO is the encryption key management: safe generation, storage, and rotation, even by reusing the Rails secrets key.

If we allow to specify a key for prefs, that we can also use defaults that try in sequence:
- an explicit key set via an attribute accessor
- an environment variable (e.g. `ENV['SOLIDUS_PREFERENCES_MASTER_KEY']`)
- the rails master key

In this way we don't stay too much in the way of the user and allow enough flexibility to allow key rotation, either manual or via migrations. In any case there's an improvement over the current situation which is at least on par with what rails secrets provides.

**Comment by softr8** [comment]
Did you try writing a [custom serializer](https://github.com/solidusio/solidus/blob/a363a7484f0d537887dfb23937615ecb20da4a42/core/app/models/spree/base.rb#L6) to encrypt/decrypt values? I think it could be worth to see how it looks like

**Comment by kennyadsl** [comment]
🎉 thanks @stefano-sarioli!
