### ISSUE TITLE
Admin user controller doesn't respect some abilities

### ISSUE THREAD

**Issue by halilim** [solidusio/solidus#3668]
1. `#collection` does not check the current admin's abilities and returns all users. It can probably be fixed by using `super.ransack...` which makes use of `#accessible_by`.
 https://github.com/solidusio/solidus/blob/4079b58fe4a1917c1a5c81db86427e90f1d918f8/backend/app/controllers/spree/admin/users_controller.rb#L127

2. Similar issue for `#load_roles`, `#load_stock_locations` & `#set_stock_locations`, though `super` wouldn't cut it in these cases.
 https://github.com/solidusio/solidus/blob/4079b58fe4a1917c1a5c81db86427e90f1d918f8/backend/app/controllers/spree/admin/users_controller.rb#L163-L164
 https://github.com/solidusio/solidus/blob/4079b58fe4a1917c1a5c81db86427e90f1d918f8/backend/app/controllers/spree/admin/users_controller.rb#L170-L171
  `#load_stock_locations` also doesn't respect `user_params` and uses `params` directly instead.
 https://github.com/solidusio/solidus/blob/4079b58fe4a1917c1a5c81db86427e90f1d918f8/backend/app/controllers/spree/admin/users_controller.rb#L180-L181

3. `#set_roles` checks the general ability but not the roles given in params. I.e. a role that can't be managed could be given to a user by manually passing its id in params.
 https://github.com/solidusio/solidus/blob/4079b58fe4a1917c1a5c81db86427e90f1d918f8/backend/app/controllers/spree/admin/users_controller.rb#L175-L176

**Solidus Version**:
2.10.1

**To Reproduce**
In Admin > Users, with an admin whose permissions defined as:
```ruby
cannot :manage, ::Spree::User, ['some SQL'], &:foo?
cannot :manage, ::Spree::Role, ['some SQL'], &:bar?
```

**Current behavior**
1. Users with `foo? => true` are listed
2. Roles with `bar? => true` are included in Search > Roles, New User > Roles etc.
3. Roles with `bar? => true` can be assigned to a user

**Expected behavior**
1. Users with `foo? => true` are not listed
2. Roles with `bar? => true` are excluded from Search > Roles, New User > Roles etc.
3. Roles with `bar? => true` cannot be assigned to a user

**Comment by kennyadsl** [comment]
We can close this one. Thanks @igorbp and @halilim for reporting!
