### ISSUE TITLE
Not find payment methos in store credit

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#3678]
User store credit is not applying to the order

**Solidus Version**:
solidus (2.11.0.alpha)

**To Reproduce**
1. Add store credit to a user 
2. Create an order and confirm the order

**Current behavior**
Order not apply discount for store credit

**Expected behavior**
Should apply to the order

**Additional context**
I have seen that in model order , method 'add_store_credit_payments'  not create payment due to  payment_method = Spree::PaymentMethod::StoreCredit.first is nil

**Comment by kennyadsl** [comment]
Have you created a payment method with type Store Credit in admin first?

**Comment by sechix** [comment]
No, sorry. I didn't know that. Thanks @kennyadsl
