### ISSUE TITLE
[RFC] Remove required validation from address phone numbers

### ISSUE THREAD

**Issue by seand7565** [solidusio/solidus#3679]
**Is your feature request related to a problem? Please describe.**
Solidus requires phone numbers in addresses by default. Since these phone numbers aren't used by Solidus (besides being displayed to admin) it's not obvious why this field is required, and it being required has the possibility of [decreasing conversions](https://baymard.com/blog/explain-phone-number-field). 

Additionally, as a consumer, required phone numbers in eCommerce is a bit of a pet peeve of mine - you already have my email address if you need to contact me!

**Describe the solution you'd like**
I think this should not be a required field by default, and the documentation should be updated to describe how to make it required if desired by the store.

**Comment by seandawes** [comment]
Many stores will have this as a requirement as it is a required piece of information to run instant financing approvals in the cart such as Affirm. cc @peterberkenbosch 

We ran into issues with paypal/braintree solidus gem and phone number formatting so we don't pass that data point anymore.

Marketing requirements may want it for order tracking or marketing customers wish to opt in to (think flash sales etc) which is done via twilio or other services such as [Klaviyo ](https://www.klaviyo.com/features/sms-marketing) which is on the roadmap

**Comment by seand7565** [comment]
I totally see why it would be a requirement for some stores, especially for cases like Affirm - but IMO Solidus shouldn't be opinionated on what a customer _might_ integrate with. For the handful of Solidus stores I've worked on, I've never seen a case where phone number was required for anything important, so I think it may be overkill to require it on all Solidus stores by default - especially when it has an impact on conversions.

**Comment by seandawes** [comment]
Its gonna be needed for any mainstream enterprise store but Im in favor of stripping it from core and having core do less. This could also be addressed in overhauling the full checkout which is bad for CRO at its current stage. ie. needs single page checkout

**Comment by aldesantis** [comment]
I agree that the phone number shouldn't be required by default. I think the idea was to also use the information for fraud detection, but it's a decision that should be left to the individual store.

**Comment by jarednorman** [comment]
I'm fine making that validation optional. Some stores need to require phone numbers and others don't. Seems like the perfect case for adding an option.

**Comment by peterberkenbosch** [comment]
totally onboard with this. For some shipping providers they like to have a phone number to text delivery time updates or just call to get the delivery made. That being said, having that as an optional validation sounds like the best way forward.
