### ISSUE TITLE
RFC: Remove deprecated pricing functionality

### ISSUE THREAD

**Issue by jarednorman** [solidusio/solidus#3681]
In #1251 we officially deprecated `Spree::Variant#price_in`, `Spree::Variant#amount_in` and `Spree::Variant.active` in favour of the `price_selector`-aware versions.

What do people think about removing them? They've been deprecated since v1.4, which was a long time ago.

**Comment by kennyadsl** [comment]
They should be removed now with Soldius 3.0!
