### ISSUE TITLE
Associate gateway_customer_profile_id with users, rather than credit cards?

### ISSUE THREAD

**Issue by brchristian** [solidusio/solidus#3682]
Context: Am currently trying to build a subscription/autorenew platform on top of `solidus_stripe`.

I noticed (along with @spaghetticode in https://github.com/solidusio/solidus_stripe/issues/26) that a new Stripe profile is created every time someone uses a new credit card.

In our case, it looks like even orders with the _same_ credit card result in new Stripe "customer" objects being created. So according to Stripe, every order that our store has ever processed has been from a "new" customer.

Creating persistent "customer" objects is crucial to subscription/renew functionality. But it also helps almost any store with metrics, retention, etc.

Partly this will require some updates to the `solidus_stripe` gem, but in part I think it goes back to Solidus core.

For instance, the `gateway_customer_profile_id` exists on the `Spree::CreditCard` object...but not on the `Spree::User` object.

I'd love to see about making some progress here toward better tracking customers in a robust, persistent way.

Would PRs be helpful? I'm happy to do the work if this is aligned with the Solidus community.

**Comment by jarednorman** [comment]
A more detailed explanation of what changes to Solidus are required to support this functionality would be great at this point.

**Comment by brchristian** [comment]
Sure thing. Off the top of my head, I'm imagining a migration to add a `gateway_customer_profile_id` column to the `Spree::User` model (we could move it from the `Spree::CreditCard` model, but for guest orders there is no user, so in that case perhaps it's better have the `gateway_customer_profile_id ` column in both tables, even if slightly redundant in many cases). I'm just starting to dig into this, though, so I can follow up as I start to learn more.

**Comment by jarednorman** [comment]
That's not really viable because a customer might have multiple gateway profiles and there's no reason that you can't reuse the gateway profile id off the customers. I know from experience with other Stripe implementations that this works just fine.

I suspect there's no need to make any changes to Solidus itself to support that issue on `solidus_stripe`.

**Comment by brchristian** [comment]
I see. If I understand correctly, you're saying that you could
theoretically support PayPal and Stripe and Braintree on the same Solidus
store, and you'd obviously need  more than one profile then for a given
user.

That makes sense.

Okay, so it sounds like it's really a case of keeping the user identifier
on the `CreditCard` object, but just finding ways to reuse previous profile
IDs when that `CreditCard` is attached to the same `User` as another
`CreditCard`.

If my understanding above is correct, then I think I agree with you and we
can close this issue here and I'll continue the conversation over at
`solidus_stripe`. Thanks!

**Comment by jarednorman** [comment]
Yep, that's exactly it! I'll close the issue and discussion can continue on the `solidus_stripe` issue.
