### ISSUE TITLE
Added products in admin panel not showing on the frontend

### ISSUE THREAD

**Issue by papebarka** [solidusio/solidus#3691]
I'm trying solidus for the first time. I can add products in the admin panel with no problem and when I click on "View Product On Store" it takes me to the product page and shows everything. However, I don't see any product when I go to the storefront (frontend). All I get is this message "No products found".
How can I solve this problem?

**Solidus Version**:2.10.1

**Comment by kennyadsl** [comment]
Hey there! How are you setting the "Available On" date of these products?

**Comment by papebarka** [comment]
> Hey there! How are you setting the "Available On" date of these products?

Hey! My bad! I was leaving the field empty and that's why they weren't showing. Now, they are.

Thank you :)
