### ISSUE TITLE
Payment method auto-capture boolean provides 3 options to the user

### ISSUE THREAD

**Issue by seand7565** [solidusio/solidus#3697]
The value of auto-capture is a boolean, but has three possible values in the following image: `false`, `yes`, and `no`.

![image](https://user-images.githubusercontent.com/5720486/87042756-b6e82880-c1b9-11ea-982a-2263c9bae57c.png)

IMO we should use `true` and `false` instead of `yes` and `no`, but we could also set the value of app default to `yes` and `no` - as long as we're consistent with our options.

**Comment by aldesantis** [comment]
@seand7565 hmm, not sure this is an actual issue. The first option corresponds to `nil`, which tells Solidus to use the application's default `auto_capture` setting. In this case, that setting is `false`, so it's displayed next to "Use App Default" for the user's convenience.

**Comment by seand7565** [comment]
@aldesantis Right, behind the scenes the value is either `true` or `false`, but the dropdown indicates to the user that there are 3 possible values - `false`, `yes` or `no`. As a user, I'd expect to see something like this:
![image](https://user-images.githubusercontent.com/5720486/87049502-abe5c600-c1c2-11ea-9529-80a412857670.png)
Or this:
![image](https://user-images.githubusercontent.com/5720486/87049610-d5065680-c1c2-11ea-9775-b9188ef147f5.png)

(I prefer the first option, but maybe that's just me)

No problem with the logic, just nitpicking at the text in the provided options. 😛

**Comment by aldesantis** [comment]
Ah, sorry, didn't realize you were referring to the label! I think the best option is to use yes/no consistently, since true/false only makes sense for developers.

**Comment by jarednorman** [comment]
Yeah, for consistency I think the ideal options are probably:

- Use App Default (No)
- Yes
- No

**Comment by michaelmichael** [comment]
I believe I fixed this in #3703 according to the consensus here.

- Use App Default (No)
- Yes
- No

However, I wonder if it would be better to remove the redundant option from the dropdown to reduce cognitive overhead. 

While having the third option makes sense to the store's developer, it could be confusing to users. Why have three answers to a yes or no question? The user may wonder if there is any difference between "Use App Default (No)" and "No"—At least, I wondered this when first setting up payment methods.

So, my pull request as submitted makes the verbiage more consistent. That said, I could update it if others agree that reducing it to just two options is preferable, as in:

- Use App Default (No)
- Yes

To take it one step further, I think something like the following would be easiest to scan and parse:
- No (Default)
- Yes

**Comment by aldesantis** [comment]
@michaelmichael when you select "Use App Default", what happens under the hood is that the value of the preference will be set to `nil`, and the actual logic will change depending on the current store default. When you select Yes/No, the value of the preference will be fixed and will not change with the store's default preference. So choosing "No" and "Use App Default (No)" will actually lead to two different behaviors. Hope I explained it clearly, let me know if you have any questions!

**Comment by michaelmichael** [comment]
@aldesantis Makes perfect sense 👍

**Comment by seand7565** [comment]
Yep, that covers it! Thanks so much @michaelmichael
