### ISSUE TITLE
Empty promotion action type to create can be send / isn't catched

### ISSUE THREAD

**Issue by SyborgStudios** [solidusio/solidus#3707]
Solidus 2.5 introduced a prompt on the dropdown.
Just clicking add will send an empty action type to create. This leads to a @promotion_action == nil.
Which throws an error in the create.js.erb.

https://github.com/solidusio/solidus/blob/57ea33fef4c179b928790e5f639131b01d8e3fd6/backend/app/views/spree/admin/promotions/_actions.html.erb#L11

**Comment by mabry1985** [comment]
I've setup and recreated the issue and I found a similar error is thrown with the 'Discount Rules' dropdown. 

I will add nil catches to the respective controllers and get a PR in.

**Comment by mabry1985** [comment]
I've setup and recreated the issue and I found a similar error is thrown with the 'Discount Rules' dropdown.

I will add some catches and get a PR in.
