### ISSUE TITLE
autoprefixer-rails is deprecated

### ISSUE THREAD

**Issue by brchristian** [solidusio/solidus#3727]
Unfortunately, the [`autoprefixer-rails`](https://github.com/ai/autoprefixer-rails/) gem has been [deprecated](https://github.com/ai/autoprefixer-rails/wiki/Deprecated).

Using the latest version of `autoprefixer-rails` will fill the user’s logs with the following message:

```
DEPRECATION WARNING: autoprefixer-rails was deprected. Migration guide:
https://github.com/ai/autoprefixer-rails/wiki/Deprecated
```

This is a dependency of `solidus_backend`:

https://github.com/solidusio/solidus/blob/3883757b66bd48054a8a835bb4d880697ac2c895/backend/solidus_backend.gemspec#L35

I am not experienced with `autoprefixer-rails` or `autoprefixer` itself, so I cannot advise on the best path forward. But it looks like it may involve shifting from `sprockets` to `webpacker`?

Others who are more familiar with this than I am can advise on the best approach to handle this deprecation.

**Solidus Version**:
2.10.2

**Comment by jarednorman** [comment]
Thanks for the report! This may become an issue at some point, but is likely something we will just live with for now. Many sites rely on how easy it is to override or add to the different assets that come with Solidus and Webpacker doesn't really offer any kind of similar functionality. We'll have to keep an eye on this, though.

**Comment by waiting-for-dev** [comment]
Closing, as autoprefixer-rails is no longer deprecated. See https://github.com/ai/autoprefixer-rails/commit/9306d3ed5ad034dff1d293ce3b73d3f9df85af70
