### ISSUE TITLE
Error cancelling an order

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#3729]
**Solidus Version**:
Master last version

**To Reproduce**
Go to orders and cancel one

**Current behavior**
Gives an error and not cancel order

**Screenshots**

![image](https://user-images.githubusercontent.com/24247266/90025889-f1f8e280-dcb6-11ea-99aa-4769503612d7.png)

**Additional context**
Problem in model spree/payment/processing

      def handle_void_response(response)
        record_response(response)

        if response.success?
          self.response_code = response.authorization
          void
        else
          gateway_error(response)
        end
      end

Response get boolean and break sucess?

**Comment by spaghetticode** [comment]
@sechix thanks for reporting this. I had seen this error when using an old version of Solidus Stripe. Are you using that gem? Was the order in error paid with Stripe? If that's the case, I suggest you upgrade Solidus Stripe to the latest version.

**Comment by sechix** [comment]
hi @spaghetticode ,  you are right. Solved updating solidus_stripe. Many thanks!!!!
