### ISSUE TITLE
Support for Tracking Order

### ISSUE THREAD

**Issue by errawn** [solidusio/solidus#3735]
Does Solidus supports order tracking? [highlighted in blue in image below]

![image](https://user-images.githubusercontent.com/18679035/90659557-69121600-e277-11ea-91f2-4e0789ca9e2a.png)

**Comment by jarednorman** [comment]
It has support for recording the tracking number on a shipment, but no built-in UI to show the tracking history or anything as that's specific to the given provider.

Please direct any follow up questions to [our Slack](https://slack.solidus.io) as we use GitHub issues strictly for bug reports and feature requests. 🙂
