### ISSUE TITLE
Running  bin/rails g spree:install -> [WARNING] Could not load generator "generators/spree/install/install_generator". Error: superclass mismatch for class Command.

### ISSUE THREAD

**Issue by delphaber** [solidusio/solidus#3752]
Hi :)

I wanted to create a new app using solidus 2.10.2 on rails 6.0.3.2 on ruby 2.7.1 on macOS Catalina 10.15.6

I was not able to complete `bin/rails g spree:install`: rails told me that the generator does not exist. The problem is related to this warning: [WARNING] Could not load generator "generators/spree/install/install_generator". Error: superclass mismatch for class Command.

I think this is related: https://github.com/erikhuda/thor/issues/721

How to fix:

I added this line to `Gemfile`

`gem 'thor', '~> 0.20.3'`

But I had to manually uninstall the other thor version using `gem uninstall` and I had to clean bootsnap cache and stop spring. Then I was able to finish the installation :)

**Comment by jarednorman** [comment]
Thanks for the detailed report!

**Comment by kennyadsl** [comment]
Closing, we are not supporting this versions anymore and it doesn't seem to be still here. Thanks for the report!
