### ISSUE TITLE
DefaultTax Calculator considers invalid TaxRates when calculating tax for an item whose tax is included in price

### ISSUE THREAD

**Issue by jugglinghobo** [solidusio/solidus#3766]
When calculating the tax for line items whose tax is included in the price, solidus uses TaxRates in the calculation even though they are invalid according to their `start_date` and/or `end_date`. This results in incorrect tax calculations if there are multiple tax rates for the same tax category and only some of them are currently valid.

**Solidus Version**:
`2.9.4` up to the current master version.

**To Reproduce**
1. In the admin backend, create a new TaxRate
2. Set the following attributes: Included in Price: true, Zone: North America, Tax Category: Default, name: "Active"
3. Create a second TaxRate with: Included in Price: true, Zone: North America, Tax Category: Default, name: "Inactive", end_date: sometime in the past
4. Delete the originally existing tax rate (to not interfere with this repro)

5. Go to the shop, add any product to cart and proceed to checkout
6. On the address page, enter a valid address for US
7. On the delivery page, you can now see the calculated tax.
8. As shown on the screenshot, this calculation includes the invalid tax rate

**Screenshots**
![Screenshot 2020-09-21 at 14 34 27](https://user-images.githubusercontent.com/814278/93772201-d6bab480-fc1e-11ea-9ba2-f29e2fd723a3.png)

**Current behavior**
The current calculation for line item tax that's included in the price is based on these methods (in `DefaultTax` calculator):

```
def deduced_total_by_rate(item, rate)
  round_to_two_places(
    rate.amount * item.total_before_tax / (1 + sum_of_included_tax_rates(item))
  )
end

def sum_of_included_tax_rates(item)
  rates_for_item(item).sum(&:amount)
end
```

`rates_for_item(item)` returns all tax rates whose category matches the categories for this item, and __does not consider whether this tax rate is valid or not__.

This leads to incorrect calculations, for example:

* item price: 119
* active tax rate amount: 0.16
* inactive tax rate amount: 0.19
* calculated tax: 14.103703704 = `0.16 * 119 / (1 + 0.16 + 0.19)`

Note how the inactive tax rate is part of the divisor in the above equation.

**Expected behavior**
The calculation for line item tax that's included in the price takes into account if a tax rate is valid or invalid, and calculates the tax only based on the valid tax rates.

Example for the correct calculation:

* item price: 119
* active tax rate amount: 0.16
* inactive tax rate amount: 0.19
* calculated tax: 16.413793103 = `0.16 * 119 / (1 + 0.16)`

**Additional context**
I forked the repo and created a failing spec and a very basic fix here: https://github.com/jugglinghobo/solidus/commit/b45fa15f5f5c28e4a13dc0f4b263081fd77ea0c6
However I'm not sure if this is the correct approach. Maybe it would make sense to think about whether `rates_for_item` should already filter out invalid tax rates and only return currently valid rates.

If you think my current approach makes sense I can gladly open a PR with it.

**Comment by aldesantis** [comment]
@jugglinghobo thanks! I think your fix is okay, but as you pointed out, that code should probably live in `rates_for_item`, which is responsible for returning the rates to apply to an item. Feel free to open a PR!
