### ISSUE TITLE
Shipping/Billing addresses appear inconsistent on frontend vs. backend

### ISSUE THREAD

**Issue by brchristian** [solidusio/solidus#3771]
**Solidus Version**:
2.10

**To Reproduce**
1. On frontend, begin checkout and get to Address step. Notice that shipping is on the _right_:

<img width="722" alt="Screen Shot 2020-09-23 at 5 56 57 PM" src="https://user-images.githubusercontent.com/2460418/94088979-bb8aa900-fdc6-11ea-97b4-ae2f6b7fcdc7.png">

2. On backend, go to Order > Customer. Notice that shipping is on the _left_:

<img width="884" alt="Screen Shot 2020-09-23 at 5 59 09 PM" src="https://user-images.githubusercontent.com/2460418/94089030-dd842b80-fdc6-11ea-8a82-5e328ae75442.png">

**Current behavior**
The order is different.

**Expected behavior**
The order is the same

**Steps to fix**
I would be very happy to prepare a PR for this. The question is, which order is the correct one?

**Comment by aldesantis** [comment]
@brchristian since the Shipping Address column has the "Use Billing Address" checkbox, I think the correct order would be Billing and then Shipping, like in the frontend. @solidusio/core-team do you have any opinions here?

**Comment by tvdeyen** [comment]
@aldesantis @brchristian I agree with Billing, then Shipping

**Comment by kennyadsl** [comment]
I also agree to make them consistent

**Comment by brchristian** [comment]
Great, that sounds good! And it also makes it consistent with other backend views as well, e.g., `orders/confirm/_customer_details` and others. I have submitted a PR at #3773.
