### ISSUE TITLE
Rails 6.1 compatibility

### ISSUE THREAD

**Issue by elia** [solidusio/solidus#3784]
The latest rails-master introduced some changes that broke the CI for any PR. Solidus should be upgraded in order to take those changes into account. ~Additionally rails@master can be allowed to fail without blocking merges.~ _It's already the case, although the red mark can't be removed._

In this context we should prep for the upcoming release of Rails 6.1.

**Solidus Version**:
master

**To Reproduce**

Just look at any recent CI run, the typical error looks like this:

```
ArgumentError:
  wrong number of arguments (given 3, expected 2)
./lib/spree/testing_support/factories/variant_factory.rb:25:in `block (4 levels) in <top (required)>'
./lib/spree/testing_support/factories/stock_package_factory.rb:25:in `block (5 levels) in <top (required)>'
./lib/spree/testing_support/factories/stock_package_factory.rb:19:in `block (3 levels) in <top (required)>'
./spec/models/spree/calculator/shipping/flat_rate_spec.rb:14:in `block (2 levels) in <module:Shipping>'
```

https://app.circleci.com/pipelines/github/solidusio/solidus/1517/workflows/7e34a2fa-bf02-46bc-953c-b9f8d9eedcd7/jobs/20534

(the affected factory may vary, and the issue may well may be in `factory_girl`, but that needs to be verified)

**Comment by aldesantis** [comment]
@kennyadsl I think you had investigated this issue in the past, right?

**Comment by kennyadsl** [comment]
Not yet: in the past, we had different errors, mainly related to our dependencies that are still not ready for rails master. This looks new to me.

**Comment by filippoliverani** [comment]
The `ArgumentError:  wrong number of arguments (given 3, expected 2)` is releated to associations/joins syntax.
Updating the code using legacy`joins` syntax would be quite simple, I'm investigating if there the error happens in other cases.

**Comment by filippoliverani** [comment]
We have a problem with CanCanCan too: [`undefined method 'resolve_column_aliases' for`](https://github.com/CanCanCommunity/cancancan/issues/652)`, but it has already been addressed [here](https://github.com/CanCanCommunity/cancancan/pull/657)

**Comment by filippoliverani** [comment]
Ransack main branch [is now compatible](https://github.com/activerecord-hackery/ransack/pull/1172) with Rails 6.1.0.RC1 ❤️
