### ISSUE TITLE
Fix migration CreateSpreeReturnAuthorizationReasons

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#382]
https://github.com/solidusio/solidus/blob/master/core/db/migrate/20140713140455_create_spree_return_authorization_reasons.rb#L13-L23

Afaict `if defined?(Spree::ReturnAuthorizationReason)` will never be true, as it was renamed `Spree::ReturnReason`. What is the intention here? Should we be adding these to the table directly, or should we not add them at all?

**Comment by BenMorganIO** [comment]
I would opt to remove it if you're coming from Spree 3. If you're coming from Spree 2.2 => Solidus 1.1, then maybe rename it. There's tons of things we could do to help with this.

**Comment by jordan-brough** [comment]
@jhawthorn see this PR: https://github.com/solidusio/solidus/pull/230
