### ISSUE TITLE
Remove all occurrencies of spree@example.com from the codebase

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#3829]
We still have a lot of places where we use this email, the most critical one is probably sample data that populate the sandbox (and the demo?)

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Please assign this issue to me, I am new to open source and looking for opportunities to contribute

**Comment by jarednorman** [comment]
@AmeyaPhadnis-2019H1030012G You're welcome to take a stab at it and reference this issue in your pull request.
