### ISSUE TITLE
Setting permissions for custom actions

### ISSUE THREAD

**Issue by Shalashtein** [solidusio/solidus#3870]
Hi, I've created a Spree::ProductsController decorator and added a new action called vendor
```
def vendor
      session[:return_to] = request.url
      @collection = Spree::Product.all.select { |p| p.spree_user_id == current_spree_user.id }
    end
```
I have a role called vendor, a permission set, and the permission set is assigned to the role in the spree initializer
```
module Spree
  module PermissionSets
    class VendorDashboard < PermissionSets::Base
      def activate!
        can [:admin, :home], :dashboards
        can [:read, :admin, :edit, :destroy, :vendor, :create, :manage], Spree::Product, spree_user_id: user.id
        can [:read, :admin, :edit, :destroy, :create], Spree::Image
      end
    end
  end
end
```
And still when I try to access the view associated with the vendor action I get an Unauthorized error
The error is gone if I give the role the ability to :manage  :all  so what am I missing here to allow him to access the view where only the user's products exist

**Comment by kennyadsl** [comment]
Hey there! 

Is that decorator for a frontend or an admin controller?

**Comment by kennyadsl** [comment]
@Shalashtein did you manage to solve this?

**Comment by Shalashtein** [comment]
Not exactly, I ended up giving the vendor the ability to `:vendor :all` since I couldn't figure out which class is raising the exception

**Comment by kennyadsl** [comment]
Maybe it's too late but you could try to debug it with this (taken from [cancancan repo](https://github.com/CanCanCommunity/cancancan/blob/585e5ea54c900c6afd536f143cde962ccdf68607/docs/Debugging-Abilities.md)):

```ruby
# in ApplicationController

rescue_from CanCan::AccessDenied do |exception|
  Rails.logger.debug "Access denied on #{exception.action} #{exception.subject.inspect}"
  # ...
end
```

Should tell you exactly where it needs more permissions.

**Comment by Shalashtein** [comment]
> uld try to debug it with this

I've tried that, however putting the code in the ApplicationController doesn't rescue from the exception, and I tried prepending it to some solidus controllers using decorators but then I get an error saying no 'rescue_from' method in these controllers
