### ISSUE TITLE
Remove awesome_nested_set override for ActiveStorage

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#3871]
With https://github.com/solidusio/solidus/pull/3501/commits/73cd0eff42e7d350e02f44db97c14b0d1bf7f76f we monkey patched `awesome_nested_set` to introduce the fix done here: https://github.com/collectiveidea/awesome_nested_set/pull/413. 

Now that the PR has been merged, and [3.2.1](https://rubygems.org/gems/awesome_nested_set/versions/3.2.1) released, we can safely remove the override but lock the `awesome_nested_set` dependency to version `3.2.1`. 

cc @filippoliverani

**Comment by parndt** [comment]
Version 3.3.1 of `awesome_nested_set` has been released, so probably the entire override file can be removed now.

**Comment by ikraamg** [comment]
@kennyadsl This issue looks solved by your PR, I think we can close it.
