### ISSUE TITLE
Switch allow_forgery_protection to false in test

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#3873]
With [this commit](https://github.com/solidusio/solidus/commit/3b8311230cd8ec208a89c526b03cd04bea1818f1) I switched the default value of `allow_forgery_protection` to true in our spec suite to mimic what we see in a new Rails application after https://github.com/rails/rails/commit/ec4a836. 

But this doesn't mean that Rails wants us to test the application with that value set to `true`, in fact, the default is `false` in the [test environment template](https://github.com/rails/rails/blob/56c9be11ad1cd75f9d0114947cbad36ad2b5901e/railties/lib/rails/generators/rails/app/templates/config/environments/test.rb.tt#L39).

Other than not adhere to a Rails convention, it's important that we change this in order to be able to use system specs in Solidus frontend, which we are trying to convert in the new [starter frontend project](https://github.com/nebulab/solidus_starter_frontend/pull/90).

**Comment by FrancescoAiello01** [comment]
Hey @kennyadsl taking a look at this issue.

I'm wondering if `dummy_app.rb` should always turn off forgery protection, just as real Rails apps turn it off in their test env? Or should it still be true in certain circumstances?

Thanks,
Francesco

**Comment by kennyadsl** [comment]
Hey @FrancescoAiello01, I can't see any circumstance when we need to keep it enabled at the moment. I think we are good if we just disable it.

**Comment by FrancescoAiello01** [comment]
Cool @kennyadsl sounds good. Just opened a PR over [here](https://github.com/solidusio/solidus/pull/3887). Let me know what you think.
