### ISSUE TITLE
Evaluate deprecation of spree_user_return_to 

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#3874]
It's not clear if we really need to keep the custom `spree_user_return_to` session key. 

We used it in https://github.com/solidusio/solidus_auth_devise/blob/b90a7f8e91d337637804a940adb9b8e6fe7343d4/lib/controllers/backend/spree/admin/user_sessions_controller.rb#L42 and https://github.com/solidusio/solidus_auth_devise/blob/b90a7f8e91d337637804a940adb9b8e6fe7343d4/lib/controllers/frontend/spree/user_sessions_controller.rb#L52, storing it at each store visit via the [Spree::UserLastUrlStorer class](https://github.com/solidusio/solidus/blob/a17109b07a817ae34bc61491c3ed1ea824ee32c5/core/app/models/spree/user_last_url_storer.rb).

I think it's to evaluate the deprecation of this custom session value (and setter class) since we can probably just use [`redirect_back(fallback_location:)`](https://apidock.com/rails/v6.0.0/ActionController/Redirecting/redirect_back) provided by Rails since version 5.0.

**Comment by elia** [comment]
As pointed out by @cpfergus1 in https://github.com/solidusio/solidus/pull/4533 `redirect_back` does a different thing that what we need, so we can't use is to replace our custom location storing system.

**Comment by waiting-for-dev** [comment]
Closing in favor of #4533
