### ISSUE TITLE
Product promotion rule input only shows first page of products

### ISSUE THREAD

**Issue by AlistairNorman** [solidusio/solidus#3902]
The product promotion rule select2 only shows the first page of products regardless of how many products are associated with the rule on the admin promotion edit page. There is no way to see the rest of the products associated with the rule.

**Solidus Version**:
2.9.6

**To Reproduce**

1. Go to /admin/promotions/:promotion_id/edit
2. Add 13 products to a rule
3. See that only 12 products show up

On my store the limit is 12, configured on the product model decorator. This will vary for other configurations.

**Current behavior**
It only shows the first 12 products in the input.

**Expected behavior**
All products associated with the rule are shown in the input.

**Screenshots**
![image](https://user-images.githubusercontent.com/272581/105097257-29856b00-5a5d-11eb-939b-93936eb94c2c.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser Chrome 
 - Version 87.0.4280.141

**Additional Details**
We have tracked down the issue to the pagination in the admin search controller in the product action.
https://github.com/solidusio/solidus/blob/d51518a3ac75e15b19088afbf6e397f5698abf57/backend/app/controllers/spree/admin/search_controller.rb#L24

**Comment by adammathys** [comment]
@jarednorman I believe this was fixed by #3934.

**Comment by jarednorman** [comment]
Thanks!
