### ISSUE TITLE
Restrict shipping methods by stock location

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#391]
This is a common need for any store with multiple stock locations. Shipping methods should be able to restrict which stock locations they can be used from.

This will likely require improvements or changes to `Spree::Stock::Package`

**Comment by hhff** [comment]
:+1: i was looking into this recently and was so surprised this doesn't exist

**Comment by alexstoick** [comment]
:+1: we have this in our app, and I'd be more than happy to port this over

**Comment by gmacdougall** [comment]
@alexstoick That would be great. We would really appreciate any help in this area that you could offer.

**Comment by athal7** [comment]
@alexstoick yes!

**Comment by jhawthorn** [comment]
Resolved by #412! Thanks to @alexstoick for the hard work on this. :tada:
