### ISSUE TITLE
Removing `confirm` checkout step doesn't allow transition to `complete`

### ISSUE THREAD

**Issue by seand7565** [solidusio/solidus#3926]
**Solidus Version**:
2.11

**To Reproduce**
1. Start with a vanilla solidus app
2. Create this file:
```
# app/decorators/my_app/spree/order_decorator.rb
module MyApp
  module Spree
    module OrderDecorator
      def self.prepended(base)
        base.remove_checkout_step :confirm
        # base.insert_checkout_step :complete
      end

      ::Spree::Order.prepend self
    end
  end
end
```
3. Try to check out
4. Unable to transition to complete
<img width="971" alt="Screen Shot 2021-02-05 at 4 57 26 PM" src="https://user-images.githubusercontent.com/5720486/107097907-9e81d000-67d3-11eb-9eda-080d3fa85173.png">

_HOWEVER_ if you go back to that file you created and uncomment out the line that adds the `complete` step to the checkout flow, then checking out with the `confirm` step works as normal.

The `complete` step is added by default to any checkout flow that doesn't include it, so it seems unintentional to not be able to complete checkout from any state but `confirm` without also adding a `complete` step to your custom flow. As far as I understand it, you should be able to `complete` from any step, so long as the order is actually able to be completed and there are no steps above the step you are on.

**Current behavior**

Checkout is unable to proceed from payment without the `confirm` step, or without `checkout` specifically being added as a checkout step.

**Expected behavior**
You should be able to complete from the last checkout step without having to manually add a `complete` step

**Comment by kennyadsl** [comment]
I think the issue is in the order state machine code, here:

```ruby
event :complete do
  transition to: :complete, from: :confirm
end
```

the `from: :confrim` part should probably be dynamic (taking the last step before confirm) if we want to make it configurable.
