### ISSUE TITLE
Check the Solidus demo on Docker Hub: still working?

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#3944]
We have a demo of Solidus on Docker Hub here https://hub.docker.com/repository/docker/solidusio/solidus-demo but it's out of date. 

We need to be sure it works by using the last code available and probably also to automate its update somehow anytime we release a new version. Maybe, the easiest iteration on this could be just adding some instructions in the [How-to-release-Solidus](https://github.com/solidusio/solidus/wiki/How-to-release-Solidus) wiki page. 

Another thing to explore is by using directly the demo app (https://github.com/solidusio/solidus-demo/) we created that powers the demo at demo.solidus.io, even if it has some custom code to [bypass the authentication](https://github.com/solidusio/solidus-demo/#authentication), which is probably not needed by people running a demo with Docker. 

Ref: #3106 The original PR that added the demo for Docker Hub.

**Comment by peterberkenbosch** [comment]
I can confirm this is not working anymore.

**Comment by kennyadsl** [comment]
I propose to remove that docker demo. The person who claimed to maintain it is not doing that, and that's fine. Personally, I can't find any value in that demo but feel free to let me know your thoughts. Tagging @waiting-for-dev cause he is our Docker expert. :)

**Comment by jarednorman** [comment]
I think we definitely have more valuable things to spend our time maintaining.

**Comment by waiting-for-dev** [comment]
I also think it's ok to remove it. In the end, it only gives easy access to the visual appearance of Solidus, and the demo app already does that. For local development, it's already dockerized.
