### ISSUE TITLE
Customer info are not auto-populated correctly in admin creating a new order

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#3966]
When `use_combined_first_and_last_name_in_address` is set to `false`, creating a new order in admin, in the customer tab, it is not populating First Name and Last Name fields when you pick an existing customer from the autosuggestion dropdown.

**Solidus Version**:
v2.11.4

**To Reproduce**
1. Install Solidus at the specified version, 
2. Change `use_combined_first_and_last_name_in_address` to `false` in `spree.rb` initializer
3. Login in the admin panel
4. Go to Orders and click `New order`
5. Click `Customer` tab
6. Select any user 
7. `First Name` and `Last Name` are not populated

**Expected behavior**
`First Name` and `Last Name` fields of the auto-populated address are not filled with customer's info and left blank.

**Screenshots**
<img width="866" alt="CleanShot 2021-03-01 at 12 20 44@2x" src="https://user-images.githubusercontent.com/167946/109490477-92162d80-7a88-11eb-95ef-5d00a583c1ee.png">

**Comment by cesartalves** [comment]
@kennyadsl there's a linked PR that seems to reference this issue. Perhaps you could take a look and close this one if the problem is already fixed? Or is there any other needed action here?

**Comment by kennyadsl** [comment]
@cesartalves We can definitely close this one. Thanks!
