### ISSUE TITLE
Normalize i18n keys

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#3978]
`i18n-tasks` gem now comes with the following post-install message:

```
Post-install message from i18n-tasks:
# Install default configuration:
cp $(bundle exec i18n-tasks gem-path)/templates/config/i18n-tasks.yml config/
# Add an RSpec for missing and unused keys:
cp $(bundle exec i18n-tasks gem-path)/templates/rspec/i18n_spec.rb spec/
```

It's a good opportunity to follow these instructions and improve i18n in our platform. I tried and there are a couple of things to configure and fix, but in general, it would be great to have the suggested specs to run in the CI.

**Comment by sridhar-belagod** [comment]
@kennyadsl I am willing to take this. Can you please assign this to me and give few pointers on how to begin

**Comment by sriddbs** [comment]
@kennyadsl I would like to take this up, can you please assign this to me and provider some pointers on how to begin

**Comment by kennyadsl** [comment]
Hey @sriddbs, no need to assign this you can submit the PR directly. I have no more details other than what I posted in the description. This task requires an exploratory phase to understand what those tasks do and how we could benefit from them. 

Thanks for contributing!
