### ISSUE TITLE
Solidus dependancy on paperclip makes it incompatible with ruby 3.0

### ISSUE THREAD

**Issue by iqre8** [solidusio/solidus#3993]
https://github.com/solidusio/solidus/blob/master/frontend/app/views/spree/shared/_image.html.erb#L5 causes an error. It indicates undefined method `escape' for URI:Module

**Solidus Version**:
Spree.solidus_version 2.11.5
solidus_frontend 2.11.5
paperclip 6.1.0

**To Reproduce**
I don't seem to have task sandbox

**Current behavior**

**Expected behavior**
I expected a shop to be visible.

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/57012516/111068974-a9eaaa00-84a9-11eb-88b4-24edb48d6560.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 86.0 (64-bit)

**Additional context**

A pull request has been created @ paperclip:
https://github.com/thoughtbot/paperclip/pull/2676

**Comment by jarednorman** [comment]
I'm on my phone at this moment, but if I remember correctly we are moving to the maintained fork of paperclip with the next release.

**Comment by iqre8** [comment]
What's the solution if I wanna stay on stable? Downgrade ruby to 2.7.2?

**Comment by jarednorman** [comment]
Yeah, for now 2.11 doesn't support Ruby 3.0.

**Comment by filippoliverani** [comment]
> What's the solution if I wanna stay on stable? Downgrade ruby to 2.7.2?

Another solution could be switching to ActiveStorage.
If your application is already running with Rails >= 6.1 you can migrate any esisting Paperclip uploads with a task like [this](https://gorails.com/episodes/migrate-from-paperclip-to-rails-active-storage) (_could need some updates for Rails 6.1_) and change [`AppConfiguration#image_attachment_module`](https://docs.solidus.io/spree/appconfiguration#image_attachment_module-instance_method) and [`AppConfiguration#taxon_attachment_module`](https://docs.solidus.io/spree/appconfiguration#taxon_attachment_module-instance_method) settings.

**Comment by zernie** [comment]
@filippoliverani does `kt-paperclip` support ruby 3.0?

**Comment by kennyadsl** [comment]
This has been addressed now. Solidus depends on kt-paperclip.
