### ISSUE TITLE
Orders: Unfulfilled orders/Shipment state filter missing

### ISSUE THREAD

**Issue by mntmn** [solidusio/solidus#4023]
In the backend under "Orders" (`/admin/orders`), it seems impossible to get a list of orders that are not yet shipped. It appears that there was a checkbox "Unfulfilled Orders" at one point which got removed in this commit: https://github.com/solidusio/solidus/commit/2d8cd38e704b765345e75a5ea61aaf79a399af92

Adding `?q[shipment_state_eq]=ready` to the `orders` URL works. So i guess there's just a dropdown missing in the filter form?

**Solidus Version**:
2.11.8

**Desktop (please complete the following information):**
All platforms.

**Comment by jarednorman** [comment]
That is a _very_ old commit that removed that. I don't see why we couldn't bring back the shipment state dropdown if people find it valuable.

**Comment by kennyadsl** [comment]
Yes, seems reasonable to add the dropdown to the order filters.
