### ISSUE TITLE
Extending API resources attributes in applications does not work in development anymore

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#4027]
See also: https://github.com/solidusio/solidus/discussions/3956. 

**Versions**:
2.9+, Rails 5.2+

**To Reproduce**

In a new store or in the sandbox add a new field to `Spree::Product`:

```sh
rails g migration AddLikesCountToSpreeProducts likes_count:integer
```

and add this to the `spree.rb` initializer:

```
# config/initializers/spree.rb

Spree::Api::ApiHelpers.product_attributes << :likes_count
```

It is something related to the new Rails Autoloading system that reloads the classes at each request, but the initializer is not reloaded, so the product_attributes is restored to the original value at each request. This means that when the classes are cached (in production for example), this should not happen.

**Current behavior**

```bash
$ rails c
2.6.6 :001 > Spree::Api::ApiHelpers.user_attributes
 => [:id, :email, :created_at, :updated_at]
```

**Expected behavior**

```bash
$ rails c
2.6.6 :001 > Spree::Api::ApiHelpers.user_attributes
 => [:id, :email, :created_at, :updated_at, :likes_count]
```

**Additional context**

This can be temporarily solved by opening the `ApiHelpers` module with

```ruby
# host_app/path/to/your_decorators/api_helpers_decorator.rb

Spree::Api::ApiHelpers.module_eval do
  user_attributes << :likes_count
end
```

But we really need a long-term solution. This is what I attempted, and seems to work:

```ruby
# solidus/api/app/helpers/spree/api/api_helpers.rb

# for each attribute:
def self.user_attributes
 Spree::Deprecation.warn("Please use Spree::Api::Config::user_attributes instead.")
 Spree::Api::Config.user_attributes
end
# We also need to deprecate accessing the ATTRIBUTES constant in this file.
```

```ruby
# solidus/api/lib/spree/api_configuration.rb

module Spree
  class ApiConfiguration < Preferences::Configuration
    # ..
    
    # for each ApiHelpers attribute:
    preference :user_attributes, :array, default: [:id, :email, :created_at, :updated_at]
  end
end
```

With this in the host app we can now just do:

```ruby
# host_app/config/initializers/spree.rb

Spree::Api::Config.configure do |config|
  config.user_attributes += [ :your_custom_attributes ]
end
```

- [ ] We also need to change the [edgeguides](https://edgeguides.solidus.io/customization/customizing-the-api#extending-existing-resources) accordingly.
- [ ] Check if this effects also setting PermittedAttributes, as described [here ](https://guides.solidus.io/developers/customizations/customizing-attributes.html#customizing-model-attributes).

**Comment by snada** [comment]
Hey Solidus community! :wave: 

I think I can take a look at this one. You can find the PR to both solidus and edgeguides linked in the PR.

My approach follows the comments made by @kennyadsl and moves the actual attributes location from the helper file to the config class, by defining preferences.

I think this problem would definitely also apply to PermittedAttributes, and could be easily solved following a similar approach.

I don't know if you feel like this should change in this very same PR or a following one would be better: however a decision on how to best handle this would be needed, as there could be a naming clash.

Would something like this work?

```ruby
Spree::Api::Config.configure do |config|
  config.user_attributes += [ :your_custom_attributes ]
  config.user_permitted_attributes += [ :your_custom_attributes ]
end
```
I'm sure there might be a better approach to this.

Thank you!

**Comment by kennyadsl** [comment]
Hey @snada, thanks for taking care of this one!

I think permitted attributes are not scoped into the `api` module because they also apply to frontend and backend (if I recall correctly). Permitted attributes are something that live in `core` and so in the `Spree::Config` class instead.

Anyway having some sort of granularity here would be a good option, for example I may want to permit `your_custom_attributes` only in the API and not in the frontend calls, so maybe having the preference in both places (with the API one inheriting from core) is something we want to explore. 

I think this should definitely be handled in another separate PR. I guess that keeping this issue open until that happens is enough. 

Thanks again! 🙏

**Comment by kennyadsl** [comment]
Starting from Solidus 3.1, we can use the following approach:

```
Spree::Api::Config.configure do |config|
  config.user_attributes += [ :your_custom_attributes ]
end
```

Thanks, @snada for completing the work in #4039.
