### ISSUE TITLE
Fresh Install Error - Login as Admin - Click on Order - Please use symbols for polymorphic route arguments.

### ISSUE THREAD

**Issue by cmittal791** [solidusio/solidus#4050]
1. Created new rails app and added 'solidus' gem
2. installed 'solidus' inside app with all defaults and sample data
3. opened http://localhost:3000/admin and logged in
4. clicked on orders and clicked on any 1 order
5. gets an error "Please use symbols for polymorphic route arguments."

![Screen Shot 2021-05-07 at 11 45 41 PM](https://user-images.githubusercontent.com/81350194/117492155-d47b4f80-af8e-11eb-9d94-b726f966d23f.png)

**Comment by benjaminwil** [comment]
There is a fix for this that has been merged, but it has not been released in a new version of the gem. 👍 

See https://github.com/solidusio/solidus/pull/4048.

**Comment by cmittal791** [comment]
Closing issue.
