### ISSUE TITLE
Admin user routes are sometimes wrong when using a custom user class

### ISSUE THREAD

**Issue by seand7565** [solidusio/solidus#4052]
[The admin users page](https://github.com/solidusio/solidus/blob/7cd6c4db6e352088be8588f4b469948b447945c1/backend/app/views/spree/admin/users/index.html.erb#L89-L94) uses the `spree.#{action}_admin_user_path` route in most places - and in fact, uses `edit_admin_user_path` directly, however in the actions on the index page, it instead uses `link_to_edit` and `link_to_destroy` and provides the `user` resource.

If the resource provided isn't named `user` (which will happen if you're using a custom user-like model), this breaks the admin user page - because it tries to fetch `edit_admin_#{user_class_name}_path` which probably doesn't exist.

It also creates inconsistencies where we're using `edit_admin_user_path` in some places (which works) and `edit_admin_#{user_class_name}_path` in others (which doesn't work all the time depending on your user class).

(most) of the rest of the admin user section works. The two places I see this issue are:
[The admin user index page](https://github.com/solidusio/solidus/blob/7cd6c4db6e352088be8588f4b469948b447945c1/backend/app/views/spree/admin/users/index.html.erb#L89-L94)
[The admin user store credit page](https://github.com/solidusio/solidus/blob/7cd6c4db6e352088be8588f4b469948b447945c1/backend/app/views/spree/admin/store_credits/index.html.erb#L60) (line 71-73 as well)
Though there are probably others I have missed

**To Reproduce**
* Start a new Rails app
* Install Devise, create a `Vendor` model, and run the devise generator on it
* Install Solidus without `solidus_auth_devise`, then run the spree:custom_user generator on Vendor (and add correct devise routes + current_vendor method to the generated auth helper), migrate
* Add `include Spree::UserMethods` to `vendor.rb` so you can use roles
* Create a vendor, add the admin role, then log in.
* Go the the admin users index page... whoops, it's broken!

**Current behavior**
Some admin user paths are generated as `admin_#{user_class_name}_path`, while others use the (correct) `admin_user_path`

**Expected behavior**
Since the admin user page was designed to work with any instance of `Spree.user_class`, the URLs should be adjusted to always generate as `spree_user_path`.

**Comment by waiting-for-dev** [comment]
Is it related to #4010?

**Comment by seand7565** [comment]
@waiting-for-dev Yep, I thought I checked this wasn't already an issue but I guess I missed it. 😛
