### ISSUE TITLE
TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by Ruk33** [solidusio/solidus#4055]
Unable to complete installation steps.

**Solidus Version**:

3.0.1

**To Reproduce**

1. Follow installation steps
2. Start rails server
3. Go to localhost:3000

**Current behavior**

The following error can be seen on the page

Showing /usr/local/bundle/gems/solidus_frontend-3.0.1/app/views/spree/shared/_head.html.erb where line #7 raised:

TypeError: Cannot read property 'version' of undefined
Trace of template inclusion: /usr/local/bundle/gems/solidus_frontend-3.0.1views/spree/layouts/spree_application.html.erb

Rails.root: /app

**Expected behavior**

The app works properly

**Screenshots**

![image](https://user-images.githubusercontent.com/1719111/117749151-a80e4000-b1e7-11eb-9f45-e682942af7e8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows using WSL and Docker
 - Browser [e.g. chrome, safari] Brave
 - Version [e.g. 22] V1.24.82

**Additional context**

- Tried my own custom docker version
- Tried using plain ruby and rails
- Tried with rails 5 and 6
- Tried using the docker version from master

In all scenarios, I get the same error.

**Comment by jlacaciom** [comment]
I have the same problem :(, i try in two different macbook and nothing. :(

**Comment by Ruk33** [comment]
As an additional note, if the line https://github.com/solidusio/solidus/blob/master/frontend/app/views/spree/shared/_head.html.erb#L8 gets commented out, the page loads correctly (without styles but at least it works)

**Comment by Ruk33** [comment]
Hello @jarednorman , yes I do

```
➜  ~ node -v
v15.4.0
➜  ~ npm -v
7.0.15
``` 

As a note, I also tried the dockerfile you guys have on the project and that didn't worked either (I used the sandbox application)

**Comment by jlacaciom** [comment]
Yes i have v14.16.1 and other mac v14.15.4 but still the error persist.

**Comment by benjaminwil** [comment]
Hello, I saw this same error yesterday.

It seems to be an incompatibility with the new version of `execjs` and Ruby <  2.7.

See https://github.com/rails/execjs/issues/99.

For me, the short-term solution is to lock to an older version of `execjs`

**Comment by jarednorman** [comment]
Either upgrade Ruby or downgrade execjs if you hit this issue. https://github.com/rails/execjs/issues/99#issuecomment-837369385

**Comment by Ruk33** [comment]
Ok, tried again with:

- Ruby 3.0.1
- Rails 6.1.3.2
- Solidus 3.0.1

Did no extra step and not it's working just fine:

![image](https://user-images.githubusercontent.com/1719111/117890293-4a333400-b28b-11eb-8c87-7cc75c733953.png)

**Comment by jarednorman** [comment]
Sounds like it's actually an autoprefixer-rails issue: https://github.com/ai/autoprefixer-rails/issues/203

**Comment by kennyadsl** [comment]
I'd keep this open until we have a solution to give it more visibility to the community.

**Comment by dominicsanto** [comment]
Still experiencing this issue with the following :


    Ruby 3.0.1
    Rails 6.1.3.2
    Solidus 3.0.1

**Comment by kennyadsl** [comment]
@dominicsanto we are not seeing the issue anymore in our specs. Can you share your `Gemfile.lock` in a gist please?

**Comment by dominicsanto** [comment]
@kennyadsl I had to upgrade my version of `autoprefixer-rails` to use `10.2.5.0`. Now the store is loading correctly

**Comment by waiting-for-dev** [comment]
> I had to upgrade my version of autoprefixer-rails to use 10.2.5.0. Now the store is loading correctly

However, keep in mind [it's not compatible with Ruby 3.0](https://github.com/ai/autoprefixer-rails/issues/203#issuecomment-838566156), although Solidus is not 100% compatible either yet. A definitive fix from `autoprefixer-rails` side [should be available soon](https://github.com/ai/autoprefixer-rails/issues/203#issuecomment-838789599).
