### ISSUE TITLE
Create product through API doc is misleading

### ISSUE THREAD

**Issue by Ruk33** [solidusio/solidus#4058]
Create a product by following the documentation here https://solidus.docs.stoplight.io/api-reference/products/create-product is misleading since all the data must be sent through a "product" key (which is not mentioned at all in the documentation and was able to figure it out by looking at the code).

**Solidus Version**:

NA

**To Reproduce**

1. Try to create a product using the API endpoint

**Current behavior**

The documentation doesn't mention that the product's information must be sent inside of a "product" key, thus, the endpoint fails with a validation error.

**Expected behavior**

The documentation mentions the product key.

**Screenshots**

![image](https://user-images.githubusercontent.com/1719111/117898519-7f478280-b29b-11eb-8870-43243e3cf37d.png)

![image](https://user-images.githubusercontent.com/1719111/117898546-8ec6cb80-b29b-11eb-88db-c9738bbe5b22.png)

(Notice how the generated code doesn't include the product key)

Below is how it should be sent
![image](https://user-images.githubusercontent.com/1719111/117898628-c9c8ff00-b29b-11eb-9887-975dbe868d7c.png)

(Notice how the info gets sent inside of `{ "product": { ... } }`.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] NA
 - Browser [e.g. chrome, safari] NA
 - Version [e.g. 22] NA

**Additional context**

NA

**Comment by kennyadsl** [comment]
Thanks for reporting. I honestly was aware of this due to https://github.com/solidusio/solidus/discussions/3983. I'm started taking a look at how to fix this and I think I'll submit a solution soon.

**Comment by kennyadsl** [comment]
Tracking down the list of request bodies we need to update in the openapi doc file:

- [ ] taxon
- [ ] line-item
- [ ] payment
- [ ] zone
- [ ] product-property
- [ ] stock-location
- [ ] product
- [ ] property
- [ ] address
- [ ] order  
- [ ] image
- [ ] variant
- [ ] user
- [ ] return-authorization
- [ ] customer-return
- [ ] option-value
- [ ] stock-item
- [ ] taxonomy

- [ ] coupon-code
- [ ] shipment

I will submit one or more PR to address this problem.

**Comment by kennyadsl** [comment]
This is fixed now for all endpoints. Eg. https://solidus.docs.stoplight.io/api-reference/products/create-product

Thanks for opening the issue!
