### ISSUE TITLE
Return item model: inventory_unit association is set as optional but there's also a validation presence

### ISSUE THREAD

**Issue by blocknotes** [solidusio/solidus#4086]
It looks like there's a conflict between the association definition and a validation rule.

The association in the `return_item` model:
`belongs_to :inventory_unit, inverse_of: :return_items, optional: true`
https://github.com/solidusio/solidus/blob/master/core/app/models/spree/return_item.rb#L33

The validation rule some lines below:
`validates :inventory_unit, presence: true`
https://github.com/solidusio/solidus/blob/master/core/app/models/spree/return_item.rb#L45

**Solidus Version**:
Master @ 5f35714

**Current behavior**
Using `shoulda-matchers` gem to check the association fails with or without `.optional`:
`it { is_expected.to belong_to(:inventory_unit).inverse_of(:return_items).touch(true).optional }`

_Expected Spree::ReturnItem to have a belongs_to association called inventory_unit (and for the record not to fail validation if :inventory_unit is unset; i.e., either the association should have been defined with `optional: true`, or there should not be a presence validation on :inventory_unit)_

While removing `optional`:
_Expected Spree::ReturnItem to have a belongs_to association called inventory_unit (and for the record to fail validation if :inventory_unit is unset; i.e., either the association should have been defined with `required: true`, or there should be a presence validation on :inventory_unit)_

**Expected behavior**
Perhaps we could remove the validation rule introduced with this old commit:
https://github.com/solidusio/solidus/commit/108e01331a35ec4a59e7253d55d3cce3339d0e50#diff-81e13a48112d990ac138e28c8ceebadc3bbb6c8db28b8c9eef50a0b23bcf9efaR20
But we need to make some extra checks, there are references in the model itself that could break in some situations.

**Comment by Brian-Demon** [comment]
I'm having trouble reproducing the issue you are experiencing. Where did you place the expectation provided? `it { is_expected.to belong_to(:inventory_unit).inverse_of(:return_items).touch(true).optional }`

**Comment by Brian-Demon** [comment]
I was able to reproduce your issue by modifying the code you provided to:
`it { should belong_to(:inventory_unit).inverse_of(:return_items).optional }` for including the optional check...
and `it { should belong_to(:inventory_unit).inverse_of(:return_items) }` when not checking for optional.

For each I received the following outputs:

`it { should belong_to(:inventory_unit).inverse_of(:return_items)}`
```
Expected Spree::ReturnItem to have a belongs_to association called inventory_unit (and for the record to fail validation if :inventory_unit is unset; i.e., either the association should have been defined with `required: true`, or there should be a presence validation on :inventory_unit)
```

`it { should belong_to(:inventory_unit).inverse_of(:return_items).optional }`
```
Expected Spree::ReturnItem to have a belongs_to association called inventory_unit (and for the record not to fail validation if :inventory_unit is unset; i.e., either the association should have been defined with `optional: true`, or there should not be a presence validation on :inventory_unit)
```

Does this seem to replicate your issue accurately?

**Comment by jarednorman** [comment]
I'm not clear on whether the change we need is:

1. Remove the validation and the `optional: true` on the association.
2. Remove the validation and keep the `optional: true` on the association.
3. Something else entirely.

I would certainly appreciate some clarity on what the impacts are of this change. Assuming we don't want to change the functionality here, I'd lean towards option 1, but I'm also not clear if there are edge cases where this could have some kind of impact.

**Comment by Brian-Demon** [comment]
I would also love clarity. My approach was to make the validation only apply when the association exists to satisfy the optional state. If that is not the desired state then I’m happy to adjust my PR.

**Comment by spaghetticode** [comment]
I agree option 1 seems the way to go, as it should be consistent with the current behavior while removing the code inconsistency... but of course this needs to be verified.
