### ISSUE TITLE
"Deploy to Heroku" link in README.md build fails 

### ISSUE THREAD

**Issue by murraycs** [solidusio/solidus#4097]
When trying to one-click deploy a demo on Heroku from the link in the README.md file, the build fails. 

**To Reproduce**
1. Visit the Github Repository
2. Click the purple "Deploy to Heroku" button
3. Fill out required information on Heroku
4. Click "Deploy App"

**Current behavior**
The Heroku build fails. I have pasted the build log here: https://gist.github.com/murraycs/3f43301159dbf6a2affa00496362bfc5

**Expected behavior**
App should deploy to Heroku

**Desktop (please complete the following information):**
 - OS: Pop_OS 20.10 (Ubuntu-based Linux)
 - Browser: Firefox
 - Version 89.0

**Comment by RyanofWoods** [comment]
Hi there! It seems that you are using a `Rails` version that is relying on `mimemagic` at version 0.3.5. Unfortunately, there were some licensing issues with `mimemagic` and so all versions before 0.3.5 were pulled. See more [here](https://github.com/rails/rails/issues/41750).

To solve your issue, here's 3 methods:
- Add `mimemagic `to your `Gemfile` and use a 0.3.5 ref. [Example](https://github.com/rails/rails/issues/41757#issuecomment-808024283)
- Update the gem `mimemagic` -> `bundle update mimemagic` (check it's compatibility)
- Update Rails to a version that no longer relies on `mimemagic` such as: 5.2.5, 6.0.3.6 and 6.1.3.1

**Comment by RyanofWoods** [comment]
Hi there @murraycs 😊 Thank you raising this issue and for the clear outline, the build log is very helpful!

I will create a PR to fix this right away.

**Comment by dpaola2** [comment]
I believe this is easily solved by bumping the version of `mimemagic` in the Gemfile via `bundle update --conservative mimemagic`

**Comment by RyanofWoods** [comment]
Hi @murraycs, [PR](https://github.com/solidusio/solidus-example-app/pull/25) has been merged and issue has been fixed. Thanks again for raising the issue! 👍

**Comment by murraycs** [comment]
Thanks for fixing that and you're welcome! I'll give it a try sometime this week - looking forward to trying Solidus (and having a nice way to refresh myself on how to use Heroku after a decade...)

**Comment by RyanofWoods** [comment]
Awesome, good luck and have fun! 🙂 @murraycs
