### ISSUE TITLE
How to block order if product is out of stock

### ISSUE THREAD

**Issue by dcalixto** [solidusio/solidus#4141]
Hello, i'm using Solidus 3.0.1 and would like to know how to block the user from order more than have on stock.
because if your stock has 3 products on product page and checkout the user can order more than 3, even if your stock has only 3 products.

**Comment by jarednorman** [comment]
Hey @dcalixto, we use GitHub Issues exclusively for bugs and feature requests, not for question and troubleshooting. You can head over to the [Solidus Slack](https://slack.solidus.io) or our [Troubleshooting Discussions board](https://github.com/solidusio/solidus/discussions/categories/troubleshooting).

For what it's worth, if the product isn't backorderable, then a customer shouldn't be able to checkout with more stock than you have.
