### ISSUE TITLE
can't run bin/rails generate solidus:install on M1 MacBook

### ISSUE THREAD

**Issue by NotSaifA** [solidusio/solidus#4143]
OS: Big Sur 11.5.1
ruby: 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
rails: 6.1.4
sqlite3: 3.32.3 2020-06-18 14:16:19 02c344aceaea0d177dd42e62c8541e3cab4a26c757ba33b3a31a43ccc7d4aapl

I am trying to install solidus using the [guide](https://guides.solidus.io/developers/getting-started/first-time-installation.html), but when I try to generate the config file using bin/rails generate solidus:install, I get this error:

/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.bundle, 0x0009): could not use '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.bundle' because it is not a compatible arch - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.bundle (LoadError)
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi.rb:5:in `rescue in <main>'
	from /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi.rb:2:in `<main>'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<main>'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<main>'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5:in `<main>'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/sass-rails-6.0.0/lib/sass-rails.rb:1:in `<main>'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler.rb:114:in `require'
	from /Users/saif/solidus_test/config/application.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
	from /Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

**Comment by jarednorman** [comment]
This isn't an issue with Solidus: you appear to be trying to use gems (specifically `ffi`) compiled for the wrong architecture. I can't say without more information what specifically you're doing wrong, but we don't use GitHub issues for troubleshooting.

You could post in [the Troubleshooting Discussions category](https://github.com/solidusio/solidus/discussions/categories/troubleshooting), but you're better off trying to get a vanilla Rails app set up before continuing with Solidus, since the error above entirely involves default Rails dependencies and not anything to do with Solidus.
