### ISSUE TITLE
Why prefer solidus over spree

### ISSUE THREAD

**Issue by ugintl** [solidusio/solidus#4153]
It is a spree fork. What makes it better or different than spree?

**Comment by dhonig** [comment]
Github issues aren't the best place for this kind of question.
Please join us in the slack channel where you will be welcomed with enthusiasm and find many community members 
who will be more than willing to share there perspectives and experiences with you.

**Comment by jarednorman** [comment]
Yep, Slack or [GitHub Discussions](https://github.com/solidusio/solidus/discussions) are the place for this conversation. Issues is for bugs and feature requests and the like.
