### ISSUE TITLE
undefined method `paths' when running solidus update generator

### ISSUE THREAD

**Issue by AlistairNorman** [solidusio/solidus#4178]
Running the `rails g solidus:update` with solidus version 3.1.0 and Rails version < 6.1 causes the following error. 

**Solidus Version**:
3.1.1

**To Reproduce**
Create a fresh install with Solidus 3.1.1 and Rails 6.0.0
Run `rails g solidus:update`

**Current behavior**
`NoMethodError: undefined method `paths' for #<Rails::Paths::Path:0x00007f8721d650b0>`

**Expected behavior**
The solidus update generator runs without errors

**Desktop (please complete the following information):**
 - OS: MacOS 11.5.2

**Additional context**
The error is coming from `Core.has_install_generator_been_run?`

**Comment by waiting-for-dev** [comment]
Thanks for reporting @AlistairNorman , we'll look into this and let you know

**Comment by AlistairNorman** [comment]
Oh I just saw that you already sent up a PR. Thanks!

**Comment by waiting-for-dev** [comment]
Yeah, @AlistairNorman, you can use that PR in the meantime until we merge it and release a new patch version. Thanks for spotting it!
