### ISSUE TITLE
Heroku Deployment does not work

### ISSUE THREAD

**Issue by techmusclepoints** [solidusio/solidus#4183]
I am attaching the log.

-----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
 !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
			Detected buildpacks: Ruby,Node.js
			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
-----> Ruby app detected
-----> Installing bundler 2.2.21
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.7.1
-----> Installing dependencies using bundler 2.2.21
       Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
       Your bundle only supports platforms ["x86_64-darwin-19"] but your local platform
       is x86_64-linux. Add the current platform to the lockfile with `bundle lock
       --add-platform x86_64-linux` and try again.
       Bundler Output: Your bundle only supports platforms ["x86_64-darwin-19"] but your local platform
       is x86_64-linux. Add the current platform to the lockfile with `bundle lock
       --add-platform x86_64-linux` and try again.
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

**Comment by afdev82** [comment]
It doesn't seem to be related with Solidus.
Have you already tried what the log suggests?

```
Add the current platform to the lockfile with bundle lock --add-platform x86_64-linux and try again.
```

**Comment by jarednorman** [comment]
I've encountered this and can confirm that doing the thing that the error message tells you to do fixed it for me.

If you're seeing this issue after doing the thing the error tells you to do, please report back with more info and what you've tried.
