### ISSUE TITLE
Add Promotion.sale field

### ISSUE THREAD

**Issue by jordan-brough** [solidusio/solidus#419]
Let's add a spree_promotions.sale fie to explicitly mark "sale" promotions.  i.e., promotions that should automatically be applied site-wide to everyone's orders.

Right now a promotion is considered a "sale" promotion if it has no codes attached to it and no path set on it.  e.g. see [this code](https://github.com/solidusio/solidus/blob/402b165/core/app/models/spree/promotion_handler/cart.rb#L42-L57).

There are two problems with the current situation:

1) The lookup in [this code](https://github.com/solidusio/solidus/blob/402b165/core/app/models/spree/promotion_handler/cart.rb#L42-L57) (same as previous link) gets very slow when there are lots of promotions (it took ~500ms for 700,000 promotions, per @jhawthorn's testing).  No one could think of a more efficient way of performing that query without changing the db structure in some way.

2) It is easy to accidentally create a "sale" promotion in the admin and accidentally apply it automatically to all orders in your store. This has happened to at least a couple actual stores.

**Comment by jordan-brough** [comment]
cc @gmacdougall @jhawthorn @alexstoick. This is from the solidus chat room discussion.

**Comment by magnusvk** [comment]
I'm :+1: on doing this. I think the current behavior is frankly kind of crazy.

Naming suggestion: `apply_automatically`

**Comment by alexstoick** [comment]
:+1: on this!

**Comment by athal7** [comment]
:+1: on this and on `apply_automatically`

**Comment by tomcartwrightuk** [comment]
Is anyone actively looking into this? If not, I will take a look.

**Comment by athal7** [comment]
@tomcartwrightuk go for it!
