### ISSUE TITLE
Security Contact Needed

### ISSUE THREAD

**Issue by agustingianni** [solidusio/solidus#4207]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

If you prefer to contact us by email, please reach out to securitylab@github.com with reference to <GHSL-ID-HERE>.

Thank you,  
Agustin Gianni
GitHub Security Lab

**Comment by kennyadsl** [comment]
@agustingianni thanks for reporting. We already have a security policy at https://solidus.io/security/. Does it work?

**Comment by agustingianni** [comment]
Hello @kennyadsl thank you for getting back at me. I've used security@solidus.io to report the issue on July 12 but I did not get an answer back, maybe the email is not working?

**Comment by kennyadsl** [comment]
Let me check if the sync on that email is still working. What about using HackerOne in the meantime? Alternatively, I can open the advisory here, as you prefer.

**Comment by agustingianni** [comment]
Hello thank you @kennyadsl if it is not much of a hassle to open the issue as a GitHub advisory that would be ideal for us. Let me know if that works for you.

Thank you.

**Comment by jarednorman** [comment]
@agustingianni I've created a draft and invited you to it.

**Comment by agustingianni** [comment]
Hello @jarednorman thank you for creating the advisory, I will post the details there.
