### ISSUE TITLE
SSL on fonts.googleapis.com 

### ISSUE THREAD

**Issue by jarednorman** [solidusio/solidus#4217]
We need to use SSL to access font.googleapis.com. Requests using regular HTTP no longer work.

There are current three PRs open that cover this for the support versions (thanks @RyanofWoods!):

- #4210
- #4211
- #4212

As I noted [here](https://github.com/solidusio/solidus/pull/4210#issuecomment-982115850), we may want to backport that to even more versions as this is liable to break specs on any extensions that still support older versions and run feature specs.

@Noah-Silvera has volunteered to do at least v2.9 and v2.10 which she needs for [our TaxJar extension](https://github.com/supergoodsoft/solidus_taxjar) if we're happy to merge the fixes into unsupported versions.

**Comment by jarednorman** [comment]
@Noah-Silvera You've got the go-ahead to PR those older versions.

**Comment by jarednorman** [comment]
We won't need to release new versions of those unsupported versions, since simply merging fixes should resolve CI issues you're seeing.

**Comment by waiting-for-dev** [comment]
I already merged the one for 2.10. As I think it's the only one needed, I'm going to close it. Thanks for working into it!

**Comment by waiting-for-dev** [comment]
Oh, I just saw a PR for 2.9. Reopening!!

**Comment by kennyadsl** [comment]
Closing, we are not supporting 2.9 anymore.
