### ISSUE TITLE
Fix TestingSupport Country Factory states_required

### ISSUE THREAD

**Issue by RyanofWoods** [solidusio/solidus#4270]
The mentioned attribute is commented out due to issues with Solidus' tests. 

https://github.com/solidusio/solidus/blob/a6c2ceeb2ee6bff832080ebb11773f7b6e4c2df0/core/lib/spree/testing_support/factories/country_factory.rb#L23-L24

This should be fixed so that anyone developers can use the factory and not have to modify the factory to get its intended behaviour.

**Solidus Version**:

1.2 and above.

**Current behavior**

The attribute will always become `false` as this is the attribute's default value.

**Expected behavior**

Use carmen to get the correct `states_required` value.

**Comment by RyanofWoods** [comment]
WIP

**Comment by kennyadsl** [comment]
This bugfix will be available from Solidus 3.3!
