### ISSUE TITLE
Revisit cache invalidation strategy

### ISSUE THREAD

**Issue by athal7** [solidusio/solidus#428]
While the current model-level key-based caching strategy does provide better guarantees of realtime information, it has some downsides, including:

1) Slower writes due to nested/circular touches
2) Cache keys that require db loads to build, potentially with nested information, causing cache hits to be slower than they could be.

One potential alternative that I'd like to throw out there:
1) A single cache repository that controllers and fragment caches would use to fetch and set their caches. 
2) In that repository, the cache key definition would state all of its model dependencies
3) When a model is updated, it tells the cache repository to clear any necessary caches
4) Remove all model to model touches (except for ones that trigger denormalization)

**Comment by mtomov** [comment]
I would be very curious to see an implementation of this. Aren't there even gems for that, that put such a framework in place? It can't be that everyone is doing it the rails "touch" way.

Another downside
3) Locks & lock violations causing .. well lots of trouble

**Comment by gmacdougall** [comment]
Closing due to staleness
