### ISSUE TITLE
International shipping method

### ISSUE THREAD

**Issue by Nissrine-laal** [solidusio/solidus#4306]
Hello
### I just started to maintain a website that was developped by another team.

I'm new to **ROR, spree and solidus,** which r the technologies they used for the website. 

The problem i'm facing now is that i have to create a new functionnality for the website, i need to add an **_international shipping_** method, the shipping fees will be different for **each** country with also a different tax rate. I managed to create the method and display it but i can't seem to wrap my head around how i'm gonna give the admin the possibility to modify each shipping fee in the **dashboard** and how to create a **new table** in database to save the fees and stuff. The actual website calculates the shipping fee **before** displaying the address page in checkout which complicates it a lil bit more.

I'm just curious if anyone have tried before to add the international shipping, how can I do that? What files to add? Controllers? Helpers? Decorators? I'm not even sure what's the difference between all of that..

Any help would be really appreciated. Thanks.

**Comment by jarednorman** [comment]
We using issues for reporting issues and for RFCs, not for support. I'll respond over on [the discussion you opened](https://github.com/solidusio/solidus/discussions/4305).
