### ISSUE TITLE
kt-paperclip version mismatch

### ISSUE THREAD

**Issue by tvdeyen** [solidusio/solidus#4308]
`kt-paperclip` is open ended in v2.11.5 but constrained to v6 in latest versions.
This allows paperclip v7 in 2.11.15 and only v6 in 3.0 and above. Not sure if this intentional
or a mistake. It surely is confusing for folks updating from v2 to v3

**Solidus Version**:

`>= v2.11.15`

**To Reproduce**

See the core gemspec in `master` https://github.com/solidusio/solidus/blob/master/core/solidus_core.gemspec#L44
The gemspec in v2.11.15 https://github.com/solidusio/solidus/blob/v2.11/core/solidus_core.gemspec#L42

Not sure what is the expected version. Happy to provide a PR if we agree on a version we want to support.

**Comment by spaghetticode** [comment]
Definitely not intentional (I introduced KT-Paperclip on v2.11), I agree we should have the same high version constraint that we have in 3.x

**Comment by kennyadsl** [comment]
@tvdeyen do you think we can close this one now? BTW, I saw that master now allows [kt-paperclip 7 as well](https://github.com/solidusio/solidus/blob/master/core/solidus_core.gemspec#L44).

**Comment by tvdeyen** [comment]
Yes
