### ISSUE TITLE
What do order approvals mean in general?

### ISSUE THREAD

**Issue by gvaughn** [solidusio/solidus#431]
In working through these PRs:
https://github.com/solidusio/solidus/pull/424
https://github.com/solidusio/solidus_signifyd/pull/9

we (@athal7, @jordan-brough and myself) wanted to disambiguate the `ready` event and state in the Shipment. The PR in progress has the event currently named `ready_to_ship` but we thought about calling it `approve` when we ran across the `approve` method of OrderContents (https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order_contents.rb#L41). It appears to be an isolated island of functionality that just sets metadata about an approval, but doesn't actually do anything. How do other stores use that? Should it additionally try to `ready_to_ship` the shipments of the order too?

**Comment by bbuchalter** [comment]
Pinging this open issue to @jhawthorn as I've wondered about this feature too. Is this something that can get extracted to a gem?

**Comment by fastjames** [comment]
I had the same question, so I dug in a little bit and found that the approved feature was introduced here:
https://github.com/solidusio/solidus/commit/a0c69672a96f1a11d2dad265ac353d589eb099ae

it was intended to appear when an order is considered "risky." Beyond that I can't tell that clicking the button does much, so maybe the feature was never completed?

**Comment by jasonfb** [comment]
I fully support it being extracted if it is an island of functionality. We are heavily dependent on a complex hybrid system that relies on both Kount scoring and our own internal fraud tools to have orders in this 'limbo' (completed but not sent to the 3PL) state until they are approved by our fraud department. 

If Solidus is to have no fraud functionality, then I think extracting it into a gem makes a lot of sense. But this seems odd to me, as hacking & fraud are both seriously on the rise globally, it seems like a robust fraud-management (at least, to gate the orders) should be a first-class functionality in a modern e-commerce platform.

**Comment by cbrunsdon** [comment]
We very much agree that fraud needs to be treated as a first-class citizen in solidus, but the implementation we inherited from the Spree codebase is not anywhere near what is required.

As we plan solidus fraud management going forward, it is unlikely to have anything to do with the 'approved' state.
