### ISSUE TITLE
[Admin] Emptying the cart doesn't update the cart/order totals

### ISSUE THREAD

**Issue by spaghetticode** [solidusio/solidus#4430]
**Solidus Version**:
all, including master

**To Reproduce**
Please check the attached video: https://www.loom.com/share/ad878419beab485c84deb35c13a3413d

Add an item to the cart, and then push the `Empty Cart` button. 
All items will be removed from the cart, but given the request is remote the totals shown on the page are not being updated. 
This is a very minor issue, but I think it's still worth reporting.

**Current behavior**
Order totals on the page are not updated (should be set to zero).

**Expected behavior**
Order totals on the page are updated to zero.

**Comment by maniSHarma7575** [comment]
Hi @spaghetticode, @kennyadsl can I take up this issue? 😊

**Comment by kennyadsl** [comment]
Sure thing.

**Comment by maniSHarma7575** [comment]
@kennyadsl PR: https://github.com/solidusio/solidus/pull/4655

**Comment by kennyadsl** [comment]
Thanks @maniSHarma7575!
