### ISSUE TITLE
Update User account in the admin gives password error

### ISSUE THREAD

**Issue by afdev82** [solidusio/solidus#4441]
I'm trying to set a role for one user in the admin interface, but I'm getting an error because the password field is empty.

For sure I don't want to change the password of the user to just update the profile.
How this is supposed to work? I see the empty password fields in the form.
I've found some issues and PRs related to admin ability to reset password, so I don't know if it's already a known issue.

**Solidus Version**:
v3.1.6

**To Reproduce**

1. Go to Users using the menu on the left in the admin interface
2. Click on one email in the list
3. Click on a role in the form and press Update

**Current behavior**
It throws the following error:
> 
> 
> 1 error prohibited this record from being saved:
> 
> There were problems with the following fields:
> 
>     Password can't be blank

**Expected behavior**
It saves the user profile.

**Additional context**
I've installed the `solidus_user_roles` gem.

**Comment by kennyadsl** [comment]
@afdev82 Hey there, I just tried on the [Solidus Demo](http://demo.solidus.io/admin/users/1/edit) and it works. I think it's something with the extension itself. I'm going to close this issue here but feel free to reopen it on the extension's repository. Thanks for reporting!

**Comment by afdev82** [comment]
Thank you for your feedback!
I will do that or fix myself if I have time.
