### ISSUE TITLE
ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect string value: '\xC4\x81n' for column `store`.`spree_states`.`name` at row 1

### ISSUE THREAD

**Issue by joyboy67** [solidusio/solidus#4443]
Hello, I recently installed solidus, but I can't login on admin panel (/admin) with the default credidentals `admin@example.com` and `test123`

I think it's because the failure of `rake db:seed`

**Solidus Version**:
3.2.0.alpha

**To Reproduce**
rake db:seed

**Current behavior**
```
$ rake db:seed      
Loading seed file: stores
Loading seed file: store_credit
Loading seed file: countries
Loading seed file: return_reasons
Loading seed file: states
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect string value: '\xC4\x81n' for column `store`.`spree_states`.`name` at row 1
/home/computer/store/db/seeds.rb:9:in `<main>'

Caused by:
Mysql2::Error: Incorrect string value: '\xC4\x81n' for column `store`.`spree_states`.`name` at row 1
/home/computer/store/db/seeds.rb:9:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

**Desktop (please complete the following information):**
 - OS: OpenBSD 7.1 x64
 - Ruby: 3.1.2p20
 - Rails: 7.0.3
 - MariaDB: mariadb-server-10.6.7p0v1
 - Browser: Firefox
```
$ bundle info mysql2
   * mysql2 (0.5.4)
```

**Comment by joyboy67** [comment]
I think the problem is from mysql encodage ->
https://github.com/spree/spree/issues/6582#issuecomment-133496788

**Comment by gsmendoza** [comment]
Hello @joyboy67 ! I'm investigating the issue you're having. Can you provide me the following information:

* Rails version
* MySQL version
* MySQL gem and its version

Thank you!

**Comment by gsmendoza** [comment]
Hi again @joyboy67 ! I was able to install Solidus 3.2.0.alpha successfully with the following specs:

* OS: Pop!_OS 22.04 LTS
* ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
* Rails 7.0.3
* solidus (3.2.0.alpha) rev 78f68a71d5bc0ca93383a4b1ec5a2e4e41f17af1
* MySQL Server version: 8.0.29-0ubuntu0.22.04.2 (Ubuntu)
* mysql2 gem (0.5.4)

This is my default database configuration:

```
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password:
  host: localhost
```

With the other specs, I was able to run `rake db:seed` successfully. I'm also able to log in to the admin panel.

Tomorrow, I'll try installing Solidus on OpenBSD.

**Comment by joyboy67** [comment]
Thank you @gsmendoza for your help :)

I have this following configuration :
- Rails version: _7.0.3_
- MySQL version: _mariadb-server-10.6.7p0v1_
- MySQL gem and its version: _mysql2 0.5.4_

**Comment by gsmendoza** [comment]
Good to hear that you were able to find the cause of the issue! :)

**Comment by joyboy67** [comment]
> Good to hear that you were able to find the cause of the issue! :)

Yes, thanks again for your help :)
