### ISSUE TITLE
Incorrect validation message for `category_id` on `Spree::StoreCredit`

### ISSUE THREAD

**Issue by johnpitchko** [solidusio/solidus#4468]
When creating a store credit via console, I received a validation error. The message indicated that the error was a missing/invalid store credit type attribute, however the real cause of the issue was a missing store credit category attribute.

**Solidus Version**:

**To Reproduce**

1. Sign into Rails console.
2. Execute the following command (after assuring referential tables are populated): 
```
Spree::StoreCredit.create!(user_id: Spree::User.first.id, amount: 500.00, currency: 'USD', type_id: 1, created_by_id: Spree::User.first.id)
```
3. Observe the error message:
```
ActiveRecord::RecordInvalid: Validation failed: Credit Type can't be blank
```
2. Execute the adjusted command, which includes the `category_id`:
```
Spree::StoreCredit.create!(user_id: Spree::User.first.id, amount: 500.00, currency: 'USD', type_id: 1, created_by_id: Spree::User.first.id, category_id: Spree::StoreCreditCategory.first.id)
```
4. Observe the record created successfully.

**Current behavior**

**Expected behavior**

The error message should state that the missing attribute is the `category_id`, or that `Category can't be blank`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 12.4
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] 15.5

**Additional context**

**Comment by gsmendoza** [comment]
Thanks @johnpitchko ! I was able to confirm the issue on a [fresh Solidus 3.1 app](https://github.com/gsmendoza/solidus-4468). WIll add this to our list of tickets :+1:

**Comment by johnpitchko** [comment]
Thank you @gsmendoza I opened [this PR](https://github.com/solidusio/solidus/pull/4481) to resolve but note its branched off _another_ PR to fix a Docker issue.

**Comment by gsmendoza** [comment]
@waiting-for-dev Since https://github.com/solidusio/solidus/pull/4481 has been merged, I think we can close this issue now.

**Comment by waiting-for-dev** [comment]
Yeah, thanks @gsmendoza
