### ISSUE TITLE
Solidus 2.11.17 causes Psych to resolve to v4 which breaks Rails lower than v7

### ISSUE THREAD

**Issue by RyanofWoods** [solidusio/solidus#4476]
Due to the new [2.11.17 patch](https://github.com/solidusio/solidus/pull/4455/commits/85087700e1a19557544bf3b91355cfd12dd2afd1), `solidus_core` now causes `psych` to resolve at 4+ (if not already locked). Psych v4 introduced breaking changes (see additional notes).

Only Rails 7 has [patches](https://github.com/rails/rails/commit/179d0a1f474ada02e0030ac3bd062fc653765dbe) to make it compatible. This means if stores are using Rails lower than 7, Rails commands break.

**Solidus Version**:

2.11.17

**To Reproduce**
1. Use solidus 2.11.17
2. Use rails lower than 7, e.g. 6.1.6.1
3. Trigger bin/rails, e.g. by `bundle exec rails server`

Ruby version used: `2.7.5`

**Current behavior**

Rails commands fail with this error:
```
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/psych-4.0.4/lib/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Unknown alias: development (Psych::BadAlias)
```

**Expected behavior**

Rails to still work.

Changing the dependency lock to only have a minimum Psych version could resolve the issue.
https://github.com/solidusio/solidus/blob/86b70ac7d47a0f52927945449502631b30613e22/core/solidus_core.gemspec#L44

Otherwise, even updating the change/release log to indicate that stores need to lock Psych could be useful 👍 

**Additional context**

Ruby discussing the breaking change from Psych v4
https://bugs.ruby-lang.org/issues/17866

**Comment by RyanofWoods** [comment]
I am happy to make PR if desired

**Comment by gsmendoza** [comment]
Hi @RyanofWoods! I wasn't able to reproduce your error. I tested the issue on this [app](https://github.com/gsmendoza/rails_6161_store/tree/solidus_2_11_17_ruby_2_7_5). When you run that app on your machine, do you still encounter the error?

**Comment by RyanofWoods** [comment]
> Hi @RyanofWoods! I wasn't able to reproduce your error. I tested the issue on this [app](https://github.com/gsmendoza/rails_6161_store/tree/solidus_2_11_17_ruby_2_7_5). When you run that app on your machine, do you still encounter the error?

I realise now that it isn't just due to a mixture of solidus `2.11.17` and rails `<7`. After removing our `figaro` gem, the app works as expected. However, I was not able to reproduce it in a new repo with these gems, so there's more to it. (Sorry I should have tried this first.) @gsmendoza 

Although the bump of psych was caused by the solidus patch, this error isn't purely down to solidus. So I will close the ticket for now.
