### ISSUE TITLE
Cannot use a custom `PaymentSource` with fields that aren't defined in `PermittedAttributes` as `source_attributes`

### ISSUE THREAD

**Issue by alecvn** [solidusio/solidus#4478]
**Description**
When writing a custom `PaymentSource` by [following the tutorial](https://edgeguides.solidus.io/advanced-solidus/payments-and-refunds/), it is suggested that an `auth_token` field could be defined for the payment source which could then be submitted through a form on the `payment` action.

I however encountered the validation error mentioned in #4067 even though I had followed the tutorial exactly.  After some digging I found that a source isn't being instantiated, and that because the source parameter (`auth_token`) isn't being passed through because [it's not a permitted paramter](https://github.com/solidusio/solidus/blob/0c6ad9067432781c104f395fa6b82be086f49b6c/core/lib/spree/permitted_attributes.rb#L94).

I looked around but found no way that those parameters are extended by declaring or installing a custom payment source, unless I missed it somewhere.  If there is a way, please point me in the right direction, otherwise if this is a bug, I'd be happy to contribute a fix, just might need some direction again.

**Solidus Version**
3.1.7

**To Reproduce**
Follow the tutorial: https://edgeguides.solidus.io/advanced-solidus/payments-and-refunds/

**Current behavior**
Custom payment source cannot have custom fields.

**Expected behavior**
Custom payment source should be able to have custom fields.

**Comment by benjaminwil** [comment]
You can customize the the permitted attribute from an initializer. For my payment integration I needed to add:

```
Spree::PermittedAttributes.checkout_payment_attributes << :authorisation_token
```

It'd absolutely be worth adding this context to documentation you linked to, or by linking to documentation that's specifically about Solidus's permitted attributes. In the non-edge guides, [that's in the Customizing Model Attributes article](https://guides.solidus.io/developers/customizations/customizing-attributes#allowing-custom-attributes-to-be-saved), but that's maybe not the most obvious place for it if someone is, say, working through a payment integration and needs to change some permitted controller parameters.

**Comment by alecvn** [comment]
Thank you. I suspected it was probably configurable somewhere.

For the sake of completeness, I agree that the tutorial on writing a custom `PaymentMethod` should either include that code snippet, or the link to that article. I see the edge documents are hosted on another repo, I'll close this issue and make a pull request there.

**Comment by gsmendoza** [comment]
@alecvn I am able to reproduce this issue as follows:

## Expected behavior

Given I have cloned `git@github.com:gsmendoza/rails_6161_store.git`
And I have checked out the branch https://github.com/gsmendoza/rails_6161_store/tree/solidus-4478
And I have created the app's development database, migrated the database, and seeded it
And I am now running the app
And I am now checking out an order
And I am now in the Payment step
When I select Solidus Pay
And I enter any value for the SolidusPay Auth Token
And I click "Save and Continue"
Then I should see the payment step succeed
And I should see the Checkout page

## Actual behavior

I see the error "Payments source can't be blank".

**Comment by alecvn** [comment]
Thanks @gsmendoza

I confirmed that it was still giving me an error with:
```
Spree::PermittedAttributes.checkout_payment_attributes << :auth_token
```

As you suggested in https://github.com/solidusio/edgeguides/pull/50 the correct solution is to add:
```
Spree::PermittedAttributes.source_attributes << :auth_token
```
