### ISSUE TITLE
Free shipping promotions can apply regardless of eligibility in certain cases

### ISSUE THREAD

**Issue by seand7565** [solidusio/solidus#4505]
Bear with me here, our promotions system is _really_ complicated, and this issue takes some explaining.

First a TL:DR; When adding an item using `order_contents#add` and passing in a specific shipment, a free shipping promotion where the order would normally be ineligible will be applied to that order.

Now the long-form explanation:

`order_contents#after_add_or_remove` will, when not specifically passed a shipment, run `ensure_updated_shipments` ([link](https://github.com/solidusio/solidus/blob/81d5bd9a14779754aeab82e4da34771ddeb177ee/core/app/models/spree/order_contents.rb#L76)) on the order before checking for promotions; For an order that already has shipments, this will destroy the shipments and push it back to the `address` state.

`order_contents#after_add_or_remove` will then check the `cart` promotion handler ([link](https://github.com/solidusio/solidus/blob/81d5bd9a14779754aeab82e4da34771ddeb177ee/core/app/models/spree/order_contents.rb#L77)) after adding a line_item, with that new line_item as a parameter. The handler then checks all promotions for eligibility against that line_item ([link](https://github.com/solidusio/solidus/blob/81d5bd9a14779754aeab82e4da34771ddeb177ee/core/app/models/spree/promotion_handler/cart.rb#L27)). Rules that normally only apply on the order level are ignored, and any promotion that has no rules for line_items will return eligible for that line_item ([link](https://github.com/solidusio/solidus/blob/81d5bd9a14779754aeab82e4da34771ddeb177ee/core/app/models/spree/promotion.rb#L149-L192)). Basically, a promotion can be eligible for a line_item, but not for the line_items order. Makes sense so far.

Most promotion actions, when applying, will in some form or another check order eligibility before performing their action ([link](https://github.com/solidusio/solidus/blob/81d5bd9a14779754aeab82e4da34771ddeb177ee/core/app/models/spree/promotion/actions/create_item_adjustments.rb#L38), which checks order eligibility [here](https://github.com/solidusio/solidus/blob/81d5bd9a14779754aeab82e4da34771ddeb177ee/core/app/models/spree/promotion.rb#L220-L235)). For the `FreeShipping` action, [this is not true](https://github.com/solidusio/solidus/blob/81d5bd9a14779754aeab82e4da34771ddeb177ee/core/app/models/spree/promotion/actions/free_shipping.rb#L7-L21); but most of the time it doesn't matter, because the order has no shipments, so the action cannot apply.

However, when you pass a shipment into `after_add_or_remove` (because you want to add to a specific shipment) ([link](https://github.com/solidusio/solidus/blob/81d5bd9a14779754aeab82e4da34771ddeb177ee/core/app/models/spree/order_contents.rb#L76)), the orders shipments are not destroyed and the order is not pushed back to the `address` state. This makes sense - because otherwise how would you add the item to the specified shipment?

So when the `cart` promotion_handler is run, and the otherwise-ineligible-for-that-order FreeShipping promotion attempts to apply, it _will_ apply to that orders shipment.

The issue is basically: The free shipping action does not take order eligibility into account when applying, and probably should.

To replicate:
* Create a free shipping promotion with a product rule, requiring some random product.
* Create an order with any product other than the one selected above (so the promotion is ineligible for the order)
* Push the order to the `payment` step, ensuring it has shipments
* Add an item to the order (again, not the one selected for the promotion) using `order.contents.add(variant, shipment: #{shipment here})`
* The order should have the free shpping promotion, even though it was ineligible for it.

**Comment by seand7565** [comment]
To solve this, we made the following adjustment to the free shipping action:
```ruby
  module Spree
    module Promotion
      module Actions
        module FreeShipping
          module Overrides
            def perform(payload = {})
              return false unless promotion.eligible? payload[:order]

              super
            end
          end
        end
      end
    end
  end
```

It basically mirrors the other actions, which already check for eligibility on the order before applying a discount to anything.

**Comment by waiting-for-dev** [comment]
Thanks for describing it so accurately. Would you like to submit the fix for it?

**Comment by seand7565** [comment]
@waiting-for-dev Sure, done!

**Comment by kennyadsl** [comment]
Thanks @seand7565!
