### ISSUE TITLE
Find out why `spree_zones.kind` exists

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#451]
It used to be calculated, but in spree 3.0 was changed to be stored in the DB (although in some cases it was recalculated).

I don't think type should exist at all, so I'm curious why it was added to the DB.

**Comment by mtomov** [comment]
Well, a Zone can be country based, like North America zone can include Canada and USA, but it can also be state based. A state based would be for example a zone called USA, which consists of the states that you ship to. Then, one can define different shipping methods based on the different zones.

But, maybe that is something you already know and you were asking something more intricate.

**Comment by tvdeyen** [comment]
The same is true for the European Union. That's a country based zone. Each country inside is state based.

But, this could be done with a type/kind column. Since a zone member can be either state or country.

**Comment by jhawthorn** [comment]
Yes, that's always been the case. The question I had was why it was changed in spree 3.0 from something inferred by the contents of zone_members to something stored on zone itself. There was IMO, no benefit to this in core, so was looking for if it was done for extensions support.

**Comment by mamhoff** [comment]
I think it was done to speed up things. In https://github.com/spree/spree/pull/5650 and https://github.com/spree/spree/pull/5650/files you'll see that it can [be anything, really](https://github.com/spree/spree/blob/master/core/spec/models/spree/zone_spec.rb#L329-L345), but that it should be 'country' when it's a `Spree::Country` and `state` when the zone contains states.

**Comment by mamhoff** [comment]
I believe this issue was created to facilitate migrating a 3.0 store to Solidus. This goal has been accomplished in 1.4 at the latest. Closing.
