### ISSUE TITLE
Join Slack linkes are broken

### ISSUE THREAD

**Issue by MrTin** [solidusio/solidus#4542]
I can't find a way to join the Slack community.

**Current behavior**

* If you press the Slack link at https://solidus.io/contributors/ or in this repos README, you will be taken to a Sign up page with Slack but you can only sign up using a nebulab.com or supergood.software email.

**Expected behavior**

Be able to join the Slack community.

**Screenshots**

![image](https://user-images.githubusercontent.com/408528/188334235-30e37d69-aad7-4160-b576-72854c05f777.png)

**Comment by aldesantis** [comment]
Looks like our Slack invite link had stopped working for some reason. I have just generated a new link—can you check if it works now? Thanks!

**Comment by kennyadsl** [comment]
It seems to be working now, thanks @aldesantis and @MrTin for reporitng! Going to close this one.
