### ISSUE TITLE
Make more api controllers use the api resource controller

### ISSUE THREAD

**Issue by athal7** [solidusio/solidus#462]
There is a lot of duplicated code across api controllers, leveraging https://github.com/solidusio/solidus/blob/master/api/app/controllers/spree/api/resource_controller.rb should help clean a good chunk of that up.

**Comment by BenMorganIO** [comment]
@athal7 I'm actually :-1: on using resources controllers. Over time, I feel like they just do too much. A lot of things end up getting hidden on you and that can make debugging a pain. Having a `render_collection` and a `render_instance` has been helpful for me.

**Comment by athal7** [comment]
@BenMorganIO I have similar frustrations with the admin resource controller, which is why the api resource controller is slim. I can't speak for everyone, but I at least have an intention to keep it slim that the code is explicit enough. I would find it helpful here if we debate specifics of the implementation, rather than the abstract concept of code-sharing.

**Comment by Senjai** [comment]
There are certainly difficulties when using the resource controller for non restful situations, or situations where you require a lot of custom behavior, however, with simple controllers, nothing has been more helpful than the resource controller. It cuts down the time significantly for controllers that match what it's trying to accomplish and works well with resource controller specific helpers like `link_to_destroy`

**Comment by gmacdougall** [comment]
Closing due to staleness
