### ISSUE TITLE
2.11.17 release contains a breaking change for YAML loading of `LogEntry` records

### ISSUE THREAD

**Issue by forkata** [solidusio/solidus#4679]
The switch to `YAML.safe_load` in this commit is a breaking change https://github.com/solidusio/solidus/pull/4455/commits/d2b05aa1a9ec6903027a880f5d466c5abd5b8f05

**Solidus Version**:
2.11.17

**Current behavior**
When trying to deserialize any classes other than the ones [explicitly](https://github.com/solidusio/solidus/commit/d5f759b1e4c1562ff0b2f9ed906f71565f9d704e#diff-96cc27eba934e1e96a1ffc0e5574406061f5b4f48770faeba62a062544b8633bR11-R16) permitted an exception will be raised. For host applications which use this record for storing references to other classes a configuration change is require to add those to `Spree::AppConfiguration#log_entry_permitted_classes`
 
**Expected behavior**
Since this was introduced as a backport of a security patch, there isn't much we can do, other than document the breaking change better in the Changelog for the 2.11.17 release. This update came down as a `dependabot` bump and it was not obvious from the Changelog that we need to update our configuration to include any classes that need to be explicitly allowed.

**Comment by gsmendoza** [comment]
@forkata Would you like to submit a PR to update the Changelog? If not, I can work on it :)

**Comment by forkata** [comment]
Thanks for the quick response @gsmendoza. I can work on a PR to update the changelog 👍🏼

**Comment by forkata** [comment]
@gsmendoza I've opened up a PR to add an entry to the CHANGELOG.md for this release. I don't have the ability to update the Release notes, but if this looks good we could copy the note over to that.

**Comment by gsmendoza** [comment]
Thanks @forkata !

**Comment by waiting-for-dev** [comment]
Thanks, @forkata. I updated the corresponding [release notes](https://github.com/solidusio/solidus/releases/tag/v2.11.17).
