### ISSUE TITLE
`$.ajaxSetup.xhr` is not a function

### ISSUE THREAD

**Issue by pelargir** [solidusio/solidus#4706]
With [this recent change](https://github.com/solidusio/solidus/pull/4625) we're getting errors whenever we try to upload new images to a product: "server could not process the image" 

After defining an Ajax error handler (code is at the very bottom of this issue) we can see the underlying error is "$.ajaxSetup.xhr is not a function"

**Solidus Version**:
3.2.3

**To Reproduce**
1. Edit a product in the admin backend
2. Click on the images tab
3. Choose a file to upload
4. Observe error

**Current behavior**
Uploading a product image results in an error: "server could not process the image"

**Expected behavior**
The image upload should succeed without error.

**Screenshots**
![Screenshot 2022-11-07 at 2 58 26 PM](https://user-images.githubusercontent.com/3756/200403023-ca33346c-39c8-480a-b1d0-150f05946ba9.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura
 - Browser: Chrome
 - Version: 107.0.5304.87

**Additional context**

Checking from the browser console, `$.ajaxSetup` is defined but `$.ajaxSetup.xhr` is undefined. Is this a function we're expected to define ourselves?

The jQuery [documentation](https://api.jquery.com/jquery.ajaxsetup/) for `ajaxSetup` states:

> Description: Set default values for future Ajax requests. **Its use is not recommended.**

So it seems the official jQuery position is that we shouldn't be using this.

We can fix the problem by explicitly defining the function like this:

```js
$.ajaxSetup.xhr = function() {
  return new window.XMLHttpRequest();
}
```

But it doesn't seem like we should have to do this to get the Solidus backend to work properly.

We can see in `jquery3.js` where `ajaxSettings.xhr` is explicitly getting defined as a function, but `ajaxSetup.xhr` isn't getting defined anywhere. In fact, the _only_ reference we can find to `ajaxSetup.xhr` across our entire project (including external source libraries) is in Solidus' `upload_progress.js` file.

I'm unsure how the change in #4625 would be working for anyone else unless they are explicitly defining `ajaxSetup.xhr` as we were forced to do to get around this problem.

This is the handler we defined so we could see the underlying error:

```js
$(document).ajaxError(function(event, jqxhr, settings, thrownError) {
  window.show_flash("error", thrownError);
});
```

**Comment by kennyadsl** [comment]
@pelargir thanks for reporting and @cpfergus1 thanks for jumping into this. Can you please also check why this is not covered by specs? 🙏
