### ISSUE TITLE
Conditionally pick a different paypal version during the installation, based on the frontend selected

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#4742]
- Blocked by solidusio/solidus_paypal_commerce_platform#170. 

During the installer (only for the master version, so will be available from 3.3), we want to pick a different version of the Paypal gem.

Legacy Frontend -> `solidus_paypal_commerce_platform ~> 0.6`
Starter Frontend -> `solidus_paypal_commerce_platform ~> 1.0`

This will ensure we install the version compatible with the frontend of choice.

**Comment by elia** [comment]
Tackling this in https://github.com/solidusio/solidus/pull/4743
