### ISSUE TITLE
We are unable to calculate shipping rates for the selected items.

### ISSUE THREAD

**Issue by negouseid** [solidusio/solidus#479]
I am pretty new at this and I keep running into this issue. 
When I get to https://storename.herokuapp.com/checkout/address
I receive the error "We are unable to calculate shipping rates for the selected items." and I am not sure where to go from there. I have not made any changes to the Gems beside add  "gem 'rails_12factor', group: :production"  for the production. 
thanks

**Comment by mamhoff** [comment]
I think you're missing some set-up. Have a look at [The Spree Shipments guide](https://guides.spreecommerce.com/developer/shipments.html) - basically, you'll have to add a `shipping category` and `shipping methods` for each of the `zone`s you want to ship to.

**Comment by negouseid** [comment]
I still get the same error, 
I set my shipping category to "ground" and "ground Int" 
set my shipping methods to "Ground, North America, flat rate"
"Ground,EU_VAT, flat rate"
So I am missing something else, this was the first thing I tried. 
Thanks for helping

**Comment by jhawthorn** [comment]
@negouseid this has always been a pain, and is something I hope we make easier in the future.

Make sure all the products in your cart matches the shipping category of your desired shipping method.
Make sure your zone includes the country (or region) that you're entering as a shipping method.

Hope this helps.
