### ISSUE TITLE
Update Order#fully_discounted? implementation

### ISSUE THREAD

**Issue by stewart** [solidusio/solidus#481]
The current implementation of `Order#fully_discounted?` is strange:

```ruby
def fully_discounted?
  adjustment_total + line_items.map(&:final_amount).sum == 0.0
end
```

This implementation:

- does not include shipping total, if present
- does not account for line-item level adjustments
- likely has some other edge cases I didn't encounter

I'd like to propose a possible replacement implementation:

```ruby
def fully_discounted?
  total + shipment_total == 0.0
end
```

According to the OrderUpdater class, `total` is calculated to be equivalent to `item_total` + `adjustment_total`. Similarly, `shipment_total` is calculated by summing the cost of all shipments on the order.

This suggested implementation might not be optimal for some stores, as they'd rather simply check that adjustments cover all line items, but not shipping.

I can see reasonings for both including and not including `shipment_total` in the calculation, so figured I'd ask here rather than just opening a PR.

It might also be good to include a check to determine that there are, in fact, line items being discounted, rather than an empty order.

**Comment by athal7** [comment]
@stewart can you link the line that excludes the shipment total in the order.total calculation? I see it included here https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order_updater.rb#L72

**Comment by stewart** [comment]
Hmm, that's correct! I didn't see it in the inline doc I was referencing, and assumed it wasn't included in the calculation. Perhaps a good default then is:

```ruby
def fully_discounted?
  item_total + adjustment_total == 0.0
end
```

**Comment by stewart** [comment]
Or, just check if `total == 0.0` if we'd prefer to include the `shipment_total` in the `fully_discounted` calculation.

**Comment by athal7** [comment]
I can't speak for what the average store wants because we have highly customized logic, but total == 0.0 seems reasonable to me.
