### ISSUE TITLE
Find a way to avoid manually change starter frontend version at each release

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#4899]
We need to find a way to make the master branch of solidus always point to the development branch of the Starter Frontend, but before releasing a new minor/major version, it switches to the released version.

For now, we still need to do this manually, as I did here: https://github.com/solidusio/solidus/pull/4898.

**Comment by waiting-for-dev** [comment]
As `master` and `v*.*` need to point to different branches no matter what, I don't think there's a way to make it 100% dynamic. We could add another [bumper step](https://github.com/solidusio/solidus/blob/2dcd90e9aca83c6e570ccbb03ea4844c6ef53efe/.github/workflows/prepare_release.yml#L26) to the prepare release action, though. We would need to make sure (wiki instructions for now) to create the branch before the release, though.

**Comment by kennyadsl** [comment]
> We could add another [bumper step](https://github.com/solidusio/solidus/blob/2dcd90e9aca83c6e570ccbb03ea4844c6ef53efe/.github/workflows/prepare_release.yml#L26) to the prepare release action, though

If I recall correctly, the bumper steps act on the `master` branch, while this needs to be the first thing to do after the new branch has been created and before the actual release. 

> We would need to make sure (wiki instructions for now) to create the branch before the release, though.

Do you mean the new version's branch on Solidus Starter Frontend? If yes, perfect sync will be hard here but it's enforced by this [CI job](https://github.com/solidusio/solidus/blob/2dcd90e9aca83c6e570ccbb03ea4844c6ef53efe/.circleci/config.yml#L221), which will fail until we create that branch.

**Comment by waiting-for-dev** [comment]
> If I recall correctly, the bumper steps act on the master branch, while this needs to be the first thing to do after the new branch has been created and before the actual release.

Now, the commit that consolidates a release is shared both by master and the v* branch, i.e., tags for new minor and major releases are in both branches. So, for a moment, master is exactly the same that what has been published into RubyGems. That changes when the post release action runs and updates master to follow the next release, moment at which we should reference `main` again.

> Do you mean the new version's branch on Solidus Starter Frontend? If yes, perfect sync will be hard here but it's enforced by this [CI job](https://github.com/solidusio/solidus/blob/2dcd90e9aca83c6e570ccbb03ea4844c6ef53efe/.circleci/config.yml#L221), which will fail until we create that branch.

I'm not sure to understand. Why that CI job on Solidus will fail when we create the branch on SSF?

**Comment by kennyadsl** [comment]
> I'm not sure to understand. Why that CI job on Solidus will fail when we create the branch on SSF?

I mean that if we update Solidus core to point to the new Solidus Starter Frontend branch (as done [here](https://github.com/solidusio/solidus/pull/4898)) but that branch still didn't exist, we'll see a Ci failure on that job. Sounds correct?

**Comment by waiting-for-dev** [comment]
Yeah, because of that creating the branch should be the first step in the process (I meant that we need to add that step to the instructions we have on our wiki).

**Comment by kennyadsl** [comment]
Not sure it's the best place yet, but added via: https://github.com/solidusio/solidus/wiki/How-to-release-Solidus/54a8a8f947928afa2f58ae523352e48fdbad968c

**Comment by kennyadsl** [comment]
@waiting-for-dev I was thinking again about this now that we are approaching some releases (because I'm quite sure we will forget again 🙂). 

What about this approach:

- **prepare release** workflow bumps the version of [the starter template](https://github.com/nebulab/solidus/blob/fd277b0b04a4013f0f5b3c041078c12042fee36d/core/lib/generators/solidus/install/app_templates/frontend/starter.rb) from `main` to the candidate version.
- **prepare post release** workflow resets the version from the candidate version to `main`.


Not ideal to go back and forth with the version, but I have no other ideas, because right now, we are creating the `v.X.Y` branch in the **prepare post release** workflow, but we need to update that value in the released version, so before that.

**Comment by waiting-for-dev** [comment]
I left a review there with some comments! :slightly_smiling_face: The plan looks good, although we still need to create the branch on SSF.

**Comment by kennyadsl** [comment]
Yes, but with [the installer tests](https://github.com/solidusio/solidus/blob/04a4d68ef9c6957a88e6d66618397754e58367c0/.circleci/config.yml#L215) we have in the CI, the suite should fail until we create that branch.
