### ISSUE TITLE
Current version of Deface

### ISSUE THREAD

**Issue by ajkamel** [solidusio/solidus#490]
Im having an issue with integrating Solidus with my rails app using dotenv-rails  It seems like there are some issues related to this with Deface.  

According to this issue it seems like Deface no longer pushes the current version to rubygems and pointing to the github repo might be a better fix.  How do we feel about adding this to the next release?

https://github.com/bkeepers/dotenv/issues/177

`gem 'deface', github: 'spree/deface'`

**Comment by cbrunsdon** [comment]
@ajkamel I'm looking to remove deface from the core project in the next release. If people want to keep using it inside their projects, thats fine with me, but as we don't use it any more inside the solidus repo itself we shouldn't be adding it as a dependency.

But that is, of course, just pushing the problem down the line. I'll try reaching out to @bdq and seeing if he can either do a push or add someone else to the owner list.

**Comment by dhonig** [comment]
@cbrunsdon +1 for pulling deface out of core.
Why it is a nice and elegant piece of work by @bdq  I don't think it has ever found a comfortable home in the wild in Spree projects.   
Its one saving grace was that it was very useful in what became spree_backend for a standard way of customizing things, but even that can be argued.

**Comment by jhawthorn** [comment]
@ajkamel Success! We have a new deface release.

https://rubygems.org/gems/deface/versions/1.0.2
https://github.com/DefaceCommunity/deface

**Comment by cbrunsdon** [comment]
Yea, big thanks to Brian Quinn for granting us ownership on rubygems.
