### ISSUE TITLE
Add links to PR & author in the auto-generated release notes

### ISSUE THREAD

**Issue by waiting-for-dev** [solidusio/solidus#4904]
Not adding them is not a problem in the release notes, as they're automatically generated when rendered. However, we later copy the content to the Changelog, and Github doesn't generate the links there. See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls:

> Note: Autolinked references are not created in wikis or files in a repository.

**Comment by waiting-for-dev** [comment]
As per @kennyadsl 's [comment](https://github.com/solidusio/solidus/pull/4908#issuecomment-1420407992), we've decided to follow GitHub's default format for the generated release notes. That way we'll have a better experience manually updating the notes when something goes wrong with our automation. That means the PR link will be rendered, but we'll still miss the author's link, which is an acceptable tradeoff.

**Comment by kennyadsl** [comment]
Reopening, I think we also need to update the existing releases entries manually, right?

**Comment by waiting-for-dev** [comment]
Done. The only draft was for [v3.4.0](https://github.com/solidusio/solidus/releases/edit/untagged-f0f1137d960ecb8af222).
