### ISSUE TITLE
Reduce size of sample images

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#4917]
We can compress images that are stored here: https://github.com/solidusio/solidus/tree/master/sample/db/samples/images.

This will speed up everyone's `bundle install` and the release process.

**Comment by F-Hamid** [comment]
Hello @kennyadsl, i can handle it, is about 50% less size good for you ?

**Comment by kennyadsl** [comment]
Hey @F-Hamid, that would be great. About the compression, I usually rely on tools like https://compressor.io/ (or via command line, like https://optipng.sourceforge.net/), which can handle the best trade-offs in terms of quality/size. They are sample images, so I think the "Lossy" option is ok. 

If you start with this, can you please also track the folder size before and after the images resize?

A follow-up task might be having all of them in the same format (jpg or png), which might already reduce their size.

Thanks a ton in advance!!!

**Comment by F-Hamid** [comment]
![Screenshot from 2023-02-07 18-33-14](https://user-images.githubusercontent.com/82233609/217320813-1a857c5c-0347-400f-adca-ee1cb5cf5457.png)
![Screenshot from 2023-02-07 18-32-37](https://user-images.githubusercontent.com/82233609/217320817-378db164-3319-4eb8-be87-b2f7720eb117.png)
Before : 9.7 MB
After : 5.1 MB

**Comment by F-Hamid** [comment]
And yeh you are right, making them all Jpg instead of Png would make a significant impact . I am working on it

**Comment by F-Hamid** [comment]
![Screenshot from 2023-02-07 18-42-53](https://user-images.githubusercontent.com/82233609/217323581-82e862d4-af12-4ba2-b3f3-28baf3968051.png)
 Now it is 2MB for all the images : less 80%

**Comment by F-Hamid** [comment]
I've just created a pull request .

**Comment by kennyadsl** [comment]
Can't see the PR in the list. Let me know if I can help with submitting it!

**Comment by F-Hamid** [comment]
Please retry now ! and let me know if you need any thelp.
By the way I am a MERN developer and would be happy to contribute.
