### ISSUE TITLE
Refactor and restore CreateLineItems Promotion Action

### ISSUE THREAD

**Issue by peterberkenbosch** [solidusio/solidus#492]
This has been removed here https://github.com/solidusio/solidus/commit/8d75f1f5f8c65652b54bad5e73b2d825bb0fbebb with solid reasons. I would like to get this back in with some proper refactoring.

wdyt @jordan-brough ?

**Comment by gmacdougall** [comment]
I think that this is a desired feature and that we'd be happy to have a working version of this.

**Comment by jordan-brough** [comment]
Cleaning it up and refactoring it sounds great. @peterberkenbosch do you already have some high-level ideas on how to solve the issues with the previous implementation?

**Comment by peterberkenbosch** [comment]
thanks guys, I have not worked it out yet. Planning on starting with that tonight. More to come!

**Comment by dhonig** [comment]
@gmacdougall absolutely this is a desired feature!  @peterberkenbosch will be watching as I've done alot of promo work lately on Spree 2.4, and would love to be helpful where I can.

**Comment by peterberkenbosch** [comment]
So, it looks like the main issue with the previous implementation is that there is no way to remove the line item added by the promotion when the promotion is no longer eligible. This is mainly an issue when a user adds the same product that will be added by the promotion. Otherwise we could just remove all the line items from the order with the same variant as in the promotion action. 

We could iterate through the promotions, when not eligible, fetch the variant_ids when the the action type is the `Spree::Promotion::Actions::CreateLineItems` and remove the variants found from the order (with the correct quantity so the manual added items are not removed).

Currently no insight yet in how this will compromise the performance or complexity though. Other idea that might be something to experiment with, is to add an association to the line item with the promotion, or an 'added-by' field that will default to the current_user. We could even use that to track down admin added line items. However, not that keen on adding a polymorph association, it might be to complex. 

I will continue with the first approach experiment, to see if I can just make it work. Then I will take a look at performce.

@dhonig @gmacdougall @jordan-brough wdyt?

**Comment by peterberkenbosch** [comment]
Something like this: https://github.com/solidusio/solidus/blob/master/core/app/models/spree/promotion_handler/coupon.rb#L100

btw @jordan-brough this is currently still in master. That well hidden reference to the removed CreateLineItems action is still present :)

**Comment by jordan-brough** [comment]
> add an association to the line item with the promotion

I think that could be a great idea.  Something like the join table on the [CreateQuantityAdjustments](https://github.com/solidusio/solidus/blob/2fb0a97/core/app/models/spree/promotion/actions/create_quantity_adjustments.rb#L7-L8)  promotion action right?  I haven't thought it through in detail but recording the data in a discrete way seems like the easiest to reason about. @adammathys crafted that one so maybe he has some insights on it?

> That well hidden reference to the removed CreateLineItems action is still present :) 

Hah, nice find! I guess that one slipped past me. :) We should remove that...  Thanks.

**Comment by peterberkenbosch** [comment]
Right, something like that looks like a good solution, missed that particular implementation. Good ref. 



-- 
Peter Berkenbosch


GSM: (+31) (0) 64 84 61 653
Email: peter@pero-ict.nl
Skype: peter.berkenbosch
Twitter: @pberkenbosch 
Web: www.pero-ict.nl

**Comment by adammathys** [comment]
It's been a while since I created that, but I believe that with a little bit of work you should be able to use that association to help figure out which line item was added by a `CreateLineItems` action.

The more difficult task will be coming up with a nice place to hook in the line item removal. Right now, promotions are so heavily tied to adjustments that I don't think there's a nice place for it. (And that a larger re-factoring needs to happen before these types of promotions could be nicely written.) Specifically, instead of simply marking adjustments as ineligible, some sort of roll-back mechanism to remove the effects of ineligible promotions from an order is required.

Looking forward to seeing what you come up with. Maybe there's an easier path I'm not seeing.

**Comment by alepore** [comment]
> some sort of roll-back mechanism to remove the effects of ineligible promotions from an order is required

i was thinking the same thing, like a standard method (normally blank) that's called for ineligible promotions.
some of them (like this one) can use it to "clean up" stuff

**Comment by alepore** [comment]
Just an update:
i did a quick hack adding two methods on a site of mine:
`PromotionHandler::Cart` when ineligible calls `Promotion#deactivate`, which calls each `PromotionAction#rollback`

it's a pretty easy solution and works for me (TM), but i'm on spree 3 and i'm using a custom action

**Comment by peterberkenbosch** [comment]
@alepore I like the conventions!

**Comment by dougjohnston** [comment]
@peterberkenbosch Is this any further along? Since my marketing team is now asking for this, I'm going to be working on it one way or another.

Also, @alepore, that's sounds like a nice solution. Do you have any sample code you could post?

**Comment by cbrunsdon** [comment]
We implement these in some of our stores, but we understand the conditions they are used under and are *incredibly* careful with tthem. They're not difficult to add to your own store, but I don't think this is safe to add to core, there are too many edge cases people are almost certain to run into and ruin their day.
