### ISSUE TITLE
Use `#call`able objects in AppConfiguration

### ISSUE THREAD

**Issue by jordan-brough** [solidusio/solidus#493]
(Note: This is extracted from the discussion here: https://github.com/solidusio/solidus/pull/477#issuecomment-154481461)

@mbj suggests that we use `#call`able objects in our AppConfiguration for things like `promotion_chooser_class` instead of classes.  I think @mbj has some good points and it wouldn't be hard to deprecate the old configs.

Right now in general what we require for these configuration settings is:

> Provide an object that responds to `new(...)` and returns an object that responds to `foo` which returns `bar`

With a `#call` approach what we would be saying:

> Provide an object that responds to `call(...)` and returns `bar`

Some of the nice things about `#call`:
- It's simpler
- It encourages single-focus preferences and preference objects

Existing classes could be easily retrofitted by adding something like:

``` ruby
class CustomPromoChooser
  def self.call(adjustments)
    new(adjustments).update
  end
  # ...original code...
end
```

Thoughts? Do we think the real world benefits are worth the cost of us switching things around?

**Comment by jhawthorn** [comment]
I think for a lot of extension points this would be a lot cleaner. Especially for sorting it makes a lot of sense.

I think in some cases classes probably still make sense.

**Comment by cbrunsdon** [comment]
Aye, I agree with @jhawthorn. Rather than making any decisions right now I think we should chat about them on case-by-case basis' for a while and see what we think as we work on things. Definitely happy to have these conversations though, I expect these will be some of the most important design decisions we end up making in solidus.

**Comment by gmacdougall** [comment]
Closing due to staleness
