### ISSUE TITLE
Remove solidus_frontend from the solidus meta gem

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#4986]
`solidus_frontend` has been moved to its repository: https://github.com/solidusio/solidus_frontend and people have had the time to use it instead of the gem provided in the meta gem (there's a deprecation message for that). 

At this point, we can remove it from the meta gem in 4.0, introducing this breaking change.

**Comment by waiting-for-dev** [comment]
We also need to remove it from the installer, right?

**Comment by kennyadsl** [comment]
Good point! We could also keep it, actually. I'll make sure to open a discussion about the pros and cons of this choice. 

cc/ @solidusio/core-team @solidusio/nebulab

**Comment by kennyadsl** [comment]
I assumed that we could remove that complexity once it's out of the meta gem. I imagine the [app template](https://github.com/solidusio/solidus/blob/ab59d6435239b50db79d73b9a974af057ad56b52/core/lib/generators/solidus/install/app_templates/frontend/classic.rb) to become something like:

```
bundle add solidus_frontend
generate 'solidus_frontend:install'
```

If that's true, in my view, it's more a matter of deciding if we want to deprecate it or just recommend users to go with the starter frontend.

**Comment by waiting-for-dev** [comment]
Oh, yeah, you're right. That's two different things. Probably, as we're deprecating it, it makes no sense to give it as an option, but the reasons are not as strong as I falsely assumed.
