### ISSUE TITLE
Release Solidus 4.0

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#4988]
As usual, we can follow the related Wiki guide for this: https://github.com/solidusio/solidus/wiki/How-to-release-Solidus.

**Comment by waiting-for-dev** [comment]
Before this one, we should release v3.4 and freeze the code afterward. Should we create an issue for that?

**Comment by kennyadsl** [comment]
@waiting-for-dev good point, opened https://github.com/solidusio/solidus/issues/4990.
