### ISSUE TITLE
Add a more fine-grained ACL system

### ISSUE THREAD

**Issue by chrean** [solidusio/solidus#5034]
Many of the users we interviewed mentioned the lack of a more fine-grained ACL system as a pain point with Solidus.
We could review an unmaintained extension ( https://github.com/boomerdigital/solidus_user_roles ) and integrate it into the core. It should be a relatively low-effort, high-impact activity.

**Comment by BenMorganIO** [comment]
We already have a lot of `can?` checks throughout the system. Perhaps increased documentation may also be another low-effort, high-impact alternative. Both these solutions can go hand-in-hand.
