### ISSUE TITLE
Rename default Solidus branch to `main`

### ISSUE THREAD

**Issue by waiting-for-dev** [solidusio/solidus#5038]
We'll take the occasion of releasing v4.0 to perform the long-due rename of Solidus's default branch from `master` to `main`. See #4585 for more context.

We need to perform the following list of tasks in the given order. After renaming the branch (step 3), we might experience some provisional build errors on extensions.

- [x] Rename `master` references from our [dev tools](https://github.com/solidusio/solidus/tree/master/dev_tools) to `main`. We have several GitHub action automation that only applies to the default branch. (https://github.com/solidusio/solidus/pull/5042)
- [x] Rename references to `master` in comments, README, etc. Although GitHub will automatically redirect them, it's a good housekeeping chore. (https://github.com/solidusio/solidus/pull/5042)
- [x] Rename `master` branch to `main`, just before merging 1 & 2.
- [x] Update [CircleCI orb](https://github.com/solidusio/circleci-orbs-extensions) to use `main` as the default branch. Otherwise, `bundle` will fail to fetch the unexistent `master` branch once it's removed. (https://github.com/solidusio/circleci-orbs-extensions/pull/84)
- [x] Update extensions to fetch Solidus from `main` for development. There's no need to tackle all of them at once, and we can change them opportunistically. However, let's make sure the following ones (including all the ones in the solidusio organization) are updated upfront:
  - [x] solidus_starter_frontend (https://github.com/solidusio/solidus_starter_frontend/pull/337)
  - [x] solidus_stripe (https://github.com/solidusio/solidus_stripe/pull/296)
  - [x] solidus_paypal_commerce_platform (https://github.com/solidusio/solidus_paypal_commerce_platform/pull/198)
  - [x] solidus_braintree (https://github.com/solidusio/solidus_braintree/pull/139)
  - [x] solidus_dev_support (https://github.com/solidusio/solidus_dev_support/pull/204)
  - [x] solidus_support (https://github.com/solidusio/solidus_support/pull/76)
  - [x] solidus_subscriptions (https://github.com/solidusio/solidus_subscriptions/pull/288)
  - [x] solidus_affirm (https://github.com/solidusio/solidus_affirm/pull/75)
  - [x] solidus_bolt (https://github.com/solidusio/solidus_bolt/pull/152)
  - [x] solidus_i18n (https://github.com/solidusio/solidus_i18n/pull/204)
  - [x] solidus_auth_devise (https://github.com/solidusio/solidus_auth_devise/pull/245)
  - [x] solidus_webhooks (https://github.com/solidusio-contrib/solidus_webhooks/pull/15)
- [x] Rename solidus_frontend default branch to `main`, as some extensions expect the same branch name as Solidus.
- [x] List `main` and unlist `master` on stoplight for our API docs.

**Comment by waiting-for-dev** [comment]
I updated the issue description to all the related PRs.

**Comment by kennyadsl** [comment]
@waiting-for-dev all the PRs above have been merged, can we close this issue now?

**Comment by waiting-for-dev** [comment]
Sure thing, closing!
