### ISSUE TITLE
Add flyout triggered by hover to left nav

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#505]
The current model of the side nav has the user clicking on a parent item to expand what's underneath.  We can save the user a click/expand and give them a flyout menu to see sub menu items. This feature would only be included on desktop. A similar interaction is for touch not being considered at this time.

The flyout would appear when a user hovers over any parent item that has a menu underneath it. When the user clicked on a sub item, that page would load and the menu would expand to show that page highlighted in the menu, while the last page's section would collapse.

The attached screenshots are from Wordpress, to show an example. Our branding will be different.

Please let me know your thoughts in the comments below.

![flyout example](https://cloud.githubusercontent.com/assets/15271353/11127505/7cc81aca-8929-11e5-830b-123c273e38eb.png)
<img width="407" alt="flyout example after" src="https://cloud.githubusercontent.com/assets/15271353/11127506/7ccc267e-8929-11e5-8cc0-c9a5fa9395db.png">

**Comment by tvdeyen** [comment]
👍

**Comment by tvdeyen** [comment]
I really like the Wordpress fly out example, because it offers quick interaction with tasks often used, like "create user". 

It would be great for extension developers to easily create fly out menus. Maybe though some kind of plugin registry, that also holds menu items and fly out interactions!

👌

**Comment by tvdeyen** [comment]
Sorry for this shameless plug, but in AlchemyCMS we have a plugin registry that offers the developer to set main menu and submenu entries with url to the desired action. 

https://github.com/AlchemyCMS/alchemy_cms/blob/master/config/alchemy/modules.yml

Maybe this helps considering this feature. 

I think the old way of patching/overriding/defacing a view and use the `tab` and `menu_tree` helpers is not an ideal situation for extension developers.
