### ISSUE TITLE
link_to_cart

### ISSUE THREAD

**Issue by negouseid** [solidusio/solidus#508]
When I add products to carts and press check out, I get this error.
"1 error prohibited this record from being saved:
There were problems with the following fields:
Number can't be blank"
It's not blank at all, I try to change the number to 2,3, 4 and so on. No luck. I have seen this issue posted a few places and no answers yet. On the ruby log it shows this "  Couldn't find template for digesting: store/cart_link"
Any body else experience this issue?

**Comment by cbrunsdon** [comment]
Are you experiencing this on a vanilla solidus store?

**Comment by cbrunsdon** [comment]
Going to assume you figured it out or decided to classify the bug as a feature.
