### ISSUE TITLE
Incorrect refund amounts with an order which has a whole order discount

### ISSUE THREAD

**Issue by alex-handley** [solidusio/solidus#512]
Hi, we have noticed that if you do a single item refund on an order that has a whole order promo discount you receive the whole amount back for the item. 

For example:

Item 1: £6
Item 2: £4
Discount for buying multiple items (10%): £1  
Total : £9

When you refund item1 you get a refund of £4.

Im happy to investigate this more but wanted to see if anyone has come up against this already?

**Comment by athal7** [comment]
That is correct, the [default logic](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/calculator/returns/default_refund_amount.rb#L19) only takes into account adjustments, not refunds.

A few ideas that come to mind to resolve this for your store:
1) [Register a different refund amount calculator](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/return_item.rb#L29)
2) Have you admins create an adjustment prior to the refund
3) We could consider taking refunds into account in the default refund amount calculator, though I would have to dust off some cobwebs as to why they were originally excluded.

**Comment by alex-handley** [comment]
Thanks @athal7 ill investigate some more.
