### ISSUE TITLE
Line Item Quantity Validation

### ISSUE THREAD

**Issue by BenMorganIO** [solidusio/solidus#515]
When adding a line item to the cart, I've discovered that in Spree you get a simple `ActiveRecord::RecordInvalid` if the variant is out of stock. However, in Solidus, when you add a variant to the cart and its not in stock, there's no error until transitioning the order to complete. Tracked this change down to here: https://github.com/solidusio/solidus/commit/7ba53b2c0c9a33140f299e04541834d6fbf9ccb1

I can understand why this may have ended up in the repo, but I think that there should be a constraint for line item creation, regardless of state. I'm kinda scared about line items accidentally being created at ridiculous quantities by accident and then getting an error of out of stock on checkout.

What I'm thinking:

There's a validation at the end of checkout, are we able to add a second one for when a line item is created?

**Comment by BenMorganIO** [comment]
Here's the spec failure that I encountered: https://circleci.com/gh/wildcardlabs/solidus_json_api/58
The fix I ended up with: https://github.com/wildcardlabs/solidus_json_api/commit/e3b467e295a976baab964c19de6183a8caf1f5c2

**Comment by athal7** [comment]
This seems like a good improvement to the line item creation api.

**Comment by cbrunsdon** [comment]
I'm a bit of a tossup, Half the time I find that validations aren't always ran at the appropriate time (especially when its done on a AR callback) and find they get in the way of the store I'm working on, and the other half I appreciate that they're there and often do okay things.

For this, if I had to weigh the before_save against the delayed stock check on checkout, I'd say skip it when its added to the cart.

**Comment by jhawthorn** [comment]
I don't believe it's appropriate to use validations for checking stock, since it could become invalid _after_ being saved to the database.

Closing due to staleness.
