### ISSUE TITLE
Feature: Gift Returns

### ISSUE THREAD

**Issue by austenito** [solidusio/solidus#518]
_This issue is to provide some context on eventual PRs related to allowing users to perform a return on an item that was gifted to them._

I spelunked around in the code a bit and hopefully have a reasonable approach to gift returns. I'm open to other suggestions on how one would implement this feature.

## Terms

* Gifter - The customer who bought the pants
* Giftee - The person who was given the pair of pants and wants to return it.

## Scenarios

There are a couple scenarios where gift returns make sense for us and I hope to highlight how we can get the proper code/hooks in place in Solidus that will work  for the majority of stores. Note these scenarios add the concept of a `GiftReturn`, which is explained a bit later.

```
Scenario: A giftee, goes through a frontend gift return flow

GIVEN I am gifted a pair of pants from my Mom
WHEN I go through the gift return user flow
THEN a GiftReturn is created
AND a ReturnAuthorization is created

GIVEN I send back the pair of pants
WHEN the warehouse receives the pants
THEN I (the giftee) receive store credit
``` 

```
Scenario: A giftee returns a the pair of pants without going through the gift return flow

GIVEN I am gifted a pair of pants from my Mom
WHEN I send back the pair of pants
AND the warehouse receives the pants
THEN the gifter receives a refund of their original payment
``` 

```
Scenario: An admin creates a gift return for a giftee

GIVEN I am a admin helping a giftee create a gift return
WHEN I create a ReturnAuthorization for the giftee
THEN a ReturnAuthorization is created
AND a GiftReturn with giftee information is created

GIVEN the giftee sends back the pair of pants
WHEN the warehouse receives the pants
THEN the the giftee receives store credit
``` 

```
Scenario: An admin creates a CustomerReturn for the giftee

GIVEN I am admin creating a customer return for the giftee
WHEN I create a Reimbursement
THEN I am able to select the recipient of the reimbursement
```

```
Scenario: An admin creates a gift return for a giftee with a reimbursement type 
other than store credit

GIVEN I am a admin helping a giftee create a gift return
WHEN I create a ReturnAuthorization for the giftee with a reimbursement type that is not store credit
THEN an error is displayed 

```
## Approach

Currently, `Reimbursements` and `Spree::Reimbursement::Credit` are tied to the order's user. See:

https://github.com/solidusio/solidus/blob/master/core/app/models/spree/reimbursement.rb#L74

and

https://github.com/solidusio/solidus/blob/master/core/app/models/spree/reimbursement_type/reimbursement_helpers.rb#L53

One approach would be to add a `recipient_id` column to a `Reimbursement` and implement the concept of a `GiftReturn`. A `GiftReturn` would have the following:

* An `Order`
* A `ReturnAuthorization`
* A giftee, which is a user id of the person receiving said pants

The `GiftReturn` would be the resource created by each store implementation. A `GiftReturn` would have the ability to create a `ReturnAuthorization`, which will allow `CustomerReturns` to be created with a `Reimbursement` with either a gifter or giftee recipient.

When building `CustomerReturn` reimbursements (https://github.com/solidusio/solidus/blob/master/core/app/models/spree/reimbursement.rb#L74), it's possible to have return items that are part of the gift return and some that are not. In those cases, we could create separate `Reimbursements` with return items related to the `GiftReturn` and those that are not.

```
def build_from_customer_return(customer_return)
  order = customer_return.order

  # Create reimbursements based on gift returns and non gift returns (this is just an example)

  order.reimbursements.build({
    customer_return: customer_return,
    return_items: gift_return_items
    recipient: gift_return.giftee
  })

  order.reimbursements.build({
    customer_return: customer_return,
    return_items: customer_return.return_items.accepted.not_reimbursed - gift_return_items
    recipient: order.user
  })
end
```

## Admin UI Changes

To support gift returns, the `ReturnAuthorization` and `CustomerReturn` admin UI will need to be updated to choose a recipient for reimbursement. 

_Once wires are finalized, I can attach them here._

**Comment by cbrunsdon** [comment]
Okay! To start, thank you. This is a fantastic way to start this issue and was very understandably laid out.

However, I don't think the concept of a "GiftReturn" is something I'd want inside of core at this time. For the added complexity I don't think its likely to be used by very many stores and therefore isn't appropriate for core. 

Though I am curious if anyone has differing opinions?

Is there something we could do to make the existing returns API more flexible to allow you to implement your GiftReturn in your own store or an extension in a supported way?

**Comment by cbrunsdon** [comment]
@athal7 and I had an offline chat and we narrowed down the scope a bit for something we think could end up as a good addition to core.

We're going to scrap the concept of "GIftReturn" in core for now, but are going to support the concept of re-reimbursing to another user. This would allow admins, when doing a return, to optionally specify a different user that should get the re-reimbursement.

**Comment by austenito** [comment]
Great. We will be posting up a pr soon for early feedback :)
