### ISSUE TITLE
Locale differences with Default Country

### ISSUE THREAD

**Issue by ajkamel** [solidusio/solidus#523]
In digging deeper into Spree I found that the config class that looks for a default country by `name` depends on the locale and so this was changed in a later version of Spree at this commit. https://github.com/spree/spree/commit/d0b1da954d285c86d146df620209c7b4525029c2

as you can see it references the country by ISO: US rather than `name: 'United States' ` 

I was wondering what thoughts were on how to best merge these changes from proposing a PR or from updating from Spree?

**Comment by jhawthorn** [comment]
@ajkamel thanks for the issue. That looks like a good change: looking up by ISO instead of name in the seed data. If you wanted to cherry-pick that change on top of our master (minus the guide changes, as we no longer have guides). I'm pretty sure we would merge it quickly.

**Comment by ajkamel** [comment]
:+1: great ill work on the PR
