### ISSUE TITLE
Promotions: Best way of mass creating coupon codes?

### ISSUE THREAD

**Issue by larskluge** [solidusio/solidus#526]
I was wondering what is the best way to create thousands of coupon codes for the promotion feature? As far as I see it currently, only one single code is possible per promotion. My use case is the need to hand out many different coupon codes, each only a single time usable.

Is there something in Solidus? Upcoming? Or perhaps available per extension?

Alternative, what's the best to hand-code it? Something that might be interesting to build for the core?

Thanks!

_initially opened over at Spree https://github.com/spree/spree/issues/6882_

**Comment by gmacdougall** [comment]
We have recently added a one-to-many relationship between promotion and promotion code. Please see https://github.com/solidusio/solidus/blob/v1.1.0.beta1/core/app/models/spree/promotion.rb#L19

**Comment by larskluge** [comment]
Woo, this is awesome! Thanks @gmacdougall !! :)
