### ISSUE TITLE
[Admin] Align the admin and backend menus for a transparent switch 

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#5271]
Our strategy for releasing the new admin in an iterative way is to allow to enable new pages individually (or by group, eg product management) on top of the legacy backend. 

To do that, we need the old admin sidebar to be identical to the new admin sidebar. 

This is why we changed the default backend theme via https://github.com/solidusio/solidus/pull/5091 and https://github.com/solidusio/solidus/pull/5092. 

The goal for the next release is to release our first opt-in section for the new admin and to accomplish this goal; we need to complete the following tasks:

- [x] Add remix icons support for the backend. We want the sidebar to be identical and the new admin uses this new icon set. At least in the sidebar, we should use the same icons.
- [x] Replicate the account menu in the backend. Right now, we still have the account and logout items together. We should merge them and make it look exactly like the new admin. Bonus point but not required if the onClick dropdowns are identical, but I think we can also live with slight differences here because it will show up only after a click and there will be no visual jumps navigating from the one admin interface to the other.
- ~Backward compatibility support for the new legacy backend menu items customizations. We have a new system in place that allow people to change the content of the new admin sidebar, but we should build an easy path to allow previous customization of the backend sidebar menu items to be visible on both sides. This will ensure that the sidebar will look identical on both sides.~ See https://github.com/solidusio/solidus/issues/5283
- [x] When all the above is done, we should adjust the remaining discrepancy in style (spaces/font sizes) to make the navigation look identical from one admin to the other.

**Related PRs**

- #5304
- #5303
- #5297
- #5295
- #5294

**Comment by elia** [comment]
Fixed!
