### ISSUE TITLE
Promotions - Add product

### ISSUE THREAD

**Issue by timmyArch** [solidusio/solidus#528]
This is just a question, i don't tried it with solidus. 
On spree 2.3 i was able to push products to cart if some cases are matched e.g amount is over or equal then 20€. but if customers reduces cart amount, the promotions wouldn't be recalculated. the client got also the possibilty to increase the quantity of it. My workarround was to inject orderupdater with custom module and tag products as promotion product. So i was able to make a difference between the customer choosen products and promotion ones. This allows me to reject all promotions and recreate them. I don't wanna talk about performance reasons ;), but it worked. I don't like such 'fidgeting' solutions, but i hadn't got enogth time. Does this problem also persists in current master of solidus?

**Comment by peterberkenbosch** [comment]
see #492, the promotion action that added line items was removed here. Working on getting this back in here.

**Comment by jhawthorn** [comment]
Closing in favour of #492
