### ISSUE TITLE
[Admin] add a banner for turning solidus_admin `on` and `off`

### ISSUE THREAD

**Issue by elia** [solidusio/solidus#5282]
SolidusAdmin can be turned on and off by setting the `solidus_admin` cookie to `false`.

- [ ] add a banner allowing to go back to the original solidus_backend version to solidus_admin
- [ ] add a banner allowing to re-enable solidus_admin to solidus_backend
- [ ] add a feedback link to the banner 
  - [ ] Use a discussion with instructions on how to setup things with a link similar to https://github.com/solidusio/solidus/discussions/new?category=new-admin-ui-ux-feedback&title=test
  - [ ] Use a shortener so we can change the target URL retroactively

Both should take the form of a top banner, if that turns out to generate issues in the CSS layout other means are also acceptable.

**Comment by waiting-for-dev** [comment]
@elia, @the-krg, can we close this one?
