### ISSUE TITLE
[Admin] Refactor "accounts/show" view into a separate component

### ISSUE THREAD

**Issue by rainerdema** [solidusio/solidus#5292]
In relation to this [comment](https://github.com/solidusio/solidus/pull/5214#discussion_r1279352285), it has been suggested that the "account/show" view could be refactored into a separate component.

The goal of this issue is to create a new component, accounts/show, that will encapsulate the existing functionality of the "account/show" view.

The resulting implementation should allow the "account/show" view to be rendered as follows:
```ruby
# admin/app/views/solidus_admin/accounts/show.html.erb
<%= render component('accounts/show').new(
      email: current_solidus_admin_user.email,
      logout_path: solidus_admin_logout_path,
      logout_method: solidus_admin_logout_method,
    )
%>
```

**Comment by elia** [comment]
We'll tackle the account section later, for now we turned the page into a redirect to admin_user_edit_path
