### ISSUE TITLE
Solidus style guide

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#533]
We’re transitioning towards a more consistent look and interaction model in the Solidus admin. In favour of giving us a bit of a roadmap and making Solidus easier to extend in the future, I’d like to get started on a style guide. We can look at the first issue as a base to build other more complicated items that might require discussion on how it currently exists (like the grid) or how to clean it up (like the way font awesome icons have been implemented).

I’m proposing the following features for the style guide site:
- site title in left nav
- accordion left nav
- utility navigation (top or bottom TBD) that includes a link to Slack channel, Github, and Solidus site
previous and next buttons (possibly with some keyboard shortcuts too) to navigate through each item
- one topic per page
- two layouts for content depending on the width of images/length of code
- working example components at 100% size used in the graphics area (box with an X through it)
- area for code used (rounded corner box with </>)
- light colour palette. (no dark sidebar like the admin UI rebrand)

![solidus-style-guide-layout](https://cloud.githubusercontent.com/assets/15271353/11352638/6b2b60fc-91f2-11e5-8c5b-c89b92965fa2.JPG)

The first chunks of content I’d like to get in are the basics:
- menu
- colours
- typography
 - heading
 - body text
 - unordered and ordered lists
- forms
 - labels
 - text fields
 - text boxes
 - dropdowns
 - select2 dropdowns
 - select2 combo input
 - radio buttons
 - checkboxes
 - buttons

The question I have for you is - Should this be a code Style guide where we document the way we want to code our components, or should it be more of a visual reference when we’re trying to design a new component or extend the backend?

Feel free to comment on the proposed style guide design as well. The more conversation we have at the start the better the end product should be.

**Comment by tvdeyen** [comment]
Like the idea. 

I would like to see more like a code guideline site, then a visual guideline. 

En Detail:

* Sass Variables explained
* an icon reference
* and syntax preferences

But, first and foremost I would like to see a list of components and how to use and extend them.

**Comment by Sinetheta** [comment]
I'm a big fan of showing components, especially those specific to Solidus. When it comes to something like sass variables though, I worry about overreach.

Rather than trying to take on "how to internet" I would prefer a references to other resources.

**Comment by tvdeyen** [comment]
@Sinetheta Too make this clear: With "Sass variables explained" I meant the sass variables used in Solidus, not how to use them in general ;)

**Comment by Sinetheta** [comment]
AH! Sorry about that, I misunderstood. Then I completely agree, I would love to see justification for our things. "colors" sections always look pretty, with swatches and variable names.

**Comment by graygilmore** [comment]
We have this now!

`/admin/style_guide`
