### ISSUE TITLE
Move from erb to Slim

### ISSUE THREAD

**Issue by pusewicz** [solidusio/solidus#545]
[Slim](http://slim-lang.com) is a great alternative to Erb that's both faster to run, saves keystrokes and automatically closes tags. This allows the developers to edit the templates faster and does not introduce bugs caused by missing closing tags or wrong position of such.

What do you think about migrating erb to Slim?

I'd be more than happy to help.

**Comment by daisuke-3** [comment]
I think your suggestion is great! :muscle:
I like haml more than slim though.

**Comment by peterberkenbosch** [comment]
:-1: I'm all for keeping standard rails conventions.

**Comment by tvdeyen** [comment]
👎 Slim/HAML offer no benefit other then abstraction. Sass and Coffescript are also abstraction layers, but they also have benefits. 

Anyway: You're free to use slim/HAML in your view overrides. That works in the frontend and in the backend. You can even override an erb view with an slim variant. 

But I strongly advise against slim and HAML as template languages in the core.

**Comment by moholtzberg** [comment]
:-1:

**Comment by jamatthews** [comment]
Please stick with ERB!

**Comment by pusewicz** [comment]
Thanks!
