### ISSUE TITLE
Scope Admin Orders to Store

### ISSUE THREAD

**Issue by jarednorman** [solidusio/solidus#5614]
**Desired Behavior**

When viewing the admin orders index, I should see only the orders for the current store.

**Current Behavior**

When viewing the admin orders index, I see all orders for all stores.

**(Optional) Additional notes**

I'm curious where we want to draw the line with multi-store support. What belongs in core and what belongs in solidus_multi_domain (which isn't in great shape at the moment.)

Given that the new admin shows the current store and orders are one of only a couple models that are tied to the store, should we be scoping the visible orders down to that store? It seems like it would be trivial to change by altering [this line](https://github.com/solidusio/solidus/blob/main/admin/app/controllers/solidus_admin/orders_controller.rb#L16).

Another option would be adding the current store to the default search query on that page.

Thoughts?

**Comment by kennyadsl** [comment]
Hey @jarednorman, thanks for reporting. How is it working currently on the legacy admin? Is the feature you are describing always available, or only combined with solidus_multi_domain?

**Comment by jarednorman** [comment]
I've not got a store handy to test whether it works on solidus_multi_domain, but the legacy admin doesn't do it. This would be a functional change in the admin. I can see arguments both ways, but mainly I thought it seemed weird that the new admin navigation shows you what store you are viewing... but then doesn't scope the orders (or literally anything, as far as I know) down to that store.

**Comment by forkata** [comment]
The only records other than orders that seem to be scoped to store are payment methods and shipping methods. There is also a promotion rule that is used for filtering out orders from a store.

We made a small change to add a filter to the orders index by store. This replicates the behaviour in the legacy admin order search!

**Comment by jarednorman** [comment]
I'm going to call this resolved then. I think some multi-tenant stores might need to do additional work here, but I don't think it makes sense for any of that to live within Solidus.

**Comment by fthobe** [comment]
We are in the process of restoring multi domain, @jarednorman do you have any particular idea on how you want order filters done?
