### ISSUE TITLE
The action 'show' could not be found for Spree::Admin::PropertiesController

### ISSUE THREAD

**Issue by chuckaiyu** [solidusio/solidus#5698]
**Solidus Version**:
4.3.3

**To Reproduce**

Go to admin
Click left menu products
Click left menu properties
Click Property Type list anyone row

**Current behavior**
Raise an error. Error message is Unknown action, The action 'show' could not be found for Spree::Admin::PropertiesController.

**Expected behavior**
Show property detail.

**Screenshots**
![截屏2024-03-14 19 58 43](https://github.com/solidusio/solidus/assets/161027936/18f3be30-2b21-49cc-96c6-0656e89d95de)

**Desktop (please complete the following information):**
 - OS: Mac os
 - Browser: Safari
 - Version: 17.3.1

**Comment by nvandoorn** [comment]
Hey @chuckaiyu, it looks like this feature is not implemented in the new admin yet and is being tracked in #5857.

In the meantime, I think it may be prudent to default back to the legacy UI so users don't encounter this in progress feature. I'll talk this over with some others and consider opening a pull request to improve the experience here.
