### ISSUE TITLE
Deprecation warnings don't raise when they should

### ISSUE THREAD

**Issue by mamhoff** [solidusio/solidus#5766]
When running the test suite while having `SOLIDUS_RAISE_DEPRECATIONS` set to `true`, we expect the test suite to fail if any code deprecated by `Spree.deprecator` is called. 

This is not the case currently; and I'm not sure how to fix it.

**Solidus Version**:
Current `main` (as of 2024-05-29)

**To Reproduce**

Deprecate a commonly called method, such as Spree::Order#recalculate by inserting
```
    deprecate :recalculate, deprecator: Spree.deprecator
```
into the core `order.rb` class.

Now run the following command: 

`SOLIDUS_RAISE_DEPRECATIONS=true rspec spec/models/spree/order_spec.rb:245` 

**Current behavior**
The spec calls `Spree::Order#recalculate`, which we just deprecated, and the test suite prints a warning.

**Expected behavior**
The spec calls `Spree::Order#recalculate`, which we just deprecated, and the test suite fails.

**Desktop (please complete the following information):**
 - OS: zsh on Fedora

**Additional context**

We can't currently be sure that we have no deprecation warnings in the test suite. I somewhat rely on this working because with the work on extracting legacy promotions, I work with a lot of deprecations and would like to be sure I don´t accidentally call deprecated code. 

My hunch is that this has to do with the move vom `Spree::Deprecation` to `Spree.deprecator`, which instacaches the instance on a module instance variable. It appears this instacaching doesn't work as it should.

**Comment by tvdeyen** [comment]
Maybe related to Rails 7.1?

https://edgeguides.rubyonrails.org/7_1_release_notes.html#add-rails-application-deprecators

**Comment by benjaminwil** [comment]
@forkata and I looked into this for a bit today. I don't have anything insightful to add yet, but in [our initial tests](https://github.com/SuperGoodSoft/solidus/commit/20b7172536ada6347d14efbc776548a36a218e28), we saw:

- `Spree.deprecator.behavior = :raise` works as expected on Rails 7.1
- `Spree.deprecator.behavior = :raise` works as expected on Rails 7.0

For whatever that's worth, in the context of these simple tests.

**Comment by mamhoff** [comment]
I think it's something to do with how we load the app / test harness. In the spec setup linked above, we are sure that `Spree.deprecator` is the same object, but in real-life tests, it seems like it gets reset or there's more than one. Something like that?

**Comment by forkata** [comment]
Hey @mamhoff, @benjaminwil and I were able to track this down to the call to `DummyApp.initialize` resetting the deprecation behaviour. 
Moving the code to set the override after that call seems to resolve the issue. We were also able to reproduce this in the tests 🎉

**Comment by mamhoff** [comment]
That's great! Thank you for putting in that time!
