### ISSUE TITLE
Solidus demo app doesn't work (styles are not loading?) 

### ISSUE THREAD

**Issue by AOneP** [solidusio/solidus#5777]
Hi,

your demo app (https://demo.solidus.io) doesn't work, looks like styles are not loading.
I checked that on every known browser.  
The friends I sent this to confirm that the problem exists.

Sometimes after refreshing it's loading properly, but still with no few elements (like search bar).

Sorry if it's wrong place to report. I'm not at the mid level in IT and I haven't found any other way to contact you.

<img width="1440" alt="Zrzut ekranu 2024-06-6 o 00 26 07" src="https://github.com/solidusio/solidus/assets/49039289/347f9993-7d75-463d-893b-3fda078fcf9e">
<img width="1440" alt="Zrzut ekranu 2024-06-6 o 00 25 47" src="https://github.com/solidusio/solidus/assets/49039289/78822b44-784f-435b-81d3-5cdb1c64a132">
<img width="1440" alt="Zrzut ekranu 2024-06-6 o 00 25 28" src="https://github.com/solidusio/solidus/assets/49039289/61649bf7-5333-4bdd-a9ef-4199bbe0ddc4">

**Comment by GauravRewaliya** [comment]
Hi @AOneP
is Issue is still persisted ..?
as i cant able to recreate this issue , i checked on Brave and chrome as you mention , all style and Search bar also working properly
can you please check and update
