### ISSUE TITLE
[Admin][Settings] Introduce role creation and modification capability

### ISSUE THREAD

**Issue by MadelineCollier** [solidusio/solidus#5823]
## Description

Introduce a new interface for creating and editing roles.

## Features

- Implement the interface described in the design with specified fields.

## Figma Design

[Storyboard](https://www.figma.com/file/h7eZRxh8KhPakTMr7c9NlB/Solidus-%E2%80%94-Admin-Dashboard?type=design&node-id=1046-125370)

![Image](https://github.com/solidusio/solidus/assets/19948291/d18fe1f5-2d08-468d-aa58-5c33ae5dd593)

**Comment by MadelineCollier** [comment]
Going to repost my questions form [this PR](https://github.com/solidusio/solidus/pull/5826) for visibility!

Additional Questions
This is the first piece for the new [Admin][Settings] Introduce role creation and modification capability ticket.

Example designs:
Screenshot 2024-08-14 at 7 43 40 PM

Spree::Role currently lacks:

Types
Descriptions
Any validation on "Name" except that it be unique (it is still allowed to be blank).
I am assuming that to support the example designs, I will be adding those attributes to the Spree::Role model in a future PR, but I am unsure whether that should go in solidus_admin or whether that should be added to core.

Additionally, the [example designs](https://www.figma.com/design/h7eZRxh8KhPakTMr7c9NlB/Solidus-%E2%80%94-Admin-Dashboard?node-id=1046-125370) seem to differentiate between "custom" and "standard" roles. Will we be creating new stock roles with default permissions sets and adding them to [core/db/default/spree/roles.rb](https://github.com/solidusio/solidus/blob/main/core/db/default/spree/roles.rb)? If so, what will those default roles and permissions be?

**Comment by benjaminwil** [comment]
Just my two cents:

- Descriptions are valuable for stores who have many custom roles. I think it's worth adding.
- I do not think types add very much value.
- Why the checkboxes? I don't think any bulk actions add much value at this stage.
- Any roles that come with Solidus or `solidus_admin` or a Solidus extension--or at the very least: the **Admin** role--should not be able to be destroyed via the web view.
  - Alternatively, _no roles should be destroyable via the web view_.

**Comment by MadelineCollier** [comment]
@rainerdema @kennyadsl What do you guys think of the above? Was any of this discussed internally during the sprint planning/design stages?

**Comment by kennyadsl** [comment]
Good points @MadelineCollier and @benjaminwil. 

@MadelineCollier 

I think that the design in Figma is an implementation of Solidus with the [solidus_user_roles](https://github.com/solidusio-contrib/solidus_user_roles) gem installed. That's where the confusion comes from, I guess. 

Now, it's still to be discovered how we want to get to the state described by the design. We could incorporate the code of the gem into Solidus core/admin. @MadelineCollier can you please explore if that's doable? That gem doesn't have a lot of code, I think the trickiest part will be keeping backward compatibility with people with custom roles and people who already have that gem installed. 


@benjaminwil 

> Descriptions are valuable for stores who have many custom roles. I think it's worth adding.

👍 I also do

> I do not think types add very much value.

It could be useful to differentiate the roles that come with Solidus and those made custom by the merchant, but yeah, we can live without it. 

> Why the checkboxes? I don't think any bulk actions add much value at this stage.

Right, I think this was more to keep all the tables uniform, we can get rid of that part

> Any roles that come with Solidus or solidus_admin or a Solidus extension--or at the very least: the Admin role--should not be able to be destroyed via the web view.
Alternatively, no roles should be destroyable via the web view.

Absolutely, maybe only custom roles (with no user associated) can be destroyed? That's where the type might be used.

**Comment by kennyadsl** [comment]
> Definitely, should be pretty easy. Same question though @kennyadsl should these new additions be added to core or to solidus_admin ?

I'd say that the changes to the models and business logic should be done in core. `solidus_admin` should just be the UI to interact with those models. In fact, we should also update the solidus API to reflect the new changes to roles.

**Comment by MadelineCollier** [comment]
Role creation and modification capability has been added

**Comment by fthobe** [comment]
@tvdeyen When I find a bug do we reopen an issue or create a new one?
