### ISSUE TITLE
Can I use Spree extensions at Solidus?

### ISSUE THREAD

**Issue by dennisluan** [solidusio/solidus#586]
Hi all, can I know whether Solidus can use those Spree extensions which are available at: https://github.com/spree-contrib ?

I know there might be some compatibility issues, since Solidus is a fork of Spree 2.4. Other than this, is it possible? If it is possible, what to pay attention to when using the Spree extensions?

Thank you!!

**Comment by tvdeyen** [comment]
Please read https://github.com/solidusio/solidus/wiki/FAQ#can-i-use-the-spree_-extension-with-solidus

Thanks
