### ISSUE TITLE
switching to closure_tree for taxonomies

### ISSUE THREAD

**Issue by simo163** [solidusio/solidus#588]
Hi all, 

As we use taxonomies with large number of levels, and also some of our stores are depending to others therefor we update taxons putting them all together. Using the old method of Spree awesome_nested_set, we find it a bit heavy for large taxonomies in terms of the queries complexity and does not help either in case of modifications in the dataset when adding or moving new nodes. We are thinking to switch our project to use closure_tree it seems to be more convenient for this kind of problems, but we would like to hear your opinion about this issue, and the posibility of solidus to use it, so the whole community benefits from it.

Sincerely,

**Comment by cbrunsdon** [comment]
I'm definitely unsure of what the scope of the change required is, and the cost/benefit of the switch. 

Is this going to be a large, invasive change? What kind of performance gains are we looking to get, and under what circumstances?

Both gems seem to be reasonably well maintained.

**Comment by tvdeyen** [comment]
A user of [Alchemy reported](https://github.com/AlchemyCMS/alchemy_cms/issues/894), that switching from `awesome_nested_set` to `closure_tree` solved performance issues of CMS installations of several hundred thousand pages. 

The switch seems to be relatively easy. But, we are talking about trees with *several thousand* entries. Does anyone has this large taxonomy trees?

I say: If the switch is painless and backwards compatible in a manner of running a migration, why not? Performance gain for nearly free, give it to me!

**Comment by simo163** [comment]
At the moment we don't use large trees with thousand entries, but we deal with transactions that create or update up to 600 trees at one time. ```awesome_nested_set``` goes really very slow here, moreover it may perform better than ```closure_tree ``` in reading.

I think the switch is not invasive since both gems have in common many methods that spree uses. I found ```closure_tree ``` doesn't have any function which moves a node according to its position, so I did override the [move_to_child_with_index](https://github.com/simo163/spree_closure_tree/commit/f813424a08ad5a986d414552749e27ed1db949ff#diff-bdba634446bcffa37ae166a13f3280fcR6) method of  ```awesome_nested_set```.

The only thing is I must remove the  [acts_as_nested_set](https://github.com/spree/spree/blob/master/core/app/models/spree/taxon.rb#L10) method call in the original Spree::Taxon model. Is there anyway to do that?

Indeed, we didn't collaborate with spree before, so we don't know if using an  [extension](https://github.com/simo163/spree_closure_tree) this way is actually the best solution to this problem or there is a better way to do so. Any advise or help will be really appreciated!

Thanks,

**Comment by tvdeyen** [comment]
This is too invasive for an extension IMO. I would fork the repo and rewrite it so it works with closure_tree, then open a pull request, so it can be merged into the core.

**Comment by simo163** [comment]
Thanks for the feedback, I just sent a [PR](https://github.com/solidusio/solidus/pull/662) with closure_tree. 

PS. It complains an error in the api while in development doesn't.

**Comment by cbrunsdon** [comment]
As this is now handled by #662 I'm closing the issue.
