### ISSUE TITLE
Incompatible versions gems

### ISSUE THREAD

**Issue by hadivarp** [solidusio/solidus#5898]
I am trying to add Solidus to my new Rails project, following the installation instructions on GitHub. Below is my current Gemfile:

```
source "https://rubygems.org"

gem "rails", "~> 7.2.2"
gem "sprockets-rails"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end

```

However, I keep running into compatibility issues. 
`Solidus requires rails >= 7.2.2, < 8.0.0.beta1 and solidus_core >= 2.3.0.beta1, < 2.5.0.beta1, which depends on rails ~> 5.1.0.`

This version conflict is preventing me from using Solidus with Rails 7.2.2, and even when I try downgrading Rails, the issue persists.

If anyone has faced a similar problem or found a workaround, please let me know how you resolved it. Thank you!

**Comment by kennyadsl** [comment]
https://github.com/solidusio/solidus/pull/5843 has been merged, but not released yet. If the issue persists downgrading Rails, did you try deleting the Gemfile.lock already?

**Comment by hadivarp** [comment]
Yes, I did, but up to version 7.0.0, nothing changed.

**Comment by hadivarp** [comment]
> #5843 has been merged, but not released yet. If the issue persists downgrading Rails, did you try deleting the Gemfile.lock already?

Can you tell me when it might be released?

**Comment by jarednorman** [comment]
@tvdeyen and @mamhoff started preparing to release version 4.4.0 a couple days ago. Should be soon.

**Comment by tvdeyen** [comment]
You can also use the git source in your `Gemfile` to point to the `main` branch and actually help the community with probably existing bugs.

https://bundler.io/guides/git.html
