### ISSUE TITLE
Better api error handling

### ISSUE THREAD

**Issue by athal7** [solidusio/solidus#59]
Rather than rescuing all exceptions in the api, maybe we can leverage a few pieces of Rails' built-in functionality.

1) ExceptionWrapper (e.g. https://github.com/elabs/pundit/issues/111)
2) Custom exceptions app (e.g. https://coderwall.com/p/w3ghqq/rails-3-2-error-handling-with-exceptions_app)

**Comment by cbrunsdon** [comment]
Killing this as its more likely that we'll do a new API than make any significant changes.
