### ISSUE TITLE
Allow Inbound Shipment Flag

### ISSUE THREAD

**Issue by fthobe** [solidusio/solidus#5903]
**Desired Behavior**

Some transactions require an inbound shipment such as
- circular economy transactions like repairs for consumer electronics (pick up the device to repair it and ship it again) 
- trade-in solutions

The feature would require: 
- Inbound shipping stock_location selector in products
- Inbound shipping shipping method

Using this flags shipping extensions could be extended to cover this feature.

**Comment by jarednorman** [comment]
@fthobe I love your enthusiasm, but you are misusing issues on this project. Issues are for planned features or reporting bugs. If you have ideas for new features, please propose them in [the GitHub discussions](https://github.com/solidusio/solidus/discussions/categories/new-features-or-ideas).

Please also consider that we only accept new features that we believe will be useful to all or at least most stores. Most of the core team work at consultancies who work on a large number of stores, so we have pretty good perspective on this.

I don't want to discourage you from contributing work back to core, but this feature is an example of something we _probably_ wouldn't accept as it's only useful to stores in the cases you describe. Those are great use-cases for Solidus, but features to support that are better off built as part of your store _or_ as an extension. Your metadata feature proposal is an example of a feature that **is** a good candidate for inclusion in core. It's general purpose and likely useful to most or all stores.

I'm going to close this issue, but feel free to open up a thread in the GitHub Discussions if you want to solicit ideas or advice around building this functionality. 🙂
