### ISSUE TITLE
Migrating from Spree 3.1 to Solidus 1.2.0.alpha

### ISSUE THREAD

**Issue by bricesanchez** [solidusio/solidus#592]
Hello, 

Today, i've tried to migrate from Spree edge github master to Solidus 1.2.0.alpha.
I've changed Spree gems : 

```
-gem 'spree',                   github: 'spree/spree',                          branch: 'master'
-gem 'spree_auth_devise',       github: 'spree/spree_auth_devise',              branch: 'master'
-gem 'spree_i18n',              github: 'spree-contrib/spree_i18n',             branch: 'master'
-gem 'spree_globalize',         github: 'spree-contrib/spree_globalize',        branch: 'master'
+gem 'solidus', github: 'bricesanchez/solidus', branch: 'patch-1'
+gem 'solidus_auth_devise'
+gem 'solidus_i18n', github: 'solidusio-contrib/solidus_i18n', branch: 'master'
+gem 'solidus_globalize', github: 'solidusio-contrib/solidus_globalize', branch: 'master'
```

Then, i've run : `bundle exec rake railties:install:migrations`

The main problem was in fact that all `ConvertHabtmToHmtFor*` Solidus migrations was already present in my schema because i've this migration in my app : 
https://github.com/spree/spree/blob/master/core/db/migrate/20150726141425_rename_has_and_belongs_to_associations_to_model_names.rb

I've commented these Solidus migrations to finish my `rake db:migrate`

I'm now able to start the app but i'm not sure everything works well.

I share my experience on this migration, you could do it too.

**Comment by BenMorganIO** [comment]
Ah, that was me :p

We could update the existing migrations so that they have `if` statements in them. This way they run, but nothing is added. OR we could update Spree 3.1 and make it easier for Spree to migrate over.

**Comment by tvdeyen** [comment]
:+1: for updating the existing migrations

**Comment by jhawthorn** [comment]
> We could update the existing migrations so that they have if statements in them. This way they run, but nothing is added.

I think this is the best approach. It will mean that "down" migrations will not be able to function from spree 3.1 but I think that is an acceptable compromise.

**Comment by tvdeyen** [comment]
> It will mean that "down" migrations will not be able to function from spree 3.1 but I think that is an acceptable compromise.

That's totally ok.

**Comment by jhawthorn** [comment]
We did eventually incorporate Ben's great HABTM migrations from Spree 3.1. It will never be a totally seamless upgrade since the projects have diverged, but this should help.

If anyone finds other actionable improvements we can make to the upgrade please file a new issue.
