### ISSUE TITLE
Factories aren't require-able independently

### ISSUE THREAD

**Issue by tvdeyen** [solidusio/solidus#595]
The factories should be `require`'able independently. Using them in your own project is not possible at the moment, because each factory has lots of dependencies, that are not met in the factory file itself.

**Comment by cbrunsdon** [comment]
Ugh, agreed. I'm likely to get angry enough to take care of this one myself some time in the near future, but definitely a really reasonable task for anyone that wants to start getting solidus experience to work on.

**Comment by tvdeyen** [comment]
We refactored lots of Spree 3 factories lately and hopefully can find some time to push upwards. /c @mamhoff

**Comment by mamhoff** [comment]
This can be closed since #627 is in.

**Comment by tvdeyen** [comment]
🚀

**Comment by cbrunsdon** [comment]
Huzzah! Crazy this is actually got done, good job everyone.
