### ISSUE TITLE
New release of `solidus_legacy_promotions` needed 

### ISSUE THREAD

**Issue by benjaminwil** [solidusio/solidus#6032]
There is no RubyGems release for `solidus_legacy_promotions` 4.4.2, but because of its dependency graph, this means I'm unable to upgrade to `solidus_core` 4.4.2.

This seems like a mistake, since the release Rake task includes `solidus_legacy_promotions`, and its gemspec uses `solidus_core`'s `VERSION` to set dependency version constraints.

```sh
$ grep solidus Gemfile.lock
    solidus_api (4.4.1)
      solidus_core (= 4.4.1)
    solidus_auth_devise (2.5.9)
      solidus_core (>= 3, < 5)
      solidus_support (~> 0.5)
    solidus_core (4.4.1)
    solidus_legacy_promotions (4.4.1)
      solidus_api (= 4.4.1)
      solidus_core (= 4.4.1)
      solidus_support
    solidus_support (0.10.3)
  solidus_auth_devise (~> 2.5)
  solidus_core (~> 4.4)
  solidus_legacy_promotions (~> 4.4)
  solidus_support
```

If you browse RubyGems.org for [`solidus_core`](https://rubygems.org/gems/solidus_core) and [`solidus_legacy_promotions`](https://rubygems.org/gems/solidus_legacy_promotions) you will be able to see the mismatch as of December 11, 2024.

**Solidus Version**: 4.4.2

**To Reproduce**

This is a bit tricky to reproduce with the sandbox, because it has to do with RubyGems.org. So instead, let's reproduce with a new Rails application.

1. Add `solidus_core` and `solidus_legacy_promotions` to your Gemfile at version `~> 4.4`.
2. Run `bundle install`.
Notice that 4.4.1 of `solidus_core` installed even though there are newer 4.4.x versions available.

**Current behavior**

Version 4.4.1 of `solidus_core` is installed even though there are newer 4.4.x versions available.

**Expected behavior**

The latest version of `solidus_core` 4.4.x is installed, and the latest version of `solidus_legacy_promotions` isn't blocking `solidus_core`.

**Comment by tvdeyen** [comment]
Published https://rubygems.org/gems/solidus_legacy_promotions/versions/4.4.2
