### ISSUE TITLE
Restful API Endpoint for All products Under a Taxon

### ISSUE THREAD

**Issue by chi6rag** [solidusio/solidus#607]
I was building an Android Client with a Solidus Backend and wanted to fetch all the products for a particular category but I realized that the API endpoint for all the products under a taxon is not RESTful in nature.

The current endpoint is:
/api/taxons/products?id=12

Suggested endpoint:
/api/taxons/:taxon_id/products

What do you guys think about this enhancement?

API Endpoints for Products
![screen shot 2015-12-19 at 3 21 46 pm](https://cloud.githubusercontent.com/assets/6065869/11912482/497a88bc-a664-11e5-971f-9bbfc960a75d.png)

API Endpoints for Taxons
![screen shot 2015-12-19 at 3 27 28 pm](https://cloud.githubusercontent.com/assets/6065869/11912492/0cf2ab8a-a665-11e5-8989-a1cb4a649c0f.png)

**Comment by cbrunsdon** [comment]
@chi6rag I'd be okay with this in addition, as long as we don't break existing API compatibility.

However we're still in talks about what we're doing long term so I also wouldn't necessarily go out of your way to make this change.

The existing RABL rendered API is old and clunky and there is strong desire to build a smarter, better designed API for the future of solidus.

Will leave it up to you if you want to put together a PR.

**Comment by cbrunsdon** [comment]
Guessing this got solved elsewhere and closing it.

Hopefully next version of solidus API is more robust and supports this.
