### ISSUE TITLE
Helper method conflict font-awesome-sass gem

### ISSUE THREAD

**Issue by harin** [solidusio/solidus#610]
Both solidus and font-awesome-sass uses the `icon` method. There should be a way to prevent helper method conflict. One way is to set `include_all_helpers` to false in the application config, but that would cause several features of solidus to not work. Or namespace the method like spree_icon etc.

**Comment by cbrunsdon** [comment]
Probably best to address this as part of #348?

**Comment by mamhoff** [comment]
This is still an issue. I would vote for deprecating usage of the `icon` helper and creating a new namespaced `solidus_icon` helper.

**Comment by dividedharmony** [comment]
Working on it!

**Comment by jhawthorn** [comment]
Fixed by #1952! :tada: 

We will remove the deprecated method completely for our next major release, Solidus 3.0.

Thanks!
