### ISSUE TITLE
payments_spec.rb:75   => expected: "PAID" got: "BALANCE DUE"

### ISSUE THREAD

**Issue by stabenfeldt** [solidusio/solidus#612]
Hi,

My goal is to extend Solidus so an admin that belongs to one stock location can't see items belonging to other admins stock locations. 

I cloned solidus into `#{RAILS_ROOT}/solidus` and updated my Gemfile:
```ruby
gem 'solidus', :path => '/Users/martins/Work/MyShop/solidus'
```

➜  core git:(master) pwd
/Users/martins/Work/MyShop/solidus/core
➜  core git:(master) sh build.sh

Output from the test is in [this gist](https://gist.github.com/stabenfeldt/83fee6944cee36bc2de3).

I expect you don't need to see my Gemfile, as I'm running the tests within the solidus gem. Let me know otherwise. :-)

Any idea why some of the tests are failing? Can I provide more debug info?

**Comment by jordan-brough** [comment]
I think this is the same thing as https://github.com/solidusio/solidus/issues/609. Can you confirm whether the latest version of Solidus master fixes it?

**Comment by stabenfeldt** [comment]
Hi,

Tried again from updated master branch. Only 1 failing here:

```ruby
Failures:

  1) Payments with a pre-existing payment lists and create payments for an order
     Failure/Error: expect(find('#payment_status').text).to eq('PAID')

       expected: "PAID"
            got: "BALANCE DUE"

       (compared using ==)
     # ./spec/features/admin/orders/payments_spec.rb:98:in `block (3 levels) in <top (required)>'

Finished in 10 minutes 19 seconds (files took 4.63 seconds to load)
591 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/features/admin/orders/payments_spec.rb:75 # Payments with a pre-existing payment lists and create payments for an order
```


![screenshot_2015-12-21-17-52-14 763](https://cloud.githubusercontent.com/assets/181272/11936142/3c2af896-a80c-11e5-9679-8d5f0b2061a6.png)
[Corresponding .html file](https://gist.github.com/stabenfeldt/9b1a5d7156926bd1dd35)



Cheers,
Martin

**Comment by stabenfeldt** [comment]
updated issue title

**Comment by jhawthorn** [comment]
Hi @stabenfeldt. Really appreciate the issue, sorry your first experience with our test suite was like this.

I've created #615 which should fix the issue in the payment_spec.

**Comment by stabenfeldt** [comment]
@jhawthorn No worries! I'm pleasantly surprised by how quick you guys respond and patch bugs. Overall a positive experience reporting this bug. :+1: :wink:
