### ISSUE TITLE
is there a direction to integrate with Spree_marketplace extension?

### ISSUE THREAD

**Issue by blacktea3937** [solidusio/solidus#617]
Hi, 

I wonder whether Solidus has anything like Spree_marketplace, or there is any guidance on how to integrate this extension to make Solidus become a marketplace?

Anyone has done this before? Look forward to knowing your experience on it.

Thanks!

**Comment by cbrunsdon** [comment]
Hi @blacktea3937, nobody has updated the spree_marketplace extension to be solidus compat yet (that I know of).

You'll need to give it a run yourself if you're looking to get it working with solidus. Generally speaking its not too difficult to take any 2.4 branch of an extension and update it to point to solidus instead, but will be very tricky if you haven't done much spree/solidus or rails development before.

**Comment by dhonig** [comment]
We did a bunch of work on it back in Feb.  If there is interest in using this extension I'd be glad to work on porting our fork of it.

**Comment by dennisluan** [comment]
Thanks @dhonig! if marketplace can be made compatible with Solidus, it will be great!

**Comment by blacktea3937** [comment]
thank you @cbrunsdon, I actually test the Spree_marketplace at Spree_drop_ship on Spree. I can't say they run very smoothly. Quite some bugs. Spree_marketplace is only workable on Spree 2.3, not even 2.4. 

If @dhonig can make it compatible with Solidus, that will be great! I believe there will be a good interest for this extension with Solidus!

thank you @dhonig and @cbrunsdon!

**Comment by dhonig** [comment]
Cool!  I'll do an initial investigation over the holiday period and see how
much is involved.

**Comment by blacktea3937** [comment]
Hi @dhonig I also tried to integrate the Spree_marketplace and Spree_drop_ship with Solidus, here are what I found:

1) It seems Spree_drop_ship can be integrated by doing some modifications at .Gemspec file. Only issue I found is: "WARN  DurableDecorator: Spree::Shipment#after_ship decoration uses an invalid SHA. The original method definition could have been tampered with!"

2) While integrating Spree_marketplace seems causing some issues with the database (after modifying .Gemspec file too): "SQLite3::SQLException: no such column: spree_payment_methods.environment:"

Wonder whether you have any findings?

thanks!

**Comment by mtomov** [comment]
Hi @blacktea3937 ,

Have you gone any further with your ideas to realize a maintained Marketplace extension for Solidus? We have interest in doing so, and if you want, we can combine some effort : )

**Comment by AknEp** [comment]
Hi @mtomov,
I found https://github.com/boomerdigital/solidus_marketplace
but It seems to be in progress.

**Comment by usmanasif** [comment]
Any update upon this extension @solidus_marketplace

**Comment by mamhoff** [comment]
@usmanasif The link above is actively developed. To find information about their progress, please consult that repository.
