### ISSUE TITLE
Compatibility with sprockets-rails 3.0

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#618]
samanmohamadi helpfully points out in #609 that the handlebars_assets issue is fixed in their latest master.

After upgrading to that I have other asset issues:

```
ActionView::Template::Error:
  Asset was not declared to be precompiled in production.
  Add `Rails.application.config.assets.precompile += %w( logo/solidus_logo.png )` to `config/initializers/assets.rb` and restart your server
# /home/jhawthorn/src/solidus/core/app/helpers/spree/base_helper.rb:67:in `logo'
```

**Comment by jhawthorn** [comment]
Optimistically tagging this for 1.2. The sooner we sort this out the better

**Comment by Blackening999** [comment]
I strongly suggest to add a *Troubleshooting* section to README. I've installed raw solidus gem (not bleeding edge pointing to github repo) and it's 1.1.0. The issue still the same.
I've lost 1 hour to find out the solution for that :\

Thank you

**Comment by tvdeyen** [comment]
It is very unfortunate that you lost an hour of your precious time.

What should a troubleshooting section in the README cover? Bugs like these happen and can have several causes. We really can't cover every  potentially issue.

Debugging is annoying, cumbersome and frustrating, but explaining how to debug a Rails app can't be the purpose of this projects README.

There are lots of great resources out there covering debugging Rails apps. 

What Solidus specific debugging advice should we add to the README?

**Comment by jhawthorn** [comment]
@Blackening999 sorry you lost time, but our latest release v1.1.1 does set an explicit dependency on the older sprockets-rails. There's not much more we can do than that to avoid issues.
