### ISSUE TITLE
Move page title and action buttons into a sticky header

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#630]
Currently the page title and action buttons are scrollable with the rest of the page content. I’d like to place these items in a sticky area of the page so that the user can always see what page they’re on and have easy access to functions like adding new items to lists. 

The page title would be left aligned and the action buttons would be right aligned to the screen. The content in the page would remain fixed and centered. The page title would truncate if it was exceptionally long and the screen was too small for it to fit on one line, although if the user hovered over it they could see the full page title in a browser styled tooltip.

See the mockup for details. (ignore the left nav visual design for now)

Please let me know your thoughts in the comments below.

![6-sticky-header](https://cloud.githubusercontent.com/assets/15271353/12044198/75ef11de-ae42-11e5-8ae2-70e9af93e44a.png)

**Comment by BenMorganIO** [comment]
:+1:

**Comment by tvdeyen** [comment]
Would love to see this happening. This is a great improvement. 

As next step I would love to see the content not being centered and narrowed any more. It does not fit into the overall look anymore and is a waste of screen space. 

@cbrunsdon How do you plan to release all of these backend improvements? As the individual PRs are great, releasing them individually would lead to a very inconsistent UI. So, I guess that if all UI PRs landed, we will release them all together, right?

**Comment by Mandily** [comment]
I haven't posted all 4 of the following issues up yet, but we're starting to plan for the 1.3 release.
Assuming we don't run into any problems along the way, we'd like to get a sticky header, 100% width, tabs and moving the settings right side navigation into 1.3.

**Comment by cbrunsdon** [comment]
@tvdeyen What is up there now (menu on the left, some colour changes) are what we're targeting for 1.2 (which we're hoping to get out the door sooner rather than later).

But aye, what @Mandily said. Kevin is AFK for the week but Hawth, Mandily and myself sat down yesterday and tried to see what would target 1.3 release. I think we came up with a good balance of consistency but still reasonable to do in a single release. 

We'll have to play it by ear as the work and feedback comes in, but will keep the releases in mind.

**Comment by tvdeyen** [comment]
Ok, sounds like a good plan. Besides the colour (British Columbia ^_^, love that) changes in #603. This would lead to a strange mix of colours in the admin UI. I would move the colour changes all together in one release (1.3 then). Also #629 would be a better candidate for 1.3.

Moving around the navigation and flash notices is ok IMO, but having two colour themes is not.

How do you think about it @cbrunsdon @Mandily ?

**Comment by cbrunsdon** [comment]
Okay, as per discussion in the #gui room in slack (which we made to talk about the gui) we're leaning towards pulling out the last commit here (that actually changes the colors) for a future PR when more colors are ready to change. Final decisions still pending though.

**Comment by Mandily** [comment]
To update this ticket to reflect conversations outside of this thread - rebranding and colour changes will be in 1.4. Only structural things on the UI side will be addressed in 1.3.

**Comment by Mandily** [comment]
As per the two reference issues above, work has been done to remove the grid from the header and align the title and buttons to the outer sides. We're still in talks as to whether the stickiness is useful at this point.

**Comment by gmacdougall** [comment]
Closing due to staleness
