### ISSUE TITLE
Add tabs to replace right side nav

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#633]
Third level navigation currently exists in a vertical list on the right side of pages that belong to specific products, orders, and users. 

I'd like to move that type of navigation into tabs at the top of the page where it will be more accessible and easier to click on. It will also free up some space horizontally so that we can expand tables that would be more helpful with additional columns. 

One thing to note is that in doing this, we won’t be using the title from the right side nav in the tabs.

This would hopefully be implemented in the same release as a 100% width issue, so the tabs should expand across the full width of the content area of the page. If it made it into a release before the 100% width, we could just fit the tabs within the fixed width we have now. 

![tabs](https://cloud.githubusercontent.com/assets/15271353/12044802/bef883c4-ae4c-11e5-9271-07af7419912f.png)

There are two options for what would happen if there were too many tabs to fit on the screen.
1. Add a horizontal scrollbar to the bottom of the screen
2. Add a dropdown to select the other tabs 
<img width="508" alt="tabs dropdown menu" src="https://cloud.githubusercontent.com/assets/15271353/12054952/ffb24a0e-aedc-11e5-9462-3d09fcb0a6b4.png">

My preference is adding a dropdown to select the other tabs, but I'd like to hear what the community thinks.

**Comment by tvdeyen** [comment]
Great. Far better, then current state of third level nav. 

I also prefer the dropdown navigation for tabs not fitting the screen :+1: 

@Mandily I don't understand what you mean with:

> One thing to note is that in doing this, we won’t be using the title from the right side nav in the tabs

What title? The text inside the link we have now?

**Comment by Mandily** [comment]
The 'configurations' title at the top of the column. I don't think there's much use for it. <img width="252" alt="configurations title" src="https://cloud.githubusercontent.com/assets/15271353/12054974/3f82580e-aedd-11e5-8371-096df4d67478.png">

**Comment by tvdeyen** [comment]
@Mandily ah yes, totally useless.

**Comment by Senjai** [comment]
:+1: :tada: :raised_hands:

**Comment by BenMorganIO** [comment]
:+1:

**Comment by Dkendal** [comment]
pretty!

**Comment by peterberkenbosch** [comment]
:tada: :+1:

**Comment by Mandily** [comment]
Tabs have been merged into the admin. They'll be included in the 1.3 release.

<img width="1168" alt="screen shot 2016-04-18 at 9 57 41 am" src="https://cloud.githubusercontent.com/assets/15271353/14612487/12804e22-054c-11e6-9490-c1c213737976.png">
<img width="673" alt="screen shot 2016-04-18 at 9 59 14 am" src="https://cloud.githubusercontent.com/assets/15271353/14612873/5d9410d6-054e-11e6-927f-82892d1e8496.png">
