### ISSUE TITLE
Group settings pages and move them into the left nav and tabs

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#634]
I’d like to take the long list of settings and break it up into groups to make it easier to scan.  
* reorder nav items so that it follows the natural progression of an order
* remove right side nav
* create parent group items settings pages
* put pages in tabs

Below is the proposed information architecture of the settings and further down a mockup of what that would look like. 

![settings-ia](https://cloud.githubusercontent.com/assets/15271353/12056024/75112298-aee7-11e5-9296-e72f4a5b23eb.png)

Ignoring obvious brand/colour discrepancies, this is what the settings area of the site would look like:
![settings](https://cloud.githubusercontent.com/assets/15271353/12056038/839d3392-aee7-11e5-96a7-a49f51f99fba.png)

I want to make sure this is expendable because I know a lot of stores have more than just out of the box functionality stored in here. Please provide feedback in the comments below.

**Comment by dfranciosi** [comment]
Neat :gem: :+1:

**Comment by tvdeyen** [comment]
I like the idea of grouping the settings in logical groups. But this comes with a downside I want to discuss here. 

We won't reduce clicks. Removing clicks was one of the mayor reasons to move the individual settings into the main navigation. 

Any ideas in how we address this? I absolutely see the benefits of grouping the settings and like to see this implemented, but I also like the settings to be easily reachable. 

Second: I don't think Taxonomies is Store related. It should be its own "Page" don't you think?

**Comment by cbrunsdon** [comment]
@tvdeyen The settings are so infrequently used I don't think we should be prioritizing click reduction

**Comment by hhff** [comment]
agree w/ @cbrunsdon - I think expandable sections will really help the admin feel "less overwhelming", which IMO is a bigger problem at the moment

**Comment by tvdeyen** [comment]
Yeah, yep, you're all right. A cleaner settings section > less clicks. Granted.

What about putting Taxonomies on the Store settings page?

**Comment by Mandily** [comment]
I'm a couple of comments behind, but the reason I want to move the settings into the main navigation is because that's technically where it belongs. It never fit in the second level at the top in the old model so it was put into the right nav. 

Once we started talking about it here, we realized it would be easier to scan if it was broken up into groups. More useable is the end goal. Less clicks is one of the ways to get there, but so is grouping. 

As for taxonomies on the store settings page, I think if we started combining pages, we should look at all of the settings, which I'm not sure if we want to do right now. What if we created a category called products? Would it be useful for other things people are customizing their stores with?

**Comment by Mandily** [comment]
Does anyone have thoughts on moving taxonomies into a "Products" category? Do your stores have other items that would benefit from a "Products" category or would we be creating this just for the sake of Taxonomies?

**Comment by Mandily** [comment]
Thinking about this a little more, do we even need taxonomies in the settings? It's weird that it has two access points. It's like it doesn't belong. I'd rather make it accessible from one (products) and remove it completely from settings. What do you think?

**Comment by cbrunsdon** [comment]
@Mandily I say we leave everything in now for this issue as we're just re-arranging, if we also want to yank it we can handle that later separately.

**Comment by Mandily** [comment]
This work has been completed and merged into the repo. It will be included in the 1.3 release.

<img width="509" alt="screen shot 2016-04-18 at 10 22 25 am" src="https://cloud.githubusercontent.com/assets/15271353/14613084/80924340-054f-11e6-91a9-65940b53e379.png">
