### ISSUE TITLE
Ruby 2.3 Support

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#648]
We seem to have some spec failures running under 2.3

https://circleci.com/gh/jhawthorn/solidus/444

**Comment by mamhoff** [comment]
It's the tax rate specs. I replaced them in https://github.com/solidusio/solidus/pull/536 - ready for Ruby 2.3 ;)

**Comment by jhawthorn** [comment]
Locally I'm also seeing an issue caused by rubysherpas/paranoia#292

**Comment by jhawthorn** [comment]
Fixed by #656 and I've released paranoia 2.1.5
