### ISSUE TITLE
AssetNotPrecompiled in Spree::Orders#edit raised on /cart

### ISSUE THREAD

**Issue by Devalo** [solidusio/solidus#654]
Hello.
When trying to enter /cart this error is raised: (This is on a fresh setup of Solidus)

`Sprockets::Rails::Helper::AssetNotPrecompiled in Spree::Orders#edit
Showing ../.rvm/gems/ruby-2.2.2/gems/solidus_frontend-1.1.0/app/views/spree/orders/_line_item.html.erb where line #32 raised: `

`Asset was not declared to be precompiled in production.`
`Add Rails.application.config.assets.precompile += %w( icons/delete.png ) to config/initializers/assets.rb and restart your server`

I've tried adding that line, however this did not clear the error.
The only way I was able to visit /cart was to remove 'icons/delete.png' from line #33 inside the gemfile,
and leave the image_tag helper empty.

**Comment by jhawthorn** [comment]
Hi @Devalo thanks for the report. This I believe is caused by a sprockets-rails 3.0 incompatibility. This is similar to #609.

What version of solidus are you using? The two [latest versions](https://github.com/solidusio/solidus/releases) are 1.1.1 and 1.0.3

**Comment by cbrunsdon** [comment]
Assuming solidus version was bumped or sprockets was locked and this got resolved.
