### ISSUE TITLE
can't install solidus whlie run 'bundle exec rails g spree:install'

### ISSUE THREAD

**Issue by sullivanLi** [solidusio/solidus#663]
I tried to run the generators, but an error is raised
this is more details for my app
https://gist.github.com/sullivanLi/6a4d91b0caec971a7f44

is there anything that I missed?

**Comment by gmacdougall** [comment]
Can you try upgrading to solidus 1.1.1, then running a `bundle update`? This is a compatibility issue with sprockets 3.

**Comment by hhff** [comment]
`solidu v1.1.1` fixed this for me

**Comment by jhawthorn** [comment]
This is breaking due to sprockets-rails 3.0. Either change your dependency to `"~> 2.0"` or upgrade to solidus 1.1.1.

**Comment by sullivanLi** [comment]
thank you all, solidus 1.1.1. fixed it
