### ISSUE TITLE
Bundler could not find compatible versions for gem "activemerchant":

### ISSUE THREAD

**Issue by saroar** [solidusio/solidus#669]
gem 'spree_i18n', git: 'git://github.com/spree/spree_i18n.git', branch: '3-0-stable'
gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings', branch: '3-0-stable'

Bundler could not find compatible versions for gem "activemerchant":
  In Gemfile:
    solidus was resolved to 1.0.0, which depends on
      solidus_core (= 1.0.0) was resolved to 1.0.0, which depends on
        activemerchant (~> 1.48.0)

    spree_i18n was resolved to 3.0.0, which depends on
      spree_core (~> 3.0.4) was resolved to 3.0.4, which depends on
        activemerchant (~> 1.47.0)

**Comment by gmacdougall** [comment]
You'll need to remove `spree_i18n` from your Gemfile and replace it with https://github.com/solidusio-contrib/solidus_i18n

You will need to do the same with any other spree_* gems as well.

**Comment by saroar** [comment]
thanks for your quick reply what about this spree_mail_settings gem ?

**Comment by tvdeyen** [comment]
> You will need to do the same with any other spree_* gems as well.

;)

**Comment by saroar** [comment]
https://github.com/spree-contrib/spree_mail_settings/issues/23

**Comment by tvdeyen** [comment]
You need a solidus compatible version of the gems you are replacing. Please read more about spree extensions in Solidus [in the wiki](https://github.com/solidusio/solidus/wiki/FAQ#can-i-use-the-spree_-extension-with-solidus)

**Comment by gmacdougall** [comment]
That gem has not been ported to Solidus. I would recommend not using it and instead configuring your mail settings using standard ActionMailer configuration.

**Comment by saroar** [comment]
ok this this but very luck of documentation for customise and customise also very difficult but thanks

**Comment by saroar** [comment]
@gmacdougall i will give try standard ActionMailer configuration. thanks will update later
