### ISSUE TITLE
Rails console password change does not reflect on web frontend

### ISSUE THREAD

**Issue by punjab** [solidusio/solidus#673]
If locked out of admin account, changing the account password via rails console does not allow login in.

    [2] pry(main)> user =  Spree::User.first
    #<Spree::User:0x007fe6045a6df0
     id: 1,
     ...
     email: "admin@example.com",
      remember_token: nil,
      persistence_token: nil,
     ...
    [3] pry(main)> user.password = "abc123"
    => "abc123"
    [4] pry(main)> user.password_confirmation = "abc123"
    => "abc123"
    [5] pry(main)> user.save!
       (0.2ms)  begin transaction
      SQL (0.9ms)  UPDATE "spree_users" SET "password_salt" = 'BEsBKC9Lpu9L3_VGPkgs', "encrypted_password" = '4df0075c03703f84eabbc88c66d83b3b535ffb2121259bb202a72db162660b97cfb0b7c48d726986a44ac2ed4dfcc734f162b6b851ccf8180fc10f9130a878b6', "updated_at" = '2016-01-09 07:57:26.173020', "spree_api_key" = '1de96376315b52db647f093c6bc8784c7033f14bb3296586', "lock_version" = 4 WHERE "spree_users"."id" = ? AND "spree_users"."lock_version" = ?  [["id", 1], ["lock_version", 3]]
       (0.9ms)  commit transaction
    => true
    [6] pry(main)> user.admin?
      Spree::Role Load (0.2ms)  SELECT "spree_roles".* FROM "spree_roles" INNER JOIN "spree_roles_users" ON "spree_roles"."id" = "spree_roles_users"."role_id" WHERE "spree_roles_users"."user_id" = ?  [["user_id", 1]]
    => true
    [8] pry(main)> user.valid_password?("abc123")
    => true

Now when I you try to login to localhost:3000/admin, the login silently fails. Rails console reports the following.
    
    Spree::User Load (0.1ms)  SELECT  "spree_users".* FROM "spree_users" WHERE   "spree_users"."deleted_at" IS NULL AND "spree_users"."email" = ?  ORDER BY "spree_users"."id" ASC LIMIT 1  [["email", "admin@example.com"]]
   (0.1ms)  begin transaction
   (0.1ms)  commit transaction
   Completed 401 Unauthorized in 10ms (ActiveRecord: 0.3ms)

**Comment by gmacdougall** [comment]
I have verified that this is working correctly on a fresh sandbox. Can you please verify and try the same on a sandbox?
