### ISSUE TITLE
Adapt to new Sprockets to prevent undefined method `register_engine'

### ISSUE THREAD

**Issue by dt1973** [solidusio/solidus#679]
Ref. https://github.com/solidusio/solidus/issues/598
https://github.com/fnando/i18n-js/issues/381
https://github.com/fnando/i18n-js/commit/f5dcfac7721938b3f5440e81565c79bd48b6aa09

**Comment by jhawthorn** [comment]
Duplicate of #618 

Soldius 1.1.1 and 1.0.3 have an explicit dependency on the old sprockets-rails version.

We need a new release of leshill/handlebars_assets in order to support the new version of sprockets-rails
