### ISSUE TITLE
Confirm before Payment

### ISSUE THREAD

**Issue by samanmohamadi** [solidusio/solidus#716]
I use an offsite payment and need to place confirm state before payment.
```
# app/models/spree/order_decorator.rb
checkout_flow do
    go_to_state :address
    go_to_state :delivery
    go_to_state :confirm
    go_to_state :payment, if: ->(order) { order.payment_required? }
  end
```
But this Fix ( spree/spree#4117 ) prevent it to work : 
````
# app/controllers/spree/checkout_controller.rb
 # If confirmation of payment fails, redirect back to payment screen
 if params[:state] == "confirm" && @order.payment_required? && @order.payments.valid.empty?
    flash.keep
    redirect_to checkout_state_path("payment")
 end
````

**Comment by samanmohamadi** [comment]
there is a presumption about default checkout flow in other places which makes difficult to customize checkout flow.
```
# app/models/spree/order/checkout.rb

before_transition to: :confirm, do: :add_store_credit_payments
```
```
# app/controllers/spree/checkout_controller.rb

def update
  
  ...
  
success = if @order.state == 'confirm'
       @order.complete
    else
        @order.next
    end

   ...

end
```

**Comment by dangerdogz** [comment]
I'd suggest using another name than confirm and creating a custom step with custom logic. Confirm is already a step at the end of the process and there is a lot of logic tied to it.

If you try to move it around you will quite possibly break a lot of code since most of the callbacks related to closing an order are tied to the confirm step and assume it's the last step.

**Comment by samanmohamadi** [comment]
If I use another step between delivery and payment, I don't need confirm state after payment any more because it doesn't make sense to ask for confirmation after money was captured.
Another issue is that  `confirmation_required?` is deprecated and I must remove it in checkout flow which probably case consequence problems.

**Comment by samanmohamadi** [comment]
#757
