### ISSUE TITLE
Login page does not accept locales (Version 1.1.1)

### ISSUE THREAD

**Issue by modreoci** [solidusio/solidus#718]
It displays still in the default language.
![bw_login_page](https://cloud.githubusercontent.com/assets/10616435/12456130/b9062cec-bf9e-11e5-96ee-b6d7e6e6ba4e.png)

**Comment by tvdeyen** [comment]
I guess your are using `solidus_i18n`? 

Would you please [open an issue on that repo](https://github.com/solidusio-contrib/solidus_i18n/issues/new) then?

Thanks.

**Comment by modreoci** [comment]
Ok
