### ISSUE TITLE
Button "Edit" (stock item) in /admin/stock_items# fires no action

### ISSUE THREAD

**Issue by modreoci** [solidusio/solidus#719]
Resp. it links to self (site).

**Comment by gmacdougall** [comment]
Hi @modreoci Thank you for your interest in Solidus.

Unfortunately, this is not enough information to investigate or comment on this issue. If you are able to provide more information please file a new issue.

**Comment by modreoci** [comment]
This is probably the same problem like https://github.com/solidusio/solidus/issues/720
