### ISSUE TITLE
Options from products show not passed to orders_controller when product added to cart

### ISSUE THREAD

**Issue by cindyward1** [solidusio/solidus#721]
There is a bug in the populate method of frontend/app/controllers/spree/orders_controller.rb that prevents the options of the add to cart action of the product show view from being passed to the order.contents.add method.

The code in question was originally written in Spree when the OrderPopulator class was removed with Spree commit [c2870cf](https://github.com/spree/spree/commit/c2870cfa2fa22e91e8529edb0136c21cfa1b4e2a#diff-b186dacad723e791bc7a32692c875066). The code was then modified to remove the merge of the options argument with current_currency with commit [4e4d5b2](https://github.com/spree/spree/blob/4e4d5b2653cb739d348f43aa7c69f30fce695f0a/frontend/app/controllers/spree/orders_controller.rb).

The code from Spree commit c2870cf was modified incorrectly in Solidus with commit [40e4db2](https://github.com/solidusio/solidus/commit/40e6b89a0d78185d4f89afdca20561f5a3a97ba5#diff-b186dacad723e791bc7a32692c875066), which completely eliminated passing the options argument to the order.contents.add method. It should have been modified like it was in Spree commit 4e4d5b2 to read as shown below:

``` ruby
  # Adds a new item to the order (creating a new order if none already exists)
  def populate
      order    = current_order(create_order_if_necessary: true)
      variant  = Spree::Variant.find(params[:variant_id])
      quantity = params[:quantity].to_i
      options = params[:options] || {}   # This line needs to be added

      #2,147,483,647 is crazy. See issue https://github.com/spree/spree/issues/2695.
      if quantity.between?(1, 2_147_483_647)
        begin
            # options argument needs to be added to the order.contents.add method call
            order.contents.add(variant, quantity, options) 
```

We are trying to port spree_product_assembly to Solidus, and this bug is causing 4 test cases to fail with the error "Failure/Error: selected_variants[part.id.to_s], NoMethodError: undefined method `[]' for nil:NilClass". This same error also causes an abort when using the UI to add a bundle with a selection-deferred variant to the shopping cart.

**Comment by cbrunsdon** [comment]
Hi @cindyward1, thanks for doing such a thorough backtrack of that codes history.

Do you have your WIP of the spree_product_assembly port handy? I'm unsure what is actually throwing the error here, as order.contents.add() sets the default for options to be {}, so it should never be nil and we should not need to set it inside of the populate method.

**Comment by cindyward1** [comment]
Hi Clark, thank you for your prompt response.
The problem occurs with the relatively-new selectable part/variant feature of spree-product-assembly, of which I am still exploring all of the implications. The feature allows the user to select the variant of the part that they want included with the bundle. For example, if you have a bundle of a T-shirt part and a bag part, you can select in the product show view whether you want a blue size L or a green size XL T-shirt, etc. After the user clicks the add to cart button, the selected_variant ends up in params[:options] in the orders_controller. The logic for handling the bundle expects the "selected variants" information to be in the options argument. When it tries to get the information out of the options hash, there's nothing there, and so the code aborts.
Here's the error from the spree-product-assembly's test suite:
1) Adding items to the cart when adding a bundle to the cart when one of the bundle items has a user-selectable variant the cart includes the variant when listing bundle items     Failure/Error: click_button "add-to-cart-button"     NoMethodError:       undefined method `[]' for nil:NilClass     # ./app/models/spree/order_contents_decorator.rb:67:in `variant_id_for'
Here's the variant_id_for method that's encountering the problem (from order_contents_decorator.rb that is modifying core/app/models/spree/order_contents.rb):
def variant_id_for(part, selected_variants)      if part.variant_selection_deferred?        selected_variants[part.id.to_s]      else        part.part.id      end
If variant selection has been deferred, it expects to see the selected variants in the options hash (which is passed to this method as selected_variants). Since the hash is empty, trying to find a value for a non-existent key fails, thus the nil:NilClass error.
When I look at the core/app/models/spree/order_contents.rb, many of the methods pass an options parameter as options = {}. This leads me to believe that the authors of the code intended to allow the possibility of the option hash's not being empty. The authors of spree-product-assembly used this possibility to implement their code, but Solidus removed it which guarantees that the options hash will be empty when the order is populated. I'm asking for it to be put back because the logic to create line items for user selected parts/variants requires params[:options] from the view. There may be other functionality in the future that also wishes to use the options hash to pass information into the order populator.
Please let me know if you need more information. Thanks again for your response ... Cindy

 

    On Friday, January 22, 2016 9:56 AM, Clarke Brunsdon <notifications@github.com> wrote:
 

 Hi @cindyward1, thanks for doing such a thorough backtrack of that codes history.Do you have your WIP of the spree_product_assembly port handy? I'm unsure what is actually throwing the error here, as order.contents.add() sets the default for options to be {}, so it should never be nil and we should not need to set it inside of the populate method. —

**Comment by cindyward1** [comment]
I apologize that I did not address your questions about a WIP repository in my previous response. My spree-product-assembly port is pretty broken right now, but hopefully I'll have it in much better shape by the end of Monday. I'll LYK when I push a WIP release out to solidus_product_assembly on [Trial Guides' github](https://github.com/TrialGuides). What's in there now is an unmodified copy of spree-product-assembly, and it won't even bundle install in its current state.

**Comment by cbrunsdon** [comment]
@cindyward1 Hi cindy, I went through the code there and at no time is options["selected_variants"] set anywhere.

https://github.com/TrialGuides/solidus_product_assembly/blob/master/app/models/spree/order_contents_decorator.rb#L4-L63

Following that backwards it looks like you set it in the params and expect it to be passed through, as it was originally in the spree 'populate' method:
```options  = (params[:options] || {})```

@jhawthorn I'd be good taking that line back as it is really the only point where we'd reasonable be able to extend order_contents.add, thoughts?

**Comment by cindyward1** [comment]
My new code is done but is not out on the TrialGuides github yet due to a misunderstanding between my manager and me. It should be posted soon.

Where options["selected_variants"] is set is in the current (non-working) repository, in the view partial [_parts.html.erb](https://github.com/TrialGuides/solidus_product_assembly/blob/master/app/views/spree/products/show/_parts.html.erb). The specific line of code is 
```
<%= select_tag "options[selected_variants][#{part.id}]", options_for_select(opts, disabled: opts_disabled)%>
```

The model code to which you referred expects the options parameter to have already been set (if appropriate) in the order_contents controller, and the options parameter turns into the selected_variants parameter. The flag part.variant_selection_deferred is looked up from the table spree_assemblies_parts, which is added in a solidus_product_assembly migration during installation.

If you have any further questions PLMK. Thank you for your consideration ... Cindy

**Comment by mamhoff** [comment]
If I see things correctly, this issue is still outstanding and could be fixed by adding 

```ruby
options = (params[:options] || {})
```

and replacing 

```ruby
 @line_item = @order.contents.add(variant, quantity)
```

with 

```ruby
 @line_item = @order.contents.add(variant, quantity, options)
```

@jhawthorn any objections to re-adding this extension point?

**Comment by mamhoff** [comment]
@acreilly is working on this!

**Comment by cbrunsdon** [comment]
Conversation was continued in #1918, closing this.
