### ISSUE TITLE
Uncaught TypeError: Cannot read property 'opener' of null

### ISSUE THREAD

**Issue by stabenfeldt** [solidusio/solidus#728]
I get this error message in the JavaScript console on every page i load from Solidus.
Not sure what caused it, but it has broken all JavaScript functionality on the site.
The error occurs in development mode and in production. I have not added any JS myself.

I'm using v1.2.0.rc1 (4c3c71c)

**Developer console from Chrome**
![screen shot 2016-01-22 at 06 59 09](https://cloud.githubusercontent.com/assets/181272/12503590/d9e507de-c0d5-11e5-9192-3106408440fe.png)

**Developer console from Safari**
![screen shot 2016-01-22 at 07 02 30](https://cloud.githubusercontent.com/assets/181272/12503636/4f3e23c6-c0d6-11e5-8629-ca7e977084df.png)

**Comment by manoharkshetty** [comment]
We are also facing the issue with `version 1.1.1`.

**Comment by stabenfeldt** [comment]
@manoharkshetty: The problem disappeared when I upgraded to latest version of the master branch.

**Comment by cbrunsdon** [comment]
Aye, please see #691 and #720, its related to jquery-rails > 4.0. We will be doing a release shortly.

**Comment by cbrunsdon** [comment]
Closing this, as we now have releases out to peg the jquery-rails dependency.

**Comment by jhawthorn** [comment]
Version 1.1.2 has been released which is compatible with jquery-rails 4.0
