### ISSUE TITLE
Products image bug in show page

### ISSUE THREAD

**Issue by saroar** [solidusio/solidus#729]
this is core bug i think look at this http://prntscr.com/9telx9 
picture always in middle not full inside box

**Comment by mamhoff** [comment]
I think this is a matter of taste more than a bug. If you'd like it to be different, I suggest opening a PR. 

Also, when submitting issues, please try to add punctuation and capitalization to your sentences, it makes things much easier to read and comprehend. 

As an additional bonus, GitHub has support for pasting images in issues; if you used that, the people reviewing this don't have to navigate away.

**Comment by tvdeyen** [comment]
As the view is not really used by any shop, I don't see that this needs to be "fixed". Most shops will most likely change the frontend styles anyway. 

But we won't reject a pull request.
