### ISSUE TITLE
running tests: Solidus complains about undefined spree_users.deleted_at - even though it exists

### ISSUE THREAD

**Issue by stabenfeldt** [solidusio/solidus#733]
I've copied the spec folder from solidus/core into RAILS_ROOT so that I can run the tests in the context of the app that includes Solidus.

I get this error when I run rspec spec/models/spree/user_spec.rb:

      1) Spree::Product#items_belonging_to_user returns only products that belong to the same stock location as the user
         Failure/Error: let(:user)           { create(:user) }
         ActiveRecord::StatementInvalid:
           PG::UndefinedColumn: ERROR:  column spree_users.deleted_at does not exist
           LINE 1: ...E ("spree_users"."email" = 'amya@dubuque.biz' AND "spree_use...
                                                                        ^
           : SELECT  1 AS one FROM "spree_users" WHERE ("spree_users"."email" = 'amya@dubuque.biz' AND "spree_users"."deleted_at" IS NULL) LIMIT 1

I find this a bit strange, because I've verified the that the spree_users.deleted_at is present:

    $ psql Solidus_test
     \d spree_users # => 
      Table "public.spree_users"
      deleted_at             | timestamp without time zone |

How can that be? Why can't it find spree_users.deleted_at?

**Comment by gotoAndBliss** [comment]
@stabenfeldt Why'd you close this? Getting the same issue.
