### ISSUE TITLE
customizing checkout flow dynamically

### ISSUE THREAD

**Issue by samanmohamadi** [solidusio/solidus#757]
I want to remove delivery step for orders which contain just digital products.
One way is to redefine checkout flow 
```
checkout_flow do
  ... 
  go_to_state :delivery, if: ->(order) { !order.digital? }
  ....
end
```
But this way makes me redefine all other steps.
It could be good to add a `:if` parameter to `remove_checkout_step` and `insert_checkout_step`  methods.

**Comment by cbrunsdon** [comment]
Hi @samanmohamadi, seeing as our long-term plan is to remove more of the "pre-complete" state machine steps I'm not sure we want to do too much here.

We generally find that attempting to customize the state machine in these ways usually leads to brittle, very difficult to test and debug code.

I'd suggest making sure the order is ".next"able through your order states and do a while order.next; or work on explicitly calling the transition you desire conditionally in your action.

**Comment by samanmohamadi** [comment]
Thank You for answer.
