### ISSUE TITLE
Spree to Solidus Migration Guide?

### ISSUE THREAD

**Issue by sahal2080** [solidusio/solidus#777]
I am, like some other spree users I assume, very interested in the Solidus project. However I don't see any project migration guide anywhere. Is it as simple as changing the gem names in the gemfile and everything should still work?

**Comment by ajkamel** [comment]
@sahal2080 did you read this https://github.com/solidusio/solidus/wiki/Upgrading-from-Spree

**Comment by sahal2080** [comment]
Not really. There were no links to it on the main page or website. I blame that on other github libraries which, when you click on their wiki tab, there's nothing there to be found :\

> Solidus 1.1 should be released soon which will support upgrades from Spree 3.0

I'm actually using Spree 3. Since Solidus 1.1 is out, does that mean it's ready? 
> One major difference is that Solidus doesn't include Spree 3.0's change to a bootstrap frontend and backend.

How can that issue be resolved? Is the situation better with Solidus 1.2?

**Comment by ajkamel** [comment]
@sahal2080 take a look at #592 I haven't personally done a migration since I started fresh.  You can also ask specific questions at the [Slack](http://slack.solidus.io/) #support room.

**Comment by sahal2080** [comment]
@ajkamel though the issue you referred me to does pertain to migration, it's very limited in scope to (DB migrations).

Also, I'm not sure this is a good approach to resolve an issue that will keep coming up and should be of concern _if the Solidus core team actually cares about_:
- Spree users who are contemplating a migration
- Growing its community in general

At present, the lack of both a migration guide and a user documentation (not technical documentation) makes me wonder what the priorities of this new project/community are. I fully understand that for any nascent open-source project prioritizing is crucial (security, bugs, etc.), but growing a community that can help take care of these issues and others should be somewhere on that list.

I [made a suggestion](https://github.com/solidusio/solidus/issues/655#issuecomment-170694372) not long ago that, to involve the community more, it'd be nice to have a centralized and public place for the project roadmap. This is much better than scattered announcements/issues and can further involve the community if it was open for voting.

I hope I don't sound like I'm whining. But then again, I have to admit that I haven't read this book.

![0471654655 01 lzzzzzzz](https://cloud.githubusercontent.com/assets/6193430/12831022/10a5caf8-cb47-11e5-9316-f80ce2a45d7a.jpg)
