### ISSUE TITLE
No Registration View File

### ISSUE THREAD

**Issue by jakemumu** [solidusio/solidus#804]
Hey,

I'm trying to edit the view files of the checkout/registration page, however i can't find it in the solidus source code. I overloaded the checkout/registration.html.erb file with the default code from spree, it worked. However, It seems as though the content of the spree view is a bit different than what was in whatever solidus was loading.

Any idea where i can find the default code that was being loaded?

Sorry if this is super noobie, i'm semi new to rails and this is my first time building an ecommerce site.

Thanks,

J

**Comment by jhawthorn** [comment]
They should be in the same place in both spree_auth_devise and solidus_auth_devise

`frontend/spree/checkout/registration.html.erb`

In the future this sort of question would be more appropriate in our slack channel.
