### ISSUE TITLE
Spree::Promotion::Rules::ItemTotal prefs were broken in 2.4

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#84]
This rule changed its preferences from (amount, operator) to (amount_min, operator_min, amount_max, operator_max) without any migration to update it. I also think the new version is silly.

**Comment by cbrunsdon** [comment]
@jhawthorn can we kill this issue now, with that revert in?

**Comment by jhawthorn** [comment]
Fixed by #152
