### ISSUE TITLE
Admin taxon edit link does not account for Engine mount path

### ISSUE THREAD

**Issue by pdanzinger** [solidusio/solidus#844]
The commit 9eae061 introduced a bug where the generated edit paths for taxons are hardcoded into the html.
Therefore the code doesn't account for engine mount paths, instead it simply links to "server:port/admin/taxonomies/[...]".

I've created a pull request (#843) that should fix it, though I'm relatively new to solidus (and rails in general), so it might not be the "proper" way to do it.

**Comment by cbrunsdon** [comment]
Okay, this looks fixed in #850, thanks @pdanzinger
