### ISSUE TITLE
Creating a taxon in backend gives it the wrong parent

### ISSUE THREAD

**Issue by CallMeSH** [solidusio/solidus#846]
Hello everyone, I just faced an issue trying to create taxons in the backend.
I figured out why but I can't wrap my head around how to solve it.
I thought it would be easier to just describe it.

Steps to reproduce:
- Create a first taxonomy (T1)
    - Create a first taxon (t1)
- Create a second taxonomy (T2)
    - Create a first taxon (t2)

So you end up having:
- Two taxonomies 

| id              | taxonomy   |
| ------------- |-----------------|
|         1      |        T1        |
|        2       |        T2        |

- Four taxons

| id              | taxons   |
| ------------- |-----------------|
|         1      |        T1        |
|        2       |        t1        |
|        3       |        T2        |
|        4       |        t2        |

A bug in the coffee script in charge of generating a new taxon causes it to request the creation of the taxon with its parent_id equal to the taxonomy_id instead of the id of the master taxon.

`Parameters: {"taxon"=>{"name"=>"New node", "parent_id"=>"2", "child_index"=>"0"}, "taxonomy_id"=>"2"}`

When it should be

` Parameters: {"taxon"=>{"name"=>"New node", "parent_id"=>"4", "child_index"=>"0"}, "taxonomy_id"=>"2"}
`

As a result, in the previous example, t2 end up being a child of t1 since it's the second taxon and T2 is the second taxonomy.

The issue is related to the way [taxonomy.js.coffee in the get_create_handler](https://github.com/solidusio/solidus/blob/21038e667c60d6321ec98c566628e1681505dd65/backend/app/assets/javascripts/spree/backend/taxonomy.js.coffee#L74) handle the call.

Hope it will be helpful enough !

**Comment by jhawthorn** [comment]
Thank you for the exemplary bug report, I believe I've addressed the issue (and several others) in #850

**Comment by jhawthorn** [comment]
Thanks again @CallMeSH. This should be fixed in #850, which is merged if you'd like to check that this is fixed in master.

**Comment by CallMeSH** [comment]
I can confirm the fix
