### ISSUE TITLE
Broken product variants search when utilizing option types

### ISSUE THREAD

**Issue by Murph33** [solidusio/solidus#855]
When searching for a variant based on option types currently only the last option type sent is sent as a parameter.  After attempting the search the option types other than the last will be set to none.

![broken_search](https://cloud.githubusercontent.com/assets/12613649/13018379/06e65130-d17e-11e5-9492-534bcbb1f334.png)

**Comment by mamhoff** [comment]
I can confirm this issue. The solution would probably be to add JS to fill in a hidden field with the magical ransack `name` from the two select boxes instead of having the two select boxes fill an identically named field. @Murph33 since you found the bug, do you think you could pull up a PR?
