### ISSUE TITLE
The taxon javascript code is incompatible with the engine mounting point of the admin

### ISSUE THREAD

**Issue by CallMeSH** [solidusio/solidus#884]
This has been present for a while and #850 didn't do anything about it.

Steps to reproduce:
- In your routes.rb mount the spree engine on a different path than "/"
- In the taxonomies section of the backend, the path of the edit buttons are hardcoded and don't take into account that configuration

The source of the problem is [this line in _tree.hbs](https://github.com/solidusio/solidus/blob/7fc6f2da9071172f1b6d08371e0762869eb3664c/backend/app/assets/javascripts/spree/backend/templates/taxons/_tree.hbs#L8)

**Comment by jhawthorn** [comment]
Sorry about that @CallMeSH. My original attempt in #850 to fix this was broken and I had to revert it.

I've opened #896, which should finally fix this.

**Comment by CallMeSH** [comment]
I can confirm it's fixed!
Confgratulations :thumbsup:
