### ISSUE TITLE
Count on Hand goes to zero when adding a new variant to product

### ISSUE THREAD

**Issue by mdamian322** [solidusio/solidus#889]
I go to a product in Admin that has 20 on hand under Stock Management. I then go to Variants and add a new variant. Once I click the 'Create' button and the variant is created successfully, I go back to Stock Management and see the new variant, but I also see that 'Count on Hand' for the original variant is zero and Back Orderable is unchecked. It should be 20. Now I have to edit the Count on Hand back to 20.

**Comment by ericsaupe** [comment]
This looks to be intended behavior, https://github.com/solidusio/solidus/blob/master/core/app/models/spree/variant.rb#L358.

**Comment by jhawthorn** [comment]
I agree that this seems like intended behaviour. Master variants aren't intended to be purchasable when there are other variants on the product.
