### ISSUE TITLE
Add link to solidusio-contrib in the README

### ISSUE THREAD

**Issue by yeonhoyoon** [solidusio/solidus#892]
It would be helpful to people if a link and a little description to [solidusio-contrib](https://github.com/solidusio-contrib) was in the README file. Currently there are only links to repositories in the https://github.com/solidusio.

**Comment by jhawthorn** [comment]
It might make more sense to list these in our wiki, which is publicly editable

**Comment by ajkamel** [comment]
Just added a url to the main page on the wiki for this.

**Comment by yeonhoyoon** [comment]
:+1:

**Comment by jhawthorn** [comment]
We now just link to [extensions.solidus.io](http://extensions.solidus.io), so I think this can be closed
