### ISSUE TITLE
Recalculate Tax amount after Zone change

### ISSUE THREAD

**Issue by dangerdogz** [solidusio/solidus#894]
Issue :

1) Client complete an order in TAX ZONE 1
2) Client made a mistake with his address and the shipping billing is really in TAX ZONE 2, so you edit his address in the admin panel
3) Tax amounts (on line items) are not updated (still TAX ZONE 1) unless you manually update each line items (by adding quantity for example)

I'm not sure what is the best way to fix it, it's possible to use update_totals or persist_total in the CustomerDetailsController but it seems out of place / heavy-handed

**Comment by dangerdogz** [comment]
Gemfile :

https://gist.github.com/dangerdogz/996e7b887f2e35d40826

Gemfile.lock

https://gist.github.com/dangerdogz/06fa6c40c1e829a19205

**Comment by AdnanTheExcellent** [comment]
When the address is updated, the taxrate should be adjusted if the @order.tax_zone changes.

pseudo code:

'''
old_tax_zone = @order.tax_zone

CODE_TO_UPDATE_SHIP_ADDRESS_HERE

unless old_tax_zone == @order.tax_zone
   Spree::TaxRate.adjust(@order.tax_zone, @order.line_items)
end
'''

**Comment by dangerdogz** [comment]
Fixed by #1082
