### ISSUE TITLE
(Admin) Cannot add a payment for less than full order amount if order is not completed

### ISSUE THREAD

**Issue by dholdren** [solidusio/solidus#908]
### Reproduce:

(Using the generated sandbox app, tested on both v1.0 and v1.2 branches)
Take an order at the "Payment" stage with no payments.
As an admin, try to add a payment for less than the full amount. (e.g. a split payment)
### Expecting:

A new payment for the entered amount.
### Actual Result:

A new payment for the full amount of the order.

![](http://g.recordit.co/NXK14UffbJ.gif)
### Probable cause:

It looks like this line is the culprit:
https://github.com/solidusio/solidus/blob/v1.0/core/app/models/spree/order.rb#L674

**Comment by cbrunsdon** [comment]
@dholdren and I chatted this through in slack and the decision was to not modify existing payments if no new store credit payments were created in that call.

Long term we need to refactor and clean it up, but that should be a good fix for now.

Thanks for hunting down the code for the specific issue @dholdren, super appreciated.

**Comment by mamhoff** [comment]
@cbrunsdon Can we close this issue or do you want to keep it around until we have refactored and cleaned up?

**Comment by dholdren** [comment]
Closing, this is no longer happening.
