### ISSUE TITLE
LineItem and Shipment promotion adjustments are always eligible

### ISSUE THREAD

**Issue by AdnanTheExcellent** [solidusio/solidus#912]
using solidus 1.2

Not sure if I'm missing something obvious, but this seems to be a pretty big bug for promotions? I can't get any of my line item or shipment promotion adjustments to properly be ineligible when the promotion rules attached to it should return false.

Specifically, the bug seems to be caused at this line when you update an adjustment to check for eligibility:

https://github.com/solidusio/solidus/blob/v1.2/core/app/models/spree/adjustment.rb#L167

The adjustment sends the adjustable to promotion.rb when its checking for eligibility. it filters the rules to see which ones are applicable to the adjustable:

https://github.com/solidusio/solidus/blob/v1.2/core/app/models/spree/promotion.rb#L133

However, all the promotion rules made by Solidus are applicable only to a Spree::Order. So, if my adjustable is a LineItem or a Shipment, none of the rules i added to my promotion are getting utilized.

Lets say i have a promotion that gives free shipping (free shipping promotion action) if the order contains a specific product (product promotion rule), it is always giving free shipping regardless of product because the product rule gets filtered out because applicable? fails due to the promotable object being a shipment instead of an order. 

If i changed adjustment.rb L167 to:

`self.eligible = source.promotion.eligible?(order, promotion_code: promotion_code)`

That fixes my issue.

**Comment by gmacdougall** [comment]
Hi Adnan,

We're tidying up some old issues and I tried to reproduce this on the most recent Solidus master and was not able to reproduce the behaviour you're experiencing. Some stuff has changed in the promo system so it's possible we may have fixed this along the way.

For now, I'm closing this issue. Thanks for the report.
