### ISSUE TITLE
No devise.rb file is being generated

### ISSUE THREAD

**Issue by Optiq01** [solidusio/solidus#930]
I have ruby v2.1 and rails v4.2.5 and I'm following this video tutorial
https://youtu.be/0mxGzk1Lfwg

The only differences in here from the site is he's using the postgresql plugin and calls it up with

rails new app_name -d postgresql

after he installs the solidus and solidus_auth_devise gems he runs a bundle update on everything.

Those are the only differences from what appears on the instructions here on this page.  When I get to the spree aspect I get an error at the top telling me

[WARNING] you are not setting Devise.secret_key within your application!  You must set this in config/initializers/devise.rb.  Here's an example:

Then it gives an example on how the syntax should look with a dummy key in place and I get a bunch of lines of code.  I go to the folder to add the data and there's no devise.rb file present in that location.... or anywhere else for that matter.

It also doesn't stop and ask me for a username and password like it does in the video so I'm guessing all those lines don't mean spree is installing.  I triy to run rails server and it gives that same message and goes back to the command prompt.  I'm also running everything in Windows Vista.  why is this happening?

**Comment by 121onto** [comment]
Use this as a template:

https://raw.githubusercontent.com/spree/spree_auth_devise/master/config/initializers/devise.rb

Inside the config block, add the line:

```ruby
  config.secret_key = ENV['DEVISE_SECRET_KEY'] if Rails.env.production?
```

Or (untested) set a value for `secret_key_base` in your `config/secrets.yml`.

**Comment by graygilmore** [comment]
You can also automatically generate the file by running:

```bash
bundle exec rails generate solidus:auth:install
```

@BenMorganIO also talks about this in a still somewhat-relatable "Getting Started with Spree" article: http://blog.benmorgan.io/post/89825694756/getting-started-with-spree

Related: https://github.com/solidusio/solidus_auth_devise/issues/33

**Comment by mamhoff** [comment]
I think this is answered and also reflected in the README. Closing.
