### ISSUE TITLE
updates to instructions in README

### ISSUE THREAD

**Issue by yeonhoyoon** [solidusio/solidus#931]
in the README file, there are instructions to install solidus:

> After installing gems, you'll have to run the generators to create necessary configuration files and migrations.

```
bundle exec rails g spree:install
bundle exec rake railties:install:migrations
```
- It seems that `bundle exec rake railties:install:migrations`line doesn't actually do anything. Is it necessary to run that command?

After running the above commands, an warning comes up for devise gem like following:

```
[WARNING] You are not setting Devise.secret_key within your application!
```
- It might be good to add an instruction to add run `rails g solidus:auth:install`to create the secret key.
- Also, the images would not show up without installing `imagemagick`, so a comment about installing that is probably required too.

I'm not too familiar with the solidus yet, so made an issue instead of a pull request.

**Comment by yeonhoyoon** [comment]
Also, a comment about installing `imagemagick` is probably required too.

**Comment by cbrunsdon** [comment]
> It seems that bundle exec rake railties:install:migrationsline doesn't actually do anything. Is it necessary to run that command?

I'd prefer to leave that as if anyone jammed other extensions or the like into their gemfile that will install their migrations as well.

> It might be good to add an instruction to add run rails g solidus:auth:installto create the secret key.

Agreed, we changed something recently that stopped it from getting created by default.

> Also, the images would not show up without installing imagemagick, so a comment about installing that is probably required too.

This is fair too, as we rely on paperclip and this is required to get anything done in that. I'll take a look tomorrow at adding these two things in, thanks for the input.

**Comment by Kingdutch** [comment]
Not having `rails g solidus:auth:install` just tripped me up. I thought I followed all the instructions in the README but I didn't follow the instructions in the other README.

**Comment by mamhoff** [comment]
The `imagemagick` dependency is still not included in the README. If that gets fixed, this issue can be closed (the reference to `rails g solidus:auth:install` has since been added).

**Comment by MFRWDesign** [comment]
@mfrwdesign is working on this

**Comment by mamhoff** [comment]
The imagemagick dependency is now included in the README, thanks to @MFRWDesign . Thanks to you, we can now close this long-standing issue.
