### ISSUE TITLE
Test this project with Rails 4.2.6.rc1

### ISSUE THREAD

**Issue by rafaelfranca** [solidusio/solidus#943]
Hi team,

we just released Rails 4.2.6.rc1. To help us to find regressions, and make the final release
awesome for everyone, I'm here humbly asking you to test your project with this
Release Candidate.

We are planing the final release to 2016-03-04, so it would be great if
you test it before this date.

If you find any regression please open an issue on GitHub mentioning me and with the title starting
with:

`[Regression 4.2.6.rc1]`

Thanks in advance.

**Comment by cbrunsdon** [comment]
@jhawthorn can you take care of this with the TOPPEST OF PRIORITY please? I assume getting asked by @rafaelfranca to do something means we're now a legitimate project.

**Comment by jhawthorn** [comment]
@rafaelfranca Looks good to me. All our suites passed https://circleci.com/gh/jhawthorn/solidus/745

Thank you for keeping us in mind. :heart:

**Comment by rafaelfranca** [comment]
Awesome! Thank you for checking
